### ISSUE TITLE
Throw on table splitting with multiple roots

### ISSUE THREAD

**Issue by vtortola** [aspnet/EntityFrameworkCore#10077]
When using table splitting with more than one child entity it does not work.
For example, if I have an parent entity, with two children that are configured in table splitting, it will work if I add the parent alone or the parent with only one of the children, but if I set the two children, it will throw  a `InvalidOperationException` (exception details at the end).

In the scenario below marked as [ERROR], I notice how right after calling `ctx.Set<PurchaseOrder>().Add(po);`, the property `po.Cancellation` has become `null`, which is very odd.

Database schema was correctly generated.

#### Model
```c#
public class PurchaseOrder
{
    public int Id { get; set; }
    public string Status { get; set; }
    public CancellationTicket Cancellation { get; set; }
    public Customer Customer { get; set; }
}

public class CancellationTicket
{
    public string CancelReason { get; set; }
    public DateTime? CancelDate { get; set; }
}

public class Customer
{
    public string Name { get; set; }
    public string Surname { get; set; }
}
```
#### Mapping
```c#
class PurchaseOrderConfig : IEntityTypeConfiguration<PurchaseOrder>
{
    public void Configure(EntityTypeBuilder<PurchaseOrder> builder)
    {
        builder.ToTable("purchase_order");
        builder.HasKey(x => x.Id);
        builder.Property(x => x.Id).HasColumnName("id").ForSqlServerUseSequenceHiLo();
        builder.Property(x => x.Status).HasColumnName("status");
        builder.HasOne(x => x.Cancellation).WithOne().HasForeignKey<PurchaseOrder>(x => x.Id);
        builder.HasOne(x => x.Customer).WithOne().HasForeignKey<PurchaseOrder>(x => x.Id);
    }
}

class PurchaseOrderCancellationConfig : IEntityTypeConfiguration<CancellationTicket>
{
    public void Configure(EntityTypeBuilder<CancellationTicket> builder)
    {
        builder.ToTable("purchase_order");
        builder.Property(x => x.CancelReason).HasColumnName("cancel_reason").HasMaxLength(500);
        builder.Property(x => x.CancelDate).HasColumnName("cancel_date").HasColumnType("datetime2");

        builder.Property<int>("Id").HasColumnName("id").ForSqlServerUseSequenceHiLo();
        builder.HasKey("Id");
    }
}

class CustomerConfig : IEntityTypeConfiguration<Customer>
{
    public void Configure(EntityTypeBuilder<Customer> builder)
    {
        builder.ToTable("purchase_order");
        builder.Property(x => x.Name).HasColumnName("customer_name").HasMaxLength(100);
        builder.Property(x => x.Surname).HasColumnName("customer_surname").HasMaxLength(100);

        builder.Property<int>("Id").HasColumnName("id").ForSqlServerUseSequenceHiLo();
        builder.HasKey("Id");
    }
}
```
#### Generated schema
```sql
CREATE TABLE [dbo].[purchase_order](
	[id] [int] NOT NULL,
	[cancel_date] [datetime2](7) NULL,
	[cancel_reason] [nvarchar](500) NULL,
	[customer_name] [nvarchar](100) NULL,
	[customer_surname] [nvarchar](100) NULL,
	[status] [nvarchar](max) NULL,
 CONSTRAINT [PK_purchase_order] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
```
#### [OK] Add main entity with only first child
```c#
var po = new PurchaseOrder()
{
    Status = "hello",
    Cancellation = new CancellationTicket()
    {
        CancelDate = DateTime.Now,
        CancelReason = "reason"
    }
};
ctx.Set<PurchaseOrder>().Add(po);
ctx.SaveChanges();
```
#### [OK] Add main entity with only second child
```c#
var po = new PurchaseOrder()
{
    Status = "hello",
    Customer = new Customer()
    {
        Name = "name2",
        Surname ="surname2"
    }
};
ctx.Set<PurchaseOrder>().Add(po);
ctx.SaveChanges();
```

#### [ERROR] Add main entity with both children
```c#
var po = new PurchaseOrder()
{
    Status = "hello3",
    Customer = new Customer()
    {
        Name = "name3",
        Surname ="surname3"
    },
    Cancellation = new CancellationTicket()
    {
        CancelDate = DateTime.Now,
        CancelReason = "reason 3"
    }
};
ctx.Set<PurchaseOrder>().Add(po);
ctx.SaveChanges();
```
ERROR:
```
System.InvalidOperationException occurred
  HResult=0x80131509
  Message=The entity of 'CancellationTicket' is sharing the table 'purchase_order' with 'PurchaseOrder', but there is no entity of this type with the same key value that has been marked as 'Added'. Consider using 'DbContextOptionsBuilder.EnableSensitiveDataLogging' to see the key values.
  Source=<Cannot evaluate the exception source>
  StackTrace:
   at Microsoft.EntityFrameworkCore.Update.Internal.ModificationCommandIdentityMap.Validate(Boolean sensitiveLoggingEnabled)
   at Microsoft.EntityFrameworkCore.Update.Internal.CommandBatchPreparer.CreateModificationCommands(IReadOnlyList`1 entries, Func`1 generateParameterName)
   at Microsoft.EntityFrameworkCore.Update.Internal.CommandBatchPreparer.<BatchCommands>d__8.MoveNext()
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(Tuple`2 parameters)
   at Microsoft.EntityFrameworkCore.Storage.Internal.SqlServerExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.ExecutionStrategyExtensions.Execute[TState,TResult](IExecutionStrategy strategy, TState state, Func`2 operation)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(IEnumerable`1 commandBatches, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Storage.RelationalDatabase.SaveChanges(IReadOnlyList`1 entries)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IReadOnlyList`1 entriesToSave)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges()
   at EFCoreBug.Program.Main(String[] args) in C:\Users\valeriano.tortola\documents\visual studio 2017\Projects\EFCoreBug\Program.cs:line 51
```

### Further technical details
EF Core version: 2.0
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10
IDE: VS 2017 15.3

**Comment by smitpatel** [comment]
The exception is correct in this case.
Based on configuration made above, you are not configuring 2 children for main entity, instead you are creating 2 parents of the main entity who are using same FK property.
```C#
builder.HasOne(x => x.Cancellation).WithOne().HasForeignKey<PurchaseOrder>(x => x.Id);
builder.HasOne(x => x.Customer).WithOne().HasForeignKey<PurchaseOrder>(x => x.Id);
```
Above 2 lines of code actually makes `PurchaseOrder` to be dependent (child) side. If you intended to configure `PurchaseOrder` as parent entity then change above lines as following and app will work correctly.
```C#
builder.HasOne(x => x.Cancellation).WithOne().HasForeignKey<Cancellation>(x => x.Id);
builder.HasOne(x => x.Customer).WithOne().HasForeignKey<Customer>(x => x.Id);
```

**The cause of exception**
When `PurchaseOrder` is dependent, FK `PurchaseOrder.Id` is shared between `Cancellation` & `Customer`. It will take value from `Cancellation.Id` & `Customer.Id`.  If PurchaseOrder has both the parents then both needs to have same PK value (then only you can share FK). But when user is adding new entities, they will have temporary values and which won't be same (User needs to explicitly set PK of Cancellation & Customer to be same because there is no direct relationship between them). So in above case it throws exception since there is no `Cancellation` entity which is in Added state & having same PK value. The added Cancellation has different PK value.

**Comment by vtortola** [comment]
@smitpatel you are right, thanks for the thoughtful explanation. Is there any use for having two parents in the same entity? Maybe throwing an exception in that case would be a good idea.

Actually, I think this missconfiguration is also related to the problem I was seeing in https://github.com/aspnet/EntityFrameworkCore/issues/10067 I will run some tests to be sure and update it.

**Comment by smitpatel** [comment]
Re-opening issue for triage. Especially to look at 
> Is there any use for having two parents in the same entity? Maybe throwing an exception in that case would be a good idea.

**Comment by ajcvickers** [comment]
We should detect this is model validation and throw.
