### ISSUE TITLE
Query: cast exception when performing sum over client multiplication of nullable<decimal> and int

### ISSUE THREAD

**Issue by maumar** [aspnet/EntityFrameworkCore#10152]
repro:

```cs
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Hello World!");

            using (var ctx = new MyContext())
            {
                ctx.Database.EnsureDeleted();
                ctx.Database.EnsureCreated();

                var p1 = new Product
                {
                    Price = 20,
                };

                var c1 = new CartItem
                {
                    CartId = "1",
                    Quantity = 10,
                    ProductVariant = p1,
                };

                ctx.Products.Add(p1);
                ctx.CartItems.Add(c1);
                ctx.SaveChanges();
            }

            using (var ctx = new MyContext())
            {
                var result = ctx.CartItems
                    .Select(c => c.ProductVariant.Price.GetValueOrDefault() * c.Quantity)
                    .Sum();
            }
        }
    }

    public class MyContext : DbContext
    {
        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseSqlServer(@"Server=.;Database=Repro8652;Trusted_Connection=True;MultipleActiveResultSets=True");
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<CartItem>().HasKey(e => e.CartId);
        }

        public DbSet<CartItem> CartItems { get; set; }
        public DbSet<Product> Products { get; set; }
    }

    public class CartItem
    {
        public string CartId { get; set; }
        public Product ProductVariant { get; set; }
        public int Quantity { get; set; }
    }

    public class Product
    {
        public int ProductId { get; set; }
        public decimal? Price { get; set; }
        public string CartId { get; set; }
    }
```

exception:

```
Unhandled Exception: System.InvalidOperationException: An exception occurred while reading a database value for property 'CartItem.Quantity'. The expected type was 'System.Nullable`1[System.Decimal]' but the actual value was of type 'System.Int32'. ---> System.InvalidCastException: Unable to cast object of type 'System.Int32' to type 'System.Nullable`1[System.Decimal]'.
   at Microsoft.EntityFrameworkCore.Metadata.Internal.EntityMaterializerSource.TryReadValue[TValue](ValueBuffer valueBuffer, Int32 index, IPropertyBase property)
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Metadata.Internal.EntityMaterializerSource.ThrowReadValueException[TValue](Exception exception, Object value, IPropertyBase property)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.EntityMaterializerSource.TryReadValue[TValue](ValueBuffer valueBuffer, Int32 index, IPropertyBase property)
   at lambda_method(Closure , QueryContext , TransparentIdentifier`2 )
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.ProjectionShaper.TypedProjectionShaper`3.Shape(QueryContext queryContext, ValueBuffer valueBuffer)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.BufferlessMoveNext(Boolean buffer)
   at Microsoft.EntityFrameworkCore.ExecutionStrategyExtensions.<>c__DisplayClass12_0`2.<Execute>b__0(DbContext c, TState s)
   at Microsoft.EntityFrameworkCore.Storage.Internal.SqlServerExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.ExecutionStrategyExtensions.Execute[TState,TResult](IExecutionStrategy strategy, Func`2 operation, Func`2 verifySucceeded, TState state)
   at Microsoft.EntityFrameworkCore.ExecutionStrategyExtensions.Execute[TState,TResult](IExecutionStrategy strategy, TState state, Func`2 operation)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.MoveNext()
   at System.Linq.Enumerable.Sum(IEnumerable`1 source)
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ResultEnumerable`1.GetEnumerator()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Boolean& found)
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass17_0`1.<CompileQueryCore>b__0(QueryContext qc)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
   at System.Linq.Queryable.Sum(IQueryable`1 source)
```

Query plan:

```
(QueryContext queryContext) => IEnumerable<decimal> _InterceptExceptions(
    source: IEnumerable<decimal> _ToSequence(() => decimal Sum(IEnumerable<decimal> _ShapedQuery(
                queryContext: queryContext, 
                shaperCommandContext: SelectExpression: 
                    SELECT [c.ProductVariant].[Price], [c].[Quantity]
                    FROM [CartItems] AS [c]
                    LEFT JOIN [Products] AS [c.ProductVariant] ON [c].[ProductVariantProductId] = [c.ProductVariant].[ProductId], 
                shaper: TypedProjectionShaper<TypedCompositeShaper<ValueBufferShaper, ValueBuffer, ValueBufferShaper, ValueBuffer, TransparentIdentifier<ValueBuffer, ValueBuffer>>, TransparentIdentifier<ValueBuffer, ValueBuffer>, decimal>))), 
    contextType: Repro8652.MyContext, 
    logger: DiagnosticsLogger<Query>, 
    queryContext: queryContext)
```

Shaper (here is the problem) - TryReadValue for Quantity is typed as `nullable<decimal>` rather than `int`

```
(QueryContext queryContext | TransparentIdentifier<ValueBuffer, ValueBuffer> t1) => (decimal)!(t1.Inner.IsEmpty) ? Nullable<decimal> TryReadValue(t1.Inner, 0, Product.Price) : default(Nullable<decimal>)?.GetValueOrDefault()Nullable`1.GetValueOrDefault(?!(t1.Inner.IsEmpty) ? Nullable<decimal> TryReadValue(t1.Inner, 0, Product.Price) : default(Nullable<decimal>)?, ) * (Nullable<decimal>)Nullable<decimal> TryReadValue(t1.Outer, 1, CartItem.Quantity)
```

**Comment by natelaff** [comment]
Thank you maumar. This did work in 1.1, was it not supposed to?

**Comment by maumar** [comment]
It's definitely a bug and this scenario should work. Since it's a regression from 1.1, we will evaluate it as a candidate for one of the patches. We wanted to make sure that this was not introduced after 2.0 - in one of the patches. This would make the fix much more urgent.

**Comment by maumar** [comment]
This works in the current bits, must have been fixed as a part of some other checkin - closing
