### ISSUE TITLE
Query: FirstOrDefault on empty collection returning a value type tries to return null instead of default

### ISSUE THREAD

**Issue by shaulbehr** [aspnet/EntityFrameworkCore#10294]
Here's another one that used to work in EF Core 1.1.0:
```
var q = db.Customers
    .Select(c => new 
        { 
            c.CustomerId,
            CanSendEmail = c.EmailAddresses.Where(e => e.IsPrimary)
                        .Select(e => CanSendEmail)
                        .FirstOrDefault()
        })
    .ToList();
```
If the customer doesn't have any emails with `IsPrimary == true`, then the query throws an exception:
```
System.NullReferenceException : Object reference not set to an instance of an object.
   at lambda_method(Closure , QueryContext , ValueBuffer )
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.ProjectionShaper.TypedProjectionShaper`3.Shape(QueryContext queryContext, ValueBuffer valueBuffer)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.BufferlessMoveNext(Boolean buffer)
   at Microsoft.EntityFrameworkCore.Storage.Internal.SqlServerExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
```
Expected behavior: the `.FirstOrDefault()` should return `false`, and not attempt to set a null value to a non-nullable property in the anonymous type.

**Comment by smitpatel** [comment]
Our FirstOrDefault does not take care of `default(T)`. So database will already return null. For reference types it works correctly. For ValueType it will throw exception.

**Comment by maumar** [comment]
We should recognize the pattern (subquery with FirstOrDefault returning a single value type) and convert to 
```(type?)subquery ?? default(type)```

**Comment by maumar** [comment]
fixed in 730b63b7253cf88d6a5e33ce83ed8a76c6bee595

**Comment by sam-roadbed** [comment]
> We should recognize the pattern (subquery with FirstOrDefault returning a single value type) and convert to `(type?)subquery ?? default(type)`





https://elated-leaf19.github.io/LmXIkVUSCOfkqwkFGLkFuNBtvYE1fUIAmdEXsmyoX3SyhYQz0d2npU6flwIjxjz/

**Comment by roji** [comment]
@sam-roadbed please don't post links to 3rd-party sites, if you have a question please open a new issue with a minimal, runnable code sample.
