### ISSUE TITLE
SQL Server Migrations: CreateIndex for Memory-Optimized Table ignores schema

### ISSUE THREAD

**Issue by DenisKolpakov** [aspnet/EntityFrameworkCore#10402]
There is no chance to create index for memory-optimized table with schema different from [dbo] using migrations. Command does not use schema name to identify db object.

```
Exception message: Cannot find the object "UserInfo" because it does not exist or you do not have permissions

Stack trace:
      Microsoft.EntityFrameworkCore.Database.Command[20102]
      Failed executing DbCommand (88ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      ALTER TABLE [UserInfo] ADD INDEX [IX_NameIndex] NONCLUSTERED ([NameIndex]);
System.Data.SqlClient.SqlException (0x80131904): Cannot find the object "UserInfo" because it does not exist or you do not have permissions.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
...
```
```c#
            migrationBuilder.EnsureSchema(
                name: "Users");

            migrationBuilder.AlterDatabase()
                .Annotation("SqlServer:MemoryOptimized", true);

            migrationBuilder.CreateTable(
                name: "UserInfo",
                schema: "Users",
                columns: table => new
                {
                    ...
                })
                .Annotation("SqlServer:MemoryOptimized", true);

            ...

            migrationBuilder.CreateIndex(
                name: "IX_NameIndex",
                schema: "Users",
                table: "UserInfo",
                column: "NameIndex")
                .Annotation("SqlServer:Clustered", false);
```

### Further technical details
EF Core version: 2.1.0-preview1-27654 and earlier
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10
IDE: No matter (Rider 2017.2.1)

**Comment by smitpatel** [comment]
https://github.com/aspnet/EntityFrameworkCore/blob/9daecfd5b915336c2242ab11de471ac6f3d151ad/src/EFCore.SqlServer/Migrations/SqlServerMigrationsSqlGenerator.cs#L530-L532

It ignores schema right now. Thanks for reporting bug @DenisKolpakov
