### ISSUE TITLE
Missing multi-part identifier when executing ToListAsync

### ISSUE THREAD

**Issue by joacar** [aspnet/EntityFrameworkCore#10430]
### Failing query
```c#
var query = await ctx
.Profiles
.Include(i => i.ProfileInstagrams)
.ThenInclude(i => i.Instagram)
.Where(p => !p.Deleted)
.OrderBy(p => (int?)p.ProfileInstagrams.Sum(i => i.Instagram.FollowCount) ?? 0)
.ToListAsync();
```

Corresponding `ToList()` version works (see code at the bottom). Just paste the code into an empty WebApplication project and launch it.

The async version works if the `OrderBy` references a single property e.g. `OrderBy(p => (int?) p.ProfileInstagram.FollowCount) ?? 0)`

SQL Server Express 13.0.4001.0 (English)

### StackTrace
```
WebApplication3> System.Data.SqlClient.SqlException (0x80131904): The multi-part identifier "t.c" could not be bound.
WebApplication3> The multi-part identifier "t.Id" could not be bound.
WebApplication3>    at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__108_0(Task`1 result)
WebApplication3>    at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
WebApplication3>    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
WebApplication3>    at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
WebApplication3> --- End of stack trace from previous location where exception was thrown ---
WebApplication3>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
WebApplication3>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
WebApplication3>    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
WebApplication3>    at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.<ExecuteAsync>d__17.MoveNext()
WebApplication3> --- End of stack trace from previous location where exception was thrown ---
WebApplication3>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
WebApplication3>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
WebApplication3>    at Microsoft.EntityFrameworkCore.Query.Internal.AsyncQueryingEnumerable`1.AsyncEnumerator.<BufferlessMoveNext>d__10.MoveNext()
WebApplication3> --- End of stack trace from previous location where exception was thrown ---
WebApplication3>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
WebApplication3>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
WebApplication3>    at Microsoft.EntityFrameworkCore.Storage.Internal.SqlServerExecutionStrategy.<ExecuteAsync>d__7`2.MoveNext()
WebApplication3> --- End of stack trace from previous location where exception was thrown ---
WebApplication3>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
WebApplication3>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
WebApplication3>    at Microsoft.EntityFrameworkCore.Query.Internal.AsyncQueryingEnumerable`1.AsyncEnumerator.<MoveNext>d__9.MoveNext()
WebApplication3> --- End of stack trace from previous location where exception was thrown ---
WebApplication3>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
WebApplication3>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
WebApplication3>    at System.Linq.AsyncEnumerable.JoinAsyncIterator`4.<MoveNextCore>d__20.MoveNext()
WebApplication3> --- End of stack trace from previous location where exception was thrown ---
WebApplication3>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
WebApplication3>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
WebApplication3>    at System.Linq.AsyncEnumerable.AsyncIterator`1.<MoveNext>d__10.MoveNext()
WebApplication3> --- End of stack trace from previous location where exception was thrown ---
WebApplication3>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
WebApplication3>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
WebApplication3>    at System.Linq.AsyncEnumerable.SelectEnumerableAsyncIterator`2.<MoveNextCore>d__7.MoveNext()
WebApplication3> --- End of stack trace from previous location where exception was thrown ---
WebApplication3>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
WebApplication3>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
WebApplication3>    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
WebApplication3>    at System.Linq.AsyncEnumerable.AsyncIterator`1.<MoveNext>d__10.MoveNext()
WebApplication3> --- End of stack trace from previous location where exception was thrown ---
WebApplication3>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
WebApplication3>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
WebApplication3>    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
WebApplication3>    at Microsoft.EntityFrameworkCore.Query.Internal.QueryBuffer.<IncludeCollectionAsync>d__12.MoveNext()
WebApplication3> --- End of stack trace from previous location where exception was thrown ---
WebApplication3>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
WebApplication3>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
WebApplication3>    at Microsoft.EntityFrameworkCore.Query.Internal.IncludeCompiler.<_IncludeAsync>d__20`1.MoveNext()
WebApplication3> --- End of stack trace from previous location where exception was thrown ---
WebApplication3>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
WebApplication3>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
WebApplication3>    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
WebApplication3>    at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.TaskLiftingExpressionVisitor.<_ExecuteAsync>d__8`1.MoveNext()
WebApplication3> --- End of stack trace from previous location where exception was thrown ---
WebApplication3>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
WebApplication3>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
WebApplication3>    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
WebApplication3>    at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.AsyncSelectEnumerable`2.AsyncSelectEnumerator.<MoveNext>d__3.MoveNext()
WebApplication3> --- End of stack trace from previous location where exception was thrown ---
WebApplication3>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
WebApplication3>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
WebApplication3>    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
WebApplication3>    at System.Linq.AsyncEnumerable.SelectEnumerableAsyncIterator`2.<MoveNextCore>d__7.MoveNext()
WebApplication3> --- End of stack trace from previous location where exception was thrown ---
WebApplication3>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
WebApplication3>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
WebApplication3>    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
WebApplication3>    at System.Linq.AsyncEnumerable.AsyncIterator`1.<MoveNext>d__10.MoveNext()
WebApplication3> --- End of stack trace from previous location where exception was thrown ---
WebApplication3>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
WebApplication3>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
WebApplication3>    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
WebApplication3>    at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.<MoveNext>d__5.MoveNext()
WebApplication3> ClientConnectionId:b8a1ac8b-8515-4c53-a7e8-433b99af31b5
WebApplication3> Error Number:4104,State:1,Class:16
```

### Further technical details
Microsoft.AspNetCore.All.2.0.3
EF Core version: 2.0.1
Database Provider: Microsoft.EntityFrameworkCore.SqlServer.2.0.1
Operating system: Windows 10 Pro 1709 16299.64
IDE: Visual Studio Community 2017

### Steps to reproduce
Empty WebApp start project then just paste code
```c#
    public class ProfileInstagram
    {
        public int ProfileId { get; set; }

        public Profile Profile { get; set; }

        public int InstagramId { get; set; }

        public Instagram Instagram { get; set; }
    }

    public class Profile
    {
        public int Id { get; set; }

        public ICollection<ProfileInstagram> ProfileInstagrams { get; set; }
    }

    public class Instagram
    {
        public int Id { get; set; }

        public int FollowCount { get; set; }

        public ICollection<ProfileInstagram> ProfileInstagrams { get; set; }
    }

    public class Context : DbContext
    {
        public DbSet<Profile> Profiles { get; set; }

        public DbSet<Instagram> Instagrams { get; set; }

        // ReSharper disable once SuggestBaseTypeForParameter
        // Must declare type explicitly when used with pooling
        public Context(DbContextOptions<Context> options) : base(options)
        {
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<ProfileInstagram>(e =>
            {
                e.HasKey(_ => new
                {
                    _.ProfileId,
                    _.InstagramId
                });
                e.HasOne(_ => _.Profile)
                 .WithMany(_ => _.ProfileInstagrams);

                e.HasOne(_ => _.Instagram)
                 .WithMany(_ => _.ProfileInstagrams);
            });
            base.OnModelCreating(modelBuilder);
        }
    }

    public class Startup
    {
        // This method gets called by the runtime. Use this method to add services to the container.
        // For more information on how to configure your application, visit https://go.microsoft.com/fwlink/?LinkID=398940
        public void ConfigureServices(IServiceCollection services)
        {
            const string cs =
                "Data Source=(localdb)\\MSSQLLocalDB;Initial Catalog=Test1;Integrated Security=True;Connect Timeout=30;Encrypt=False;TrustServerCertificate=True;ApplicationIntent=ReadWrite;MultiSubnetFailover=False";
            services.AddEntityFrameworkSqlServer()
                    .AddDbContext<Context>(options => options.UseSqlServer(cs));
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(
            IApplicationBuilder app,
            IHostingEnvironment env,
            IServiceProvider prv)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }

            Seed(prv);

            app.Run(async context => { await Query(prv); });
        }

        private static async Task Query(IServiceProvider prv)
        {
            // ReSharper disable once ConstantNullCoalescingCondition
            // Force COALESCE in case no Instagram for Profile
            using (var scope = prv.CreateScope())
            {
                var ctx = scope.ServiceProvider.GetRequiredService<Context>();
                var query = ctx
                    .Profiles
                    .Include(i => i.ProfileInstagrams)
                    .ThenInclude(i => i.Instagram)
                    .OrderBy(p => (int?) p.ProfileInstagrams.Sum(i => i.Instagram.FollowCount) ?? 0);

                var influencers = query.ToList();
                var influencersAsync = await query.ToListAsync();
            }
        }

        private static void Seed(IServiceProvider prv)
        {
            using (var scope = prv.CreateScope())
            {
                var ctx = scope.ServiceProvider.GetRequiredService<Context>();
                ctx.Database.EnsureDeleted();
                ctx.Database.EnsureCreated();

                var instagrams = new List<Instagram>
                {
                    new Instagram
                    {
                        FollowCount = 10
                    },
                    new Instagram
                    {
                        FollowCount = 20
                    },
                    new Instagram
                    {
                        FollowCount = 31
                    }
                };
                ctx.Instagrams.AddRange(instagrams);
                var influencers = new List<Profile>
                {
                    new Profile
                    {
                        ProfileInstagrams = new List<ProfileInstagram>
                        {
                            new ProfileInstagram
                            {
                                Instagram = instagrams[0]
                            }
                        }
                    },
                    new Profile
                    {
                        ProfileInstagrams = new List<ProfileInstagram>
                        {
                            new ProfileInstagram
                            {
                                Instagram = instagrams[1]
                            }
                        }
                    },
                    new Profile(),
                    new Profile
                    {
                        ProfileInstagrams = new List<ProfileInstagram>
                        {
                            new ProfileInstagram
                            {
                                Instagram = instagrams[0]
                            },
                            new ProfileInstagram
                            {
                                Instagram = instagrams[1]
                            }
                        }
                    },
                    new Profile
                    {
                        ProfileInstagrams = new List<ProfileInstagram>
                        {
                            new ProfileInstagram
                            {
                                Instagram = instagrams[2]
                            }
                        }
                    }
                };
                ctx.Profiles.AddRange(influencers);
                ctx.SaveChanges();
            }
        }
    }
```

**Comment by ipeo** [comment]
I have the exact same issue when in async mode. Removing the order by clauses removes the problem.

**Comment by maumar** [comment]
Verified that this still repros in current dev

**Comment by chris31389** [comment]
This is also affecting this type of query:

```
List<Foo> foos = dbContext
    .Set<Foo>()
    .Include(x => x.Bars)
    .OrderBy(x => x.Bars.FirstOrDefault(y => y.AnotherId == anotherId2).Value)
    .ToListAsync();
```
