### ISSUE TITLE
Query: Include on derived throws in async

### ISSUE THREAD

**Issue by AndriySvyryd** [aspnet/EntityFrameworkCore#10440]
See [Repro10440](https://github.com/aspnet/EntityFrameworkCore/compare/Repro10440)

```C#
[Fact]
public async Task Can_include_derived_self_ref()
{
    using (var testDatabase = SqlServerTestStore.CreateInitialized(DatabaseName))
    {
        var options = Fixture.CreateOptions(testDatabase);
        using (var context = new GameDbContext(options))
        {
            context.Database.EnsureCreated();

            var level = new Level{Game = new Game()};
            level.Items.Add(new Item{Id = 1,Game = level.Game});
            var container = new Container{Id = 2,Game = level.Game};
            container.Items.Add(new Item{Id = 3,Game = level.Game});
            level.Items.Add(container);
            context.Levels.Add(level);

            context.SaveChanges();
        }

        using (var context = new GameDbContext(options))
        {
            // Works
            var level = context.Levels
                    .Include(l => l.Items).ThenInclude<Level, Item, Container, IEnumerable<Item>>(c => c.Items)
                    .ToList().First();

            Assert.Equal(2, level.Items.Count);
            Assert.Equal(1, level.Items.OfType<Container>().Single().Items.Count);
        }

        using (var context = new GameDbContext(options))
        {
            // Throws
            var level = (await context.Levels
                .Include(l => l.Items).ThenInclude<Level, Item, Container, IEnumerable<Item>>(c => c.Items)
                .ToListAsync()).First();

            Assert.Equal(2, level.Items.Count);
            Assert.Equal(1, level.Items.OfType<Container>().Single().Items.Count);
        }
    }
}
```

>System.NullReferenceException : Object reference not set to an instance of an object.
   at Microsoft.EntityFrameworkCore.Query.Internal.IncludeCompiler.<_IncludeAsync>d__23`1.MoveNext() in C:\enlistments\Universe\EntityFramework\src\EFCore\Query\Internal\IncludeCompiler.cs:line 349
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.TaskLiftingExpressionVisitor.<_ExecuteAsync>d__8`1.MoveNext() in C:\enlistments\Universe\EntityFramework\src\EFCore\Query\ExpressionVisitors\Internal\TaskLiftingExpressionVisitor.cs:line 67
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.AsyncSelectEnumerable`2.AsyncSelectEnumerator.<MoveNext>d__3.MoveNext() in C:\enlistments\Universe\EntityFramework\src\EFCore\Query\EntityQueryModelVisitor.cs:line 1120
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryBuffer.<IncludeCollectionAsync>d__12`3.MoveNext() in C:\enlistments\Universe\EntityFramework\src\EFCore\Query\Internal\QueryBuffer.cs:line 309
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.EntityFrameworkCore.Query.Internal.IncludeCompiler.<_IncludeAsync>d__23`1.MoveNext() in C:\enlistments\Universe\EntityFramework\src\EFCore\Query\Internal\IncludeCompiler.cs:line 349
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.TaskLiftingExpressionVisitor.<_ExecuteAsync>d__8`1.MoveNext() in C:\enlistments\Universe\EntityFramework\src\EFCore\Query\ExpressionVisitors\Internal\TaskLiftingExpressionVisitor.cs:line 67
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.AsyncSelectEnumerable`2.AsyncSelectEnumerator.<MoveNext>d__3.MoveNext() in C:\enlistments\Universe\EntityFramework\src\EFCore\Query\EntityQueryModelVisitor.cs:line 1120
--- End of stack trace from previous location where exception was thrown ---
   at System.Linq.AsyncEnumerable.SelectEnumerableAsyncIterator`2.<MoveNextCore>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Linq.AsyncEnumerable.AsyncIterator`1.<MoveNext>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.<MoveNext>d__5.MoveNext() in C:\enlistments\Universe\EntityFramework\src\EFCore\Query\Internal\AsyncLinqOperatorProvider.cs:line 157
--- End of stack trace from previous location where exception was thrown ---
   at System.Linq.AsyncEnumerable.<Aggregate_>d__6`3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.EntityFrameworkCore.SqlServerEndToEndTest.<Can_include_derived_self_ref>d__27.MoveNext() in C:\enlistments\Universe\EntityFramework\test\EFCore.SqlServer.FunctionalTests\SqlServerEndToEndTest.cs:line 579

**Comment by maumar** [comment]
fixed in 04ade14d5a1ba584c737e387cf19cf437225daed
