### ISSUE TITLE
Filters: Error when referencing DbSet in filter

### ISSUE THREAD

**Issue by anpete** [aspnet/EntityFrameworkCore#10463]
```c#
modelBuilder.Entity<Blog>()
    .HasQueryFilter(b => this.Posts.Any(p => p.BlogId == b.Id));
```
yields:
```
Unable to cast object of type 'System.Linq.Expressions.Expression`1[System.Func`2[Microsoft.EntityFrameworkCore.Query.QueryBugsTest+MyContext10___,Microsoft.EntityFrameworkCore.DbSet`1[Microsoft.EntityFrameworkCore.Query.QueryBugsTest+Post10___]]]' to type 'System.Linq.IQueryable'.
	C:\dev\github\aspnet\EntityFrameworkCore\src\EFCore\Query\ExpressionVisitors\Internal\ParameterExtractingExpressionVisitor.cs(223,0): at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.ParameterExtractingExpressionVisitor.VisitMember(MemberExpression memberExpression)
	at System.Linq.Expressions.MemberExpression.Accept(ExpressionVisitor visitor)
	at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
	at System.Linq.Expressions.ExpressionVisitor.VisitArguments(IArgumentProvider nodes)
	at System.Linq.Expressions.ExpressionVisitor.VisitMethodCall(MethodCallExpression node)
	C:\dev\github\aspnet\EntityFrameworkCore\src\EFCore\Query\ExpressionVisitors\Internal\ParameterExtractingExpressionVisitor.cs(97,0): at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.ParameterExtractingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
```
And, accessing via a closure fails, in a slightly different way:
```
 System.InvalidOperationException : An exception was thrown while attempting to evaluate the LINQ query parameter expression 'value(Microsoft.EntityFrameworkCore.Query.QueryBugsTest+MyContext10___+<>c__DisplayClass14_0).context.Set()'.
---- System.ObjectDisposedException : Cannot access a disposed object. A common cause of this error is disposing a context that was resolved from dependency injection and then later trying to use the same context instance elsewhere in your application. This may occur if you are calling Dispose() on the context, or wrapping the context in a using statement. If you are using dependency injection, you should let the dependency injection container take care of disposing context instances.
Object name: 'MyContext10___'.
	C:\dev\github\aspnet\EntityFrameworkCore\src\EFCore\Query\ExpressionVisitors\Internal\ParameterExtractingExpressionVisitor.cs(513,0): at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.ParameterExtractingExpressionVisitor.Evaluate(Expression expression, String& parameterName)
	C:\dev\github\aspnet\EntityFrameworkCore\src\EFCore\Query\ExpressionVisitors\Internal\ParameterExtractingExpressionVisitor.cs(105,0): at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.ParameterExtractingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
	at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
	at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
	at System.Linq.Expressions.ExpressionVisitor.VisitArguments(IArgumentProvider nodes)
	at System.Linq.Expressions.ExpressionVisitor.VisitMethodCall(MethodCallExpression node)
	C:\dev\github\aspnet\EntityFrameworkCore\src\EFCore\Query\ExpressionVisitors\Internal\ParameterExtractingExpressionVisitor.cs(97,0): at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.ParameterExtractingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)

```

**Comment by anpete** [comment]
Fixed in b6aed320cc
