### ISSUE TITLE
`Specified cast not valid` when using min or max after decimal to float cast

### ISSUE THREAD

**Issue by Noctune** [aspnet/EntityFrameworkCore#10537]
Casting from decimal to float before a `Min()` or `Max()` throws an exception with a `specified cast not valid` message and the following stack trace:

```
at Microsoft.EntityFrameworkCore.Query.QueryMethodProvider.GetResult[TResult](IEnumerable`1 valueBuffers, Boolean throwOnNullResult)
at lambda_method(Closure , QueryContext )
at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass17_1`1.<CompileQueryCore>b__0(QueryContext qc)
at TestProject.TestProgram.Main() in C:\...\Program.cs:line 84
```

The bug can be recreated with the following code:

```c#
public class TestTable
{
    public int Id { get; set; }
    public decimal Thing { get; set; }
}

public class TestContext : DbContext
{
    public DbSet<TestTable> ThingTable { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder builder)
    {
        builder.UseSqlServer(@"Server=SomeServer;Database=SomeDatabase;Trusted_Connection=True");
    }
}

class TestProgram
{
    public static void Main()
    {
        using (var db = new TestContext())
        {
            db.Database.EnsureCreated();

            db.ThingTable.Add(new TestTable
            {
                Thing = 20
            });

            db.SaveChanges();

            Console.WriteLine(db.ThingTable.Select(x => (float)x.Thing).Min());
        }
    }
}
```

`.Sum()` works fine. Also `.Skip(0).Min()` seems to be a workaround, oddly enough.

### Further technical details
EF Core version: 2.0.1
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10
IDE: Visual Studio 2017 15.4

**Comment by maumar** [comment]
fixed in fdb54d9288829f21364ed2e93e4b95438982138b
