### ISSUE TITLE
sqlite, decimal and non-US locale - System.FormatException: Input string was not in a correct format

### ISSUE THREAD

**Issue by avestnik** [aspnet/EntityFrameworkCore#1057]
when I query decimal non-0 value from sqlite under non-US (Cyrillic to be specific, with comma as decimal separator) I get an exception: System.FormatException: Input string was not in a correct format. looks like there is a disagreement somewhere inside EF about what format to use during query and parsing

SELECT "q"."SalesWeight" FROM "Questions" AS "q" [I got it from ILogger]

An exception occurred in the data store while iterating the results of a query.
System.AggregateException: One or more errors occurred. ---> System.AggregateException: One or more errors occurred. ---> System.AggregateException: One or more errors occurred. ---> System.FormatException: Input string was not in a correct format.
   at System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   at System.Number.ParseDecimal(String value, NumberStyles options, NumberFormatInfo numfmt)
   at System.Decimal.Parse(String s)
   at Microsoft.Data.SQLite.Utilities.SQLiteTypeMap.<>c__DisplayClass25`2.<Add>b__27(Object o)
   at Microsoft.Data.SQLite.Utilities.SQLiteTypeMap.FromInterop(Object value)
   at Microsoft.Data.SQLite.SQLiteDataReader.GetValue(Int32 ordinal)
   at Microsoft.Data.SQLite.SQLiteDataReader.GetValues(Object[] values)
   at Microsoft.Data.Entity.Relational.RelationalObjectArrayValueReader.CreateBuffer(DbDataReader dataReader)
   at Microsoft.Data.Entity.Relational.RelationalObjectArrayValueReader..ctor(DbDataReader dataReader)
   at Microsoft.Data.Entity.Relational.RelationalObjectArrayValueReaderFactory.Create(DbDataReader dataReader)
   at Microsoft.Data.Entity.Relational.Query.RelationalQueryModelVisitor.CreateEntity[TEntity](IQuerySource querySource, QueryContext queryContext, QuerySourceScope parentQuerySourceScope, DbDataReader dataReader, Int32 readerOffset, IEntityType entityType)
   at lambda_method(Closure , DbDataReader )
   at Microsoft.Data.Entity.Relational.Query.AsyncQueryingEnumerable`1.AsyncEnumerator.<MoveNext>d__1.MoveNext()

**Comment by sriramarunachalam** [comment]
Hi. I am trying to insert this into a table (sql server) through FromSqlRaw.
INSERT INTO dbo.MockAPIData (ServiceId) VALUES ('1fa550f2-1f82-48a6-ad71-4df8319032b8')

Its throwing an "Input string was not in correct format" error. Is there an issue with inserting Guid values as string through fromsqlraw?

Thanks.
