### ISSUE TITLE
Trouble scaffolding with a value converter

### ISSUE THREAD

**Issue by BradBarnich** [aspnet/EntityFrameworkCore#10638]
Trying to create a migration after adding a value converter. 

I think the value converter annotation needs to be ignored at https://github.com/aspnet/EntityFrameworkCore/blob/d4bc77cd4be34ef6482cd48334c5bdd166306cc5/src/EFCore.Design/Migrations/Design/CSharpSnapshotGenerator.cs#L435-L438
(I did this locally and got past the error)

If you are seeing an exception, include the full exceptions details (message and stack trace).

```
PM> add-migration Initial
System.InvalidOperationException: The current CSharpHelper cannot scaffold literals of type 'CareEvolution.Adapter.AccessRuleValueConverter'. Configure your services to use one that can.
   at Microsoft.EntityFrameworkCore.Design.Internal.CSharpHelper.UnknownLiteral(Object value)
   at Microsoft.EntityFrameworkCore.Migrations.Design.CSharpSnapshotGenerator.GenerateAnnotation(IAnnotation annotation, IndentedStringBuilder stringBuilder)
   at Microsoft.EntityFrameworkCore.Migrations.Design.CSharpSnapshotGenerator.GenerateAnnotations(IReadOnlyList`1 annotations, IndentedStringBuilder stringBuilder)
   at Microsoft.EntityFrameworkCore.Migrations.Design.CSharpSnapshotGenerator.GeneratePropertyAnnotations(IProperty property, IndentedStringBuilder stringBuilder)
   at Microsoft.EntityFrameworkCore.Migrations.Design.CSharpSnapshotGenerator.GenerateProperty(String builderName, IProperty property, IndentedStringBuilder stringBuilder)
   at Microsoft.EntityFrameworkCore.Migrations.Design.CSharpSnapshotGenerator.GenerateProperties(String builderName, IEnumerable`1 properties, IndentedStringBuilder stringBuilder)
   at Microsoft.EntityFrameworkCore.Migrations.Design.CSharpSnapshotGenerator.GenerateEntityType(String builderName, IEntityType entityType, IndentedStringBuilder stringBuilder)
   at Microsoft.EntityFrameworkCore.Migrations.Design.CSharpSnapshotGenerator.GenerateEntityTypes(String builderName, IReadOnlyList`1 entityTypes, IndentedStringBuilder stringBuilder)
   at Microsoft.EntityFrameworkCore.Migrations.Design.CSharpSnapshotGenerator.Generate(String builderName, IModel model, IndentedStringBuilder stringBuilder)
   at Microsoft.EntityFrameworkCore.Migrations.Design.CSharpMigrationsGenerator.GenerateMetadata(String migrationNamespace, Type contextType, String migrationName, String migrationId, IModel targetModel)
   at Microsoft.EntityFrameworkCore.Migrations.Design.MigrationsScaffolder.ScaffoldMigration(String migrationName, String rootNamespace, String subNamespace, String language)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.AddMigration(String name, String outputDir, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigrationImpl(String name, String outputDir, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
The current CSharpHelper cannot scaffold literals of type 'AccessRuleValueConverter'. Configure your services to use one that can.
```

### Steps to reproduce
Include a complete code listing (or project/solution) that we can run to reproduce the issue.

Partial code listings, or multiple fragments of code, will slow down our response or cause us to push the issue back to you to provide code to reproduce the issue.

```c#
public partial class AccessPolicy
{
    ...
    [Column("rules", TypeName = "xml")]
    public List<AccessRule> Rules { get; set; } = new List<AccessRule>();
}

public class AccessRuleValueConverter : ValueConverter<List<AccessRule>, string>
{
    private static XmlSerializer _accessRuleSerializer = new XmlSerializer( typeof( AccessRule[] ) );

    public AccessRuleValueConverter() : base(
        rules => ObjectToXml( _accessRuleSerializer, rules ),
        xml => new List<AccessRule>( XmlToObject( _accessRuleSerializer, xml ) as AccessRule[] ) )
    { }

    private static string ObjectToXml( XmlSerializer serializer, object obj )
    {
        using ( var writer = new StringWriter() )
        {
            var ns = new XmlSerializerNamespaces();
            ns.Add( "", "" );
            serializer.Serialize( writer, obj, ns );
            var builder = writer.GetStringBuilder();
            return builder.ToString();
        }
    }

    private static object XmlToObject( XmlSerializer serializer, string xml )
    {
        using ( var sr = new StringReader( xml ) )
        {
            return serializer.Deserialize( sr );
        }
    }
}

modelBuilder.Entity<AccessPolicy>( b =>
{
    b.Ignore( p => p.Rules );
    b.Property( p => p.Rules )
        .HasConversion( new AccessRuleValueConverter() )
        .HasColumnType( "xml" );
} );
```

### Further technical details
EF Core version: 2.1 nightlies
Database Provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)
Operating system: 
IDE: Visual Studio 2017 15.6 preview1

**Comment by ajcvickers** [comment]
@BradBarnich Yeah, I realized in triage this morning that I forgot to do this. Good to see people trying stuff out so quickly. 👍
