### ISSUE TITLE
Query: order by property's length twice throws NRE exception during query compilation

### ISSUE THREAD

**Issue by maumar** [aspnet/EntityFrameworkCore#10743]
Repro:

```cs
ctx.Parent.OrderBy(p => p.Name.Length).ThenBy(p => p.Name.Length).ToList();
```

stack trace:

```
   at Microsoft.EntityFrameworkCore.Query.Expressions.SqlFunctionExpression.Equals(SqlFunctionExpression other)
   at Microsoft.EntityFrameworkCore.Query.Expressions.SqlFunctionExpression.Equals(Object obj)
   at Microsoft.EntityFrameworkCore.Query.Expressions.ExplicitCastExpression.Equals(ExplicitCastExpression other)
   at Microsoft.EntityFrameworkCore.Query.Expressions.ExplicitCastExpression.Equals(Object obj)
   at Microsoft.EntityFrameworkCore.Query.Internal.ExpressionEqualityComparer.ExpressionComparer.CompareExtension(Expression a, Expression b)
   at Microsoft.EntityFrameworkCore.Query.Internal.ExpressionEqualityComparer.ExpressionComparer.Compare(Expression a, Expression b)
   at Microsoft.EntityFrameworkCore.Query.Internal.ExpressionEqualityComparer.Equals(Expression x, Expression y)
   at Microsoft.EntityFrameworkCore.Query.Expressions.SelectExpression.OrderingExpressionComparison(Ordering ordering, Expression expressionToMatch)
   at Microsoft.EntityFrameworkCore.Query.Expressions.SelectExpression.<>c__DisplayClass79_0.<AddToOrderBy>b__0(Ordering o)
   at System.Collections.Generic.List`1.Find(Predicate`1 match)
   at Microsoft.EntityFrameworkCore.Query.Expressions.SelectExpression.AddToOrderBy(Ordering ordering)
   at Microsoft.EntityFrameworkCore.Query.Expressions.SelectExpression.PrependToOrderBy(IEnumerable`1 orderings)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor.VisitOrderByClause(OrderByClause orderByClause, QueryModel queryModel, Int32 index)
   at Remotion.Linq.Clauses.OrderByClause.Accept(IQueryModelVisitor visitor, QueryModel queryModel, Int32 index)
   at Remotion.Linq.QueryModelVisitorBase.VisitBodyClauses(ObservableCollection`1 bodyClauses, QueryModel queryModel)
   at Remotion.Linq.QueryModelVisitorBase.VisitQueryModel(QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.VisitQueryModel(QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor.VisitQueryModel(QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.CreateQueryExecutor[TResult](QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](QueryModel queryModel)
```

**Comment by maumar** [comment]
fixed in e1a82f179995adc54c7f1cf14f764a7260f9e736
