### ISSUE TITLE
Investigate skipped tests: InheritanceRelationshipsQuerySqlServerTest

### ISSUE THREAD

**Issue by ajcvickers** [aspnet/EntityFrameworkCore#10805]
InheritanceRelationshipsQuerySqlServerTest
- Include_reference_with_inheritance2
- Include_reference_with_inheritance_with_filter2
- Include_collection_with_inheritance2
- Include_collection_with_inheritance_with_filter2
- Include_reference_with_inheritance_on_derived3
- Include_reference_with_inheritance_on_derived_with_filter3
- Include_collection_with_inheritance_on_derived3
- Include_collection_with_inheritance_on_derived4
- Nested_include_with_inheritance_reference_reference2
- Nested_include_with_inheritance_reference_reference4
- Nested_include_with_inheritance_reference_collection2
- Nested_include_with_inheritance_reference_collection4
- Nested_include_with_inheritance_collection_reference2
- Nested_include_with_inheritance_collection_reference3
- Nested_include_with_inheritance_collection_reference4
- Nested_include_with_inheritance_collection_collection2
- Nested_include_with_inheritance_collection_collection3
- Nested_include_with_inheritance_collection_collection4

Exception is similar to below.
```
Test 'Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests.InheritanceRelationshipsQuerySqlServerTest.Include_collection_with_inheritance_with_filter2' failed:
	System.InvalidOperationException : The property 'DerivedCollectionOnBase' is not a navigation property of entity type 'BaseInheritanceRelationshipEntity'. The 'Include(string)' method can only be used with a '.' separated list of navigation property names.
	Query\EntityQueryModelVisitor.cs(467,0): at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.<IncludeNavigations>b__42_0(IncludeResultOperator includeResultOperator)
	at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
	at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
	at System.Linq.OrderedEnumerable`1.<GetEnumerator>d__1.MoveNext()
	at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
	at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
	at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
	Query\EntityQueryModelVisitor.cs(451,0): at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.IncludeNavigations(QueryModel queryModel)
	Query\EntityQueryModelVisitor.cs(264,0): at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.CreateQueryExecutor[TResult](QueryModel queryModel)
	Storage\Database.cs(67,0): at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](QueryModel queryModel)
	--- End of stack trace from previous location where exception was thrown ---
	at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
	Query\Internal\QueryCompiler.cs(164,0): at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](Expression query, INodeTypeProvider nodeTypeProvider, IDatabase database, ILogger logger, Type contextType)
	Query\Internal\QueryCompiler.cs(102,0): at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass15_0`1.<Execute>b__0()
	Query\Internal\CompiledQueryCache.cs(68,0): at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQueryCore[TFunc](Object cacheKey, Func`1 compiler)
	Query\Internal\CompiledQueryCache.cs(45,0): at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
	Query\Internal\QueryCompiler.cs(99,0): at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
	Query\Internal\EntityQueryProvider.cs(57,0): at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
	at Remotion.Linq.QueryableBase`1.GetEnumerator()
	at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
	at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
	InheritanceRelationshipsQueryTestBase.cs(274,0): at Microsoft.EntityFrameworkCore.Specification.Tests.InheritanceRelationshipsQueryTestBase`2.Include_collection_with_inheritance_with_filter2()
	InheritanceRelationshipsQuerySqlServerTest.cs(254,0): at Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests.InheritanceRelationshipsQuerySqlServerTest.Include_collection_with_inheritance_with_filter2()
```

**Comment by maumar** [comment]
fixed in 9c7715d86c4fb7c343bceeae58cb2887a8d79fcd
