### ISSUE TITLE
Tracking query on base type when derived type has shadow properties throws

### ISSUE THREAD

**Issue by SvenEV** [aspnet/EntityFrameworkCore#11104]
In certain models that use inheritance (table-per-hierarchy) with a custom discriminator, enumerating the `DbSet<T>` for the abstract base class throws `NullReferenceException`.

```
System.NullReferenceException : Object reference not set to an instance of an object.
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalMixedEntityEntry..ctor(IStateManager stateManager, IEntityType entityType, Object entity, ValueBuffer valueBuffer)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntryFactory.NewInternalEntityEntry(IStateManager stateManager, IEntityType entityType, Object entity, ValueBuffer valueBuffer)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntryFactory.Create(IStateManager stateManager, IEntityType entityType, Object entity, ValueBuffer valueBuffer)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.StartTrackingFromQuery(IEntityType baseEntityType, Object entity, ValueBuffer valueBuffer, ISet`1 handledForeignKeys)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityTrackingInfo.StartTracking(IStateManager stateManager, Object entity, ValueBuffer valueBuffer)
   at Microsoft.EntityFrameworkCore.Query.QueryContext.StartTracking(Object entity, EntityTrackingInfo entityTrackingInfo)
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.<_TrackEntities>d__17`2.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
   at System.Collections.Generic.List`1.AddEnumerable(IEnumerable`1 enumerable)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Program.Main(String[] args) in Program.cs
```

### Steps to reproduce
```c#
using Microsoft.EntityFrameworkCore;
using System.Linq;

namespace BugRepro
{
    class Program
    {
        static void Main(string[] args)
        {
            using (var db = new Db())
            {
                db.Database.EnsureDeleted();
                db.Database.EnsureCreated();

                db.Add(new Derived1 { IsTwo = false });
                db.SaveChanges();
            }

            using (var db = new Db())
            {
                var list = db.Bases.ToList(); // <<< NullReferenceException here
            }
        }

        class Db : DbContext
        {
            public DbSet<Base> Bases { get; set; }

            protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder) => 
                optionsBuilder.UseSqlite("Filename=BugRepro.db");

            protected override void OnModelCreating(ModelBuilder modelBuilder)
            {
                modelBuilder.Entity<Base>()
                    .HasDiscriminator(x => x.IsTwo)
                    .HasValue<Derived1>(false)
                    .HasValue<Derived2>(true);
            }
        }

        abstract class Base
        {
            public int Id { get; set; }
            public bool IsTwo { get; set; }
        }

        class Derived1 : Base 
        {
            public Stuff MoreStuff { get; set; }
        }

        class Derived2 : Base
        {
        }

        class Stuff
        {
            public int Id { get; set; }
        }
    }
}
```

### Workarounds & starting points for investigation
The exception does not occur when doing any of the following:
* Using `HasDiscriminator` with a shadow property instead of a real property
* Removing the `OnModelCreating` override
* Removing the `Derived1.MoreStuff` property
* Moving the `db.Bases`-query into the first `using`-block, right after `db.SaveChanges()`
* Disabling change tracking, e.g. via `db.Bases.AsNoTracking().ToList()`

### Further technical details
EF Core version: 2.0.1
Database Provider: Microsoft.EntityFrameworkCore.Sqlite
Operating system: Windows 10 Pro, Build 17107
IDE: Visual Studio 2017 15.5.7

**Comment by smitpatel** [comment]
As a work-around you can declare `public int MoreStuffId` on `Derived1` class to avoid having shadow property altogether.
