### ISSUE TITLE
Owned type - property could not be mapped - string is not a supported primitive type

### ISSUE THREAD

**Issue by fbrier** [aspnet/EntityFrameworkCore#11152]
Owned types was working in 2.1.0-preview2-28189 as per a [previous issue](https://github.com/aspnet/EntityFrameworkCore/issues/10911). mrswain tracked it down to a commit in 2.1.0-preview2-28212. AndriySvyryd asked me to create a small repro, which is below. The exception below is the one that I originally saw, but then was fixed and has now reappeared in 2.1.0-preview2-30230.
```
System.InvalidOperationException
  HResult=0x80131509
  Message=The property 'TargetedCredential.NetworkAddress' could not be mapped, because it is of type 'string' which is not a supported primitive type or a valid entity type. Either explicitly map this property, or ignore it using the '[NotMapped]' attribute or by using 'EntityTypeBuilder.Ignore' in 'OnModelCreating'.
  Source=Microsoft.EntityFrameworkCore
  StackTrace:
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.PropertyMappingValidationConvention.Apply(InternalModelBuilder modelBuilder)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ImmediateConventionScope.OnModelBuilt(InternalModelBuilder modelBuilder)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.CreateModel(DbContext context, IConventionSetBuilder conventionSetBuilder, IModelValidator validator)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.Internal.InternalAccessorExtensions.GetService[TService](IInfrastructure`1 accessor)
   at Microsoft.EntityFrameworkCore.Infrastructure.DatabaseFacade.get_DatabaseCreator()
   at Microsoft.EntityFrameworkCore.Infrastructure.DatabaseFacade.EnsureCreated()
   at TestOwnedTypes.Program.Main(String[] args) in M:\Projects\TestOwnedTypes\TestOwnedTypes\Program.cs:line 21
```

### Steps to reproduce
Complete code listing is below. Just compile and run.
```c#
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.Data.Sqlite;
using Microsoft.EntityFrameworkCore;

namespace TestOwnedTypes
{
    public class Program
    {
        public static void Main(string[] args)
        {
            SqliteConnection conn = null;
            var cfg = new DbContextOptionsBuilder();
            var connectionStringBuilder = new SqliteConnectionStringBuilder { DataSource = "file::memory:?cache=shared" };
            var connectionString = connectionStringBuilder.ToString();
            conn = new SqliteConnection(connectionString);
            conn.Open();
            cfg.UseSqlite(conn);
            var ctx = new TestContext(cfg.Options);
            ctx.Database.EnsureCreated();
        }
    }

    [Owned]
    public class TargetedCredential
    {
        [Required]
        [StringLength(80)]
        public string NetworkAddress { get; set; }
    }

    [Table("Resource")]
    public class Resource
    {
        [Key]
        [DatabaseGenerated(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }

        public TargetedCredential TargetedCredential { get; set; }
    }

    public class TestContext : DbContext
    {
        public TestContext(DbContextOptions options) : base(options)
        {
        }

        public DbSet<Resource> Resources { get; set; }
    }
}
```
The TestOwnedTypes.csproj is:
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="2.1.0-preview2-30230" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="2.1.0-preview2-30230" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="2.1.0-preview2-30230" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite.Core" Version="2.1.0-preview2-30230" />
  </ItemGroup>
  <ItemGroup>
    <DotNetCliToolReference Include="Microsoft.EntityFrameworkCore.Tools.DotNet" Version="2.0.0" />
  </ItemGroup>
</Project>
```

### Further technical details
EF Core version: 2.1.0-preview2-30230
Database Provider: Sqlite
Operating system: Windows 7SP1
IDE: Visual Studio Community 2017 15.5.7
I can double check that it is the same with the Professional/Enterprise version on Monday.

**Comment by fabianus76** [comment]
Same Problem here: 

`[Owned]
public class StreetAddress
{
    public string Street { get; set; }
    public string City { get; set; }
}

public class Order
{
    public int Id { get; set; }
    public StreetAddress ShippingAddress { get; set; }
}`

I get this

The property 'StreetAddress.Street' could not be mapped, because it is of type 'string' which is not a supported primitive type or a valid entity type. Either explicitly map this property, or ignore it using the '[NotMapped]' attribute or by using 'EntityTypeBuilder.Ignore' in 'OnModelCreating'.

I took the example from the documentation: 

https://docs.microsoft.com/en-us/ef/core/modeling/owned-entities

**Comment by FrederickBrier** [comment]
Thank you very much! I will try out the nightly build when it gets merged.
