### ISSUE TITLE
Query: NullReferenceException: When using Async methods with navigational collections after upgrade to 2.0.0

### ISSUE THREAD

**Issue by drjameshouse** [aspnet/EntityFrameworkCore#11294]
When using a join with an Any(), and selecting navigational collections, I receive a NullReference Exception from Microsoft.EntityFrameworkCore.Metadata.Internal.EntityMaterializerSource.TryReadValue.  This only seems to happen when using the Async version (FirstOrDefaultAsync vs FirstOrDefault).  If I don't include the Any() selection in the join it works as well.

System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=Microsoft.EntityFrameworkCore
  StackTrace:
   at Microsoft.EntityFrameworkCore.Metadata.Internal.EntityMaterializerSource.TryReadValue[TValue](ValueBuffer valueBuffer, Int32 index, IPropertyBase property)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.TaskLiftingExpressionVisitor.<_ExecuteAsync>d__8`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.AsyncSelectEnumerable`2.AsyncSelectEnumerator.<MoveNext>d__3.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Linq.AsyncEnumerable.<FirstOrDefault_>d__165`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.TaskResultAsyncEnumerable`1.Enumerator.<MoveNext>d__3.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Linq.AsyncEnumerable.SelectEnumerableAsyncIterator`2.<MoveNextCore>d__7.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Linq.AsyncEnumerable.AsyncIterator`1.<MoveNext>d__10.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.<MoveNext>d__5.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<ExecuteSingletonAsyncQuery>d__21`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at EfCoreBugTest.Program.Main(String[] args) in E:\Development\Sandbox\EfCoreBugTest\EfCoreBugTest\Program.cs:line 114

### Steps to reproduce
The following is a small sample program that reproduces the issue.

```c#
public class Author
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Other { get; set; }
    }
public class AuthorProfile
    {
        public int Id { get; set; }
        public int AuthorId { get; set; }
        public virtual Author Author { get; set; }
        public virtual ICollection<Post> Posts { get; set; }
    }
public class Post
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int AuthorProfileId { get; set; }
    }

public class MyDbContext : DbContext
    {
        public MyDbContext(DbContextOptions<MyDbContext> options) : base(options)
        { }

        protected override void OnModelCreating(ModelBuilder builder)
        {
            base.OnModelCreating(builder);

            builder.Entity<Author>(x => { x.HasKey(p => p.Id); });
            builder.Entity<AuthorProfile>(x =>
            {
                x.HasKey(p => p.Id);
                x.HasOne(p => p.Author).WithOne().HasForeignKey<AuthorProfile>(p => p.AuthorId).OnDelete(DeleteBehavior.Cascade);
                x.HasMany(p => p.Posts).WithOne().HasForeignKey(p => p.AuthorProfileId).OnDelete(DeleteBehavior.Cascade); 
            });
            builder.Entity<Post>(x => x.HasKey(p => p.Id));
        }
    }

public static readonly LoggerFactory MyLoggerFactory
            = new LoggerFactory(new[] { new ConsoleLoggerProvider((_, __) => true, true) });
        static void Main(string[] args)
        {
            var connection = new SqliteConnection("DataSource=:memory:");
            connection.Open();

            try
            {
                
                using (var context =
                    new MyDbContext(new DbContextOptionsBuilder<MyDbContext>().UseSqlite(connection).UseLoggerFactory(MyLoggerFactory).Options))
                {
                    context.Database.EnsureCreated();

                    var entities = new List<AuthorProfile>
                    {
                        new AuthorProfile
                        {
                            Author = new Author {Other = "Man",Name = "Bob"},
                            Posts = new List<Post>{ new Post{ Name = "Bob's first post"}}
                            },
                        new AuthorProfile
                        {
                            Author = new Author {Other = "Alien",Name = "Tom"},
                            Posts = new List<Post>{ new Post{ Name = "Tom's first post" } }
                        }
                    };
                    context.Set<AuthorProfile>().AddRange(entities);
                    var martha = new Author { Other = "Woman", Name = "Martha"};
                    context.Set<Author>().Add(martha);
                    context.SaveChanges();

                    var valid = new string[] {"Man", "Woman"};

                    var query =
                        from s in context.Set<Author>().Where(x => valid.Any(a => a == x.Other) )
                        join sp in context.Set<AuthorProfile>()
                            on s.Id equals sp.AuthorId into authprofiles
                        from profile in authprofiles.DefaultIfEmpty()
                        select new AuthorProfile
                        {
                            Id = profile == null ? 0 : profile.Id,
                            Author = s,
                            AuthorId = s.Id,
                            Posts = profile == null ? null : profile.Posts
                        };

                    var entity = query.FirstOrDefaultAsync(x => x.AuthorId == martha.Id).GetAwaiter().GetResult();
                    Console.WriteLine(entity);
                }
            }
            finally
            {
                connection.Close();
            }
        }
```

### Workaround
1) Use non Async version of call
2) Initialize navigational collection property to empty collection instead of null in select

### Further technical details
EF Core version: 2.0.0, 2.0.2, 2.0.3, 2.1.0-preview1-final
Database Provider: Microsoft.EntityFrameworkCore.Sqlite, Npgsql.EntityFrameworkCore.PostgreSQL
Operating system: Windows 10
IDE: Visual Studio 2017 15.6.0

**Comment by fasterfish** [comment]
@drjameshouse, I found workaround for the issue, try next code for your example:
`var entity = query.DefaultIfEmpty().Where(x => x != null).FirstOrDefaultAsync(x => x.AuthorId == martha.Id) .GetAwaiter().GetResult();`

**Comment by smitpatel** [comment]
```SQL
      SELECT [t].[c], [t].[Id], [t].[Name], [t].[Other], [p].[Id], [p].[AuthorProfileId], [p].[Name]
      FROM (
          SELECT TOP(1) CASE
              WHEN [a0].[Id] IS NULL THEN 0
              ELSE [a0].[Id]
          END AS [c], [a].[Id], [a].[Name], [a].[Other], [a0].[Id] AS [Id0]
          FROM [Author] AS [a]
          LEFT JOIN [AuthorProfile] AS [a0] ON [a].[Id] = [a0].[AuthorId]
          WHERE [a].[Other] IN (N'Man', N'Woman') AND ([a].[Id] = @__martha_Id_1)
      ) AS [t]
      LEFT JOIN [Post] AS [p] ON [t].[Id0] = [p].[AuthorProfileId]
      ORDER BY [t].[Id], [p].[Id]
```
