### ISSUE TITLE
Failures on Benchmarks

### ISSUE THREAD

**Issue by sebastienros** [aspnet/EntityFrameworkCore#11304]
Source:
https://github.com/aspnet/benchmarks/tree/dev/src/Benchmarks

```
[06:47:49.616] fail: Microsoft.AspNetCore.Server.Kestrel[13]
[06:47:49.616]       Connection id "0HLCBDPGVL78N", Request id "0HLCBDPGVL78N:00000049": An unhandled exception was thrown by the application.
[06:47:49.616] System.MissingMethodException: Method not found: 'System.String Microsoft.EntityFrameworkCore.Internal.CoreStrings.ArgumentIsEmpty(System.Object)'.
[06:47:49.616]    at Microsoft.EntityFrameworkCore.Utilities.Check.NotEmpty(String value, String parameterName)
[06:47:49.616]    at Microsoft.EntityFrameworkCore.NpgsqlDbContextOptionsExtensions.UseNpgsql(DbContextOptionsBuilder optionsBuilder, String connectionString, Action`1 NpgsqlOptionsAction)
[06:47:49.616]    at Benchmarks.Startup.<>c__DisplayClass8_0.<ConfigureServices>b__0(DbContextOptionsBuilder options) in /tmp/tmp91eWQU.tmp/w41s0lbx.b4o/benchmarks/src/Benchmarks/Startup.cs:line 62
[06:47:49.616]    at Microsoft.Extensions.DependencyInjection.EntityFrameworkServiceCollectionExtensions.<>c__DisplayClass5_0`2.<AddDbContextPool>b__0(IServiceProvider sp, DbContextOptionsBuilder ob)
[06:47:49.616]    at Microsoft.Extensions.DependencyInjection.EntityFrameworkServiceCollectionExtensions.DbContextOptionsFactory[TContext](IServiceProvider applicationServiceProvider, Action`2 optionsAction)
[06:47:49.616]    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
[06:47:49.616]    at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
[06:47:49.616]    at Microsoft.Extensions.DependencyInjection.EntityFrameworkServiceCollectionExtensions.<>c__5`2.<AddDbContextPool>b__5_1(IServiceProvider sp)
[06:47:49.616]    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
[06:47:49.616]    at lambda_method(Closure , ServiceProviderEngineScope )
[06:47:49.616]    at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
[06:47:49.616]    at Microsoft.Extensions.DependencyInjection.EntityFrameworkServiceCollectionExtensions.<>c__5`2.<AddDbContextPool>b__5_2(IServiceProvider sp)
[06:47:49.616]    at lambda_method(Closure , ServiceProviderEngineScope )
[06:47:49.616]    at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
[06:47:49.616]    at Benchmarks.Middleware.FortunesEfMiddleware.Invoke(HttpContext httpContext) in /tmp/tmp91eWQU.tmp/w41s0lbx.b4o/benchmarks/src/Benchmarks/Middleware/FortunesEfMiddleware.cs:line 30
[06:47:49.616]    at Microsoft.AspNetCore.Hosting.Internal.RequestServicesContainerMiddleware.Invoke(HttpContext httpContext)
[06:47:49.616]    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)


```

**Comment by divega** [comment]
@smitpatel

**Comment by smitpatel** [comment]
cc: @bricelam 

This is because of moving some messages from CoreStrings to AbstractionStrings. Which breaks providers.

**Comment by divega** [comment]
@ajcvickers @roji just the heads up that this seems to be yet another way providers uses internal types. @bricelam will add the resource back in Microsoft.EntityFrameworkCore for 2.1 to avoid breaking anyone.

**Comment by ErikEJ** [comment]
@divega Yes, I and others already mentioned this,, I plan to remove usages
