### ISSUE TITLE
DbContextPooling does not throw exception when trying to get model from disposed context

### ISSUE THREAD

**Issue by smitpatel** [aspnet/EntityFrameworkCore#11309]
Repro:
```C#
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;

namespace EFSampleApp
{
    public class Program
    {
        public static void Main(string[] args)
        {
            var serviceCollection = new ServiceCollection();
            serviceCollection.AddDbContextPool<MyContext>(
                b => b.UseInMemoryDatabase("EF"));

            var serviceProvider = serviceCollection.BuildServiceProvider();

            var db = serviceProvider.GetService<MyContext>();
            db.Dispose();
            var model = db.Model;

            Console.WriteLine("Program finished.");
        }
    }

    public class MyContext : DbContext
    {
        public MyContext(DbContextOptions<MyContext> options)
            : base(options)
        {
        }
        public DbSet<Blog> Blogs { get; set; }
    }

    public class Blog
    {
        public int Id { get; set; }
    }
}
```
Output:
// Non-pooling case
```
D:\code\EFSampleApp\EFSampleApp [2.1.0-preview1 +0 ~1 -0 !]> dotnet run

Unhandled Exception: System.ObjectDisposedException: Cannot access a disposed object. A common cause of this error is disposing a context that was resolved from dependency injection and then later trying to use the same context instance elsewhere in your application. This may occur if you are calling Dispose() on the context, or wrapping the context in a using statement. If you are using dependency injection, you should let the dependency injection container take care of disposing context instances.
Object name: 'MyContext'.
   at Microsoft.EntityFrameworkCore.DbContext.CheckDisposed()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_Model()
   at EFSampleApp.Program.Main(String[] args) in D:\code\EFSampleApp\EFSampleApp\Program.cs:line 13
```
// Pooling case
```
Program finished.
```

Disabled test Race_when_context_disposed_before_query_termination

**Comment by ajcvickers** [comment]
Assigning to @smitpatel to re-enable the test without pooling.
