### ISSUE TITLE
Benchmarks scenarios broken

### ISSUE THREAD

**Issue by sebastienros** [aspnet/EntityFrameworkCore#11399]
```
[10:50:41.232] fail: Microsoft.AspNetCore.Server.Kestrel[13]
[10:50:41.232]       Connection id "0HLCGSQA8IJCH", Request id "0HLCGSQA8IJCH:00000004": An unhandled exception was thrown by the application.
[10:50:41.232] System.TypeLoadException: Method 'Clone' in type 'Microsoft.EntityFrameworkCore.Storage.Internal.NpgsqlTypeMapping' from assembly 'Npgsql.EntityFrameworkCore.PostgreSQL, Version=2.0.1.0, Culture=neutral, PublicKeyToken=5d8b90d52f46fda7' does not have an impleme
ntation.
[10:50:41.232]    at Microsoft.EntityFrameworkCore.Storage.Internal.NpgsqlEFTypeMapper.<>c.<.ctor>b__6_1(TypeAndMapping tam)
[10:50:41.232]    at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
[10:50:41.232]    at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
[10:50:41.232]    at Microsoft.EntityFrameworkCore.Storage.Internal.NpgsqlEFTypeMapper..ctor(RelationalTypeMapperDependencies dependencies)
[10:50:41.232] --- End of stack trace from previous location where exception was thrown ---
[10:50:41.232]    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProviderEngineScope scope)
[10:50:41.232]    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
[10:50:41.237]    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProviderEngineScope scope)
[10:50:41.237]    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
[10:50:41.237]    at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
[10:50:41.237]    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
[10:50:41.237]    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProviderEngineScope scope)
[10:50:41.237]    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
[10:50:41.237]    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProviderEngineScope scope)
[10:50:41.237]    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
[10:50:41.237]    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProviderEngineScope scope)
[10:50:41.237]    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
[10:50:41.237]    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProviderEngineScope scope)
[10:50:41.237]    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
[10:50:41.237]    at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
[10:50:41.237]    at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel()
[10:50:41.237]    at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()
[10:50:41.237]    at lambda_method(Closure , ServiceProviderEngineScope )
[10:50:41.237]    at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
[10:50:41.237]    at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
[10:50:41.237]    at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
[10:50:41.237]    at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
[10:50:41.237]    at Microsoft.EntityFrameworkCore.DbContext.get_ChangeTracker()
[10:50:41.237]    at Benchmarks.Data.ApplicationDbContext..ctor(DbContextOptions options) in C:\Users\Administrator\AppData\Local\Temp\2\tmp147B.tmp\pa5hnw3x.31v\benchmarks\src\Benchmarks\Data\ApplicationDbContext.cs:line 11
[10:50:41.237]    at lambda_method(Closure )
[10:50:41.237]    at Microsoft.EntityFrameworkCore.Internal.DbContextPool`1.Rent()
[10:50:41.237]    at lambda_method(Closure , ServiceProviderEngineScope )
[10:50:41.237]    at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
[10:50:41.237]    at Microsoft.Extensions.DependencyInjection.EntityFrameworkServiceCollectionExtensions.<>c__5`2.<AddDbContextPool>b__5_2(IServiceProvider sp)
[10:50:41.237]    at lambda_method(Closure , ServiceProviderEngineScope )
[10:50:41.237]    at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
[10:50:41.241]    at Benchmarks.Middleware.FortunesEfMiddleware.Invoke(HttpContext httpContext) in C:\Users\Administrator\AppData\Local\Temp\2\tmp147B.tmp\pa5hnw3x.31v\benchmarks\src\Benchmarks\Middleware\FortunesEfMiddleware.cs:line 30
[10:50:41.241]    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
```

**Comment by bricelam** [comment]
Need to add this back: https://github.com/aspnet/EntityFrameworkCore/pull/11325/files#r176824368

**Comment by divega** [comment]
@ajcvickers this apparently a breaking change for 2.0 providers that we need to revert.

@sebastienros if you need this fixed before next week we can probably find someone else to fix it.

**Comment by sebastienros** [comment]
FYI, if I use 2.1.0-preview from Npgsql provider, I get this:

```
[11:28:21.687] fail: Microsoft.AspNetCore.Server.Kestrel[13]
[11:28:21.687]       Connection id "0HLCGTFC7EMQK", Request id "0HLCGTFC7EMQK:00000008": An unhandled exception was thrown by the application.
[11:28:21.687] System.TypeLoadException: Could not load type 'Microsoft.EntityFrameworkCore.Storage.IRelationalCoreTypeMapper' from assembly 'Microsoft.EntityFrameworkCore.Relational, Version=2.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.
[11:28:21.691]    at Microsoft.Extensions.DependencyInjection.NpgsqlEntityFrameworkServicesBuilderExtensions.AddEntityFrameworkNpgsql(IServiceCollection serviceCollection)
[11:28:21.691]    at Microsoft.EntityFrameworkCore.Infrastructure.Internal.NpgsqlOptionsExtension.ApplyServices(IServiceCollection services)
[11:28:21.691]    at Microsoft.EntityFrameworkCore.Internal.ServiceProviderCache.ApplyServices(IDbContextOptions options, ServiceCollection services)
[11:28:21.691]    at Microsoft.EntityFrameworkCore.Internal.ServiceProviderCache.<>c__DisplayClass4_0.<GetOrAdd>b__2(Int64 k)
[11:28:21.691]    at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
[11:28:21.691]    at Microsoft.EntityFrameworkCore.DbContext..ctor(DbContextOptions options)
[11:28:21.691]    at Benchmarks.Data.ApplicationDbContext..ctor(DbContextOptions options) in C:\Users\Administrator\AppData\Local\Temp\2\tmp147B.tmp\s0u4jmec.rrd\benchmarks\src\Benchmarks\Data\ApplicationDbContext.cs:line 11
[11:28:21.691]    at lambda_method(Closure )
[11:28:21.691]    at Microsoft.EntityFrameworkCore.Internal.DbContextPool`1.Rent()
[11:28:21.691]    at lambda_method(Closure , ServiceProviderEngineScope )
[11:28:21.691]    at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
[11:28:21.691]    at Microsoft.Extensions.DependencyInjection.EntityFrameworkServiceCollectionExtensions.<>c__5`2.<AddDbContextPool>b__5_2(IServiceProvider sp)
[11:28:21.691]    at lambda_method(Closure , ServiceProviderEngineScope )
[11:28:21.691]    at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
[11:28:21.691]    at Benchmarks.Middleware.FortunesEfMiddleware.Invoke(HttpContext httpContext) in C:\Users\Administrator\AppData\Local\Temp\2\tmp147B.tmp\s0u4jmec.rrd\benchmarks\src\Benchmarks\Middleware\FortunesEfMiddleware.cs:line 30
[11:28:21.691]    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
```

**Comment by bricelam** [comment]
@sebastienros Possibly expected--we've had a lot of churn in this area
