### ISSUE TITLE
Query: `Must be reducible node` thrown for some queries using 'let' keyword

### ISSUE THREAD

**Issue by QuantumHive** [aspnet/EntityFrameworkCore#11425]
I'd like to cast a `DateTime` property from my entity model to a nullable `DateTime` and set it on my [DTO](https://en.wikipedia.org/wiki/Data_transfer_object). Whenever I do that in my select statement within my linq query I'm getting the following exception:

```
Exception message: must be reducible node
Stack trace:

System.ArgumentException: must be reducible node
   at System.Linq.Expressions.Expression.ReduceAndCheck()
   at System.Linq.Expressions.Expression.ReduceExtensions()
   at System.Linq.Expressions.Compiler.StackSpiller.RewriteExtensionExpression(Expression expr, Stack stack)
   at System.Linq.Expressions.Compiler.StackSpiller.RewriteExpression(Expression node, Stack stack)
   at System.Linq.Expressions.Compiler.StackSpiller.RewriteMemberExpression(Expression expr, Stack stack)
   at System.Linq.Expressions.Compiler.StackSpiller.RewriteExpression(Expression node, Stack stack)
   at System.Linq.Expressions.Compiler.StackSpiller.ChildRewriter.Add(Expression expression)
   at System.Linq.Expressions.Compiler.StackSpiller.RewriteBinaryExpression(Expression expr, Stack stack)
   at System.Linq.Expressions.Compiler.StackSpiller.RewriteExpression(Expression node, Stack stack)
   at System.Linq.Expressions.Compiler.StackSpiller.RewriteExpressionFreeTemps(Expression expression, Stack stack)
   at System.Linq.Expressions.Compiler.StackSpiller.Rewrite[T](Expression`1 lambda)
   at System.Linq.Expressions.Expression`1.Accept(StackSpiller spiller)
   at System.Linq.Expressions.Compiler.StackSpiller.RewriteLambdaExpression(Expression expr)
   at System.Linq.Expressions.Compiler.StackSpiller.RewriteExpression(Expression node, Stack stack)
   at System.Linq.Expressions.Compiler.StackSpiller.ChildRewriter.Add(Expression expression)
   at System.Linq.Expressions.Compiler.StackSpiller.ChildRewriter.AddArguments(IArgumentProvider expressions)
   at System.Linq.Expressions.Compiler.StackSpiller.RewriteMethodCallExpression(Expression expr, Stack stack)
   at System.Linq.Expressions.Compiler.StackSpiller.RewriteExpression(Expression node, Stack stack)
   at System.Linq.Expressions.Compiler.StackSpiller.ChildRewriter.Add(Expression expression)
   at System.Linq.Expressions.Compiler.StackSpiller.ChildRewriter.AddArguments(IArgumentProvider expressions)
   at System.Linq.Expressions.Compiler.StackSpiller.RewriteMethodCallExpression(Expression expr, Stack stack)
   at System.Linq.Expressions.Compiler.StackSpiller.RewriteExpression(Expression node, Stack stack)
   at System.Linq.Expressions.Compiler.StackSpiller.ChildRewriter.Add(Expression expression)
   at System.Linq.Expressions.Compiler.StackSpiller.ChildRewriter.AddArguments(IArgumentProvider expressions)
   at System.Linq.Expressions.Compiler.StackSpiller.RewriteMethodCallExpression(Expression expr, Stack stack)
   at System.Linq.Expressions.Compiler.StackSpiller.RewriteExpression(Expression node, Stack stack)
   at System.Linq.Expressions.Compiler.StackSpiller.ChildRewriter.Add(Expression expression)
   at System.Linq.Expressions.Compiler.StackSpiller.ChildRewriter.AddArguments(IArgumentProvider expressions)
   at System.Linq.Expressions.Compiler.StackSpiller.RewriteMethodCallExpression(Expression expr, Stack stack)
   at System.Linq.Expressions.Compiler.StackSpiller.RewriteExpression(Expression node, Stack stack)
   at System.Linq.Expressions.Compiler.StackSpiller.RewriteUnaryExpression(Expression expr, Stack stack)
   at System.Linq.Expressions.Compiler.StackSpiller.RewriteExpression(Expression node, Stack stack)
   at System.Linq.Expressions.Compiler.StackSpiller.RewriteConditionalExpression(Expression expr, Stack stack)
   at System.Linq.Expressions.Compiler.StackSpiller.RewriteExpression(Expression node, Stack stack)
   at System.Linq.Expressions.Compiler.StackSpiller.MemberAssignmentRewriter..ctor(MemberAssignment binding, StackSpiller spiller, Stack stack)
   at System.Linq.Expressions.Compiler.StackSpiller.BindingRewriter.Create(MemberBinding binding, StackSpiller spiller, Stack stack)
   at System.Linq.Expressions.Compiler.StackSpiller.RewriteMemberInitExpression(Expression expr, Stack stack)
   at System.Linq.Expressions.Compiler.StackSpiller.RewriteExpression(Expression node, Stack stack)
   at System.Linq.Expressions.Compiler.StackSpiller.RewriteExpressionFreeTemps(Expression expression, Stack stack)
   at System.Linq.Expressions.Compiler.StackSpiller.Rewrite[T](Expression`1 lambda)
   at System.Linq.Expressions.Expression`1.Accept(StackSpiller spiller)
   at System.Linq.Expressions.Compiler.StackSpiller.RewriteLambdaExpression(Expression expr)
   at System.Linq.Expressions.Compiler.StackSpiller.RewriteExpression(Expression node, Stack stack)
   at System.Linq.Expressions.Compiler.StackSpiller.ChildRewriter.Add(Expression expression)
   at System.Linq.Expressions.Compiler.StackSpiller.ChildRewriter.AddArguments(IArgumentProvider expressions)
   at System.Linq.Expressions.Compiler.StackSpiller.RewriteMethodCallExpression(Expression expr, Stack stack)
   at System.Linq.Expressions.Compiler.StackSpiller.RewriteExpression(Expression node, Stack stack)
   at System.Linq.Expressions.Compiler.StackSpiller.ChildRewriter.Add(Expression expression)
   at System.Linq.Expressions.Compiler.StackSpiller.ChildRewriter.AddArguments(IArgumentProvider expressions)
   at System.Linq.Expressions.Compiler.StackSpiller.RewriteMethodCallExpression(Expression expr, Stack stack)
   at System.Linq.Expressions.Compiler.StackSpiller.RewriteExpression(Expression node, Stack stack)
   at System.Linq.Expressions.Compiler.StackSpiller.RewriteExpressionFreeTemps(Expression expression, Stack stack)
   at System.Linq.Expressions.Compiler.StackSpiller.Rewrite[T](Expression`1 lambda)
   at System.Linq.Expressions.Expression`1.Accept(StackSpiller spiller)
   at System.Linq.Expressions.Compiler.LambdaCompiler.Compile(LambdaExpression lambda)
   at System.Linq.Expressions.Expression`1.Compile(Boolean preferInterpretation)
   at System.Linq.Expressions.Expression`1.Compile()
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.CreateExecutorLambda[TResults]()
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.CreateQueryExecutor[TResult](QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](QueryModel queryModel)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](Expression query, INodeTypeProvider nodeTypeProvider, IDatabase database, IDiagnosticsLogger`1 logger, Type contextType)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass15_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQueryCore[TFunc](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
   at Remotion.Linq.QueryableBase`1.GetEnumerator()
   at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
```

### Steps to reproduce
Given the following models:

```c#
public class Item
{
    public IEnumerable<SubItem> SubItems { get; set; }
}
public class SubItem
{
     public DateTime Date { get; set; }
}
```

```c#
from item in db.Set<Item>()
let subitems =
    from subitem in item.SubItems
    select subitem.Date
select new
{
    Date = subitems.Any() ? (DateTime?)subitem.First() : null
}
```

where `db` is an instance of the database context.

### Further technical details
EF Core version: 2.0
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10
IDE: Visual Studio 2017 15.6.4

**Comment by QuantumHive** [comment]
After some more digging and hours of headaches, I've noticed the exception is thrown because of the `.Any()`  call. Casting has nothing to do with it. Let's simplify the example:

```
from item in db.Set<Item>()
let subitems =
    from subitem in item.SubItems
    where subitem.Date < someDate
    select subitem.Date
where subItems.Any()
select new
{
    Count = subitems.Count()
}
```

It appears that whenever I put the `where subItems.Any()`, the exception gets thrown. If I remove that line, then no exception is thrown and the query performs (which would make the query invalid).  
However my workaround is:

```
from item in db.Set<Item>()
let subitems = (
    from subitem in item.SubItems
    where subitem.Date < someDate
    select subitem.Date).ToArray()
where subItems.Any()
select new
{
    Count = subitems.Count()
}
```

to put a `.ToArray()` around the subquery. However this really has a big impact on performance, so this is not a workable solution/workaround. In production, this query alone would already hit more than 10 seconds, and put the 20 DTU's on the Azure SQL Database at 100%, which is obviously unacceptable.  

Why is this exception thrown? Is this a confirmed bug? Or am I doing something wrong?  

Also I'd like to suggest to improve the exception message. The message doesn't help me to find the root of the problem. My example was just an extremely simplified version of the query I'm dealing with in code.

**Comment by SSkovboiSS** [comment]
Looks similar to #9751

**Comment by ShamsulAmry** [comment]
Facing exact same issue. I'm trying to have something similar to the subitems subquery above as a means to not duplicate the where clause and thus prevent unnecessary future human error.

**Comment by maumar** [comment]
@QuantumHive problem here is the "let" statement - currently EFCore doesn't handle it well. As a workaround you can inline the subquery like so:

```cs
var query = from item in db.Set<Item11425>()
			where 
				(from subitem in item.SubItems
				where subitem.Date < someDate
				select subitem.Date).Any()
			select new
			{
				Count = (from subitem in item.SubItems
						 where subitem.Date < someDate
						 select subitem.Date).Count()
			};
```

It's not ideal since it makes queries ugly and as @ShamsulAmry pointed out could lead to coding errors, but it should produce efficient query:

```sql
SELECT (
	SELECT COUNT(*)
	FROM [SubItems] AS [subitem0]
	WHERE ([subitem0].[Date] < @__someDate_1) AND ([item].[Id] = [subitem0].[Item11425Id])
) AS [Count]
FROM [Items] AS [item]
WHERE EXISTS (
	SELECT 1
	FROM [SubItems] AS [subitem]
	WHERE ([subitem].[Date] < @__someDate_0) AND ([item].[Id] = [subitem].[Item11425Id]))
```

wrt the exception message - it happens when unexpected (non-reducible) node is present in the final query plan, just before it gets compiled. It usually means a wrong assumptions somewhere in the compiler, or entire scenario that was not accounted for. Providing a better error would incur some perf impact (either validate the final tree before compilation or catch & rethrow) and it would be hard to provide better message than "something went wrong".
