### ISSUE TITLE
Deleting/Updating entities with Unique Filtered Index - ArgumentException: An item with the same key has already been added

### ISSUE THREAD

**Issue by Carq** [aspnet/EntityFrameworkCore#11505]
Exception ArgumentException: "An item with the same key has already been added" is thrown when DbContext.SaveChanges() is invoked after changes in two or more entities with Filtered Unique Index.

```
Exception message: An item with the same key has already been added. Key: System.Object[]
Stack trace:
   at System.ThrowHelper.ThrowAddingDuplicateWithKeyArgumentException(Object key)
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at Microsoft.EntityFrameworkCore.Update.Internal.CommandBatchPreparer.AddUniqueValueEdges(Multigraph`2 commandGraph)
   at Microsoft.EntityFrameworkCore.Update.Internal.CommandBatchPreparer.TopologicalSort(IEnumerable`1 commands)
   at Microsoft.EntityFrameworkCore.Update.Internal.CommandBatchPreparer.<BatchCommands>d__8.MoveNext()
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(Tuple`2 parameters)
   at Microsoft.EntityFrameworkCore.Storage.Internal.SqlServerExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.ExecutionStrategyExtensions.Execute[TState,TResult](IExecutionStrategy strategy, TState state, Func`2 operation)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(IEnumerable`1 commandBatches, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Storage.RelationalDatabase.SaveChanges(IReadOnlyList`1 entries)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IReadOnlyList`1 entriesToSave)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges()
```

### Steps to reproduce
Here is complete code listing: https://github.com/Carq/EFCore.UniqueFilteredIndex

#### Partial code listings
Creating model in DbContext:
```c#
protected override void OnModelCreating(ModelBuilder modelBuilder)
{
    modelBuilder
      .Entity<User>()
      .HasIndex("Email", "Login")
      .HasFilter("IsActive = 1")
      .IsUnique();
}
```

Code in which the exception is thrown:
```c#
static void Main(string[] args)
{
    CreateTwoTheSameEntitiesWhichDoNotMetFilterConditions(context);
    RemoveTwoEntitiesWithFilteredIndex(context);
}

private static void RemoveTwoEntitiesWithFilteredIndex(JustDatabaseContext context)
{
    var entitiesToDelete = context.Users.Where(x => x.IsActive == false);
    context.RemoveRange(entitiesToDelete);

    // The problem occurs during saving changes
    context.SaveChanges();
}

private static void CreateTwoTheSameEntitiesWhichDoNotMetFilterConditions(JustDatabaseContext context)
{
    context.Users.Add(new Model.User { IsActive = false, Login = "2", Email = "Jan@Kowalski.pl" });
    context.Users.Add(new Model.User { IsActive = false, Login = "2", Email = "Jan@Kowalski.pl" });
    context.SaveChanges();
}
```

### Further technical details
EF Core version: **2.0.2**
Database Provider: **Microsoft.EntityFrameworkCore.SqlServer 2.0.2**
Operating system: **Windows 10 Pro**
IDE: **Visual Studio 2017 15.6.4**

### Workaround 1
Invoke DbContext.SaveChanges() after change in single entity

### Workaround 2
Remove code responsible for adding filter index after migration creation.
```c#
protected override void OnModelCreating(ModelBuilder modelBuilder)
{
    /// Removing this code after migration creation will solve the problem
    modelBuilder
      .Entity<User>()
      .HasIndex("Email", "Login")
      .HasFilter("IsActive = 1")
      .IsUnique();
}
```

**Comment by smitpatel** [comment]
Related #11062
