### ISSUE TITLE
Small issue in wiky - Getting and building the Code

### ISSUE THREAD

**Issue by ilmax** [aspnet/EntityFrameworkCore#11519]
In the wiki there's an error in the **[Getting and building the Code](https://github.com/aspnet/EntityFrameworkCore/wiki/getting-and-building-the-code#build-from-visual-studio)** page.
The powershell command to correctly change the PATH variable should be this one
`
$env:PATH="$env:USERPROFILE/.dotnet/x64;"+$env:PATH
`
i.e. the semicolon should be inside the string not outside otherwise this error is raised:

```
Cannot convert value "C:\Users\Whatever/.dotnet/x64" to type "System.Int32". Error: "Input string was not in a correct
format."
At line:1 char:42
+ $env:PATH="$env:USERPROFILE/.dotnet/x64";+$env:PATH
+                                          ~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvalidCastFromStringToInteger

```

**Comment by smitpatel** [comment]
Updated. Let us know if there is anything else we can improve on that page to make it easier for external contributors.

**Comment by ilmax** [comment]
I've got some xUnit error and to fix them I had to update xUnit and add a binding redirect to the test runner, but I wasn't sure if it was worth mentioning/creating an issue.

**Comment by smitpatel** [comment]
Can you specify what kind of errors? And which version of xUnit are you using? (previous version and the version which fixed issues)

**Comment by ilmax** [comment]
Uhm, I was using the xUnit visual studio runner defined in `dependencies.props` and it wasn't able to run tests from inside VS, this was the error:

```
[02-Apr-18 10:33:32 PM Informational] [xUnit.net 00:00:00.0154623] xUnit.net VSTest Adapter v2.4.0-beta.1.build3945 (32-bit Universal Windows)
[02-Apr-18 10:33:32 PM Error] [xUnit.net 00:00:00.0739876] Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests: Catastrophic failure: System.InvalidOperationException: The process has no package identity. (Exception from HRESULT: 0x80073D54)
   at Windows.ApplicationModel.Package.get_Current()
   at Xunit.Runner.VisualStudio.VsTestRunner.RunTestsInAssembly(IRunContext runContext, IFrameworkHandle frameworkHandle, LoggerHelper logger, TestPlatformContext testPlatformContext, RunSettings runSettings, IMessageSinkWithTypes reporterMessageHandler, AssemblyRunInfo runInfo)
[02-Apr-18 10:33:32 PM Warning] No test is available in C:\Code\EntityFrameworkCore\test\EFCore.SqlServer.FunctionalTests\bin\Debug\net461\Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests.dll. Make sure that test discoverer & executors are registered and platform & framework version settings are appropriate and try again.

```
so after some research I updated the runner, this is the output of git diff
```
diff --git a/build/dependencies.props b/build/dependencies.props
index 508191f73..c6627739b 100644
--- a/build/dependencies.props
+++ b/build/dependencies.props
@@ -36,7 +36,7 @@
     <SystemInteractiveAsyncPackageVersion>3.1.1</SystemInteractiveAsyncPackageVersion>
     <XunitAssertPackageVersion>2.3.1</XunitAssertPackageVersion>
     <XunitCorePackageVersion>2.3.1</XunitCorePackageVersion>
-    <XunitRunnerVisualStudioPackageVersion>2.4.0-beta.1.build3945</XunitRunnerVisualStudioPackageVersion>
+    <XunitRunnerVisualStudioPackageVersion>2.4.0-beta.2.build3981</XunitRunnerVisualStudioPackageVersion>
   </PropertyGroup>
   <Import Project="$(DotNetPackageVersionPropsPath)" Condition=" '$(DotNetPackageVersionPropsPath)' != '' " />
 </Project>
diff --git a/build/sources.props b/build/sources.props
index 9215df975..c0562423d 100644
--- a/build/sources.props
+++ b/build/sources.props
@@ -8,6 +8,7 @@
       https://dotnet.myget.org/F/dotnet-core/api/v3/index.json;
       https://dotnet.myget.org/F/aspnetcore-dev/api/v3/index.json;
       https://dotnet.myget.org/F/aspnetcore-tools/api/v3/index.json;
+         https://www.myget.org/F/xunit/api/v3/index.json;
     </RestoreSources>
     <RestoreSources Condition="'$(DotNetBuildOffline)' != 'true'">
       $(RestoreSources);
```

After this change I was able to run and debug tests from VS.
Please note that I didn't had any problem running test from command line.

**Comment by smitpatel** [comment]
@ilmax - You hit the issue mentioned here https://github.com/xunit/xunit/issues/1665

**Comment by ilmax** [comment]
yep, but with the mentioned workaround I was able to make test runner to work
