### ISSUE TITLE
Investigate ProxyGraphUpdatesOracleTest failures

### ISSUE THREAD

**Issue by AndriySvyryd** [aspnet/EntityFrameworkCore#11554]
Tests fail with
>	System.AggregateException : One or more errors occurred.
---- Oracle.ManagedDataAccess.Client.OracleException : ORA-00972: identifier is too long
ORA-06512: at line 2
---- The following constructor parameters did not have matching fixture data: ProxyGraphUpdatesWithLazyLoadingOracleFixture fixture
	
>	----- Inner Stack Trace #1 (Oracle.ManagedDataAccess.Client.OracleException) -----
	at OracleInternal.ServiceObjects.OracleConnectionImpl.VerifyExecution(Int32& cursorId, Boolean bThrowArrayBindRelatedErrors, SqlStatementType sqlStatementType, Int32 arrayBindCount, OracleException& exceptionForArrayBindDML, Boolean& hasMoreRowsInDB, Boolean bFirstIterationDone)
	at OracleInternal.ServiceObjects.OracleCommandImpl.ExecuteNonQuery(String commandText, OracleParameterCollection paramColl, CommandType commandType, OracleConnectionImpl connectionImpl, Int32 longFetchSize, Int64 clientInitialLOBFS, OracleDependencyImpl orclDependencyImpl, Int64[]& scnFromExecution, OracleParameterCollection& bindByPositionParamColl, Boolean& bBindParamPresent, OracleException& exceptionForArrayBindDML, OracleConnection connection, OracleLogicalTransaction& oracleLogicalTransaction, Boolean isFromEF)
	at Oracle.ManagedDataAccess.Client.OracleCommand.ExecuteNonQuery()
	at Microsoft.EntityFrameworkCore.TestUtilities.OracleTestStore.<>c.<ExecuteNonQuery>b__30_0(DbCommand command)
	at Microsoft.EntityFrameworkCore.TestUtilities.OracleTestStore.ExecuteCommand[T](DbConnection connection, Func`2 execute, String sql, Boolean useTransaction, Object[] parameters)
	at Microsoft.EntityFrameworkCore.TestUtilities.OracleTestStore.Execute[T](DbConnection connection, Func`2 execute, String sql, Boolean useTransaction, Object[] parameters)
	at Microsoft.EntityFrameworkCore.TestUtilities.OracleTestStore.ExecuteNonQuery(DbConnection connection, String sql, Object[] parameters)
	at Microsoft.EntityFrameworkCore.TestUtilities.OracleTestStore.CreateDatabase()
	at Microsoft.EntityFrameworkCore.TestUtilities.OracleTestStore.Initialize(Func`1 createContext, Action`1 seed)
	at Microsoft.EntityFrameworkCore.TestUtilities.TestStore.<>c__DisplayClass11_0.<Initialize>b__1()
	at Microsoft.EntityFrameworkCore.TestUtilities.TestStoreIndex.CreateShared(String name, Action initializeDatabase)
	at Microsoft.EntityFrameworkCore.TestUtilities.TestStore.Initialize(IServiceProvider serviceProvider, Func`1 createContext, Action`1 seed)
	at Microsoft.EntityFrameworkCore.TestUtilities.RelationalTestStore.Initialize(IServiceProvider serviceProvider, Func`1 createContext, Action`1 seed)
	at Microsoft.EntityFrameworkCore.SharedStoreFixtureBase`1..ctor()
	at Microsoft.EntityFrameworkCore.ProxyGraphUpdatesTestBase`1.ProxyGraphUpdatesFixtureBase..ctor()
	at Microsoft.EntityFrameworkCore.ProxyGraphUpdatesOracleTest.ProxyGraphUpdatesOracleTestBase`1.ProxyGraphUpdatesOracleFixtureBase..ctor()
	at Microsoft.EntityFrameworkCore.ProxyGraphUpdatesOracleTest.LazyLoading.ProxyGraphUpdatesWithLazyLoadingOracleFixture..ctor()
	----- Inner Stack Trace #2 (Xunit.Sdk.TestClassException) -----

**Comment by ajcvickers** [comment]
@smitpatel to investigate what is failing, and whether we should fix or punt.

**Comment by ralmsdeveloper** [comment]
This is caused by a column / table name greater than 30 characters!

**Comment by ralmsdeveloper** [comment]
@ajcvickers in an attempt to help.

I did some tests:
One of the problems is the user name '**ProxyGraphLazyLoadingUpdatesTest**', we have a limitation of 30 character, and we are trying to create a user 32 characters.

I believe it can be resolved here:
https://github.com/aspnet/EntityFrameworkCore/blob/dev/samples/OracleProvider/test/OracleProvider.FunctionalTests/TestUtilities/OracleTestStore.cs#L118-L121

With something like this:
```csharp
private static string ResolveName(string name)
    => name.Substring(0, Math.Min(name.Length, 30));

ExecuteNonQuery(
    master,
    $@"BEGIN
                EXECUTE IMMEDIATE 'CREATE USER {ResolveName(Name)} IDENTIFIED BY {ResolveName(Name)}';
                EXECUTE IMMEDIATE 'GRANT DBA TO {ResolveName(Name)}';
            END;");
```

Or shorten the class name.

**Comment by ralmsdeveloper** [comment]
If it were to use the above logic to shorten the name it would have to refactor some things in **OracleTestStore.cs**

**Comment by smitpatel** [comment]
@ralmsdeveloper - That seems like a good fix. Can you submit a PR?

**Comment by ralmsdeveloper** [comment]
@smitpatel Done!
