### ISSUE TITLE
IQueryable.CountAsync wth no predicate throws exception when used in conjunction with Cast

### ISSUE THREAD

**Issue by LizNettleship** [aspnet/EntityFrameworkCore#11596]
Exception thrown when using CountAsync on an IQueryable with Cast
               var a = filteredAccountData.FilteredContext(databaseContext.Account.AsNoTracking().AsQueryable());
                var b = a.CountAsync().GetAwaiter().GetResult(); //works

                var c = a.Cast<AccountEntity>();

                var e = c.CountAsync(x => true).GetAwaiter().GetResult(); // works

                var f = c.ToListAsync().GetAwaiter().GetResult(); //works

                var d = c.CountAsync().GetAwaiter().GetResult(); //blows up
If you are seeing an exception, include the full exceptions details (message and stack trace).
```
Exception message:

Message: Test method Api.UnitTests.Repositories.AccountRepositoryUnitTests.AccountRepositoryDataRetrievalTests.UsingAccountRepositoryCountAsync_WithSeededData_ReturnsCorrectCount threw exception: 
System.ArgumentException: Expression of type 'System.Collections.Generic.IAsyncEnumerable`1[Microsoft.EntityFrameworkCore.Storage.ValueBuffer]' cannot be used for parameter of type 'System.Collections.Generic.IAsyncEnumerable`1[System.Object]' of method 'System.Collections.Generic.IAsyncEnumerable`1[Api.Data.Entities.AccountEntity] Cast[AccountEntity](System.Collections.Generic.IAsyncEnumerable`1[System.Object])'
Stack trace:
Result1 StackTrace:	
at System.Linq.Expressions.Expression.ValidateOneArgument(MethodBase method, ExpressionType nodeKind, Expression arg, ParameterInfo pi)
   at System.Linq.Expressions.Expression.Call(MethodInfo method, Expression arg0)
   at Microsoft.EntityFrameworkCore.Query.ResultOperatorHandler.HandleResultOperator(EntityQueryModelVisitor entityQueryModelVisitor, ResultOperatorBase resultOperator, QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.Internal.RelationalResultOperatorHandler.HandleResultOperator(EntityQueryModelVisitor entityQueryModelVisitor, ResultOperatorBase resultOperator, QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.VisitResultOperator(ResultOperatorBase resultOperator, QueryModel queryModel, Int32 index)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor.VisitResultOperator(ResultOperatorBase resultOperator, QueryModel queryModel, Int32 index)
   at Remotion.Linq.QueryModelVisitorBase.VisitResultOperators(ObservableCollection`1 resultOperators, QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.VisitQueryModel(QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor.VisitQueryModel(QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.CreateAsyncQueryExecutor[TResult](QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQueryCore[TFunc](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteAsync[TResult](Expression query, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.ExecuteAsync[TResult](Expression expression, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ExecuteAsync[TSource,TResult](MethodInfo operatorMethodInfo, IQueryable`1 source, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.CountAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
   at Api.Data.Repositories.AccountRepository.GetBaseData(String[] includes) in C:\Users\LizN\source\repos\MODA.Service\MODA\Api\Data\Repositories\AccountRepository.cs:line 69
   at Api.Data.Repositories.AccountRepository.CountAsync() in C:\Users\LizN\source\repos\MODA.Service\MODA\Api\Data\Repositories\AccountRepository.cs:line 36
   at Api.UnitTests.Repositories.AccountRepositoryUnitTests.AccountRepositoryDataRetrievalTests.<UsingAccountRepositoryCountAsync_WithSeededData_ReturnsCorrectCount>d__0.MoveNext() in C:\Users\LizN\source\repos\MODA.Service\MODA\Api.UnitTests\Repositories\AccountRepositoryUnitTests\AccountRepositoryDataRetrievalTests.cs:line 42
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices.ThreadOperations.ExecuteWithAbortSafety(Action action)

### Steps to reproduce
Include a complete code listing (or project/solution) that we can run to reproduce the issue.

Partial code listings, or multiple fragments of code, will slow down our response or cause us to push the issue back to you to provide code to reproduce the issue.

```c#
  var a = filteredAccountData.FilteredContext(databaseContext.Account.AsNoTracking().AsQueryable());
                var b = a.CountAsync().GetAwaiter().GetResult(); //works

                var c = a.Cast<AccountEntity>();

                var e = c.CountAsync(x => true).GetAwaiter().GetResult(); // works

                var f = c.ToListAsync().GetAwaiter().GetResult(); //works

                var d = c.CountAsync().GetAwaiter().GetResult(); //blows up
```

### Further technical details
EF Core version: (found in project.csproj or packages.config) 2.0.1
Database Provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer) Sqlite (in memory)
Operating system: windows 10
IDE: (e.g. Visual Studio 2017 15.4) Visual Studio Version 15.5.6

**Comment by smitpatel** [comment]
@LizNettleship - There is not enough info for us to investigate this issue.
Specifically,
 - The shape of `a` is unknown. That is the actual query on which operators are being called but its construction is opaque in the code listing. Just the exact queryable value of `a` would be enough.
- Is `a` is IQueryable of `AccountEntity` or some base type of `AccountEntity`?
- Is `AccountEntity` is part of the model?
- Does the test work in sync code path?

**Comment by LizNettleship** [comment]
@smitpatel  Attached is a sample project and tests 
[Repository.zip](https://github.com/aspnet/EntityFrameworkCore/files/1894292/Repository.zip)
[RepositoryTests.zip](https://github.com/aspnet/EntityFrameworkCore/files/1894293/RepositoryTests.zip)

**Comment by smitpatel** [comment]
@LizNettleship - Thanks for repro code. I am able to reproduce this.
The query which fails
`db.Account.Cast<AccountEntity>().CountAsync();`
