### ISSUE TITLE
Flaky: ComplexNavigationsWeakQuerySqlServerTest.Level4_Include

### ISSUE THREAD

**Issue by ryanbrandenburg** [aspnet/EntityFrameworkCore#11599]
This test [fails](http://aspnetci/viewLog.html?buildId=442715&tab=buildResultsDiv&buildTypeId=XPlat_Windows_Win8_Universe#testNameId7594357616969876089) occasionally with the following error:

```
Assert.Equal() Failure
                  ↓ (pos 8)
Expected: SELECT [l1.OneToOne_Required_PK.OneToOne_Required···
Actual:   SELECT [t.OneToOne_Required_PK.OneToOne_Required_···
                  ↑ (pos 8)
   at Microsoft.EntityFrameworkCore.TestUtilities.TestSqlLoggerFactory.AssertBaseline(String[] expected, Boolean assertOrder)
   at Microsoft.EntityFrameworkCore.Query.ComplexNavigationsWeakQuerySqlServerTest.AssertSql(String[] expected)
   at Microsoft.EntityFrameworkCore.Query.ComplexNavigationsWeakQuerySqlServerTest.Level4_Include()
```

Future instances of this failure can be found [here](http://aspnetci/project.html?projectId=XPlat&buildTypeId=&tab=testDetails&testNameId=7594357616969876089&order=TEST_STATUS_DESC&branch_XPlat=__all_branches__&itemsCount=50).

**Comment by smitpatel** [comment]
@ryanbrandenburg - Please let us know when this test fails after the merged PR propagates to build system. We had added additional logging steps to help us debug.
