### ISSUE TITLE
Query with projection cast on correlated collections throws on 2.1.0-preview2

### ISSUE THREAD

**Issue by mbashov** [aspnet/EntityFrameworkCore#11687]
The following query selecting a collection of projections and casting them to a base class throws:

```c#
using System;
using System.Collections.Generic;
using System.Data.Common;
using System.Linq;
using Microsoft.Data.Sqlite;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;

class Program
{
    static void Main(string[] args)
    {
        using (var db = new Context())
        {
            var query = db
                .Entities
                .Select(e => new
                {
                    Dependent = e
                        .Dependent
                        .Select(d => new DependentProjection2 { Id = d.Id })
                        .ToList<DependentProjection1>()
                })
                .ToList();
        }

        Console.WriteLine("Program finished.");
    }
}

public class Context : DbContext
{
    public DbSet<Main> Entities { get; set; }
    public DbSet<Dependent> Values { get; set; }
}

public class Main
{
    public int Id { get; set; }
    public ICollection<Dependent> Dependent { get; set; }
}

public class Dependent
{
    public int Id { get; set; }
    public int MainId { get; set; }
    public Main Main { get; set; }
}

public class MainProjection
{
    public ICollection<DependentProjection1> Dependent { get; set; }
}

public class DependentProjection1
{
    public int Id { get; set; }
}

public class DependentProjection2 : DependentProjection1
{
}
```

```
System.InvalidOperationException: 'No coercion operator is defined between types 'System.Collections.Generic.List`1[DependentProjection2]' and 'System.Collections.Generic.List`1[DependentProjection1]'.'
Stack trace:
   at System.Linq.Expressions.Expression.GetUserDefinedCoercionOrThrow(ExpressionType coercionType, Expression expression, Type convertToType)
   at System.Linq.Expressions.Expression.Convert(Expression expression, Type type, MethodInfo method)
   at Remotion.Linq.Parsing.RelinqExpressionVisitor.<AdjustArgumentsForNewExpression>d__0.MoveNext()
   at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
   at System.Dynamic.Utils.CollectionExtensions.ToReadOnly[T](IEnumerable`1 enumerable)
   at System.Linq.Expressions.Expression.New(ConstructorInfo constructor, IEnumerable`1 arguments, IEnumerable`1 members)
   at System.Linq.Expressions.NewExpression.Accept(ExpressionVisitor visitor)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.TryOptimizeCorrelatedCollections(QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.VisitSelectClause(SelectClause selectClause, QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor.VisitSelectClause(SelectClause selectClause, QueryModel queryModel)
   at Remotion.Linq.QueryModelVisitorBase.VisitQueryModel(QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.VisitQueryModel(QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor.VisitQueryModel(QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.CreateQueryExecutor[TResult](QueryModel queryModel)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](Expression query, IQueryModelGenerator queryModelGenerator, IDatabase database, IDiagnosticsLogger`1 logger, Type contextType)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass13_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQueryCore[TFunc](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Remotion.Linq.QueryableBase`1.GetEnumerator()
   at System.Collections.Generic.List`1.AddEnumerable(IEnumerable`1 enumerable)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Program.Main(String[] args)
```

Also, if the anonymous class is replaced with an explicit class with public properties, the exception message is far less helpful:

```c#
            var query = db
                .Entities
                .Select(e => new MainProjection
                {
                    Dependent = e
                        .Dependent
                        .Select(d => new DependentProjection2 { Id = d.Id })
                        .ToList<DependentProjection1>()
                })
                .ToList();
```

```
System.ArgumentException: 'Argument types do not match'
Stack trace:
   at System.Linq.Expressions.Expression.Bind(MemberInfo member, Expression expression)
   at System.Linq.Expressions.MemberAssignment.Update(Expression expression)
   at System.Linq.Expressions.ExpressionVisitor.VisitMemberAssignment(MemberAssignment node)
   at System.Linq.Expressions.ExpressionVisitor.VisitMemberBinding(MemberBinding node)
   at System.Linq.Expressions.ExpressionVisitor.Visit[T](ReadOnlyCollection`1 nodes, Func`2 elementVisitor)
   at System.Linq.Expressions.ExpressionVisitor.VisitMemberInit(MemberInitExpression node)
   at System.Linq.Expressions.MemberInitExpression.Accept(ExpressionVisitor visitor)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.TryOptimizeCorrelatedCollections(QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.VisitSelectClause(SelectClause selectClause, QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor.VisitSelectClause(SelectClause selectClause, QueryModel queryModel)
   at Remotion.Linq.QueryModelVisitorBase.VisitQueryModel(QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.VisitQueryModel(QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor.VisitQueryModel(QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.CreateQueryExecutor[TResult](QueryModel queryModel)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](Expression query, IQueryModelGenerator queryModelGenerator, IDatabase database, IDiagnosticsLogger`1 logger, Type contextType)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass13_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQueryCore[TFunc](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Remotion.Linq.QueryableBase`1.GetEnumerator()
   at System.Collections.Generic.List`1.AddEnumerable(IEnumerable`1 enumerable)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Program.Main(String[] args)
```

EF Core version: 2.1.0-preview2-final

**Comment by maumar** [comment]
We should detect this case and revert back to old behavior for 2.1 release. Also opened https://github.com/aspnet/EntityFrameworkCore/issues/11699 to use optimization for result ops post 2.1

**Comment by maumar** [comment]
workaround is to perform the type conversion on the client:

```cs

                var query = db
                    .Entities
                    .Select(e => new
                    {
                        Dependent = e
                            .Dependent
                            .Select(d => new DependentProjection2 { Id = d.Id })
                            .ToList()
                    })
                    .ToList().Select(e => new { Dependent = e.Dependent.Cast<DependentProjection1>() });
```

**Comment by maumar** [comment]
fixed in 60e9a430262e413670d534ea9c9effc5e43d696d

**Comment by mrhmouse** [comment]
I'm seeing something similar when the projection is a nullable struct in a conditional expression, like this:

```c#
quux.Select(q => new Foo
{
    Bar = q.X.HasValue && q.Y.HasValue
        ? new Bar { X = q.X.Value, Y = q.Y.Value }
        : (Bar?)null,
})
```

**Comment by maumar** [comment]
@mrhmouse are you using EFCore version 2.1?
