### ISSUE TITLE
Incorrect syntax near ')'

### ISSUE THREAD

**Issue by joshmouch** [aspnet/EntityFrameworkCore#11901]
I just upgraded from version 2.0.2 to 2.1.0-preview2-final, and I started getting an exception. The exception is:

```
System.Data.SqlClient.SqlException : Incorrect syntax near ')'.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at System.Data.SqlClient.SqlDataReader.get_MetaData()
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior, String method)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteReader(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.BufferlessMoveNext(DbContext _, Boolean buffer)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)

```

This exception occurs when I take a query and project it on to an anonymous type.
The error seems to be caused by by the "Contains" method.  

Here is the code:
```C#
List<Guid?> parEntityOneIds = ...;


var entityOnesQuery = from entityOne in dbContext.entityOnes.Where(a => parEntityOneIds.Contains(a.EntityOneId))
					join acs in dbContext.entityTwos on entityOne.entityOneSystemId equals acs.entityOneSystemId
					select new { Id = entityOne.Id, Code = entityOne.Value, CodeType = acs.Name };
var entityOnes = entityOnes.ToList();
```

Here is the generated SQL.  You can see the bad code on the last line: IN ()
```sql
SELECT [a].[EntityOneID] AS [Id], [a].[Value] AS [Code], [acs].[EntityOneCodingSystemName] AS [CodeType]
FROM [EntityOneCoding] AS [a]
INNER JOIN [EntityOneCodingSystem] AS [acs] ON [a].[EntityOneCodingSystemID] = [acs].[EntityOneCodingSystemID]
WHERE [a].[EntityOneID] IN () OR [a].[EntityOneID] IS NULL
```

**Comment by divega** [comment]
Note for triage: 2.1 candidate.
