### ISSUE TITLE
Group by an empty key with an aggregate throws 'must be reducible node'

### ISSUE THREAD

**Issue by AlekseyMartynov** [aspnet/EntityFrameworkCore#11905]
Version: `2.1.0-preview2-final`

Query:

```c#
var context = new NorthwindContext();

var query = context.Orders
    .GroupBy(obj => new { }) // ← here
    .Select(g => new {
        Sum = g.Sum(obj => obj.Freight)
    });
```

Exception:

```c#
System.ArgumentException: must be reducible node
   at System.Linq.Expressions.Expression.ReduceAndCheck()
   at System.Linq.Expressions.Expression.ReduceExtensions()
   
   ... repeated System.Linq.Expressions.Compiler.StackSpiller lines ...

   at System.Linq.Expressions.Expression`1.Accept(StackSpiller spiller)
   at System.Linq.Expressions.Compiler.LambdaCompiler.Compile(LambdaExpression lambda)
   at System.Linq.Expressions.Expression`1.Compile(Boolean preferInterpretation)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.CreateExecutorLambda[TResults]()
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.CreateQueryExecutor[TResult](QueryModel queryModel)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](Expression query, IQueryModelGenerator queryModelGenerator, IDatabase database, IDiagnosticsLogger`1 logger, Type contextType)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass13_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQueryCore[TFunc](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Remotion.Linq.QueryableBase`1.System.Collections.IEnumerable.GetEnumerator()
```

EF6 seems to handle this query by rewriting to `.GroupBy(obj => 1)`:

```sql
SELECT 
    1 AS [C1], 
    [GroupBy1].[A1] AS [C2]
    FROM ( SELECT 
        [Extent1].[K1] AS [K1], 
        SUM([Extent1].[A1]) AS [A1]
        FROM ( SELECT 
            cast(1 as bit) AS [K1], 
            [Extent1].[Freight] AS [A1]
            FROM [dbo].[Orders] AS [Extent1]
        )  AS [Extent1]
        GROUP BY [K1]
    )  AS [GroupBy1]
```

**Comment by AlekseyMartynov** [comment]
Technically, this is a regression. Versions `2.0.2` and `2.1.0-preview1-final` execute this query in memory and don't throw.

**Comment by smitpatel** [comment]
@divega @ajcvickers - Do we want to block this for 2.1 or convert to group by constant?

**Comment by divega** [comment]
@AlekseyMartynov what is the scenario exactly for this? I am guessing that a DevExpress component uses this expression, but please confirm.

**Comment by smitpatel** [comment]
@AlekseyMartynov - To add a bit more, with the fix, we will inject a custom Key of `1` instead of anonymous type. So if the key is used anywhere then it may have different result from l2o.
Further while this was doing client eval in 2.0, it was basically fetching whole table to client which had bad performance regardless. Hence we decided to inject the constant.

**Comment by AlekseyMartynov** [comment]
@divega: 
> what is the scenario exactly for this? I am guessing that a DevExpress component uses this expression, but please confirm.

Correct. I mentioned this case in https://github.com/aspnet/EntityFrameworkCore/issues/2341#issuecomment-326896770.

@smitpatel:
For our needs, both `.GroupBy(obj => new { })` and `.GroupBy(obj => C)` would work. We have used the former as a degenerate case of grouping, when all data is treated as one group. The fix in EF Core will help maintain compatibility with existing verisons of our library. Thank you.
