### ISSUE TITLE
Must be reductible node

### ISSUE THREAD

**Issue by NicolasDorier** [aspnet/EntityFrameworkCore#11933]
Describe what is not working as expected.

I am migrating to .NET 2.1, but it seems entity framework broke:
This was working in 2.0:
```
var userId = GetUserId();
using (var ctx = _ContextFactory.CreateContext())
{
    return await ctx.UserStore
        .Where(us => us.ApplicationUserId == userId)
        .SelectMany(us => us.StoreData.Apps.Select(app => new ListAppsViewModel.ListAppViewModel()
        {
            IsOwner = us.Role == StoreRoles.Owner,
            StoreId = us.StoreDataId,
            StoreName = us.Role,
            AppName = app.Name,
            AppType = app.AppType,
            Id = app.Id
        }))
        .ToArrayAsync();
```

Now it throws

```
at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at BTCPayServer.Tests.UnitTest1.CanUsePoSApp() in C:\Sources\btcpayserver\BTCPayServer.Tests\UnitTest1.cs:line 1180
----- Inner Stack Trace -----
   at System.Linq.Expressions.Expression.ReduceAndCheck()
   at System.Linq.Expressions.Expression.ReduceExtensions()
   at System.Linq.Expressions.Compiler.StackSpiller.RewriteExtensionExpression(Expression expr, Stack stack)
   at System.Linq.Expressions.Compiler.StackSpiller.RewriteExpression(Expression node, Stack stack)
   at System.Linq.Expressions.Compiler.StackSpiller.RewriteMemberExpression(Expression expr, Stack stack)
   at System.Linq.Expressions.Compiler.StackSpiller.RewriteExpression(Expression node, Stack stack)
   at System.Linq.Expressions.Compiler.StackSpiller.MemberAssignmentRewriter..ctor(MemberAssignment binding, StackSpiller spiller, Stack stack)
   at System.Linq.Expressions.Compiler.StackSpiller.BindingRewriter.Create(MemberBinding binding, StackSpiller spiller, Stack stack)
   at System.Linq.Expressions.Compiler.StackSpiller.RewriteMemberInitExpression(Expression expr, Stack stack)
   at System.Linq.Expressions.Compiler.StackSpiller.RewriteExpression(Expression node, Stack stack)
   at System.Linq.Expressions.Compiler.StackSpiller.RewriteExpressionFreeTemps(Expression expression, Stack stack)
   at System.Linq.Expressions.Compiler.StackSpiller.Rewrite[T](Expression`1 lambda)
   at System.Linq.Expressions.Expression`1.Accept(StackSpiller spiller)
   at System.Linq.Expressions.Compiler.StackSpiller.RewriteLambdaExpression(Expression expr)
   at System.Linq.Expressions.Compiler.StackSpiller.RewriteExpression(Expression node, Stack stack)
   at System.Linq.Expressions.Compiler.StackSpiller.ChildRewriter.Add(Expression expression)
   at System.Linq.Expressions.Compiler.StackSpiller.ChildRewriter.AddArguments(IArgumentProvider expressions)
   at System.Linq.Expressions.Compiler.StackSpiller.RewriteMethodCallExpression(Expression expr, Stack stack)
   at System.Linq.Expressions.Compiler.StackSpiller.RewriteExpression(Expression node, Stack stack)
   at System.Linq.Expressions.Compiler.StackSpiller.RewriteExpressionFreeTemps(Expression expression, Stack stack)
   at System.Linq.Expressions.Compiler.StackSpiller.Rewrite[T](Expression`1 lambda)
   at System.Linq.Expressions.Expression`1.Accept(StackSpiller spiller)
   at System.Linq.Expressions.Compiler.StackSpiller.RewriteLambdaExpression(Expression expr)
   at System.Linq.Expressions.Compiler.StackSpiller.RewriteExpression(Expression node, Stack stack)
   at System.Linq.Expressions.Compiler.StackSpiller.ChildRewriter.Add(Expression expression)
   at System.Linq.Expressions.Compiler.StackSpiller.ChildRewriter.AddArguments(IArgumentProvider expressions)
   at System.Linq.Expressions.Compiler.StackSpiller.RewriteMethodCallExpression(Expression expr, Stack stack)
   at System.Linq.Expressions.Compiler.StackSpiller.RewriteExpression(Expression node, Stack stack)
   at System.Linq.Expressions.Compiler.StackSpiller.ChildRewriter.Add(Expression expression)
   at System.Linq.Expressions.Compiler.StackSpiller.ChildRewriter.AddArguments(IArgumentProvider expressions)
   at System.Linq.Expressions.Compiler.StackSpiller.RewriteMethodCallExpression(Expression expr, Stack stack)
   at System.Linq.Expressions.Compiler.StackSpiller.RewriteExpression(Expression node, Stack stack)
   at System.Linq.Expressions.Compiler.StackSpiller.ChildRewriter.Add(Expression expression)
   at System.Linq.Expressions.Compiler.StackSpiller.ChildRewriter.AddArguments(IArgumentProvider expressions)
   at System.Linq.Expressions.Compiler.StackSpiller.RewriteMethodCallExpression(Expression expr, Stack stack)
   at System.Linq.Expressions.Compiler.StackSpiller.RewriteExpression(Expression node, Stack stack)
   at System.Linq.Expressions.Compiler.StackSpiller.RewriteExpressionFreeTemps(Expression expression, Stack stack)
   at System.Linq.Expressions.Compiler.StackSpiller.Rewrite[T](Expression`1 lambda)
   at System.Linq.Expressions.Expression`1.Accept(StackSpiller spiller)
   at System.Linq.Expressions.Compiler.LambdaCompiler.Compile(LambdaExpression lambda)
   at System.Linq.Expressions.Expression`1.Compile(Boolean preferInterpretation)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.CreateExecutorLambda[TResults]()
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.CreateAsyncQueryExecutor[TResult](QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQueryCore[TFunc](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteAsync[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1.System.Collections.Generic.IAsyncEnumerable<TResult>.GetEnumerator()
   at System.Collections.Generic.AsyncEnumerableHelpers.ToArrayWithLength[T](IAsyncEnumerable`1 source, CancellationToken cancellationToken)
   at System.Collections.Generic.AsyncEnumerableHelpers.ToArray[T](IAsyncEnumerable`1 source, CancellationToken cancellationToken)
   at BTCPayServer.Controllers.AppsController.GetAllApps() in C:\Sources\btcpayserver\BTCPayServer\Controllers\AppsController.cs:line 178
   at BTCPayServer.Controllers.AppsController.ListApps() in C:\Sources\btcpayserver\BTCPayServer\Controllers\AppsController.cs:line 44
```
Note that if I comment

```
            StoreId = us.StoreDataId,
            StoreName = us.Role,
```

it does not crash.

```
<PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="2.0.3" />
<PackageReference Include="Microsoft.AspNetCore.App" Version="2.1.0-rc1-final" />
<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version=" 2.1.0-rc1-final" PrivateAssets="All" />
```

**Comment by roji** [comment]
Just to get more data, would it be possible to test with 2.1.0-preview2-final for all packages (both Microsoft and Npgsql)? This would tell us whether is coming from mixing 2.0 and 2.1

(Npgsql's rc1 packages aren't out yet, but that should happen very soon)

**Comment by NicolasDorier** [comment]
sure one moment

**Comment by NicolasDorier** [comment]
Same issue in:

* 2.1.0-preview2-final
* 2.1.0-preview1-final

Same issue.

**Comment by NicolasDorier** [comment]
Note I did not updated Npgsql

**Comment by roji** [comment]
> Note I did not updated Npgsql

@NicolasDorier as I wrote above the idea is to align both Microsoft and Npgsql versions... Can you please try with all packages on 2.1.0-preview2, both Microsoft and Npgsql?

**Comment by NicolasDorier** [comment]
Ah sorry, I missed the preview package for Postgres as they were not listed by the nuget UI, trying now.

**Comment by NicolasDorier** [comment]
Both `2.1.0-preview2`, same issue. It is interesting that postgres `2.0.2` works with `2.0.1rc`, but not with postgres `2.1preview`.

**Comment by bmarder** [comment]
I received this error frequently with certain queries as well, using sqlserver and 2.1 preview 2.  @NicolasDorier Thanks for giving a full repo for this issue.

**Comment by ajcvickers** [comment]
@maumar Can you investigate this with regard to it being a regression in 2.1?

**Comment by maumar** [comment]
query plan in 2.0.2 - SelectMany gets translated, in current bits it gets client-evaled

```
Microsoft.EntityFrameworkCore.Query[10107]
      (QueryContext queryContext) => IAsyncEnumerable<ListAppViewModel> _InterceptExceptions(
          source: IAsyncEnumerable<ListAppViewModel> _ShapedQuery(
              queryContext: queryContext,
              shaperCommandContext: SelectExpression:
                  SELECT CASE
                      WHEN [us].[Role] = 1
                      THEN CAST(1 AS BIT) ELSE CAST(0 AS BIT)
                  END AS [IsOwner], [us].[StoreDataId] AS [StoreId], [us].[Role] AS [StoreName], [us.StoreData.Apps].[Name] AS [AppName], [us.StoreData.Apps].[AppType], [us.StoreData.Apps].[Id]
                  FROM [UserStore] AS [us]
                  INNER JOIN [StoreData] AS [us.StoreData] ON [us].[StoreDataId] = [us.StoreData].[Id]
                  INNER JOIN [App] AS [us.StoreData.Apps] ON [us.StoreData].[Id] = [us.StoreData.Apps].[StoreDataId]
                  WHERE [us].[ApplicationUserId] = @__userId_0,
              shaper: TypedProjectionShaper<TypedCompositeShaper<TypedCompositeShaper<ValueBufferShaper, ValueBuffer, ValueBufferShaper, ValueBuffer, TransparentIdentifier<ValueBuffer, ValueBuffer>>, TransparentIdentifier<ValueBuffer, ValueBuffer>, ValueBufferShaper, ValueBuffer, TransparentIdentifier<TransparentIdentifier<ValueBuffer, ValueBuffer>, ValueBuffer>>, TransparentIdentifier<TransparentIdentifier<ValueBuffer, ValueBuffer>, ValueBuffer>, ListAppViewModel>),
          contextType: EFSampleApp.MyContext,
          logger: DiagnosticsLogger<Query>,
          queryContext: queryContext)
```

**Comment by ajcvickers** [comment]
@maumar Do you need @anpete or @smitpatel to help on this?
/cc @divega

**Comment by maumar** [comment]
@ajcvickers the regression comes from nav rewrite, so I'm the right person to work on it.

**Comment by maumar** [comment]
simplified repro:

```cs
    class Program
    {
        static void Main(string[] args)
        {
            using (var ctx = new MyContext())
            {
                ctx.Database.EnsureDeleted();
                ctx.Database.EnsureCreated();
            }

            using (var ctx = new MyContext())
            {
                var query = ctx.Customers.SelectMany(c => c.Orders.Select(o => new { OrderName = o.Name, CustomerName = c.Name }));
                var result = query.ToList();
            }
        }
    }

    public class Customer
    {
        public int Id { get; set; }
        public string Name { get; set; }

        public List<Order> Orders { get; set; }
    }

    public class Order
    {
        public int Id { get; set; }
        public string Name { get; set; }
    }

    public class MyContext : DbContext
    {
        public DbSet<Customer> Customers { get; set; }
        public DbSet<Order> Orders { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseSqlServer(@"Server=.;Database=Repro11933;Trusted_Connection=True;MultipleActiveResultSets=True");
        }
    }
```

**Comment by maumar** [comment]
Error happens because we changed translation of SelectMany for non-qsre subqueries - https://github.com/aspnet/EntityFrameworkCore/issues/11219 Now we translate those into subqueries, rather than joins. This however exposes the binding issue, when the subquery has references to the outer query sources.

Given that this query used to work in 2.0.2 the fix to https://github.com/aspnet/EntityFrameworkCore/issues/11219 was incorrect (or at least too aggressive).

**Comment by ajcvickers** [comment]
Triage: Plan is currently to fix #11941, which should also fix this.
@maumar to investigate if 2.1 will client eval more cross apply cases than before.

**Comment by PawelGerr** [comment]
Alas, I had to go back to 2.0.x. because of this issue.
Are there any plans to make a bugfix release before 2.2.0?

**Comment by ajcvickers** [comment]
@smitpatel / @maumar to document worakrounds.

@PawelGerr We looked into this again, but unfortunately we think the change needed to fix this is too risky to ship in a patch release.

**Comment by ajcvickers** [comment]
@smitpatel / @maumar to document worakrounds.

**Comment by ajcvickers** [comment]
@smitpatel / @maumar to document worakrounds.

**Comment by maumar** [comment]
workaround is to produce joins manually:

```cs
var query = from c in ctx.Customers
			join o in (from i in ctx.Orders
			   		   select new { i.CustomerId, OrderName = i.Name, CustomerName = i.Name }) on c.Id equals o.CustomerId
			select o;

var result = query.ToList();
```

**Comment by ryan-carbon** [comment]
Alternate workaround is to add a reverse navigation property and start from other side:

`var query = ctx.Orders.Select(o => new { OrderName = o.Name, CustomerName = o.Customer.Name }));`

**Comment by maumar** [comment]
blocked by SelectMany translation in the new pipeline

**Comment by btecu** [comment]
This is a big blocker for us and we've been waiting for EF Core 3.0. Is it not going to be fixed in 3.0 anymore?

**Comment by maumar** [comment]
@btecu SelectMany translation is being implemented at the moment (you can track the PR here: https://github.com/aspnet/EntityFrameworkCore/pull/17077). Entire query pipeline has been rewritten for 3.0 so once SelectMany support is in, this bug may simply go away.

**Comment by btecu** [comment]
Can we verify this is fixed?

**Comment by ajcvickers** [comment]
@btecu Yes. You can use the [daily builds](https://github.com/aspnet/AspNetCore/blob/master/docs/DailyBuilds.md) to do your verification.

**Comment by maumar** [comment]
verified this issue has been fixed in 3.0

**Comment by smitpatel** [comment]
@maumar - Regression test.

**Comment by maumar** [comment]
@smitpatel i have test ready, will send PR with regressions for multiple issues

**Comment by btecu** [comment]
@ajcvickers I tested preview 9 and confirm that previous query that in 2.x was broken now works.
