### ISSUE TITLE
Query with coalescing operator causes exception in 2.1.0-rc1

### ISSUE THREAD

**Issue by mbashov** [aspnet/EntityFrameworkCore#11953]
Query with coalescing operator that has a left part involving collections throws.

```c#
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.EntityFrameworkCore;

class Program
{
    static void Main(string[] args)
    {
        using (var db = new Context())
        {
            db.Database.EnsureDeleted();
            db.Database.EnsureCreated();

            db.SaveChanges();

            var result = db
                .Entities
                .Select(e => new { DependentId = e.Dependent.Select(d => (int?)d.Id).FirstOrDefault() ?? e.Id })
                .FirstOrDefault();
        }
    }
}

public class Context : DbContext
{
    public DbSet<Main> Main { get; set; }
    public DbSet<Dependent> Dependent { get; set; }
}

public class Main
{
    public int Id { get; set; }
    public ICollection<Dependent> Dependent { get; set; }
}

public class Dependent
{
    public int Id { get; set; }
    public int MainId { get; set; }
    public Main Main { get; set; }
}
```

```
Exception message: Coalesce used with type that cannot be null
Stack trace:
   at System.Linq.Expressions.Expression.ValidateCoalesceArgTypes(Type left, Type right)
   at System.Linq.Expressions.Expression.Coalesce(Expression left, Expression right, LambdaExpression conversion)
   at System.Linq.Expressions.Expression.MakeBinary(ExpressionType binaryType, Expression left, Expression right, Boolean liftToNull, MethodInfo method, LambdaExpression conversion)
   at System.Linq.Expressions.BinaryExpression.Update(Expression left, LambdaExpression conversion, Expression right)
   at Microsoft.EntityFrameworkCore.Sqlite.Query.ExpressionVisitors.Internal.SqliteSqlTranslatingExpressionVisitor.VisitBinary(BinaryExpression binaryExpression)
   at System.Linq.Expressions.BinaryExpression.Accept(ExpressionVisitor visitor)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.SqlTranslatingExpressionVisitor.Visit(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.RelationalProjectionExpressionVisitor.Visit(Expression expression)
   at System.Linq.Expressions.ExpressionVisitor.VisitAndConvert[T](ReadOnlyCollection`1 nodes, String callerName)
   at Remotion.Linq.Parsing.RelinqExpressionVisitor.VisitNew(NewExpression expression)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.RelationalProjectionExpressionVisitor.VisitNew(NewExpression newExpression)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.VisitSelectClause(SelectClause selectClause, QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor.VisitSelectClause(SelectClause selectClause, QueryModel queryModel)
   at Remotion.Linq.QueryModelVisitorBase.VisitQueryModel(QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.VisitQueryModel(QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor.VisitQueryModel(QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.CreateQueryExecutor[TResult](QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](Expression query, IQueryModelGenerator queryModelGenerator, IDatabase database, IDiagnosticsLogger`1 logger, Type contextType)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass13_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQueryCore[TFunc](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at System.Linq.Queryable.FirstOrDefault[TSource](IQueryable`1 source)
   at Program.Main(String[] args)
```

EF Core version: 2.1.0-rc1-final

**Comment by ajcvickers** [comment]
Related to #11690

**Comment by maumar** [comment]
Problem is that we translate the subquery into:

```sql
SELECT TOP(1) [d].[Id]
    FROM [Dependent] AS [d]
    WHERE [e].[Id] = [d].[MainId]
```

Type of the select expression (for the purpose of Expression tree type cohesion) is taken from the first element in the projection, which comes out as int - i.e. nullability gets lost at this point. 

We should account for this possibility when translating a subquery.

**Comment by smitpatel** [comment]
@maumar Got fix for this ready. Ideally, it would have been good to have projection in ET match types in SQL tree but that could have relatively higher impact. In current pipeline whenever we are lifting SelectExpression to projection level, it will have only 1 projection inside. So putting convert around SelectExpression itself would work correctly.

**Comment by ajcvickers** [comment]
EF Triage: We are punting this fix to 2.2 given that [the workaround](https://github.com/aspnet/EntityFrameworkCore/issues/11953#issuecomment-388174599) seems reasonable.
