### ISSUE TITLE
System.InvalidCastException when filtering projected query on EnumDto, with relational, worked before 2.1.0-preview2

### ISSUE THREAD

**Issue by GeorgDangl** [aspnet/EntityFrameworkCore#11956]
_A full repro project is here: https://github.com/GeorgDangl/EFCoreProjectionInvalidCastRepro_

I noticed a regression that was introduced since `2.1.0-preview2`, it's also present in the current `2.1.0-rc1-final`. It was working with `2.1.0-preview1` and the 2.0 versions.

I am getting `System.InvalidCastExceptions` when I do a query, project it via LINQ `Select()` to a Dto class and then try to filter it with a variable representing an enum:

```csharp
// Throws System.InvalidCastException :
// Invalid cast from 'EFCoreProjectionInvalidCastRepro.EmailTemplateTypeDto'
// to 'EFCoreProjectionInvalidCastRepro.EmailTemplateType'.
[Fact]
public async Task CanFilterProjectionWithCapturedVariable()
{
    var templateType = EmailTemplateTypeDto.PasswordResetRequest;
    var template = await Context
        .EmailTemplates
        .Select(t => new EmailTemplateDto {Id = t.Id, TemplateType = (EmailTemplateTypeDto) t.TemplateType})
        .Where(t => t.TemplateType == templateType)
        .FirstOrDefaultAsync();
    Assert.NotNull(template);
}

// This works with an inline filter
[Fact]
public async Task CanFilterProjectionWithInlineVariable()
{
    var template = await Context
        .EmailTemplates
        .Select(t => new EmailTemplateDto {Id = t.Id, TemplateType = (EmailTemplateTypeDto) t.TemplateType})
        .Where(t => t.TemplateType == EmailTemplateTypeDto.PasswordResetRequest)
        .FirstOrDefaultAsync();
    Assert.NotNull(template);
}
```

The exception being thrown:

```
System.InvalidCastException: 'Invalid cast from 'EFCoreProjectionInvalidCastRepro.EmailTemplateTypeDto' to 'EFCoreProjectionInvalidCastRepro.EmailTemplateType'.'

at System.Convert.DefaultToType(IConvertible value, Type targetType, IFormatProvider provider)
at Microsoft.EntityFrameworkCore.Storage.ValueConversion.ValueConverter`2.Sanitize[T](Object value)
at Microsoft.EntityFrameworkCore.Storage.ValueConversion.ValueConverter`2.<>c__DisplayClass3_0`2.<SanitizeConverter>b__0(Object v)
at Microsoft.EntityFrameworkCore.Storage.RelationalTypeMapping.CreateParameter(DbCommand command, String name, Object value, Nullable`1 nullable)
at Microsoft.EntityFrameworkCore.Storage.Internal.TypeMappedRelationalParameter.AddDbParameter(DbCommand command, Object value)
at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalParameterBase.AddDbParameter(DbCommand command, IReadOnlyDictionary`2 parameterValues)
at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.CreateCommand(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteAsync(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues, CancellationToken cancellationToken)
at Microsoft.EntityFrameworkCore.Query.Internal.AsyncQueryingEnumerable`1.AsyncEnumerator.BufferlessMoveNext(DbContext _, Boolean buffer, CancellationToken cancellationToken)
at Microsoft.EntityFrameworkCore.Query.Internal.AsyncQueryingEnumerable`1.AsyncEnumerator.MoveNext(CancellationToken cancellationToken)
at System.Linq.AsyncEnumerable.FirstOrDefault_[TSource](IAsyncEnumerable`1 source, CancellationToken cancellationToken)
at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.TaskResultAsyncEnumerable`1.Enumerator.MoveNext(CancellationToken cancellationToken)
at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext(CancellationToken cancellationToken)
at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteSingletonAsyncQuery[TResult](QueryContext queryContext, Func`2 compiledQuery, IDiagnosticsLogger`1 logger, Type contextType)
at EFCoreProjectionInvalidCastRepro.ProjectionTests.CanFilterProjectionWithCapturedVariable() in D:\Visual Studio Projects\EFCoreProjectionInvalidCastRepro\EFCoreProjectionInvalidCastRepro\ProjectionTests.cs:line 37
```

### Other Observations
* It works with the InMemory provider
* It throws the same error for non-async calls
* It works on `2.1.0-preview1` and earlier
* It also happens when using AutoMappers queryable extension `ProjectTo<T>()`

### Further technical details
EF Core version: 2.1.0-rc1-final
Database Provider: Microsoft.EntityFrameworkCore.Sqlite
Operating system: Windows 10 X64 and Windows Server 2012 R2
IDE: Visual Studio 2017 15.7 (happens also with `dotnet test`)

### Full Repro Code

```csharp
using System;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.Data.Sqlite;
using Microsoft.EntityFrameworkCore;
using Xunit;

namespace EFCoreProjectionInvalidCastRepro
{
    public class ProjectionTests
    {
        private AppDbContext Context => new AppDbContext();
        private static bool _isInitialized = false;

        public ProjectionTests()
        {
            if (!_isInitialized)
            {
                using (var context = new AppDbContext())
                {
                    context.Database.EnsureCreated();
                    context.EmailTemplates.Add(new EmailTemplate {Id = Guid.NewGuid(), TemplateType = EmailTemplateType.PasswordResetRequest});
                    context.SaveChanges();
                }

                _isInitialized = true;
            }
        }

        // Throws System.InvalidCastException :
        // Invalid cast from 'EFCoreProjectionInvalidCastRepro.EmailTemplateTypeDto'
        // to 'EFCoreProjectionInvalidCastRepro.EmailTemplateType'.
        [Fact]
        public async Task CanFilterProjectionWithCapturedVariable()
        {
            var templateType = EmailTemplateTypeDto.PasswordResetRequest;
            var template = await Context
                .EmailTemplates
                .Select(t => new EmailTemplateDto {Id = t.Id, TemplateType = (EmailTemplateTypeDto) t.TemplateType})
                .Where(t => t.TemplateType == templateType)
                .FirstOrDefaultAsync();
            Assert.NotNull(template);
        }

        // This one succeeds, the filter condition is inlined
        [Fact]
        public async Task CanFilterProjectionWithInlineVariable()
        {
            var template = await Context
                .EmailTemplates
                .Select(t => new EmailTemplateDto {Id = t.Id, TemplateType = (EmailTemplateTypeDto) t.TemplateType})
                .Where(t => t.TemplateType == EmailTemplateTypeDto.PasswordResetRequest)
                .FirstOrDefaultAsync();
            Assert.NotNull(template);
        }

        // The same error happends for non-async materialization
        [Fact]
        public void CanFilterProjectionWithCapturedVariableNonAsync()
        {
            var templateType = EmailTemplateTypeDto.PasswordResetRequest;
            var template = Context
                .EmailTemplates
                .Select(t => new EmailTemplateDto { Id = t.Id, TemplateType = (EmailTemplateTypeDto)t.TemplateType })
                .Where(t => t.TemplateType == templateType)
                .FirstOrDefault();
            Assert.NotNull(template);
        }
    }

    public class EmailTemplate
    {
        public Guid Id { get; set; }
        public EmailTemplateType TemplateType { get; set; }
    }

    public enum EmailTemplateType
    {
        PasswordResetRequest = 0,
        EmailConfirmation = 1
    }

    public class EmailTemplateDto
    {
        public Guid Id { get; set; }
        public EmailTemplateTypeDto TemplateType { get; set; }
    }

    public enum EmailTemplateTypeDto
    {
        PasswordResetRequest = 0,
        EmailConfirmation = 1
    }

    public class AppDbContext : DbContext
    {
        public DbSet<EmailTemplate> EmailTemplates { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            var sqliteInMemoryConnectionString = InMemorySqliteHelper.GetSqliteInMemoryConnectionString();
            optionsBuilder.UseSqlite(sqliteInMemoryConnectionString);
            base.OnConfiguring(optionsBuilder);
        }
    }

    public static class InMemorySqliteHelper
    {
        // This connection must be kept open for the lifetime of the process.
        // SQLite drops the database as soon as the last connection has been closed.
        private static SqliteConnection _connection;

        public static string GetSqliteInMemoryConnectionString()
        {
            var sqliteConnectionStringBuilder = new SqliteConnectionStringBuilder
            {
                DataSource = "in_memory_sqlite.db",
                Cache = SqliteCacheMode.Shared,
                Mode = SqliteOpenMode.Memory
            };
            var sqliteConnectionString = sqliteConnectionStringBuilder.ToString();
            if (_connection == null)
            {
                _connection = new SqliteConnection(sqliteConnectionString);
                _connection.Open();
            }

            return sqliteConnectionString;
        }
    }
}
```

By the way, I would _really_ like to know if there's some workaround, other than not using a Dto for the enum. I've been unsuccessfully tackling this since yesterday.

**Comment by smitpatel** [comment]
This fails because of type mapping used for parameter tries to do casting.
Interestingly,
`var b = (MyEnum)MyEnumDto.Value` does hard casting and it does work.
But `var b = Convert.ChangeType(MyEnumDto.Value, typeof(MyEnum))` throws ICE.

**Comment by GeorgDangl** [comment]
Hey @smitpatel, thanks for the response! Can you say for which version this is planned to be fixed?

**Comment by ajcvickers** [comment]
@GeorgDangl A workaround is to move the Where clause before the projection and use the mapped enum in the Where predicate:
```C#
            var templateType = (EmailTemplateType)EmailTemplateTypeDto.PasswordResetRequest;
            var template = Context
                .EmailTemplates
                .Where(t => t.TemplateType == templateType)
                .Select(t => new EmailTemplateDto { Id = t.Id, TemplateType = (EmailTemplateTypeDto)t.TemplateType })
                .FirstOrDefault();
```
Given this workaround, current plan is to fix in the 2.2 release, but this could changed based on feedback to be a 2.1 patch.

**Comment by smitpatel** [comment]
`var c = Enum.ToObject(typeof(MyEnum), MyEnumDto.Sunday)`
works successfully. When converting from 1 Enum to another we cannot use Convert.ChangeType. (it special case casting to type `Enum` but any other enum is failure.

**Comment by smitpatel** [comment]
@John0King - Please post the stack trace. There are multiple points which could throw ICE.

**Comment by John0King** [comment]
@smitpatel  this is the stack trace ,  I tryed Sqlite and it is fine. 

```txt
System.InvalidCastException: Failed to convert parameter value from a DateTimeOffset to a DateTime. ---> System.InvalidCastException: Object must implement IConvertible.
   at System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider)
   at System.Data.SqlClient.SqlParameter.CoerceValue(Object value, MetaType destinationType, Boolean& coercedToDataFeed, Boolean& typeChanged, Boolean allowStreaming)
   --- End of inner exception stack trace ---
   at System.Data.SqlClient.SqlParameter.CoerceValue(Object value, MetaType destinationType, Boolean& coercedToDataFeed, Boolean& typeChanged, Boolean allowStreaming)
   at System.Data.SqlClient.SqlParameter.GetCoercedValue()
   at System.Data.SqlClient.SqlParameter.Validate(Int32 index, Boolean isCommandProc)
   at System.Data.SqlClient.SqlCommand.BuildParamList(TdsParser parser, SqlParameterCollection parameters)
   at System.Data.SqlClient.SqlCommand.BuildExecuteSql(CommandBehavior behavior, String commandText, SqlParameterCollection parameters, _SqlRPC& rpc)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, SqlDataReader ds)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean asyncWrite, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.SqlClient.SqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.ExecuteReader()
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteReader(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.BufferlessMoveNext(DbContext _, Boolean buffer)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
   at System.Collections.Generic.List`1.AddEnumerable(IEnumerable`1 enumerable)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at AspNetCore.Views_Home_Index.ExecuteAsync() in E:\GitHubRepos\EF20To21Test\EF20To21Test\EF20To21Test\Views\Home\Index.cshtml:line 6
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageCoreAsync(IRazorPage page, ViewContext context)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageAsync(IRazorPage page, ViewContext context, Boolean invokeViewStarts)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderAsync(ViewContext context)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ViewContext viewContext, String contentType, Nullable`1 statusCode)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ActionContext actionContext, IView view, ViewDataDictionary viewData, ITempDataDictionary tempData, String contentType, Nullable`1 statusCode)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewResultExecutor.ExecuteAsync(ActionContext context, ViewResult result)
   at Microsoft.AspNetCore.Mvc.ViewResult.ExecuteResultAsync(ActionContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeResultAsync(IActionResult result)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResultFilterAsync[TFilter,TFilterAsync]()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResultExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeResultFilters()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```


I also hit some `a second operate  started before another operate is complated` exception ,    and I fix it with some `.ToList()`  and it's hard to reproduce

**Comment by John0King** [comment]
https://github.com/John0King/EF20To21Test  this is my test repo , the test is `HomeController` and the code is in view,  I also try to reproduce my second issue, but failed.
