### ISSUE TITLE
DB Seeding Issue With Timestamp Column. System.Data.SqlClient.SqlException (0x80131904): Cannot update a timestamp column.

### ISSUE THREAD

**Issue by SPEMoorthy** [aspnet/EntityFrameworkCore#11969]
Hi,
EF Core Migration is failing with seeding data when there is a Timestamp Column involved. While doing Update, The Timestamp column  also populating in the update query.

```
UPDATE [FaGroup] SET [CreatedDate] = '2018-05-11T13:01:16.7610000+05:30', [Timestamp] = NULL, [TransactionTime] = '2018-05-11T13:01:16.7610000+05:30', [UpdatedDate] = '2018-05-11T13:01:16.7610000+05:30' 
```
which is getting failed.

I Created the Initial Data with
CreatedDate = DateTime.Now. Is this right approach?

I Hope you are detecting the Modification of the Initial Seed with all the columns value. Which is creating Update Seed which is irrelevant. 

Steps Which I followed is as follows.

1) Created Table with Timestamp Column.
```C#
 [NotMapped]
    public abstract class EntityBase : ITrackable
    {
        [NotMapped]
        public ObjectState State { get; set; }

        [NotMapped]
        public ICollection<string> ModifiedProperties { get; set; }

        [Timestamp]
        public byte[] Timestamp { get; set; }

    }

 public abstract class AuditableEntityBase : EntityBase
    {
        public DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public DateTime UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
        [DefaultValue("Getdate()")]
        public DateTime TransactionTime { get; set; }
        public virtual void Validate(){}
    }

 public class FaGroup : AuditableEntityBase
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        public int GrpId { get; set; }
        public string GrpName { get; set; }

        [ForeignKey("GrpUnder")]
        public int? GrpUnderId { get; set; }
        public virtual FaGroup GrpUnder { get; set; }

        public int GrpOrderWeight { get; set; }

        public virtual List<FaAccount> FaAccount { get; set; }
    }

```
2) Configured Model With Seeding.

```C#
 builder.Entity<FaGroup>().HasData(
                new FaGroup
                {
                    GrpId = 101,
                    GrpName = "Assets",
                    CreatedBy = "GSRetail",
                    CreatedDate = DateTime.Now,
                    GrpOrderWeight = 0,
                    UpdatedBy = "GSRetail",
                    UpdatedDate = DateTime.Now,
                    TransactionTime = DateTime.Now
                }
```
3) Add-Migration Initial
4) Update-Database
5) Added More Records for seeding.
6) Add-Migration V1
7) Update-Database Got Error

Exception message:
```
Failed executing DbCommand (3ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
UPDATE [FaGroup] SET [CreatedDate] = '2018-05-11T13:01:16.7610000+05:30', [Timestamp] = NULL, [TransactionTime] = '2018-05-11T13:01:16.7610000+05:30', [UpdatedDate] = '2018-05-11T13:01:16.7610000+05:30'
WHERE [GrpId] = 101;
SELECT @@ROWCOUNT;
```
Stack trace:
```
PM> Add-Migration Initial
Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[0]
      User profile is available. Using 'C:\Users\SITSLN\AppData\Local\ASP.NET\DataProtection-Keys' as key repository and Windows DPAPI to encrypt keys at rest.
To undo this action, use Remove-Migration.
PM> Update-Database
Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[0]
      User profile is available. Using 'C:\Users\SITSLN\AppData\Local\ASP.NET\DataProtection-Keys' as key repository and Windows DPAPI to encrypt keys at rest.
Applying migration '20180511073022_Initial'.
Done.
PM> Add-Migration V1
Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[0]
      User profile is available. Using 'C:\Users\SITSLN\AppData\Local\ASP.NET\DataProtection-Keys' as key repository and Windows DPAPI to encrypt keys at rest.
To undo this action, use Remove-Migration.
PM> Update-Database
Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[0]
      User profile is available. Using 'C:\Users\SITSLN\AppData\Local\ASP.NET\DataProtection-Keys' as key repository and Windows DPAPI to encrypt keys at rest.
Applying migration '20180511073117_V1'.
Failed executing DbCommand (3ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
UPDATE [FaGroup] SET [CreatedDate] = '2018-05-11T13:01:16.7610000+05:30', [Timestamp] = NULL, [TransactionTime] = '2018-05-11T13:01:16.7610000+05:30', [UpdatedDate] = '2018-05-11T13:01:16.7610000+05:30'
WHERE [GrpId] = 101;
SELECT @@ROWCOUNT;
System.Data.SqlClient.SqlException (0x80131904): Cannot update a timestamp column.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, Boolean sendToPipe, Int32 timeout, Boolean asyncWrite, String methodName)
   at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteNonQuery(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.ExecuteNonQuery(IEnumerable`1 migrationCommands, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.UpdateDatabase(String targetMigration, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
ClientConnectionId:dcb97cac-a670-42e2-ad83-daa39c310bb1
Error Number:272,State:1,Class:16
Cannot update a timestamp column.
PM> 
```
### Further technical details
EF Core version: 2.1.0-preview2-final
Database Provider:  Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10
IDE: Visual Studio 2017 15.6.5

**Comment by ajcvickers** [comment]
Notes from triage: 
* Workaround is to edit the migration to remove the update of the timestamp column--see below
  * Note that EnsureCreated will never hit this because it never does an Update
* Given there is a reasonable workaround, moving this to fix in 2.2.

Workaround example:
Scaffolded:
```C#
migrationBuilder.UpdateData(
    table: "FaGroup",
    keyColumn: "GrpId",
    keyValue: 101,
    columns: new[] { "CreatedDate", "Timestamp", "TransactionTime", "UpdatedDate" },
    values: new object[] { new DateTime(2018, 5, 11, 13, 31, 29, 785, DateTimeKind.Local), null, new DateTime(2018, 5, 11, 13, 31, 29, 788, DateTimeKind.Local), new DateTime(2018, 5, 11, 13, 31, 29, 788, DateTimeKind.Local) });
```
Edited:
```C#
migrationBuilder.UpdateData(
    table: "FaGroup",
    keyColumn: "GrpId",
    keyValue: 101,
    columns: new[] { "CreatedDate", "TransactionTime", "UpdatedDate" },
    values: new object[] { new DateTime(2018, 5, 11, 13, 31, 29, 785, DateTimeKind.Local), new DateTime(2018, 5, 11, 13, 31, 29, 788, DateTimeKind.Local), new DateTime(2018, 5, 11, 13, 31, 29, 788, DateTimeKind.Local) });
```

**Comment by SPEMoorthy** [comment]
Thx

**Comment by denmitchell** [comment]
I had the same issue with temporal table period columns (that have a GENERATED ALWAYS property).  The workaround that @ajcvickers suggested worked for me.  Will the fix in the upcoming release work for period columns, as well?
