### ISSUE TITLE
Scaffold-DbContext now fails if there are any SQL_VARIANT columns (instead of ignoring them)

### ISSUE THREAD

**Issue by Metritutus** [aspnet/EntityFrameworkCore#11977]
When running `Scaffold-DbContext` under .NET Core 2.1 Preview 1, if there were any table columns of type `SQL_VARIANT`, you would get a warning, "`Could not find type mapping for column 'dbo.FieldValue.Value' with data type 'sql_variant'. Skipping column.`"  The rest of the models and their properties would still be generated.

Under .NET Core 2.1 Preview 2 and .NET Core 2.1 RC1 however, an `InvalidOperationException` is thrown, stating `No mapping to a relational type can be found for the CLR type 'object'.`  No models get generated.

To replicate this, first create a SQL database containing a table that has a `SQL_VARIANT` column:
```SQL
CREATE DATABASE [ScaffoldTestDatabase]
GO
USE [ScaffoldTestDatabase]
GO
CREATE TABLE [TestTable]
(
    [Id]    INTEGER     NOT NULL PRIMARY KEY,
    [Value] SQL_VARIANT NOT NULL
)
```

Then create a .NET Core Console application building for .NET Core 2.1 RC1.  Add references to the following NuGet packages:
`Microsoft.EntityFrameworkCore` `v2.1.0-rc1-final`
`Microsoft.EntityFrameworkCore.SqlServer` `v2.1.0-rc1-final`
`Microsoft.EntityFrameworkCore.Tools` `v2.1.0-rc1-final`

Build the project and then run the `Scaffold-DbContext` command in the Package Manager Console:

`Scaffold-DbContext "Server=DbServer;Database=ScaffoldTestDatabase;User ID=<REMOVED>;Password=<REMOVED>;" Microsoft.EntityFrameworkCore.SqlServer -OutputDir Models`

At this point, it fails and error information is printed to the Package Manager Console.

### Stacktrace
```C#
System.InvalidOperationException: No mapping to a relational type can be found for the CLR type 'object'.
   at Microsoft.EntityFrameworkCore.Storage.RelationalTypeMappingSourceExtensions.GetMapping(IRelationalTypeMappingSource typeMappingSource, Type clrType)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.ScaffoldingTypeMapper.FindMapping(String storeType, Boolean keyOrIndex, Boolean rowVersion)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.RelationalScaffoldingModelFactory.GetTypeScaffoldingInfo(DatabaseColumn column)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.RelationalScaffoldingModelFactory.VisitColumn(EntityTypeBuilder builder, DatabaseColumn column)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.RelationalScaffoldingModelFactory.VisitColumns(EntityTypeBuilder builder, ICollection`1 columns)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.RelationalScaffoldingModelFactory.VisitTable(ModelBuilder modelBuilder, DatabaseTable table)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.RelationalScaffoldingModelFactory.VisitTables(ModelBuilder modelBuilder, ICollection`1 tables)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.RelationalScaffoldingModelFactory.VisitDatabaseModel(ModelBuilder modelBuilder, DatabaseModel databaseModel)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.RelationalScaffoldingModelFactory.Create(DatabaseModel databaseModel, Boolean useDatabaseNames)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.ReverseEngineerScaffolder.ScaffoldModel(String connectionString, IEnumerable`1 tables, IEnumerable`1 schemas, String namespace, String language, String contextDir, String contextName, ModelReverseEngineerOptions modelOptions, ModelCodeGenerationOptions codeOptions)
   at Microsoft.EntityFrameworkCore.Design.Internal.DatabaseOperations.ScaffoldContext(String provider, String connectionString, String outputDir, String outputContextDir, String dbContextClassName, IEnumerable`1 schemas, IEnumerable`1 tables, Boolean useDataAnnotations, Boolean overwriteFiles, Boolean useDatabaseNames)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.ScaffoldContextImpl(String provider, String connectionString, String outputDir, String outputDbContextDir, String dbContextClassName, IEnumerable`1 schemaFilters, IEnumerable`1 tableFilters, Boolean useDataAnnotations, Boolean overwriteFiles, Boolean useDatabaseNames)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.ScaffoldContext.<>c__DisplayClass0_1.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
```

I know that support was previously added to EF Core 2.1 to support `SQL_VARIANT` columns, as on Preview1, after running the `Scaffold-DbContext` command, I could then manually add the skipped columns to the relevant models with a type of `object`, and then I would map them using `builder.Property(e => e.MyColumnName).HasColumnType("sql_variant")` in my `DbContext` class.

I'm not sure what I'm doing wrong.  Is there something else I now need to do now to get this to work (ie adding additional NuGet packages that I need to add, etc)?

### Further technical details
EF Core version: netcoreapp2.1
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10
IDE: Visual Studio 2017 15.7.0

**Comment by smitpatel** [comment]
No work-around apart from ignoring the table from scaffolding.

**Comment by Metritutus** [comment]
> No work-around apart from ignoring the table from scaffolding.

Are you saying it's possible to ignore specific tables when scaffolding (aside from manually specifying the names of every *other* table I want to scaffold)?  How would I go about doing this?  I had a look at the documentation for the command, but didn't see anything regarding exclusions.

**Comment by smitpatel** [comment]
It is not possible to exclude. You have to specify others manually for now.

**Comment by ErikEJ** [comment]
Or use EF Core Power Tools 😁

**Comment by ajcvickers** [comment]
@bricelam We have an opportunity to get this approved for patch on Thursday. For that we would need to have a PR and an assessment of risk. Is that doable?

/cc @divega

**Comment by bricelam** [comment]
Will do

**Comment by bricelam** [comment]
PR is out. Very low risk. Change just calls FindX instead of GetX to avoid throwing.

**Comment by ajcvickers** [comment]
This is approved by shiproom for 2.1.1 patch, but please wait for the branch to be open before merging.

**Comment by ajcvickers** [comment]
@bricelam The release/2.1 branch is now open for 2.1.1 patch issues. Can we get this merged ASAP?
