### ISSUE TITLE
Using a Grouped Query in a join fails 

### ISSUE THREAD

**Issue by cdarrigo** [aspnet/EntityFrameworkCore#11994]
I want to create an aggregated query (using Group By), and then use that in a join to an existing dbset.

var myGroupedData = await myCtx.Entities.GroupBy(i=>id).Select(i=>new {id,count()}).ToArrayAsync();

I am able to return the grouped data without a problem,  but when I try to use that grouped query in a join, I get an exception. 

Here's the full exception details 

Describe what is not working as expected.

If you are seeing an exception, include the full exceptions details (message and stack trace).

```
Exception message: Column 'BillingNote.BillingNoteTypeId' is invalid in the select list because it is not contained in either an aggregate function or the GROUP BY clause.
Stack trace:
System.Data.SqlClient.SqlException (0x80131904): Column 'BillingNote.BillingNoteTypeId' is invalid in the select list because it is not contained in either an aggregate function or the GROUP BY clause.
   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__122_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.<ExecuteAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncQueryingEnumerable`1.AsyncEnumerator.<BufferlessMoveNext>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.<ExecuteAsync>d__7`2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncQueryingEnumerable`1.AsyncEnumerator.<MoveNext>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.<MoveNext>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Collections.Generic.AsyncEnumerableHelpers.<ToArrayWithLength>d__1`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Collections.Generic.AsyncEnumerableHelpers.<ToArray>d__0`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Blackbaud.TMS.DataManagement.Service.Data.Providers.BillingNoteTypeDataProvider.<GetUsageAsync>d__13.MoveNext() in C:\Repo\tms-dmgmt-svc\src\Blackbaud.TMS.DataManagement.Service\Data\Providers\BillingNoteTypeDataProvider.cs:line 367
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Blackbaud.TMS.DataManagement.Service.Business.Services.BillingNoteType.BillingNoteTypeService.<GetUsageAsync>d__8.MoveNext() in C:\Repo\tms-dmgmt-svc\src\Blackbaud.TMS.DataManagement.Service\Business\Services\BillingNoteType\BillingNoteTypeService.cs:line 303
```

### Steps to reproduce
2 entities involved, the BillingNoteEntity and the BillingNoteTypeEntity.  BillingNoteEntity has a FK (BillingNoteTypeId) to BillingNoteType which identifies the type of the billing note.

Include a complete code listing (or project/solution) that we can run to reproduce the issue.

Partial code listings, or multiple fragments of code, will slow down our response or cause us to push the issue back to you to provide code to reproduce the issue.

```c#
[Table("BillingNote")]
    public class BillingNoteEntity:EntityBase
    {
        public int Id { get; set; }
        
        public int SchoolId { get; set; }
        
        public int BillingNoteTypeId { get; set; }
        
        [Column(TypeName = "date")]
        public DateTime Date { get; set; }
        
        [MaxLength(100)]
        [Required]
        public string Title { get; set; }
        
        [MaxLength(4000)]
        public string Description { get; set; }
        
        public BillingNoteTypeEntity BillingNoteType { get; set; }
        
        public List<BillingNoteUserEntity> BillingNoteUsers { get; set; }
        
    }

 [Table("BillingNoteType")]
    public class BillingNoteTypeEntity:EntityBase
    {
        public int Id { get; set; }
        
        public int SchoolId { get; set; }
        
        [MaxLength(50)]
        [Required]
        public string Description { get; set; }
        
        public int? SortOrder { get; set; }
        
        public bool? Active { get; set; } = true ;
        
        public int? InsertById { get; set; }
        
        public List<BillingNoteEntity> BillingNotes { get; set; }
        
    }
In the data Context:

modelBuilder.Entity<BillingNoteEntity>(entity =>
            {
                // turn off the clustered index for the PK
                entity.HasKey(b => b.Id).ForSqlServerIsClustered(false);
                entity.HasIndex(e => new { e.SchoolId, e.Id })
                    .HasName("IX_billing_note")
                    .IsUnique()
                    .ForSqlServerIsClustered();

                
                entity.HasOne(d => d.BillingNoteType)
                    .WithMany(p => p.BillingNotes)
                    .HasForeignKey(d => d.BillingNoteTypeId);
            }

Offending Query:

      public async Task<object[]> GetUsageAsync(int schoolId)
        {
 
            var outer = this.dataContext.BillingNoteTypes.Where(i=>i.SchoolId == schoolId);
            var groupedUsage = this.dataContext.BillingNotes
                .Where(i => i.SchoolId == schoolId)
                .GroupBy(i => i.BillingNoteTypeId)
                .Select(g => new
                {
                    BillingNoteTypeId = g.Key,
                    TimesUsed = g.Count()
                });
            var query = outer.Join(
                inner: groupedUsage,
                outerKeySelector: type => type.Id,
                innerKeySelector: usage => usage.BillingNoteTypeId,
                resultSelector: (type, usage) =>
                    new
                    {
                        type.Id,
                        type.Description,
                        type.Active,
                        usage.TimesUsed,
                        type.SortOrder,
                        type.InsertById,
                        type.InsertDate
                    }
            );
            
            var usageData = await query
                    .OrderBy(i=>i.SortOrder).ThenBy(i=>i.Description)
                .ToArrayAsync();
            return usageData;


        }
```

### Further technical details
EF Core version: (found in project.csproj or packages.config) 2.1.0-preview2-final
Database Provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer) Microsoft.EntityFrameworkCore.SqlServer
Operating system: Win 10 Ultimate
IDE: (e.g. Visual Studio 2017 15.4) VS  Enterprise 2017 15.6.6

**Comment by ajcvickers** [comment]
@cdarrigo  Do you know if this used to work in the 2.0 releases? Have you tried it with the RC1 release from last week?

**Comment by cdarrigo** [comment]
I updated to the 2.1.0-rc1.final bits and it worked great.

Thanks!
 @smitpatel
