### ISSUE TITLE
Query compiler throws exception: "Sequence contains more than one element"

### ISSUE THREAD

**Issue by carlreinke** [aspnet/EntityFrameworkCore#11990]
The query compiler throws an exception.

```
System.InvalidOperationException: Sequence contains more than one element
   at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor.BindMemberOrMethod[TResult](Func`4 memberBinder, IQuerySource querySource, IProperty property, Boolean bindSubQueries)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor.<>c__DisplayClass105_0`1.<BindMemberExpression>b__0(IProperty property, IQuerySource qs)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.<>c__DisplayClass91_0`1.<BindMemberExpression>b__0(IReadOnlyList`1 ps, IQuerySource qs)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.BindPropertyExpressionCore[TResult](Expression propertyExpression, IQuerySource querySource, Func`3 propertyBinder)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor.BindMemberExpression[TResult](MemberExpression memberExpression, Func`4 memberBinder, Boolean bindSubQueries)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.RelationalEntityQueryableExpressionVisitor.VisitMember(MemberExpression node)
   at System.Linq.Expressions.MemberExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.ReplaceClauseReferences(Expression expression, IQuerySource querySource, Boolean inProjection)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.VisitSelectClause(SelectClause selectClause, QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor.VisitSelectClause(SelectClause selectClause, QueryModel queryModel)
   at Remotion.Linq.QueryModelVisitorBase.VisitQueryModel(QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.VisitQueryModel(QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor.VisitQueryModel(QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.CreateQueryExecutor[TResult](QueryModel queryModel)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](Expression query, IQueryModelGenerator queryModelGenerator, IDatabase database, IDiagnosticsLogger`1 logger, Type contextType)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass13_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQueryCore[TFunc](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Remotion.Linq.QueryableBase`1.GetEnumerator()
   at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Test.Program.Main() in C:\Users\User\Documents\Visual Studio 2017\Projects\Test\Test\Program.cs:line 34
```

### Steps to reproduce
```c#
using Microsoft.Data.Sqlite;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;

namespace Test
{
    class Program
    {
        static void Main()
        {
            var connection = new SqliteConnection("Data Source=:memory:");
            connection.Open();

            var options = new DbContextOptionsBuilder<TestContext>()
                .UseSqlite(connection)
                .Options;

            using (var dbContext = new TestContext(options))
            {
                dbContext.Database.EnsureCreated();
            }

            using (var dbContext = new TestContext(options))
            {
                var query = dbContext.Outers
                    .OrderBy(o => Guid.NewGuid())
                    .SelectMany(o => o.Inners)
                    .Distinct()
                    .Select(i => i.Name);

                var result = query
                    .ToArray();
            }
        }
    }

    internal class TestContext : DbContext
    {
        public TestContext(DbContextOptions options)
            : base(options)
        {
        }

        public DbSet<Outer> Outers { get; set; }

        public DbSet<Inner> Inners { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Outer>()
                .HasMany(a => a.Inners)
                .WithOne(t => t.Outer)
                .HasForeignKey(t => t.OuterId);
        }
    }

    internal class Outer
    {
        [Key]
        public int OuterId { get; set; }

        [Required]
        public string Name { get; set; }

        public List<Inner> Inners { get; set; }
    }

    internal class Inner
    {
        [Key]
        public int InnerId { get; set; }

        public int? OuterId { get; set; }
        public Outer Outer { get; set; }

        [Required]
        public string Name { get; set; }
    }
}
```

Test Solution: [Test.zip](https://github.com/aspnet/EntityFrameworkCore/files/1999033/Test.zip)

### Further technical details
EF Core version: 2.1.0-rc1-final
Database Provider: Microsoft.Data.Sqlite
Operating system: Windows 10
IDE: Visual Studio Community 2017 15.7.1

**Comment by embryologist** [comment]
I used to see this error with either ‘Single()’ or ‘SingleOrDefault()’ LINQ operators when I get my selection includes more than one record.

Have you tried,
,,,
var result = query.ToList();
,,,
Instead,
,,,
var result = query.ToArray();
,,,

**Comment by carlreinke** [comment]
Using `ToList()`, `FirstOrDefault()`, or `SingleOrDefault()` instead of `ToArray()` produces the same result.

**Comment by ajcvickers** [comment]
@carlreinke Do you know if this used to work in the 2.0 releases?

**Comment by maumar** [comment]
I was able to reproduce this in current bits as well as 2.0.2 (so this is not a regression). Also, the scenario fails on Sqlite but works fine on SqlServer

**Comment by maumar** [comment]
The reason why it originally reproed only on Sqlite was because we translate Guid.Newid() to server on sql server, but evaluate it on the client for sqlite.

The problem can be generalized so that it also reproduces on other providers:

```cs
        [Fact]
        public void Repro11990()
        {
            using (var ctx = new MyContext())
            {
                ctx.Database.EnsureDeleted();
                ctx.Database.EnsureCreated();
            }

            using (var ctx = new MyContext())
            {
                var query = ctx.Outers
                    .OrderBy(o => MyClientGuid(o.OuterId))
                    .SelectMany(o => o.Inners)
                    .Distinct()
                    .Select(i => i.Name);

                var result = query
                    .ToArray();
            }
        }

        public Guid MyClientGuid(int id) => Guid.NewGuid();

        internal class Outer
        {
            [Key]
            public int OuterId { get; set; }

            [Required]
            public string Name { get; set; }

            public List<Inner> Inners { get; set; }
        }

        internal class Inner
        {
            [Key]
            public int InnerId { get; set; }

            public int? OuterId { get; set; }
            public Outer Outer { get; set; }

            [Required]
            public string Name { get; set; }
        }
```

**Comment by maumar** [comment]
QM: 
```
from Inner i in 
    (from Outer o in DbSet<Outer>
    order by Guid QueryBugsTest.MyClientGuid([o].OuterId) asc
    join Inner o.Inners in DbSet<Inner>
    on (Nullable<int>)Property([o], "OuterId") equals Property([o.Inners], "OuterId")
    select [o.Inners]).Distinct()
select [i].Name
```

problem here is that when we try to replace clause references for the outermost selector, when we try to bind `[i].Name` to add appropriate column into a SelectExpression (in RelationalEntityQueryableExpressionVisitor) we expect only one query on the subquery model visitor, but because there is client evaluation, the join is client-side and we have two of them.

**Comment by ajcvickers** [comment]
@lajones Can you take a look at this?

**Comment by ajcvickers** [comment]
@lajones Sorry--commented on the wrong issue!
