### ISSUE TITLE
EF Core 2.1: InvalidOperationException while adding or retrieving object graph

### ISSUE THREAD

**Issue by grayver** [aspnet/EntityFrameworkCore#12227]
I have a project with complex data model structure. It works fine with EF Core 2.0. But after upgrading to EF Core 2.1 I get errors on adding or retrieving object graph from database:

```
Exception message:
InvalidOperationException: The foreign key '{QuestTaskId: -2147482647}' set on 'TaskChoice' with the key value '{Id: -2147482647}' matches an entity of type 'QuizTask', however the principal entity type should be assignable to 'HiddenAreaTask'.
Stack trace:
System.InvalidOperationException: The foreign key '{QuestTaskId: -2147482647}' set on 'TaskChoice' with the key value '{Id: -2147482647}' matches an entity of type 'QuizTask', however the principal entity type should be assignable to 'HiddenAreaTask'.
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.NavigationFixer.InitialFixup(InternalEntityEntry entry, ISet`1 handledForeignKeys, Boolean fromQuery)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.NavigationFixer.StateChanged(InternalEntityEntry entry, EntityState oldState, Boolean fromQuery)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntryNotifier.StateChanged(InternalEntityEntry entry, EntityState oldState, Boolean fromQuery)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.FireStateChanged(EntityState oldState)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.SetEntityState(EntityState oldState, EntityState newState, Boolean acceptChanges)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.SetEntityState(EntityState entityState, Boolean acceptChanges, Nullable`1 forceStateWhenUnknownKey)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityGraphAttacher.PaintAction(EntityEntryGraphNode node, Boolean force)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityEntryGraphIterator.TraverseGraph[TState](EntityEntryGraphNode node, TState state, Func`3 handleNode)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityEntryGraphIterator.TraverseGraph[TState](EntityEntryGraphNode node, TState state, Func`3 handleNode)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityEntryGraphIterator.TraverseGraph[TState](EntityEntryGraphNode node, TState state, Func`3 handleNode)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityGraphAttacher.AttachGraph(InternalEntityEntry rootEntry, EntityState entityState, Boolean forceStateWhenUnknownKey)
   at Microsoft.EntityFrameworkCore.DbContext.SetEntityState(InternalEntityEntry entry, EntityState entityState)
   at Microsoft.EntityFrameworkCore.DbContext.SetEntityState[TEntity](TEntity entity, EntityState entityState)
   at Microsoft.EntityFrameworkCore.DbContext.Add[TEntity](TEntity entity)
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.Add(TEntity entity)
   at EfCoreQueryBug.Controllers.ValuesController.Get() in D:\git\efcore21-query-bug\EfCoreQueryBug\Controllers\ValuesController.cs:line 70
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

### Steps to reproduce
I prepared example project which stably reproduces this error:
https://github.com/grayver/efcore21-query-bug

### Further technical details
EF Core version: 2.1.0
Database Provider: Npgsql.EntityFrameworkCore.PostgreSQL, Microsoft.EntityFrameworkCore.InMemory
Operating system: Windows 10 version 1803 (OS Build 17134.48)
IDE: Visual Studio 2017 version 15.7.3

**Comment by ajcvickers** [comment]
Notes for triage: I investigated this and it looks like the root cause is:
* StateManager.GetPrincipal can return the wrong principal if multiple FKs reference the same principal key.
* Validation added in 2.1 now checks for this instead of using the value, which in this case happened to work.

**Comment by eveneveneven** [comment]
@grayver Did you find any workaround for this issue?

**Comment by grayver** [comment]
Unfortunately no.. I upgraded all my projects to .NET Core 2.1, except EntityFramework packages. They are still 2.0
Taking in account that this bug was assigned 2.2 milestone, which will be released in the end of year, it is very frustrating..

**Comment by Eilon** [comment]
Patch is approved.

**Comment by optiks** [comment]
We're hitting the same issue - is there a preview release that we can try? How far away is the patch? Thanks.

**Comment by AndriySvyryd** [comment]
@optiks The patch should come out soon. You can try a preview version from https://dotnetfeed.blob.core.windows.net/orchestrated-release-2-1/20180711-01/final/index.json
