### ISSUE TITLE
"The multi-part identifier could not be bound" generated when a query is split into multiple statements and using a from with a subquery to join

### ISSUE THREAD

**Issue by neoGeneva** [aspnet/EntityFrameworkCore#12251]
When using a from with a subquery to join, like `from x in db.Table.Where(y => y.Id == z.Id).DefaultIfEmpty()`, if the query get split into multiple SQL statements, then the one for the joined table references a named table that doesn't exist.

```
Exception message: System.Data.SqlClient.SqlException (0x80131904): The multi-part identifier "p.ProductId" could not be bound.
Stack trace:
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at System.Data.SqlClient.SqlDataReader.get_MetaData()
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, SqlDataReader ds)
   at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteReader(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.BufferlessMoveNext(DbContext _, Boolean buffer)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.QueryMethodProvider._DefaultIfEmptyShapedQuery[T](QueryContext queryContext, ShaperCommandContext shaperCommandContext, IShaper`1 shaper)+MoveNext()
   at System.Linq.Enumerable.DefaultIfEmptyIterator`1.MoveNext()
   at System.Linq.Enumerable.SelectManyIterator[TSource,TCollection,TResult](IEnumerable`1 source, Func`2 collectionSelector, Func`3 resultSelector)+MoveNext()
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
   at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
```

### Steps to reproduce
Here's an example project that demonstrates the issue: [EFCoreBugs.FromAsLeftJoin.zip](https://github.com/aspnet/EntityFrameworkCore/files/2074356/EFCoreBugs.FromAsLeftJoin.zip)

Following is code that throws the exception:

```c#
var data = (
    from p in db.Product
    join x in
        from y in db.ProductCategory
        group new { } by y.ProductId into g
        select new { ProductId = g.Key }
        on p.ProductId equals x.ProductId
    from pc in db.ProductCategory.Where(x => x.ProductId == p.ProductId).DefaultIfEmpty()
    select new { pc.CategoryId, p.ProductId })
    .ToArray();
```

```c#
public class Product
{
    public int ProductId { get; set; }

    public ICollection<ProductCategory> ProductCategory { get; set; }
}

public class Category
{
    public int CategoryId { get; set; }

    public ICollection<ProductCategory> ProductCategory { get; set; }
}

public class ProductCategory
{
    public int ProductCategoryId { get; set; }
    public int ProductId { get; set; }
    public int CategoryId { get; set; }

    public Category Category { get; set; }
    public Product Product { get; set; }
}
```

This is the SQL that's generated:

```sql
SELECT [p].[ProductId]
FROM [Product] AS [p]

SELECT [y0].[ProductId]
FROM [ProductCategory] AS [y0]
ORDER BY [y0].[ProductId]

SELECT [t0].[CategoryId]
FROM (
    SELECT [t].*
    FROM (
        SELECT NULL AS [empty]
    ) AS [empty]
    LEFT JOIN (
        SELECT [x].*
        FROM [ProductCategory] AS [x]
        WHERE [x].[ProductId] = [p].[ProductId]
    ) AS [t] ON 1 = 1
) AS [t0]
```

### Further technical details
EF Core version: 2.1.0 (still exists in 2.2.0-preview1-34386)
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10 Version 1709 (OS Build 16299.431)
IDE: Visual Studio 2017 15.7.3

**Comment by per3ian** [comment]
same here

 Version : 2.2.100-preview1-009349

**Comment by smitpatel** [comment]
Generated SQL in 3.1
```SQL
      SELECT [p1].[CategoryId], [p].[ProductId]
      FROM [Product] AS [p]
      INNER JOIN (
          SELECT [p0].[ProductId]
          FROM [ProductCategory] AS [p0]
          GROUP BY [p0].[ProductId]
      ) AS [t] ON [p].[ProductId] = [t].[ProductId]
      LEFT JOIN [ProductCategory] AS [p1] ON [p].[ProductId] = [p1].[ProductId]
```
