### ISSUE TITLE
NullReferenceException in Sqlite when comparing nullable DateTimeOffset, only in async materialization and works in SQL Server

### ISSUE THREAD

**Issue by GeorgDangl** [aspnet/EntityFrameworkCore#12262]
When I attempt to do an async materialization that includes a comparison to a nullable `DateTimeOffset`, I get the following exception:

    System.NullReferenceException
      HResult=0x80004003
      Message=Object reference not set to an instance of an object.
      Source=Microsoft.EntityFrameworkCore
      StackTrace:
       at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.TaskLiftingExpressionVisitor.VisitMember(MemberExpression memberExpression)
       at System.Linq.Expressions.MemberExpression.Accept(ExpressionVisitor visitor)
       at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
       at System.Linq.Expressions.ExpressionVisitor.VisitUnary(UnaryExpression node)
       at System.Linq.Expressions.UnaryExpression.Accept(ExpressionVisitor visitor)
       at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
       at System.Linq.Expressions.ExpressionVisitor.VisitBinary(BinaryExpression node)
       at System.Linq.Expressions.BinaryExpression.Accept(ExpressionVisitor visitor)
       at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
       at System.Linq.Expressions.ExpressionVisitor.VisitAndConvert[T](ReadOnlyCollection`1 nodes, String callerName)
       at Remotion.Linq.Parsing.RelinqExpressionVisitor.VisitNew(NewExpression expression)
       at System.Linq.Expressions.NewExpression.Accept(ExpressionVisitor visitor)
       at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
       at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.TaskLiftingExpressionVisitor.LiftTasks(Expression expression)
       at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.VisitSelectClause(SelectClause selectClause, QueryModel queryModel)
       at Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor.VisitSelectClause(SelectClause selectClause, QueryModel queryModel)
       at Remotion.Linq.QueryModelVisitorBase.VisitQueryModel(QueryModel queryModel)
       at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.VisitQueryModel(QueryModel queryModel)
       at Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor.VisitQueryModel(QueryModel queryModel)
       at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.CreateAsyncQueryExecutor[TResult](QueryModel queryModel)
       at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQueryCore[TFunc](Object cacheKey, Func`1 compiler)
       at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteAsync[TResult](Expression query)
       at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1.System.Collections.Generic.IAsyncEnumerable<TResult>.GetEnumerator()
       at System.Linq.AsyncEnumerable.<Aggregate_>d__6`3.MoveNext()
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
       at Project.Identity.Data.Repository.UsersRepository.<NreRepro>d__3.MoveNext() in D:\Projects\Project\src\Project.Data\Repository\UsersRepository.cs:line 29

### Steps to reproduce

This is simply reproducible with the ASP.NET Core `IdentityDbContext`:

    private async Task NreRepro()
    {
        var usersQuery = await _context
                            .Users
                            .Select(u => new
                            {
                                IsLockedOut = u.LockoutEnd > System.DateTimeOffset.Now
                            })
                            .ToListAsync();
    }

My setup looks like this:

    public class MyDbContext : IdentityDbContext<ApplicationUser, Role, Guid>
    public class ApplicationUser : IdentityUser<Guid>, IMyIdentityUser
    public class Role : IdentityRole<Guid>

The `IMyIdentityUser` interface just defines one `Guid` property.

This only happens when I unit test with an in-memory **Sqlite** database, it works when I debug with SQLServer against localdb.

### Further technical details
EF Core version: 2.1.0 (I don't know if this is a regression, this was not under test before 2.1.0)
Database Provider: Microsoft.EntityFrameworkCore.Sqlite
Operating system: Windows 10
IDE: Visual Studio 2017 15.7.3

**Comment by smitpatel** [comment]
@GeorgDangl - I am not able to get the program to run in a web app with identity with custom modifications you made. Can you give us a repro without identity or share solution (with identity) which demonstrate the issue?

**Comment by GeorgDangl** [comment]
Sure, can do!
The repro is available here:
https://github.com/GeorgDangl/EFCoreProjectionInvalidCastRepro/tree/SqliteNRE  
(Make sure to use the SqliteNRE branch, I've just reused another repro repository)

The full repro is also here:

## csproj

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp2.1</TargetFramework>
  </PropertyGroup>
  
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="2.1.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="15.7.0" />
    <PackageReference Include="xunit" Version="2.3.1" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.3.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="2.1.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="2.1.0" />
    <DotNetCliToolReference Include="dotnet-xunit" Version="2.3.1" />
  </ItemGroup>
  
</Project>
```
## Code

```csharp
using System;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.Data.Sqlite;
using Microsoft.EntityFrameworkCore;
using Xunit;

namespace EFCoreProjectionInvalidCastRepro
{
    public class ProjectionTests
    {
        private AppDbContext Context => new AppDbContext();
        private static bool _isInitialized = false;

        public ProjectionTests()
        {
            if (!_isInitialized)
            {
                using (var context = new AppDbContext())
                {
                    context.Database.EnsureCreated();
                }

                _isInitialized = true;
            }
        }

        // This throws System.NullReferenceException
        // More details on GitHub:
        // https://github.com/aspnet/EntityFrameworkCore/issues/12262
        [Fact]
        public async Task CanFilterProjectionWithCapturedVariable()
        {
            var users = await Context
                        .Users
                        .Select(u => new
                        {
                            IsLockedOut = u.LockoutEnd > System.DateTimeOffset.Now
                        })
                        .ToListAsync();
            Assert.Empty(users);
        }
    }

    public class AppDbContext : IdentityDbContext<IdentityUser<Guid>, IdentityRole<Guid>, Guid>
    {
        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            var sqliteInMemoryConnectionString = InMemorySqliteHelper.GetSqliteInMemoryConnectionString();
            optionsBuilder.UseSqlite(sqliteInMemoryConnectionString);
            base.OnConfiguring(optionsBuilder);
        }
    }

    public static class InMemorySqliteHelper
    {
        // This connection must be kept open for the lifetime of the process.
        // SQLite drops the database as soon as the last connection has been closed.
        private static SqliteConnection _connection;

        public static string GetSqliteInMemoryConnectionString()
        {
            var sqliteConnectionStringBuilder = new SqliteConnectionStringBuilder
            {
                DataSource = "in_memory_sqlite.db",
                Cache = SqliteCacheMode.Shared,
                Mode = SqliteOpenMode.Memory
            };
            var sqliteConnectionString = sqliteConnectionStringBuilder.ToString();
            if (_connection == null)
            {
                _connection = new SqliteConnection(sqliteConnectionString);
                _connection.Open();
            }

            return sqliteConnectionString;
        }
    }
}
```

**Comment by GeorgDangl** [comment]
That's the test output:

```
Test Name:	EFCoreProjectionInvalidCastRepro.ProjectionTests.CanFilterProjectionWithCapturedVariable
Test FullName:	EFCoreProjectionInvalidCastRepro.ProjectionTests.CanFilterProjectionWithCapturedVariable
Test Source:	C:\Users\Georg\Documents\Git\EFCoreProjectionInvalidCastRepro\EFCoreProjectionInvalidCastRepro\ProjectionTests.cs : line 34
Test Outcome:	Failed
Test Duration:	0:00:01,533

Result StackTrace:	
at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.TaskLiftingExpressionVisitor.VisitMember(MemberExpression memberExpression)
   at System.Linq.Expressions.MemberExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at System.Linq.Expressions.ExpressionVisitor.VisitUnary(UnaryExpression node)
   at System.Linq.Expressions.UnaryExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at System.Linq.Expressions.ExpressionVisitor.VisitBinary(BinaryExpression node)
   at System.Linq.Expressions.BinaryExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at System.Linq.Expressions.ExpressionVisitor.VisitAndConvert[T](ReadOnlyCollection`1 nodes, String callerName)
   at Remotion.Linq.Parsing.RelinqExpressionVisitor.VisitNew(NewExpression expression)
   at System.Linq.Expressions.NewExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.TaskLiftingExpressionVisitor.LiftTasks(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.VisitSelectClause(SelectClause selectClause, QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor.VisitSelectClause(SelectClause selectClause, QueryModel queryModel)
   at Remotion.Linq.QueryModelVisitorBase.VisitQueryModel(QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.VisitQueryModel(QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor.VisitQueryModel(QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.CreateAsyncQueryExecutor[TResult](QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQueryCore[TFunc](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteAsync[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1.System.Collections.Generic.IAsyncEnumerable<TResult>.GetEnumerator()
   at System.Linq.AsyncEnumerable.Aggregate_[TSource,TAccumulate,TResult](IAsyncEnumerable`1 source, TAccumulate seed, Func`3 accumulator, Func`2 resultSelector, CancellationToken cancellationToken)
   at EFCoreProjectionInvalidCastRepro.ProjectionTests.CanFilterProjectionWithCapturedVariable() in C:\Users\Georg\Documents\Git\EFCoreProjectionInvalidCastRepro\EFCoreProjectionInvalidCastRepro\ProjectionTests.cs:line 33
--- End of stack trace from previous location where exception was thrown ---
Result Message:	System.NullReferenceException : Object reference not set to an instance of an object.

```

**Comment by smitpatel** [comment]
Repro:
```C#
using System;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;

namespace EFSampleApp
{
    public class Program
    {
        public static void Main(string[] args)
        {
            using (var db = new MyContext())
            {
                // Recreate database
                db.Database.EnsureDeleted();
                db.Database.EnsureCreated();

                // Seed database


                db.SaveChanges();
            }

            using (var db = new MyContext())
            {
                // Run queries
                db.Blogs
                    .Select(u => new
                    {
                        IsLockedOut = u.LockoutEnd > DateTimeOffset.Now
                    })
                    .ToListAsync().GetAwaiter().GetResult();
            }

            Console.WriteLine("Program finished.");
        }
    }


    public class MyContext : DbContext
    {
        private static ILoggerFactory LoggerFactory => new LoggerFactory().AddConsole(LogLevel.Trace);

        // Declare DBSets
        public DbSet<Blog> Blogs { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            // Select 1 provider
            optionsBuilder
                //.UseSqlServer(@"Server=(localdb)\mssqllocaldb;Database=_ModelApp;Trusted_Connection=True;Connect Timeout=5;ConnectRetryCount=0")
                .UseSqlite("filename=_modelApp.db")
                //.UseInMemoryDatabase(databaseName: "_modelApp")
                .EnableSensitiveDataLogging()
                .UseLoggerFactory(LoggerFactory);
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            // Configure model
        }
    }

    public class Blog
    {
        public int Id { get; set; }
        public DateTimeOffset LockoutEnd { get; set; }
    }
}

```
