### ISSUE TITLE
Review exception classes for best practices

### ISSUE THREAD

**Issue by smitpatel** [aspnet/EntityFrameworkCore#12285]
Some of our benchmarks on SQLite are failing with following error. (Initialization tests)
```
[07:09:07] :	 [Step 3/4] System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Runtime.Serialization.SerializationException: Type 'Microsoft.EntityFrameworkCore.DbUpdateException' in assembly 'Microsoft.EntityFrameworkCore, Version=2.2.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' is not marked as serializable.
[07:09:07] :	 [Step 3/4]    at Microsoft.EntityFrameworkCore.Benchmarks.Initialization.ColdStartEnabledTests.InitializeAndSaveChanges_AdventureWorks(Int32 count)
[07:09:07] :	 [Step 3/4]    at BenchmarkDotNet.Autogenerated.Runnable.MainMultiAction(Int64 invokeCount)
[07:09:07] :	 [Step 3/4]    at BenchmarkDotNet.Engines.Engine.Jitting()
[07:09:07] :	 [Step 3/4]    at BenchmarkDotNet.Autogenerated.Runnable.Run(IHost host)
[07:09:07] :	 [Step 3/4]    --- End of inner exception stack trace ---
[07:09:07] :	 [Step 3/4]    at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
[07:09:07] :	 [Step 3/4]    at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
[07:09:07] :	 [Step 3/4]    at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
[07:09:07] :	 [Step 3/4]    at BenchmarkDotNet.Autogenerated.Program.AfterAssemblyLoadingAttached(String[] args)
```
Commits which broke caused error to start
77e08fc0fea6 
d8b7ebbfabff 
7b9938ae5a15

**Comment by ajcvickers** [comment]
@bricelam to look at making exceptions serializable, assuming it doesn't have any other unwanted impact. Fixing the benchmarks issues can then come back to triage.

**Comment by bricelam** [comment]
Re-opening. I was going to review all our exceptions for best practices.

**Comment by ajcvickers** [comment]
Bringing this back to 3.90 since it's closely related to the underlying issue of #15214. Specifically, we should make the exception serializable, but then disable serialization of the actual entity entries.

**Comment by smitpatel** [comment]
Version 3.90 :trollface:
