### ISSUE TITLE
ef core 2.1 throws error for alternate key placed inside owned type

### ISSUE THREAD

**Issue by piotrkolodziej** [aspnet/EntityFrameworkCore#12423]
**Update2:**

Isolated the issue (see comment below) and provided link to sample project that will demonstrate it.

**Update1:**

I tried to run my app and I am getting the same result, so my guess is it's not only affecting dotnet ef database *' but occurs during a normal program run (whenever the '_hotelManagerContext.Database.EnsureCreated();' is being run

——

I have just migrated my code from 2.0 to 2.1. The project compiles but the 'dotnet ef database drop/update' produces the error mentioned below. On version 2.0 everything works as expected.

I have updated all csprojs to use netcoreapp2.1 target and new *.App meta-package:

```xml
<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>netcoreapp2.1</TargetFramework>
  </PropertyGroup>
  ...
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="2.1.0" PrivateAssets="All" />
    ...
  </ItemGroup>
	...
</Project>
```

I made sure I've also update npgsql which I am using in my data project:

```xml
<ItemGroup>
	<PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="2.1.0" />
</ItemGroup>
```

```
Exception message:

The relationship from 'Invoice.HotelDetails#BillingDetails' to 'Country' with foreign key properties {'Country' : string} cannot target the primary key {'CountryId' : int} because it is not compatible. Configure a principal key or a set of compatible foreign key properties for this relationship.

Stack trace:

Piotrs-MacBook:HotelManager.API shanti$ dotnet ef database drop
System.InvalidOperationException: The relationship from 'Invoice.HotelDetails#BillingDetails' to 'Country' with foreign key properties {'Country' : string} cannot target the primary key {'CountryId' : int} because it is not compatible. Configure a principal key or a set of compatible foreign key properties for this relationship.
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelValidator.ValidateNoShadowKeys(IModel model)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelValidator.Validate(IModel model)
   at Microsoft.EntityFrameworkCore.Infrastructure.RelationalModelValidator.Validate(IModel model)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.CreateModel(DbContext context, IConventionSetBuilder conventionSetBuilder, IModelValidator validator)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.<>c__DisplayClass5_0.<GetModel>b__1()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.GetModel(DbContext context, IConventionSetBuilder conventionSetBuilder, IModelValidator validator)
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()
   at Microsoft.EntityFrameworkCore.Infrastructure.EntityFrameworkServicesBuilder.<>c.<TryAddCoreServices>b__7_1(IServiceProvider p)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass1_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.Microsoft.EntityFrameworkCore.Infrastructure.IInfrastructure<System.IServiceProvider>.get_Instance()
   at Microsoft.EntityFrameworkCore.Internal.InternalAccessorExtensions.GetService[TService](IInfrastructure`1 accessor)
   at Microsoft.EntityFrameworkCore.Infrastructure.AccessorExtensions.GetService[TService](IInfrastructure`1 accessor)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(Func`1 factory)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(String contextType)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.GetContextInfo(String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.GetContextInfoImpl(String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.GetContextInfo.<>c__DisplayClass0_1.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
```

### Steps to reproduce

```c#

public class Invoice
{
	public int InvoiceId { get; set; }
	public BillingDetails HotelDetails { get; set; }
}

public class BillingDetails
{
	public string Country { get; set; }
}

public class Country
{
	public int CountryId { get; set; }
	public string Name { get; set; }
}

// invoice config
entity
	.OwnsOne(i => i.HotelDetails, builder =>
	{
		builder
			.HasOne<Country>()
			.WithMany()
			.HasPrincipalKey(c => c.Name)
			.HasForeignKey(d => d.Country)
			.IsRequired()
			.OnDelete(DeleteBehavior.Restrict;
	};

//country config
entity
	.HasIndex(c => c.Name)
	.IsUnique();

```

### Further technical details
EF Core version: 2.1 (2.1.300 SDK)
Database Provider: npgsql
Operating system: 10.13.5 (High Sierra)
IDE: dotnet cli

**Comment by roji** [comment]
I'm not going to have any time to look at this in the coming days, but this kind of issue is usually ef core-related rather than npgsql-related. I'd recommend opening an issue on the efcore repo.

**Comment by piotrkolodziej** [comment]
**I have managed to isolate the issue. It turns out it ONLY works if the owning type defines ONLY one owned type property:**.

```
public class Invoice
{
	public int InvoiceId { get; set; }
	public BillingDetails HotelDetails { get; set; }
// IF YOU ENABLE THIS AND APPROPRIATE CONFIG IT WILL NOT WORK
	// public BillingDetails GuestDetails { get; set; }
}

entity
	.OwnsOne(i => i.HotelDetails, builder =>
	{
		builder
			.HasOne<Country>()
			.WithMany()
			.HasForeignKey(d => d.Country)
			.HasPrincipalKey(c => c.Name)
			.IsRequired()
			.OnDelete(DeleteBehavior.Restrict);
	});
//entity
//	.OwnsOne(i => i.GuestDetails, builder =>
//	{
//		builder
//			.HasOne<Country>()
//			.WithMany()
//			.HasForeignKey(d => d.Country)
//			.HasPrincipalKey(c => c.Name)
//			.OnDelete(DeleteBehavior.Restrict);
//	});		

```

Sample project can be downloaded from the following [link](https://drive.google.com/open?id=1dLyBJ1fDneg_bJ5ouw_6HAG-CPlP4mDk).

**Comment by roji** [comment]
Again, this is very likely an EF Core issue rather than an Npgsql, @ajcvickers can you check if this rings any bells?

**Comment by piotrkolodziej** [comment]
I have the follow up question: you mentioned I should create the issue on the entity framework core repo. I just did that, and was wondering who is right here. In the last I did the same thing, and back then, also someone from npgsql commented that I should post in on efc repo. Am I doing something wrong or you guys are just getting notifications whenever someone mentions npgsql?

**Comment by ajcvickers** [comment]
@piotrkolodziej When one gets notifications from many repos (as I do and I am sure @roji does too) it is easy to get lost as to which repo one is currently working in. I suspect that @roji didn't realize this was already posted in the EF Core repo.

**Comment by ajcvickers** [comment]
@piotrkolodziej I'm trying to figure out what all the configuration you have means, but I am having trouble making sense of it. Can you describe what the intended mapping here is? If you know what database tables you expect, then that would help. Otherwise can you explain in words what the relationships between the three types is supposed to be?

**Comment by piotrkolodziej** [comment]
@ajcvickers sure, let me clarify:

Country - separate table with CountryId (int) and Name (string-alternatePK).
Invoice - separate table with InvoiceId (int), HotelDetails_Country (string FK to Country.Name) and GuestDetails_Country (string FK to Country.Name)

Please try downloading the [sample code](https://drive.google.com/open?id=1dLyBJ1fDneg_bJ5ouw_6HAG-CPlP4mDk) that I've created to isolate the issue:

**Comment by smitpatel** [comment]
Repro code:
```C#
public class Blog
    {
        public int Id { get; set; }
        public BillingDetail Bill1 { get; set; }
        public BillingDetail Bill2 { get; set; }
    }

    public class BillingDetail
    {
        public string Country { get; set; }
    }

    public class Country
    {
        public int Id { get; set; }
        public string Name { get; set; }
    }


        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            // Configure model
            modelBuilder.Entity<Blog>(b =>
            {
                b.OwnsOne(e => e.Bill1,
                    o =>
                    {
                        o.HasOne<Country>().WithMany().HasPrincipalKey(c => c.Name).HasForeignKey(d => d.Country);
                    });

                b.OwnsOne(e => e.Bill2,
                    o =>
                    {
                        o.HasOne<Country>().WithMany().HasPrincipalKey(c => c.Name).HasForeignKey(d => d.Country);
                    });
            });
        }
```
ModelBuilding fails. Worked in 2.0.2 release.

**Comment by smitpatel** [comment]
Schema in 2.0.2 release
```SQL
      CREATE TABLE [Country] (
          [Id] int NOT NULL IDENTITY,
          [Name] nvarchar(450) NOT NULL,
          CONSTRAINT [PK_Country] PRIMARY KEY ([Id]),
          CONSTRAINT [AK_Country_Name] UNIQUE ([Name])
      );
      CREATE TABLE [Blogs] (
          [Id] int NOT NULL IDENTITY,
          [Bill1_Country] nvarchar(450) NULL,
          [Bill2_Country] nvarchar(450) NULL,
          CONSTRAINT [PK_Blogs] PRIMARY KEY ([Id]),
          CONSTRAINT [FK_Blogs_Country_Bill1_Country] FOREIGN KEY ([Bill1_Country]) REFERENCES [Country] ([Name]) ON DELETE NO ACTION,
          CONSTRAINT [FK_Blogs_Country_Bill2_Country] FOREIGN KEY ([Bill2_Country]) REFERENCES [Country] ([Name]) ON DELETE NO ACTION
      );
```

**Comment by roji** [comment]
@piotrkolodziej and others sorry, it's my fault for not looking closely enough. I get email notifications about issues from both Npgsql and EF Core and I sometimes get confused...
