### ISSUE TITLE
Improve message for 'A second operation started on this context before a previous operation completed'

### ISSUE THREAD

**Issue by xav-stargate** [aspnet/EntityFrameworkCore#12470]
Hey, I migrate my project from .Net Core 2.0 to 2.1 all is fine but when I update my Microsoft.EntityFrameworkCore (+ .Design & .SqlServer) from 2.0.3 to 2.1.0/2.1.1 

I have this exception : 

```
A second operation   started on this context before a previous operation completed. Any instance   members are not guaranteed to be thread safe.

TRACE CODE
TRACE CODE
   at Microsoft.EntityFrameworkCore.Internal.ConcurrencyDetector.EnterCriticalSection()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
   at System.Collections.Generic.List`1.AddEnumerable(IEnumerable`1 enumerable)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at API.Model.Services.CategService.GetProducts(String number) in C:\Users\Xavier\Source\Workspaces\API\Dev-16012018\Core\Model\Services\CategService.cs:line 33
   at lambda_method(Closure , ValueBuffer )
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Boolean& found)
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ResultEnumerable`1.GetEnumerator()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Boolean& found)
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass15_1`1.b__0(QueryContext qc)
   at System.Linq.Queryable.First[TSource](IQueryable`1 source)
   at API.Model.Services.CategService.GetCateg(String number) in C:\Users\Xavier\Source\Workspaces\API\Dev-16012018\Core\Model\Services\CategService.cs:line 97
   at API.Controllers.CategController.GetCateg(String number) in C:\Users\Xavier\Source\Workspaces\API\Dev-16012018\API\Controllers\v1\CategController.cs:line 59
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.SyncActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at NetEscapades.AspNetCore.SecurityHeaders.Infrastructure.SecurityHeadersMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.Invoke(HttpContext context)


```
This problem does not exist with version 2.0.3

### Steps to reproduce

```c#
 public List<ProductVM> GetProducts(string number)
        {

            // A second operation started on this context before a previous operation completed. Any instance members are not guaranteed to be thread safe.
            var data = _context.DataCateg.Where(u => u.DataCategNumber == number).Select(u => new ProductVM()
            {
                id = u.DataCategId,
                account = u.DataCategAccount,
                prixe = u.DataCategPrice,
                insert = u.DataCategInsert,
                update = u.DataCategUpdate
            }).ToList();

            return data;
        }
```

```c#
 var categ = _context.Categories.Where(u => u.CategId == id || (u.CategNumber == number && u.CategCrc == crc)).Select(c =>
            new CategVM()
            {
                number = string.Concat(c.CategPrefixe,c.CategNumber, c.CategCrc),
                products = GetProducts(c.CategNumber)
            });

            if (categ.Count() == 1)
                return categ.First(); <==== Error 
```

### Further technical details
EF Core version: 2.1
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10 x64
IDE:  Visual Studio 2017 15.7.4

**Comment by sdanyliv** [comment]
@xav-stargate, it is better to rewrite your query using Eager loading. This linq query produces additional database queries for each main record and needs additional database connection for processing. It may lead bad performance and bad resources usage even when EF guys fix this issue.

**Comment by ajcvickers** [comment]
@xav-stargate Have you checked that the code is not attempting to execute multiple queries concurrently using the same context instance? If so, then please post a runnable project/solution or complete code listing that demonstrates the issue.

**Comment by sdanyliv** [comment]
@ajcvickers, sorry for the intervention, not sure but looks like in newer version changed moment when DataReader is closed.

**Comment by ajcvickers** [comment]
@sdanyliv Not sure how that is relevant.

**Comment by sdanyliv** [comment]
Ideally when First() method called, DataReader should be closed and EF should finish matherialization using client eval of non server side properties. But if you have mechanism that opens additional database connection during reading data from DataReader, yes it is not revelant.

**Comment by xav-stargate** [comment]
@ajcvickers I do not think so but I'm not sure, why in 2.1.1 and not in 2.0.3 ?
You can download a solution that demonstrates the issue here : https://drive.google.com/open?id=1gmMCPTy7EkDJy4ARzW8i5sNJa5CUaGwS

The solution use EntityFrameworkCore & EntityFrameworkCore.SqlServer 2.0.3 it's work and if you change to 2.1.1 you have the issue

@sdanyliv Thanks for the suggestion, I will rewrite my code to use the Eager Loading

**Comment by ajcvickers** [comment]
Note for triage: Simplified repro code is below. Notice that this fails only when passing an extra parameter to the method.

```C#
public class Course
{
    public int Id { get; set; }
}

public class BloggingContext : DbContext
{
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        optionsBuilder
            .UseSqlServer(@"Server=(localdb)\mssqllocaldb;Database=Test;ConnectRetryCount=0");
    }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Course>();
    }
}

public class Program
{
    private static List<Course> Works(BloggingContext context)
        => context.Set<Course>().Where(e => e.Id == 1).ToList();

    private static List<Course> Fails(BloggingContext context, int courseId)
        => context.Set<Course>().Where(e => e.Id == courseId).ToList();

    public static void Main()
    {
        using (var context = new BloggingContext())
        {
            context.Database.EnsureDeleted();
            context.Database.EnsureCreated();

            context.Add(new Course());

            context.SaveChanges();
        }

        using (var context = new BloggingContext())
        {
            var result1 = context
                .Set<Course>()
                .Select(c => Works(context))
                .SingleOrDefault();

            var result2 = context
                .Set<Course>()
                .Select(c => Fails(context, c.Id))
                .SingleOrDefault();
        }
    }
}
```
In the case that works, the inner query is executed first:
```
Compiling query model:
      'from Course e in DbSet<Course>
      where [e].Id == 1
      select [e]'
```
```sql
      SELECT [e].[Id]
      FROM [Course] AS [e]
      WHERE [e].[Id] = 1
```
```
Compiling query model:
      '(from Course c in DbSet<Course>
      select __Works_0).SingleOrDefault()'
```
```sql
      SELECT TOP(2) 1
      FROM [Course] AS [c]
```
In the case that doesn't work, the inner query is executed while the outer query is executing:
```
Compiling query model:
      '(from Course c in DbSet<Course>
      select List<Course> Fails(
          context: __context_0,
          courseId: [c].Id)).SingleOrDefault()'
```
```sql
      SELECT TOP(2) [c].[Id]
      FROM [Course] AS [c]
```
```
Compiling query model:
      'from Course e in DbSet<Course>
      where [e].Id == __courseId_0
      select [e]'
```
```
fail: A second operation started on this context before a previous operation completed. Any instance members are not guaranteed to be thread safe.
```

**Comment by ajcvickers** [comment]
Note from triage: we will attempt to write a better message here that clarifies why this is happening.

**Comment by ksmithRenweb** [comment]
Howdy,

Reading this issue, helped me track down an issue my team was having.

I don't know if this is caused by the exact same issue, but I have a simpler scenario to reproduce. I personally would have tolist before foreach but it was written by a junior dev. This code has been in production on EF Core 2.0 for months. So it is a breaking change in behavior.

IQueryable<> iterate = context.SomeQuery;

foreach(var item in iterate)
{
    IQueryable<> ret = context.SecondQuery.Where(t=>t.ItemId = item);
    var list = ret.ToList(); <=== Exception
}

EFCore SQL 2.1.1

It is late on a Friday. So if this didn't make sense, just let me know, and I'll explain it better on Monday.

Thank you,
Kevin Smith

**Comment by alexandruionescu** [comment]
I've just had this error pop up when upgrading from 2.0 to 2.2 with either lazy loading or ToList-ing before iterating. The errors went away after removing all .AsNoTracking() extension calls, which were probably used incorrectly, but were not breaking in 2.0.

**Comment by JessyParis** [comment]
EFCore 2.2.4.
I have same error message when using .AsNoTracking.
If I remove .AsNoTracking, then I get no error.

**Comment by ajcvickers** [comment]
@JessyParis Please post a new issue and include a small, runnable project/solution or complete code listing that demonstrates the behavior you are seeing.

**Comment by ajai1109** [comment]
Why this issue has been closed without the proper solution? I am also facing the same issue!!

**Comment by AndriySvyryd** [comment]
@ajai1109 This exception is expected if you are using a context concurrently from two threads. If that's not the case then please post a new issue and include a small, runnable project/solution or complete code listing that demonstrates the behavior you are seeing.
