### ISSUE TITLE
Migrations fail silently when Startup.cs code throws exception (error message says to implement DbContextFactory)

### ISSUE THREAD

**Issue by welkie** [aspnet/EntityFrameworkCore#12516]
I deleted my migrations folder because my workflow involves periodically deleting the database and recreating it (I use docker-compose to do this easily). I just wanted a fresh database after my latest model change, since I knew doing this change through a migration would involve data loss.

When I ran `dotnet ef database update` I got an error message saying the following:

```
An error occurred while accessing the IWebHost on class 'Program'. Continuing without the application service provider.
Error: Object reference not set to an instance of an object.
Unable to create an object of type 'ApplicationDbContext'. Add an implementation of 'IDesignTimeDbContextFactory<ApplicationDbContext>' to the project, or see https://go.microsoft.com/fwlink/?linkid=851728 for additional patterns supported at design time.
```

I googled and read that this happens when the EF Core tools aren't able to construct an instance of the DbContext to use to run the migrations. I tried implementing the interface myself, with the following code:

```csharp
class DesignTimeApplicationDbContextFactory : IDesignTimeDbContextFactory<ApplicationDbContext>
    {
        public ApplicationDbContext CreateDbContext(string[] args)
        {
            var optionsBuilder = new DbContextOptionsBuilder<ApplicationDbContext>();
            optionsBuilder.UseNpgsql("Server=localhost;Database=REDACTED;User ID=REDACTED;Password=REDACTED;Port=5432");

            return new ApplicationDbContext(optionsBuilder.Options);
        }
    }
```

But this made no difference. I still got the error message.

### Steps to reproduce
Private project, so source code cannot be provided.

1. Run `dotnet ef database update` from the project directory.

### Further technical details
EF Core version: (found in project.csproj or packages.config)
Using `All` package:

```xml
<PackageReference Include="Microsoft.AspNetCore.App" Version="2.1.1" />
```
Database Provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer) Npgsql
Operating system:  Windows 10 Pro
IDE: Visual Studio Code
Version 1.24.1
Commit 24f62626b222e9a8313213fb64b10d741a326288
Date 2018-06-13T17:51:32.889Z
Shell 1.7.12
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

**Comment by welkie** [comment]
After more debugging I have found what caused the issue for me. It was nothing to do with deleting my Migrations directory. I was also testing the Google Cloud SDK and I had some test code still in my program. It built and ran fine in the Visual Studio Code debugger, so I thought nothing of it. However, the code caused an instance of the Google Cloud Storage client to be created, grabbing the service account key from an environment variable. The environment variable isn't set by the EF Core CLI tool, so this would have raised an exception. Since exception details aren't exposed, I had no way to know this was the failure.

My code looked like this:

```csharp
// GoogleCloudStorageTest.cs

using System;
using Google.Apis.Auth.OAuth2;
using Google.Cloud.Storage.V1;

namespace REDACTED
{
    class GoogleCloudStorageTest
    {
        public static void Test()
        {
            var credentials = GoogleCredential.FromJson(Environment.GetEnvironmentVariable("GOOGLE_APPLICATION_CREDENTIALS_JSON"));

            StorageClient client = StorageClient.Create(credentials);

            Console.WriteLine(client);
        }
    }
}
```

```csharp
// At the end of Startup.ConfigureServices.cs

GoogleCloudStorageTest.Test();
```

I recommend the team include some details about exceptions thrown while the `dotnet ef` commands attempt to grab a DbContext instance. It feels like this can be tricky to solve.

**Comment by ajcvickers** [comment]
Notes for triage: behaviors when DbContext has no parameterless constructor.

When there are no 'hosting' methods (e.g. `BuildWebHost`) found, then:
```
PM> add-migration One
Unable to create an object of type 'BloggingContext'. Add an implementation of 'IDesignTimeDbContextFactory<BloggingContext>' to the project, or see https://go.microsoft.com/fwlink/?linkid=851728 for additional patterns supported at design time.
```
Following [the link](https://go.microsoft.com/fwlink/?linkid=851728) doesn't directly give examples of using the hosting methods, although the information can be found in further linked places.

When hosting methods exist but throw:
```
PM> add-migration One
System.InvalidOperationException: Unable to resolve service for type 'Microsoft.Extensions.Logging.LoggerFactory' while attempting to activate 'BloggingContext'.
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateArgumentCallSites(Type serviceType, Type implementationType, CallSiteChain callSiteChain, ParameterInfo[] parameters, Boolean throwIfCallSiteNotFound)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateConstructorCallSite(Type serviceType, Type implementationType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(ServiceDescriptor descriptor, Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateCallSite(Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.CreateServiceAccessor(Type serviceType)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.<>c__DisplayClass12_2.<FindContextTypes>b__11()
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(Func`1 factory)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(String contextType)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.AddMigration(String name, String outputDir, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigrationImpl(String name, String outputDir, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
Unable to resolve service for type 'Microsoft.Extensions.Logging.LoggerFactory' while attempting to activate 'BloggingContext'.
```
Notice that in this case there is no forward link.

Same behavior with dotnet command line. For example:
```
C:\Stuff\TwoOneCore\TwoOneCore>dotnet ef migrations add One
System.InvalidOperationException: Unable to resolve service for type 'Microsoft.Extensions.Logging.LoggerFactory' while attempting to activate 'BloggingContext'.
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateArgumentCallSites(Type serviceType, Type implementationType, CallSiteChain callSiteChain, ParameterInfo[] parameters, Boolean throwIfCallSiteNotFound)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateConstructorCallSite(Type serviceType, Type implementationType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(ServiceDescriptor descriptor, Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateCallSite(Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.CreateServiceAccessor(Type serviceType)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.<>c__DisplayClass12_2.<FindContextTypes>b__11()
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(Func`1 factory)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(String contextType)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.AddMigration(String name, String outputDir, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigrationImpl(String name, String outputDir, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
Unable to resolve service for type 'Microsoft.Extensions.Logging.LoggerFactory' while attempting to activate 'BloggingContext'.
```

**Comment by welkie** [comment]
I notice that your dotnet command line exposed the exception that was thrown. This behavior is actually different from mine. My code threw an exception but that caused the message "you must implement x..." to be displayed, even though

**Comment by ajcvickers** [comment]
@welkie Yes, please. That would be useful.

**Comment by ajcvickers** [comment]
Triage: assigning to Brice and Diego to improve the tool output -> docs path such that it better elucidates the options available here, including using the correct ASP.NET patterns.

**Comment by joarkm** [comment]
> See [this](https://stackoverflow.com/a/52671330/3462759)

Thank you!

**Comment by bricelam** [comment]
Note to implementer: If the logging level of any messages change, be sure to test it with Scaffolding and Publish.

**Comment by bricelam** [comment]
Filed aspnet/EntityFramework.Docs#1087 to improve the docs.
