### ISSUE TITLE
Exception when adding two Sum with one being null

### ISSUE THREAD

**Issue by fschlaef** [aspnet/EntityFrameworkCore#12520]
When adding two `Sum()` results, if one returns null, the whole query fails.
However, if no addition is performed the Sum will be 0.

Exception message: `Nullable object must have a value.`

Stack trace:
```
System.InvalidOperationException: Nullable object must have a value.
   at lambda_method(Closure , QueryContext , ValueBuffer )
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.ProjectionShaper.TypedProjectionShaper`3.Shape(QueryContext queryContext, ValueBuffer& valueBuffer)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.BufferlessMoveNext(DbContext _, Boolean buffer)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.MoveNext()
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Boolean& found)
   at lambda_method(Closure )
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ResultEnumerable`1.GetEnumerator()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()

```

### Steps to reproduce
Full repro, including workaround

```c#
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;

namespace _12520Repro
{
    class Program
    {
        static void Main(string[] args)
        {
            using (var context = new MyContext())
            {
                context.Database.EnsureDeleted();
                context.Database.EnsureCreated();

                context.Item.Add(new Item());

                context.SaveChanges();
            }

            try
            {
                using (var context = new MyContext())
                {
                    // Workaround
                    var queryWorking = context.Item
                        .Select(i => new
                        {
                            i.Id,
                            TotalAmount = i.Invoice
                                .Sum(iv => iv.Amount), // Will return 0
                        })
                        .FirstOrDefault();

                    Debug.WriteLine("THIS QUERY IS WORKING : " + queryWorking.TotalAmount);

                    var queryCrashing = context.Item
                        .Select(i => new
                        {
                            i.Id,
                            TotalAmount = i.Invoice.Sum(iv => iv.Amount) 
                                        + i.Invoice.Sum(iv => iv.Amount) // Should return 0, but throws because i.Invoice is empty
                        })
                        .FirstOrDefault();

                    Debug.WriteLine("THIS QUERY IS NOT WORKING : " + queryCrashing.TotalAmount);
                }
            }
            catch(Exception e)
            {
                Debug.WriteLine(e.Message);
            }
        }
    }

    public class MyContext : DbContext
    {
        public virtual DbSet<Invoice> Invoice { get; set; }
        public virtual DbSet<Item> Item { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            string connectionString = "Server=.;Database=Repro12520;Trusted_Connection=True;MultipleActiveResultSets=true";

            optionsBuilder.UseSqlServer(connectionString)
                .EnableSensitiveDataLogging()
                .UseLoggerFactory(new LoggerFactory().AddDebug(LogLevel.Debug));
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Invoice>(entity =>
            {
                entity.HasIndex(e => e.ItemFk)
                    .HasName("IX_Invoice_ItemId");

                entity.HasOne(d => d.ItemFkNavigation)
                    .WithMany(p => p.Invoice)
                    .HasForeignKey(d => d.ItemFk)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_Invoice_Item_ItemId");
            });
        }
    }


    public partial class Invoice
    {
        public int Id { get; set; }
        public double Amount { get; set; }
        public int ItemFk { get; set; }

        public Item ItemFkNavigation { get; set; }
    }

    public partial class Item
    {
        public Item()
        {
            Invoice = new HashSet<Invoice>();
        }

        public int Id { get; set; }
        public ICollection<Invoice> Invoice { get; set; }
    }
}

```

### Further technical details
EF Core version: 2.1.1
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 7
IDE: Visual Studio 2017 15.7.4

**Comment by maumar** [comment]
Still fails in current bits. Query plan:

```
(QueryContext queryContext) => IEnumerable<<>f__AnonymousType0<int, double>> _InterceptExceptions(
|__ source: IEnumerable<<>f__AnonymousType0<int, double>> _ToSequence(() => <>f__AnonymousType0<int, double> FirstOrDefault(IEnumerable<<>f__AnonymousType0<int, double>> _ShapedQuery(
|   |__ queryContext: queryContext, 
|   |__ shaperCommandContext: SelectExpression: 
|   |       SELECT TOP(1) [i].[Id], (
|   |           SELECT SUM([iv].[Amount])
|   |           FROM [Invoice] AS [iv]
|   |           WHERE [i].[Id] = [iv].[ItemFk]
|   |       ) AS [TotalAmount]
|   |       FROM [Item] AS [i], 
|   |__ shaper: (QueryContext queryContext | ValueBuffer i) => new { 
|           int TryReadValue(i, 0, Item.Id), 
|           (double)Nullable<double> TryReadValue(i, 1, null) ?? default(double)
|        }))), 
|__ contextType: Repro12520.MyContext, 
|__ logger: DiagnosticsLogger<Query>, 
|__ queryContext: Unhandled parameter: queryContext)
```

**Comment by fschlaef** [comment]
@ajcvickers Good news ! As of `3.0.0-rc1` this bug is "resolved", as in, it doesn't crash anymore.
Bad news ! I found another issue with `.Sum()` and null-coalescing, see https://github.com/aspnet/EntityFrameworkCore/issues/17492
