### ISSUE TITLE
.Select property from within collection causes NullReferenceException

### ISSUE THREAD

**Issue by MattOG** [aspnet/EntityFrameworkCore#12534]
Apologies if I don't submit this correctly.
Issue:
Attempting to access a collection using .First(), .FirstOrDefault(), .Single(), or .SingleOrDefault() throws a NullReferenceException when the collection is not empty.

The collection accessed (Customer.Locations) and the properties within (.Location.Country) is never null and I have confirmed it as such with the working data.

Controller Query:
```C#
var customers =
    _context.Customers
        .Include(x => x.Locations).ThenInclude(x => x.Location.Country)
        .Select(x => new IdTextCodeModel
        {
            Code = x.Locations.Single().Location.Country.CountryCode, // This .Single() could be any of the above methods
            Id = x.IdCustomer,
            Text = x.InternalName
        })
       .ToList();
```
NB: Adding a .ToList() to before the .Select(...) results in the list populated as expected.
```
Exception:
System.NullReferenceException 'Object reference not set to an instance of an object.'

Stack Trace:
at lambda_method(Closure , QueryContext , ValueBuffer )
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.ProjectionShaper.TypedProjectionShaper`3.Shape(QueryContext queryContext, ValueBuffer& valueBuffer)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.BufferlessMoveNext(DbContext _, Boolean buffer)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
   at System.Collections.Generic.List`1.AddEnumerable(IEnumerable`1 enumerable)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Proseal.Areas.Accounts.Controllers.EditorController.GetCustomers()
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.SyncActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
```
```C#
public class Customer
{
    ...
    public virtual ICollection<CustomerLocation> Locations { get; set; }
    ...
}
```
```C#
public class CustomerLocation
{
    ...
    public virtual Location Location { get; set; }
    ...
}
```
```C#
public class CustomerLocationConfiguration : IEntityTypeConfiguration<CustomerLocation>
{
    ...
    builder.HasOne(t => t.Location)
                .WithMany(t => t.CustomerLocations)
                .HasForeignKey(d => d.IdLocation);
    builder.HasOne(t => t.Customer)
                .WithMany(t => t.Locations)
                .HasForeignKey(d => d.IdCustomer);
    ...
}
```
```C#
public class Location
{
    ...
    public virtual Country Country { get; set; }
    ...
}
```
```C#
public class LocationConfiguration : IEntityTypeConfiguration<Location>
{
    ...
    builder.HasOne(t => t.Country)
                .WithMany(t => t.Locations)
                .HasForeignKey(d => d.IdCountry);
    ...
}
```

### Further technical details
EF Core version: v2.1.1
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10
IDE: Visual Studio 2017 v15.7.4

**Comment by kjbetz** [comment]
I wonder if this is similar: https://github.com/aspnet/EntityFrameworkCore/issues/12531

**Comment by umarlateef** [comment]
Any update on this issue? I am facing the same issue

**Comment by ajcvickers** [comment]
@umarlateef As indicated by the GitHub milestone and tags, this issue is triaged as a bug to be investigated in the 3.0 time frame.

**Comment by maumar** [comment]
Workaround:

```cs
var customers =
    _context.Customers
        //.Include(x => x.Locations).ThenInclude(x => x.Location.Country)
        .Select(x => new IdTextCodeModel
        {
            Code = x.Locations.Select(l => l.Location.Country.CountryCode).Single(), 
            Id = x.IdCustomer,
            Text = x.InternalName
        })
       .ToList();
```

**Comment by MattOG** [comment]
Yes, the second select will also cause the deferred execution to no longer be deferred. Easier to add .ToList() before the select as I mentioned above though I think.

**Comment by maumar** [comment]
@MattOG when pushing FirstOrDefault to the end you can achieve much better sql:

```sql
SELECT (
    SELECT TOP(1) [l.Location.Country].[CountryCode]
    FROM [CustomerLocation] AS [l]
    INNER JOIN [Location] AS [l.Location] ON [l].[IdLocation] = [l.Location].[Id]
    INNER JOIN [Country] AS [l.Location.Country] ON [l.Location].[IdCountry] = [l.Location.Country].[Id]
    WHERE [x].[Id] = [l].[IdCustomer]
) AS [Code], [x].[Id], [x].[InternalName] AS [Text]
FROM [Customers] AS [x]
```

this only works for FirstOrDefault. With Single, First and SingleOrDefault, you will get N+1

**Comment by maumar** [comment]
this is fixed in current bits, member pushdown is now applied recursively
