### ISSUE TITLE
Generating invalid SQL for RenameTable for 2.1.0-preview1 version

### ISSUE THREAD

**Issue by Materix** [aspnet/EntityFrameworkCore#12559]
I have migration generated with version `2.1.0-preview1-27377`. In this migration renaming table was generated as
```c#
            migrationBuilder.RenameTable(
                name: "Connections",
                schema: "dbo",
                newName: "ElectronicIds");
```

During creating database using IIS APPPOOL user (with default schema set to `IIS APPPOOL\DefaultAppPool`) exception occured:
```
fail: Microsoft.EntityFrameworkCore.Database.Command[20102]
      Failed executing DbCommand (27ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      EXEC sp_rename N'[dbo].[DiagramVehicles]', N'AnalysisDiagramVehicles';
      DECLARE @defaultSchema sysname = SCHEMA_NAME();
      EXEC(N'ALTER SCHEMA ' + @defaultSchema + N' TRANSFER [dbo].[AnalysisDiagramVehicles];');
System.Data.SqlClient.SqlException (0x80131904): Incorrect syntax near "APPPOOL".
Uwaga: Zmiana którejkolwiek części nazwy obiektu może spowodować uszkodzenie skryptów i procedur składowanych.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
   at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues)
ClientConnectionId:6b8ce510-b433-4735-9098-c007b6ce460e
Error Number:102,State:1,Class:15
```

Generated SQL:
```SQL
EXEC sp_rename N'[dbo].[Connections]', N'ElectronicIds';
DECLARE @defaultSchema sysname = SCHEMA_NAME();
EXEC(N'ALTER SCHEMA ' + @defaultSchema + N' TRANSFER [dbo].[ElectronicIds];');
```

Firsly, there is no escaping for @defaultSchema and therefore generated SQL is invalid. 
Secondly, there should not be transfer operation.

In https://github.com/aspnet/EntityFrameworkCore/blob/2.1.1/src/EFCore.SqlServer/Migrations/SqlServerMigrationsSqlGenerator.cs#L481
`HasLegacyRenameOperations` should return `true`, but 

```c#
> new SemanticVersionComparer().Compare("2.1.0-preview1-27377", "2.1.0")
0
```

In migrations for version `2.1.0` renaming is generated as
```c#
            migrationBuilder.RenameTable(
                name: "ElectronicIds",
                schema: "dbo",
                newName: "Test",
                newSchema: "dbo");
```

### Further technical details
EF Core version: 2.1.1
Database Provider: Microsoft.EntityFrameworkCore.SqlServer

**Comment by bricelam** [comment]
(Bringing back to Triage to discuss `SemanticVersionComparer`.)

**Comment by divega** [comment]
@bricelam to comment on the resolution.
