### ISSUE TITLE
Performing a Subquery on a string-mapped Enum results in InvalidOperationException

### ISSUE THREAD

**Issue by AtomicBlom** [aspnet/EntityFrameworkCore#12556]
I have a database with a series of Reference tables that have Enums mapped to strings using `.HasConversion(typeof(string))`

We have run into an issue where attempting to perform a query that uses the reference table's mapped enum in a subquery results in an InvalidOperationException.

I'm able to query the reference tables using the entities and they are returned as expected. I'm also able use .Include() to bring the reference table back and perform the mapping in-memory.

While attempting to reproduce the issue using the sqlite provider, I noticed that the Enum always returns default(TEnum), and does not produce an exception.

```
Exception message:
System.InvalidOperationException : An exception occurred while reading a database value. The expected type was 'EnumFailureTest.IdentificationMethod' but the actual value was of type 'System.String'.

Stack trace:
---- System.InvalidCastException : Unable to cast object of type 'System.String' to type 'System.Int32'.
   at Microsoft.EntityFrameworkCore.Metadata.Internal.EntityMaterializerSource.ThrowReadValueException[TValue](Exception exception, Object value, IPropertyBase property)
   at lambda_method(Closure , DbDataReader )
   at Microsoft.EntityFrameworkCore.Storage.Internal.TypedRelationalValueBufferFactory.Create(DbDataReader dataReader)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncQueryingEnumerable`1.AsyncEnumerator.BufferlessMoveNext(DbContext _, Boolean buffer, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncQueryingEnumerable`1.AsyncEnumerator.MoveNext(CancellationToken cancellationToken)
   at System.Linq.AsyncEnumerable.SingleOrDefault_[TSource](IAsyncEnumerable`1 source, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.TaskResultAsyncEnumerable`1.Enumerator.MoveNext(CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext(CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteSingletonAsyncQuery[TResult](QueryContext queryContext, Func`2 compiledQuery, IDiagnosticsLogger`1 logger, Type contextType)
   at EnumFailureTest.ProjectedEnumTests.EnumMapsViaIntegerWhenProjectedUsingASubquery() in C:\Users\StevenBlom\source\repos\EnumFailureTest\EnumFailureTest\ProjectedEnumTests.cs:line 56
--- End of stack trace from previous location where exception was thrown ---
----- Inner Stack Trace -----
   at System.Data.SqlClient.SqlBuffer.get_Int32()
   at lambda_method(Closure , DbDataReader )

```

### Steps to reproduce
I have isolated the issue in a github repository at
https://github.com/AtomicBlom/efcore-enum-bug

```c#
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using Xunit;

namespace EnumFailureTest
{
    public class ProjectedEnumTests
    {
        private AppDbContext Context => new AppDbContext();
        private static bool _isInitialized;

        public ProjectedEnumTests()
        {
            if (_isInitialized) return;

            using (var context = new AppDbContext())
            {
                context.Database.EnsureDeleted();
                context.Database.EnsureCreated();
                context.Animals.Add(new Animal
                {
                    IdentificationMethods = new[]
                    {
                        new AnimalIdentification
                        {
                            Method = IdentificationMethod.EarTag,
                        }
                    }
                });
                context.SaveChanges();
            }
            _isInitialized = true;
        }

        //We can query without a projection, including the child property and it maps correctly.
        [Fact]
        public async Task EnumMapsViaStringCorrectlyWhenQueriedDirectly()
        {
            var animal = await Context.Animals
                .Include(a => a.IdentificationMethods)
                .FirstOrDefaultAsync();

            var method = animal.IdentificationMethods.First().Method;
            Assert.Equal(IdentificationMethod.EarTag, method);
        }

        //Attempting to perform any subquery on IdentificationMethods causes efcore to ignore the
        //.HasConversion So it expects the enum as an integer instead of a string.
        [Fact]
        public async Task EnumMapsViaIntegerWhenProjectedUsingASubquery()
        {
            var query = from animal in Context.Animals
                select new
                {
                    animal.Id,
                    animal.IdentificationMethods.FirstOrDefault().Method
                };

            //throws InvalidOperationException:
            var result = await query.SingleOrDefaultAsync();
            Assert.Equal(IdentificationMethod.EarTag, result.Method);
        }
    }

    public class AppDbContext : DbContext
    {
        public DbSet<Animal> Animals { get; set; }
        public DbSet<AnimalIdentification> AnimalIdentifiers { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder
                //.UseSqlite("Data Source=EnumTest.db");
                .UseSqlServer("Server=(localdb)\\mssqllocaldb;Database=EnumTest;Trusted_Connection=True");
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            var postModelBuilder = modelBuilder.Entity<AnimalIdentification>();
            postModelBuilder.Property(e => e.Method)
                .IsRequired()
                .HasMaxLength(6)
                .HasConversion(typeof(string));
        }
    }

    public class Animal
    {
        public int Id { get; set; }
        public ICollection<AnimalIdentification> IdentificationMethods { get; set; }
    }

    public class AnimalIdentification
    {
        public int Id { get; set; }
        public IdentificationMethod Method { get; set; }
    }

    public enum IdentificationMethod
    {
        Notch,
        EarTag,
        Rfid
    }
}
```

### Further technical details
EF Core version: 2.1.1
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10
IDE:  Visual Studio 2017 15.7.4

edit: to try and reduce horizontal scrolling in code

**Comment by ajcvickers** [comment]
Note for triage: reproduces for me. Query logging:

```
dbug: Microsoft.EntityFrameworkCore.Query[10101]
      => Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor
      Compiling query model:
      '(from Animal animal in DbSet<Animal>
      select new <>f__AnonymousType0<int, IdentificationMethod>(
          [animal].Id,

              (from AnimalIdentification <generated>_1 in [animal].IdentificationMethods
              select [<generated>_1]).FirstOrDefault().Method
      )).SingleOrDefault()'
dbug: Microsoft.EntityFrameworkCore.Query[10104]
      => Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor
      Optimized query model:
      '(from Animal animal in DbSet<Animal>
      select new <>f__AnonymousType0<int, IdentificationMethod>(
          [animal].Id,
          (IdentificationMethod)
              (from AnimalIdentification <generated>_1 in DbSet<AnimalIdentification>
              where  ?= (Nullable<int>)Property([animal], "Id") == Property([<generated>_1], "AnimalId") =?
              select (Nullable<IdentificationMethod>)[<generated>_1].Method).FirstOrDefault()
      )).SingleOrDefault()'
dbug: Microsoft.EntityFrameworkCore.Query[10107]
      => Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor
      (QueryContext queryContext) => IAsyncEnumerable<<>f__AnonymousType0<int, IdentificationMethod>> _InterceptExceptions(
          source: IAsyncEnumerable<<>f__AnonymousType0<int, IdentificationMethod>> _ToSequence(() => Task<<>f__AnonymousType0<int, IdentificationMethod>> SingleOrDefault(
                  source: IAsyncEnumerable<<>f__AnonymousType0<int, IdentificationMethod>> _ShapedQuery(
                      queryContext: queryContext,
                      shaperCommandContext: SelectExpression:
                          SELECT TOP(2) [animal].[Id], (
                              SELECT TOP(1) [a].[Method]
                              FROM [AnimalIdentifiers] AS [a]
                              WHERE [animal].[Id] = [a].[AnimalId]
                          ) AS [Method]
                          FROM [Animals] AS [animal],
                      shaper: TypedProjectionShaper<ValueBufferShaper, ValueBuffer, <>f__AnonymousType0<int, IdentificationMethod>>),
                  cancellationToken: queryContext.CancellationToken)),
          contextType: EnumFailureTest.AppDbContext,
          logger: DiagnosticsLogger<Query>,
          queryContext: queryContext)
...
dbug: Microsoft.EntityFrameworkCore.Database.Command[20100]
      Executing DbCommand [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT TOP(2) [animal].[Id], (
          SELECT TOP(1) [a].[Method]
          FROM [AnimalIdentifiers] AS [a]
          WHERE [animal].[Id] = [a].[AnimalId]
      ) AS [Method]
      FROM [Animals] AS [animal]
...
fail: Microsoft.EntityFrameworkCore.Query[10100]
      An exception occurred in the database while iterating the results of a query for context type 'EnumFailureTest.AppDbContext'.
      System.InvalidOperationException: An exception occurred while reading a database value. The expected type was 'EnumFailureTest.IdentificationMethod' but the actual value was of type 'System.String'. ---> System.InvalidCastException: Unable to cast object of type 'System.String' to type 'System.Int32'.
         at System.Data.SqlClient.SqlBuffer.get_Int32()
         at lambda_method(Closure , DbDataReader )
         --- End of inner exception stack trace ---
         at Microsoft.EntityFrameworkCore.Metadata.Internal.EntityMaterializerSource.ThrowReadValueException[TValue](Exception exception, Object value, IPropertyBase property)
         at lambda_method(Closure , DbDataReader )
         at Microsoft.EntityFrameworkCore.Storage.Internal.TypedRelationalValueBufferFactory.Create(DbDataReader dataReader)
         at Microsoft.EntityFrameworkCore.Query.Internal.AsyncQueryingEnumerable`1.AsyncEnumerator.BufferlessMoveNext(DbContext _, Boolean buffer, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Query.Internal.AsyncQueryingEnumerable`1.AsyncEnumerator.MoveNext(CancellationToken cancellationToken)
         at System.Linq.AsyncEnumerable.SingleOrDefault_[TSource](IAsyncEnumerable`1 source, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.TaskResultAsyncEnumerable`1.Enumerator.MoveNext(CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext(CancellationToken cancellationToken)
System.InvalidOperationException: An exception occurred while reading a database value. The expected type was 'EnumFailureTest.IdentificationMethod' but the actual value was of type 'System.String'. ---> System.InvalidCastException: Unable to cast object of type 'System.String' to type 'System.Int32'.
   at System.Data.SqlClient.SqlBuffer.get_Int32()
   at lambda_method(Closure , DbDataReader )
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Metadata.Internal.EntityMaterializerSource.ThrowReadValueException[TValue](Exception exception, Object value, IPropertyBase property)
   at lambda_method(Closure , DbDataReader )
   at Microsoft.EntityFrameworkCore.Storage.Internal.TypedRelationalValueBufferFactory.Create(DbDataReader dataReader)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncQueryingEnumerable`1.AsyncEnumerator.BufferlessMoveNext(DbContext _, Boolean buffer, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncQueryingEnumerable`1.AsyncEnumerator.MoveNext(CancellationToken cancellationToken)
   at System.Linq.AsyncEnumerable.SingleOrDefault_[TSource](IAsyncEnumerable`1 source, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.TaskResultAsyncEnumerable
`1.Enumerator.MoveNext(CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext(CancellationToken cancellationToken)
```

**Comment by m-demydiuk** [comment]
I got exactly the same issue. 
Do you know any workarounds? Loading data in memory will be time-consuming and we should do it on the db side.

Seems it is not fixed in 2.2.1.

**Comment by smitpatel** [comment]
`FindProperty` method does not go inside SelectExpression to find out the property hence, we failed to find the Enum property and did not use value converter.

**Comment by smitpatel** [comment]
@maumar - Poaching this!
