### ISSUE TITLE
Unable to insert smalldatetime value into database using HasData method

### ISSUE THREAD

**Issue by Sequenta** [aspnet/EntityFrameworkCore#12584]
I am using latest Entity Framework and new feature `HasData` to populate database with initial data. 
Test entity that I am using has `DateTime` field
```c#
 public class TestEntity
 {
     public Guid Id { get; set; }
     public DateTime? SmallDate { get; set; }
 }
```
that is mapped to smalldatetime column in database.
```c#
 protected override void OnModelCreating(ModelBuilder builder)
 {
    base.OnModelCreating(builder);
    builder.Entity<TestEntity>().Property(x => x.SmallDate).HasColumnType("smalldatetime");
    ...
```
While applying migration generated for `HasData`
```c#
 builder.Entity<TestEntity>().HasData(
                new TestEntity { Id = new Guid("61242D0B-DDCF-46A2-B853-F50A30ECE25B"), SmallDate = DateTime.UtcNow }
            );
```
exception occurs
```
Exception message: Conversion failed when converting character string to smalldatetime data type.
Stack trace :System.Data.SqlClient.SqlException (0x80131904): Conversion failed when converting character string to smalldatetime data type.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, Boolean sendToPipe, Int32 timeout, Boolean asyncWrite, String methodName)
   at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteNonQuery(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Migrations.MigrationCommand.ExecuteNonQuery(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.ExecuteNonQuery(IEnumerable`1 migrationCommands, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.UpdateDatabase(String targetMigration, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabase.<>c__DisplayClass0_1.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
```
Simple add  to `DbSet` works fine:
```c#
 var result = _context.TestEntities.Add(new TestEntity
{
    SmallDate = DateTime.UtcNow
});
 _context.SaveChanges();
```
### Steps to reproduce
Using this [repository](https://github.com/Sequenta/SmallDateTimeRepro.git)
1. Create database Repro
2. Apply migrations
3. Run project and go to `/test` to see that add is working
4. Add migration for init data. Should generate migration for `HasData` method in `TestContext`
5. Migration failed with message: 
```
"Conversion failed when converting character string to smalldatetime data type."
```

### Further technical details
EF Core version: 2.1.1
Database Provider: Microsoft.EntityFrameworkCore.SqlServer, Version="2.1.1"
Operating system: Windows 10
IDE: Visual Studio 2017 15.7.3

**Comment by smitpatel** [comment]
This could be fixed by #13118
