### ISSUE TITLE
Broken test: GroupBy_Composite_Select_Dto_Sum_Min_Key_flattened_Max_Avg et all

### ISSUE THREAD

**Issue by ryanbrandenburg** [aspnet/EntityFrameworkCore#12589]
This test [fails](http://aspnetci/viewLog.html?buildId=498349&buildTypeId=XPlat_HighSierraOsxUniverse) with the following error:
```
System.ArgumentOutOfRangeException : Length cannot be less than zero.
Parameter name: length
   at System.String.Substring(Int32 startIndex, Int32 length)
   at Microsoft.CSharp.RuntimeBinder.Syntax.NameTable.Add(String key, Int32 length)
   at Microsoft.CSharp.RuntimeBinder.Syntax.NameManager.Add(String key, Int32 length)
   at Microsoft.CSharp.RuntimeBinder.SymbolTable.GetName(Type type)
   at Microsoft.CSharp.RuntimeBinder.SymbolTable.LoadSymbolsFromType(Type originalType)
   at Microsoft.CSharp.RuntimeBinder.RuntimeBinder.GetArgumentType(ICSharpBinder p, CSharpArgumentInfo argInfo, Expression param, DynamicMetaObject arg, Int32 index)
   at Microsoft.CSharp.RuntimeBinder.RuntimeBinder.CreateArgumentArray(ICSharpBinder payload, Expression[] parameters, DynamicMetaObject[] args)
   at Microsoft.CSharp.RuntimeBinder.RuntimeBinder.BindCore(ICSharpBinder payload, Expression[] parameters, DynamicMetaObject[] args, DynamicMetaObject& deferredBinding)
   at Microsoft.CSharp.RuntimeBinder.RuntimeBinder.Bind(DynamicMetaObjectBinder payload, Expression[] parameters, DynamicMetaObject[] args, DynamicMetaObject& deferredBinding)
   at Microsoft.CSharp.RuntimeBinder.BinderHelper.Bind(DynamicMetaObjectBinder action, RuntimeBinder binder, DynamicMetaObject[] args, IEnumerable`1 arginfos, DynamicMetaObject onBindingError)
   at Microsoft.CSharp.RuntimeBinder.CSharpGetMemberBinder.FallbackGetMember(DynamicMetaObject target, DynamicMetaObject errorSuggestion)
   at System.Dynamic.DynamicMetaObject.BindGetMember(GetMemberBinder binder)
   at System.Dynamic.GetMemberBinder.Bind(DynamicMetaObject target, DynamicMetaObject[] args)
   at System.Dynamic.DynamicMetaObjectBinder.Bind(Object[] args, ReadOnlyCollection`1 parameters, LabelTarget returnLabel)
   at System.Runtime.CompilerServices.CallSiteBinder.BindCore[T](CallSite`1 site, Object[] args)
   at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
   at Microsoft.EntityFrameworkCore.Query.GroupByQueryTestBase`1.<>c.<GroupBy_Composite_Select_Dto_Sum_Min_Key_flattened_Max_Avg>b__45_1(Object e) in /_/src/EFCore.Specification.Tests/Query/GroupByQueryTestBase.cs:line 751
   at System.Linq.EnumerableSorter`2.ComputeKeys(TElement[] elements, Int32 count)
   at System.Linq.EnumerableSorter`1.ComputeMap(TElement[] elements, Int32 count)
   at System.Linq.EnumerableSorter`1.Sort(TElement[] elements, Int32 count)
   at System.Linq.OrderedEnumerable`1.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Microsoft.EntityFrameworkCore.TestUtilities.TestHelpers.AssertResults[T](IList`1 expected, IList`1 actual, Func`2 elementSorter, Action`2 elementAsserter, Boolean verifyOrdered) in /_/src/EFCore.Specification.Tests/TestUtilities/TestHelpers.cs:line 278
   at Microsoft.EntityFrameworkCore.TestUtilities.QueryAsserter`1.<AssertQuery>d__11`1.MoveNext() in /_/src/EFCore.Specification.Tests/TestUtilities/QueryAsserter.cs:line 334
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

CC @ajcvickers.

**Comment by smitpatel** [comment]
Issue in corefx. Filed https://github.com/dotnet/corefx/issues/30955

**Comment by divega** [comment]
@maumar please check that this doesn't happen anymore.

**Comment by yyjdelete** [comment]
@maumar Maybe the same as dotnet/corefx#21689(aspnet/EntityFrameworkCore#8962), since it's fixed in netcoreapp`2.0.3`, but efcore2.1 still use `2.0.0` for test
https://github.com/aspnet/EntityFrameworkCore/blob/7a4539d4080163cce39f658248e7649d9b12d8a8/build/dependencies.props#L17

**Comment by smitpatel** [comment]
@yyjdelete - Possible. Though EF Core uses 2.0.0 only on release/2.1 branch. Other branches (release/2.2 & master) are using 2.0.9.

@natemcmaster - Is 2.0.0 version in release/2.1 is some magic of auto-roll-forward or just oversight?

**Comment by natemcmaster** [comment]
Looks like oversight. Universe builds with and runs tests on 2.0.7. I'm assuming something in the automation didn't run on EF Core to update it's local copy of deps.props

**Comment by ajcvickers** [comment]
Re-triage, based on comments here: https://github.com/dotnet/corefx/issues/30955
