### ISSUE TITLE
Query throws ArgumentNullException

### ISSUE THREAD

**Issue by carlreinke** [aspnet/EntityFrameworkCore#12603]
Query execution throws an exception.

```
System.ArgumentNullException: Value cannot be null.
Parameter name: source
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Boolean& found)
   at lambda_method(Closure , QueryContext , Parent )
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.ProjectionShaper.TypedProjectionShaper`3.Shape(QueryContext queryContext, ValueBuffer& valueBuffer)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.BufferlessMoveNext(DbContext _, Boolean buffer)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
   at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Test.Program.Main() in C:\Users\User\Documents\Visual Studio 2017\Projects\Test\Test\Program.cs:line 35
```

### Steps to reproduce
```c#
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;

namespace Test
{
    class Program
    {
        static void Main()
        {
            var connection = new Microsoft.Data.Sqlite.SqliteConnection("Data Source=:memory:");
            connection.Open();

            var options = new DbContextOptionsBuilder<TestContext>()
                .UseSqlite(connection)
                .Options;

            using (var dbContext = new TestContext(options))
            {
                dbContext.Database.EnsureCreated();

                var parent = new Parent();
                dbContext.Parents.Add(parent);
                dbContext.SaveChanges();
            }

            using (var dbContext = new TestContext(options))
            {
                var query = dbContext.Parents
                    .Select(p => new { Parent = p })
                    .Take(25)
                    .Select(e => e.Parent.Children.FirstOrDefault());

                var result = query.ToArray();
            }
        }
    }

    internal class TestContext : DbContext
    {
        public TestContext(DbContextOptions options)
            : base(options)
        {
        }

        public DbSet<Parent> Parents { get; set; }

        public DbSet<Child> Children { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Child>()
                .HasOne(c => c.Parent)
                .WithMany(p => p.Children)
                .HasForeignKey(c => c.ParentId);
        }
    }

    internal class Parent
    {
        [Key]
        public int ParentId { get; set; }

        public List<Child> Children { get; set; }
    }

    internal class Child
    {
        [Key]
        public int ChildId { get; set; }

        public int ParentId { get; set; }
        public Parent Parent { get; set; }
    }
}
```

### Further technical details
EF Core version: 2.1.1
Database Provider: Microsoft.EntityFrameworkCore.Sqlite (also reproduces with InMemory)
Operating system: Windows 10
IDE: Visual Studio 2017 15.7.4

**Comment by smitpatel** [comment]
Is there a reason you are using anonymous type in between?
```C#
var query = dbContext.Parents
                    .Take(25)
                    .Select(e => e.Children.FirstOrDefault());
```
Will give you desired results.

**Comment by carlreinke** [comment]
It's a `Join` in my actual code. I reduced it to a `Select` for a smaller test case.

**Comment by TrieBr** [comment]
I had this same problem when using `e.Regions.FirstOrDefault().Region.Organization.Name` in my projection. 

Replacing it with the following did the trick:

`e.Regions.Select(i=>i.Region.Organization.Name).FirstOrDefault()`

**Comment by maumar** [comment]
blocked by #15611

**Comment by smitpatel** [comment]
Dependent on #10001

**Comment by smitpatel** [comment]
Latest exception message
```
 Message: 
    System.InvalidOperationException : Processing of the LINQ expression 'AsQueryable<Weapon>(NavigationTreeExpression
        Value: new { Gear = EntityReferenceGear }
        Expression: (Unhandled parameter: e).Gear.Weapons)' by 'NavigationExpandingExpressionVisitor' failed. This may indicate either a bug or a limitation in EF Core. See https://go.microsoft.com/fwlink/?linkid=2101433 for more detailed information.
 ```

**Comment by smitpatel** [comment]
And exception message on 3.1
```C#
Unhandled exception. System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Boolean& found)
   at lambda_method(Closure , QueryContext , DbDataReader , ResultContext , Int32[] , ResultCoordinator )
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.MoveNext()
   at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at EFSampleApp.Program.Main(String[] args) in D:\code\EFSampleApp\EFSampleApp\Program.cs:line 37
   at EFSampleApp.Program.<Main>(String[] args)
```
We have finished a full circle and back to step one. Error seems to be from the fact that Children.FirstOrDefault is getting client evaluated rather than server side.
