### ISSUE TITLE
Type checking fails for GroupJoin with DefaultIfEmpty followed by SelectMany

### ISSUE THREAD

**Issue by carlreinke** [aspnet/EntityFrameworkCore#12606]
Attempting to model a [left join](https://stackoverflow.com/a/3792904/959866), but type checking fails.

```
System.ArgumentException: Expression of type 'System.Collections.Generic.IEnumerable`1[Test.Child]' cannot be used for return type 'System.Collections.Generic.IEnumerable`1[<>f__AnonymousType1`2[Test.Parent,Test.Child]]'
   at System.Linq.Expressions.Expression.ValidateLambdaArgs(Type delegateType, Expression& body, ReadOnlyCollection`1 parameters, String paramName)
   at System.Linq.Expressions.Expression.Lambda[TDelegate](Expression body, String name, Boolean tailCall, IEnumerable`1 parameters)
   at System.Linq.Expressions.Expression.Lambda[TDelegate](Expression body, Boolean tailCall, IEnumerable`1 parameters)
   at System.Linq.Expressions.Expression.Lambda[TDelegate](Expression body, ParameterExpression[] parameters)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.CreateExecutorLambda[TResults]()
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.CreateQueryExecutor[TResult](QueryModel queryModel)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](Expression query, IQueryModelGenerator queryModelGenerator, IDatabase database, IDiagnosticsLogger`1 logger, Type contextType)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass13_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQueryCore[TFunc](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Remotion.Linq.QueryableBase`1.GetEnumerator()
   at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Test.Program.Main() in C:\Users\User\Documents\Visual Studio 2017\Projects\Test\Test\Program.cs:line 38
```

### Steps to reproduce
```c#
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;

namespace Test
{
    class Program
    {
        static void Main()
        {
            var connection = new Microsoft.Data.Sqlite.SqliteConnection("Data Source=:memory:");
            connection.Open();

            var options = new DbContextOptionsBuilder<TestContext>()
                .UseSqlite(connection)
                .Options;

            using (var dbContext = new TestContext(options))
            {
                dbContext.Database.EnsureCreated();
            }

            using (var dbContext = new TestContext(options))
            {
                var query = dbContext.Parents
                    .GroupJoin(dbContext.Children, p => p.ParentId, c => c.ParentId, (p, c) => new
                    {
                        Parent = p,
                        Children = c.DefaultIfEmpty(),
                    })
                    .SelectMany(e => e.Children.Select(c => new
                    {
                        e.Parent,
                        Child = c,
                    }));

                var result = query.ToArray();
            }
        }
    }

    internal class TestContext : DbContext
    {
        public TestContext(DbContextOptions options)
            : base(options)
        {
        }

        public DbSet<Parent> Parents { get; set; }

        public DbSet<Child> Children { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Child>()
                .HasOne(c => c.Parent)
                .WithMany(p => p.Children)
                .HasForeignKey(c => c.ParentId);
        }
    }

    internal class Parent
    {
        [Key]
        public int ParentId { get; set; }

        public List<Child> Children { get; set; }
    }

    internal class Child
    {
        [Key]
        public int ChildId { get; set; }

        public int ParentId { get; set; }
        public Parent Parent { get; set; }
    }
}
```

### Further technical details
EF Core version: 2.1.1
Database Provider: Microsoft.EntityFrameworkCore.Sqlite
Operating system: Windows 10
IDE: Visual Studio 2017 15.7.4

**Comment by maumar** [comment]
@carlreinke you can try the following:

```cs
var query = (from p in dbContext.Parents
			 join c in dbContext.Children on p.ParentId equals c.ParentId into grouping
			 from c in grouping.DefaultIfEmpty()
			 select new { Parent = p, Child = c }).ToArray();
```

which looks like this using method syntax:

```cs
var query = dbContext.Parents
	.GroupJoin(
		dbContext.Children,
		o => o.ParentId,
		i => i.ParentId,
		(p, grouping) => new { p, grouping })
	.SelectMany(
		e => e.grouping.DefaultIfEmpty(),
		(e, c) => new { Parent = e.p, Child = c })
	.ToArray();
```

**Comment by maumar** [comment]
Pattern from the repro yields the following query plan:

```
IEnumerable<Child> _InterceptExceptions(
|__ source: IEnumerable<Child> _ShapedQuery(
|   |__ queryContext: Unhandled parameter: queryContext, 
|   |__ shaperCommandContext: SelectExpression: 
|   |       SELECT [p].[ParentId], [c].[ChildId], [c].[ParentId]
|   |       FROM [Parents] AS [p]
|   |       LEFT JOIN [Children] AS [c] ON [p].[ParentId] = [c].[ParentId], 
|   |__ shaper: BufferedOffsetEntityShaper<Child>), 
|__ contextType: Repro12606.MyContext, 
|__ logger: DiagnosticsLogger<Query>, 
|__ queryContext: Unhandled parameter: queryContext)
```

whereas the supported pattern produces:

```
results: IEnumerable<<>f__AnonymousType1<Parent, Child>> _ShapedQuery(
|   |   |__ queryContext: queryContext, 
|   |   |__ shaperCommandContext: SelectExpression: 
|   |   |       SELECT [p].[ParentId], [c].[ChildId], [c].[ParentId]
|   |   |       FROM [Parents] AS [p]
|   |   |       LEFT JOIN [Children] AS [c] ON [p].[ParentId] = [c].[ParentId], 
|   |   |__ shaper: TypedProjectionShaper<TypedCompositeShaper<BufferedOffsetEntityShaper<Parent>, Parent, BufferedOffsetEntityShaper<Child>, Child, TransparentIdentifier<Parent, Child>>, TransparentIdentifier<Parent, Child>, <>f__AnonymousType1<Parent, Child>>)
```

We should try to fix this, since a number of people will try it from SO

**Comment by carlreinke** [comment]
@maumar Yes, that overload of `SelectMany` does work.

**Comment by smitpatel** [comment]
We still don't support this pattern.

**Comment by smitpatel** [comment]
Converting to enhancement. The supported left join pattern in 3.1 is documented here https://docs.microsoft.com/en-us/ef/core/querying/complex-query-operators#left-join
