### ISSUE TITLE
ModelBuildering: [Owned] attribute with multiple owned navigations and inheritance in owner hits infinite recursion

### ISSUE THREAD

**Issue by kysel** [aspnet/EntityFrameworkCore#12628]
Hi,
EF Core is not able to create migration for model below. I've already found some workarounds (e.g. rename DbSet properties) but I'am not able to find the real cause.

```
PM> add-migration Initial

System.InvalidOperationException: The convention invocations have reached the recursion limit. This is likely an issue in EF Core, please report it.
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ConventionBatch.Run()
   at Microsoft.EntityFrameworkCore.Metadata.Internal.InternalModelBuilder.Entity(TypeIdentity& type, ConfigurationSource configurationSource, Boolean throwOnQuery)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.InternalModelBuilder.Entity(Type type, ConfigurationSource configurationSource, Boolean throwOnQuery)
   at Microsoft.EntityFrameworkCore.ModelBuilder.Entity(Type type)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelCustomizer.FindSets(ModelBuilder modelBuilder, DbContext context)
   at Microsoft.EntityFrameworkCore.Infrastructure.RelationalModelCustomizer.FindSets(ModelBuilder modelBuilder, DbContext context)
   at Microsoft.EntityFrameworkCore.Infrastructure.RelationalModelCustomizer.Customize(ModelBuilder modelBuilder, DbContext context)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.CreateModel(DbContext context, IConventionSetBuilder conventionSetBuilder, IModelValidator validator)
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.Internal.InternalAccessorExtensions.GetService[TService](IInfrastructure`1 accessor)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(Func`1 factory)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(String contextType)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.AddMigration(String name, String outputDir, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigrationImpl(String name, String outputDir, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
The convention invocations have reached the recursion limit. This is likely an issue in EF Core, please report it.
```

### Steps to reproduce
1. Paste context and entities to a new project
1. Try `PM> Add-Migration`

```c#
public class Ctx : DbContext
{
    //Workaround no. 1 rename dbSets 
    public DbSet<Abs> Abses { get; set; }
    public DbSet<AbsDer1> AbsDer1s { get; set; }
    public DbSet<AbsDer2> AbsDer2s { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder) 
        => optionsBuilder.UseNpgsql("fooBar");
}

[Owned]
public class Owned1
{}
[Owned]
public class Owned2
{}

public abstract class Abs
{
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int Id { get; internal set; }

    public Owned1 Owned1 { get; set; }
    //Workaround no. 2 remove second owned property
    public Owned2 Owned2 { get; set; }
}

public class AbsDer1 : Abs
{}
public class AbsDer2 : Abs
{}
```

### Further technical details
EF Core version: 2.1.1 (issue also reproduced in newest 2.1.2-rtm-30894)
Database Provider: Npgsql.EntityFrameworkCore.PostgreSQL 2.1.1
Operating system: Windows 10 Pro 1803
IDE: Visual Studio 2017 15.8.0 Preview 3.0

**Comment by AndriySvyryd** [comment]
As a workaround you can configure the owned types using fluent API instead of data annotations.
