### ISSUE TITLE
2.1.3: test failures in query

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/EntityFrameworkCore#12664]
The latest candidate build of 2.1.3 has 11 test failures in EF Core that look like regressions. Here are just two samples.

http://aspnetci/viewLog.html?buildId=503918&tab=buildResultsDiv&buildTypeId=Lite_EntityFramework
```
AsyncGroupByQueryInMemoryTest.GroupBy_Composite_Select_Dto_Sum_Min_Key_flattened_Max_Avg 

System.ArgumentOutOfRangeException : Length cannot be less than zero.
Parameter name: length
   at System.String.Substring(Int32 startIndex, Int32 length)
   at Microsoft.CSharp.RuntimeBinder.Syntax.NameTable.Add(String key, Int32 length)
   at Microsoft.CSharp.RuntimeBinder.Syntax.NameManager.Add(String key, Int32 length)
   at Microsoft.CSharp.RuntimeBinder.SymbolTable.GetName(Type type)
   at Microsoft.CSharp.RuntimeBinder.SymbolTable.LoadSymbolsFromType(Type originalType)
   at Microsoft.CSharp.RuntimeBinder.RuntimeBinder.GetArgumentType(ICSharpBinder p, CSharpArgumentInfo argInfo, Expression param, DynamicMetaObject arg, Int32 index)
   at Microsoft.CSharp.RuntimeBinder.RuntimeBinder.CreateArgumentArray(ICSharpBinder payload, Expression[] parameters, DynamicMetaObject[] args)
   at Microsoft.CSharp.RuntimeBinder.RuntimeBinder.BindCore(ICSharpBinder payload, Expression[] parameters, DynamicMetaObject[] args, DynamicMetaObject& deferredBinding)
   at Microsoft.CSharp.RuntimeBinder.RuntimeBinder.Bind(DynamicMetaObjectBinder payload, Expression[] parameters, DynamicMetaObject[] args, DynamicMetaObject& deferredBinding)
   at Microsoft.CSharp.RuntimeBinder.BinderHelper.Bind(DynamicMetaObjectBinder action, RuntimeBinder binder, DynamicMetaObject[] args, IEnumerable`1 arginfos, DynamicMetaObject onBindingError)
   at Microsoft.CSharp.RuntimeBinder.CSharpGetMemberBinder.FallbackGetMember(DynamicMetaObject target, DynamicMetaObject errorSuggestion)
   at System.Dynamic.DynamicMetaObject.BindGetMember(GetMemberBinder binder)
   at System.Dynamic.GetMemberBinder.Bind(DynamicMetaObject target, DynamicMetaObject[] args)
   at System.Dynamic.DynamicMetaObjectBinder.Bind(Object[] args, ReadOnlyCollection`1 parameters, LabelTarget returnLabel)
   at System.Runtime.CompilerServices.CallSiteBinder.BindCore[T](CallSite`1 site, Object[] args)
   at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
   at Microsoft.EntityFrameworkCore.Query.AsyncGroupByQueryTestBase`1.<>c.<GroupBy_Composite_Select_Dto_Sum_Min_Key_flattened_Max_Avg>b__44_1(Object e) in /_/src/EFCore.Specification.Tests/Query/AsyncGroupByQueryTestBase.cs:line 530
   at System.Linq.EnumerableSorter`2.ComputeKeys(TElement[] elements, Int32 count)
   at System.Linq.EnumerableSorter`1.ComputeMap(TElement[] elements, Int32 count)
   at System.Linq.EnumerableSorter`1.Sort(TElement[] elements, Int32 count)
   at System.Linq.OrderedEnumerable`1.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Microsoft.EntityFrameworkCore.TestUtilities.TestHelpers.AssertResults[T](IList`1 expected, IList`1 actual, Func`2 elementSorter, Action`2 elementAsserter, Boolean verifyOrdered) in /_/src/EFCore.Specification.Tests/TestUtilities/TestHelpers.cs:line 277
   at Microsoft.EntityFrameworkCore.TestUtilities.QueryAsserter`1.<AssertQuery>d__18`1.MoveNext() in /_/src/EFCore.Specification.Tests/TestUtilities/QueryAsserter.cs:line 360
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.Query.AsyncGroupByQueryTestBase`1.<GroupBy_Composite_Select_Dto_Sum_Min_Key_flattened_Max_Avg>d__44.MoveNext() in /_/src/EFCore.Specification.Tests/Query/AsyncGroupByQueryTestBase.cs:line 518
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

http://aspnetci/viewLog.html?buildId=504267&tab=buildResultsDiv&buildTypeId=Releases_21Public_OsxUniverse
```
GraphUpdatesSqliteTest+SnapshotNotifications.Can_add_valid_first_depedent_when_multiple_possible_principal_sides(quirk: False) 

System.InvalidOperationException : The foreign key '{QuestTaskId: 1}' set on 'TaskChoice' with the key value '{Id: 1}' matches an entity of type 'QuizTask', however the principal entity type should be assignable to 'HiddenAreaTask'.
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.NavigationFixer.InitialFixup(InternalEntityEntry entry, ISet`1 handledForeignKeys, Boolean fromQuery) in /_/src/EFCore/ChangeTracking/Internal/NavigationFixer.cs:line 550
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.NavigationFixer.TrackedFromQuery(InternalEntityEntry entry, ISet`1 handledForeignKeys) in /_/src/EFCore/ChangeTracking/Internal/NavigationFixer.cs:line 442
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntryNotifier.TrackedFromQuery(InternalEntityEntry entry, ISet`1 handledForeignKeys) in /_/src/EFCore/ChangeTracking/Internal/InternalEntityEntryNotifier.cs:line 114
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.StartTrackingFromQuery(IEntityType baseEntityType, Object entity, ValueBuffer& valueBuffer, ISet`1 handledForeignKeys) in /_/src/EFCore/ChangeTracking/Internal/StateManager.cs:line 309
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryBuffer.StartTracking(Object entity, IEntityType entityType) in /_/src/EFCore/Query/Internal/QueryBuffer.cs:line 148
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryBuffer.IncludeCollection[TEntity,TRelated,TElement](Int32 includeId, INavigation navigation, INavigation inverseNavigation, IEntityType targetEntityType, IClrCollectionAccessor clrCollectionAccessor, IClrPropertySetter inverseClrPropertySetter, Boolean tracking, TEntity entity, Func`1 relatedEntitiesFactory, Func`3 joinPredicate) in /_/src/EFCore/Query/Internal/QueryBuffer.cs:line 243
   at lambda_method(Closure , QueryContext , QuizTask , Object[] )
   at Microsoft.EntityFrameworkCore.Query.Internal.IncludeCompiler._Include[TEntity](QueryContext queryContext, TEntity entity, Object[] included, Action`3 fixup) in /_/src/EFCore/Query/Internal/IncludeCompiler.cs:line 334
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source)
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ResultEnumerable`1.GetEnumerator() in /_/src/EFCore/Query/Internal/LinqOperatorProvider.cs:line 294
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.<_TrackEntities>d__17`2.MoveNext() in /_/src/EFCore/Query/Internal/LinqOperatorProvider.cs:line 185
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext() in /_/src/EFCore/Query/Internal/LinqOperatorProvider.cs:line 149
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Boolean& found)
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass15_1`1.<CompileQueryCore>b__0(QueryContext qc) in /_/src/EFCore/Query/Internal/QueryCompiler.cs:line 138
   at System.Linq.Queryable.Single[TSource](IQueryable`1 source)
   at Microsoft.EntityFrameworkCore.GraphUpdatesTestBase`1.<>c__DisplayClass164_0.<Can_add_valid_first_depedent_when_multiple_possible_principal_sides>b__1(DbContext context) in /_/src/EFCore.Specification.Tests/GraphUpdatesTestBase.cs:line 5776
   at Microsoft.EntityFrameworkCore.TestUtilities.TestHelpers.<>c__DisplayClass35_0`1.<ExecuteWithStrategyInTransaction>b__0(TContext context) in /_/src/EFCore.Specification.Tests/TestUtilities/TestHelpers.cs:line 395
   at Microsoft.EntityFrameworkCore.ExecutionStrategyExtensions.<>c__2`1.<Execute>b__2_0(<>f__AnonymousType0`2 s) in /_/src/EFCore/Extensions/ExecutionStrategyExtensions.cs:line 74
   at Microsoft.EntityFrameworkCore.ExecutionStrategyExtensions.Execute[TState](IExecutionStrategy strategy, TState state, Action`1 operation) in /_/src/EFCore/Extensions/ExecutionStrategyExtensions.cs:line 76
   at Microsoft.EntityFrameworkCore.TestUtilities.TestHelpers.ExecuteWithStrategyInTransaction[TContext](Func`1 createContext, Action`2 useTransaction, Action`1 testOperation, Action`1 nestedTestOperation1, Action`1 nestedTestOperation2, Action`1 nestedTestOperation3)
   at Microsoft.EntityFrameworkCore.GraphUpdatesTestBase`1.ExecuteWithStrategyInTransaction(Action`1 testOperation, Action`1 nestedTestOperation1, Action`1 nestedTestOperation2, Action`1 nestedTestOperation3) in /_/src/EFCore.Specification.Tests/GraphUpdatesFixtureBase.cs:line 2639
   at Microsoft.EntityFrameworkCore.GraphUpdatesTestBase`1.Can_add_valid_first_depedent_when_multiple_possible_principal_sides(Boolean quirk) in /_/src/EFCore.Specification.Tests/GraphUpdatesTestBase.cs:line 5749
```

cc @AndriySvyryd

**Comment by maumar** [comment]
first issue is tracked here: https://github.com/dotnet/corefx/issues/30955 I've been trying to isolate the issue, but it's been tricky so far.

**Comment by AndriySvyryd** [comment]
I'm investigating the second issue.
