### ISSUE TITLE
Operations that change non-concurrent collections must have exclusive access

### ISSUE THREAD

**Issue by Ro3A** [aspnet/EntityFrameworkCore#12713]
I ran into the exact same issue as the one mentioned on the IdentityServer github:

https://github.com/IdentityServer/IdentityServer4/issues/2453

This occured when I switched from .net core 2.1.1 to 2.1.2. As soon as I reverted back, the issue went away. I'm not using IdentityServer so this must be a .net core issue specific to 2.1.2. I didn't see an open issue over here yet so figured I'd create one. 

`InvalidOperationException: Operations that change non-concurrent collections must have exclusive access. A concurrent update was performed on this collection and corrupted its state. The collection's state is no longer correct.
System.Collections.Generic.Dictionary<TKey, TValue>.FindEntry(TKey key)
System.Collections.Generic.Dictionary<TKey, TValue>.TryGetValue(TKey key, out TValue value)
Microsoft.EntityFrameworkCore.Metadata.Internal.Model.GetDisplayName(Type type)
Microsoft.EntityFrameworkCore.Metadata.Internal.Model.FindEntityType(Type type)
Microsoft.EntityFrameworkCore.ModelExtensions.FindEntityType(IModel model, Type type)
Microsoft.EntityFrameworkCore.Query.Internal.IncludeCompiler+IncludeLoadTreeNodeBase.Compile(QueryCompilationContext queryCompilationContext, QueryModel queryModel, bool trackingQuery, bool asyncQuery, ref int collectionIncludeId, QuerySourceReferenceExpression targetQuerySourceReferenceExpression)
Microsoft.EntityFrameworkCore.Query.Internal.IncludeCompiler+IncludeLoadTreeNode.CompileCollectionInclude(QueryCompilationContext queryCompilationContext, Expression targetExpression, Expression entityParameter, bool trackingQuery, bool asyncQuery, ref int collectionIncludeId)
Microsoft.EntityFrameworkCore.Query.Internal.IncludeCompiler+IncludeLoadTreeNodeBase.Compile(QueryCompilationContext queryCompilationContext, QueryModel queryModel, bool trackingQuery, bool asyncQuery, ref int collectionIncludeId, QuerySourceReferenceExpression targetQuerySourceReferenceExpression)
Microsoft.EntityFrameworkCore.Query.Internal.IncludeCompiler+IncludeLoadTree.Compile(QueryCompilationContext queryCompilationContext, QueryModel queryModel, bool trackingQuery, bool asyncQuery, ref int collectionIncludeId)
Microsoft.EntityFrameworkCore.Query.Internal.IncludeCompiler.CompileIncludes(QueryModel queryModel, bool trackingQuery, bool asyncQuery)
Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.OptimizeQueryModel(QueryModel queryModel, bool asyncQuery)
Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor.OptimizeQueryModel(QueryModel queryModel, bool asyncQuery)
Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.CreateAsyncQueryExecutor(QueryModel queryModel)
Microsoft.EntityFrameworkCore.Storage.Database.CompileAsyncQuery(QueryModel queryModel)
Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileAsyncQueryCore(Expression query, IQueryModelGenerator queryModelGenerator, IDatabase database)
Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler+<>c__DisplayClass22_0.b__0()
Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQueryCore(object cacheKey, Func<Func<QueryContext, TFunc>> compiler)
Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddAsyncQuery(object cacheKey, Func<Func<QueryContext, IAsyncEnumerable>> compiler)
Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileAsyncQuery(Expression query)
Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteAsync(Expression query)
Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.ExecuteAsync(Expression expression)
Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable.System.Collections.Generic.IAsyncEnumerable.GetEnumerator()
System.Linq.AsyncEnumerable.Aggregate_<TSource, TAccumulate, TResult>(IAsyncEnumerable source, TAccumulate seed, Func<TAccumulate, TSource, TAccumulate> accumulator, Func<TAccumulate, TResult> resultSelector, CancellationToken cancellationToken)`

Here's the offending code, in my case:

var result = await _someDbContext.SomeTable
.Where(x => x.Active.HasValue && x.Active.Value == true)
.Select(x => new SomeModel
{
Name = x.Name,
Id = x.Id
}).ToListAsync();

**Comment by benaadams** [comment]
This is an intentional exception that is being thrown by the Dictionary in newer .NET Core https://github.com/dotnet/corefx/issues/28123 which indicates the dictionary is being incorrectly modified concurrently by multiple threads (it wouldn't have been detected previously and could lead to infinite loops)

**Comment by benaadams** [comment]
It would suggest that 
```csharp
Microsoft.EntityFrameworkCore.Metadata.Internal.Model.GetDisplayName(Type type)
```
can be called by multiple threads on the same instance; one would fail on `TryGetValue` and add a new item to the Dictionary while another was calling `TryGetValue`; which would lead to this issue.

Either it should be a `ConcurrentDictionary` or a `lock` used around the access+add

**Comment by fschlaef** [comment]
I have the exact same exception occurring at random despite not using Dictionary at all.

```
System.InvalidOperationException: Operations that change non-concurrent collections must have exclusive access. A concurrent update was performed on this collection and corrupted its state. The collection's state is no longer correct.
   at System.Collections.Generic.Dictionary`2.FindEntry(TKey key)
   at System.Collections.Generic.Dictionary`2.TryGetValue(TKey key, TValue& value)
   at Remotion.Linq.Parsing.Structure.NodeTypeProviders.MethodInfoBasedNodeTypeRegistry.GetNodeType(MethodInfo method)
   at Remotion.Linq.Parsing.Structure.NodeTypeProviders.MethodInfoBasedNodeTypeRegistry.IsRegistered(MethodInfo method)
   at Remotion.Linq.Parsing.Structure.NodeTypeProviders.CompoundNodeTypeProvider.<>c__DisplayClass4_0.<IsRegistered>b__0(INodeTypeProvider p)
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at Remotion.Linq.Parsing.Structure.NodeTypeProviders.CompoundNodeTypeProvider.IsRegistered(MethodInfo method)
   at Remotion.Linq.Parsing.Structure.ExpressionTreeParser.GetQueryOperatorExpression(Expression expression)
   at Remotion.Linq.Parsing.ExpressionVisitors.SubQueryFindingExpressionVisitor.Visit(Expression expression)
   at System.Linq.Expressions.ExpressionVisitor.VisitLambda[T](Expression`1 node)
   at System.Linq.Expressions.Expression`1.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Remotion.Linq.Parsing.ExpressionVisitors.SubQueryFindingExpressionVisitor.Visit(Expression expression)
   at Remotion.Linq.Parsing.ExpressionVisitors.SubQueryFindingExpressionVisitor.Process(Expression expressionTree, INodeTypeProvider nodeTypeProvider)
   at Remotion.Linq.Parsing.Structure.MethodCallExpressionParser.ProcessArgumentExpression(Expression argumentExpression)
   at System.Linq.Enumerable.SelectListPartitionIterator`2.ToArray()
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Remotion.Linq.Parsing.Structure.MethodCallExpressionParser.Parse(String associatedIdentifier, IExpressionNode source, IEnumerable`1 arguments, MethodCallExpression expressionToParse)
   at Remotion.Linq.Parsing.Structure.ExpressionTreeParser.ParseMethodCallExpression(MethodCallExpression methodCallExpression, String associatedIdentifier)
   at Remotion.Linq.Parsing.Structure.ExpressionTreeParser.ParseNode(Expression expression, String associatedIdentifier)
   at Remotion.Linq.Parsing.Structure.ExpressionTreeParser.ParseMethodCallExpression(MethodCallExpression methodCallExpression, String associatedIdentifier)
   at Remotion.Linq.Parsing.Structure.ExpressionTreeParser.ParseTree(Expression expressionTree)
   at Remotion.Linq.Parsing.Structure.QueryParser.GetParsedQuery(Expression expressionTreeRoot)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryModelGenerator.ParseQuery(Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](Expression query, IQueryModelGenerator queryModelGenerator, IDatabase database, IDiagnosticsLogger`1 logger, Type contextType)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass13_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQueryCore[TFunc](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
   at Remotion.Linq.QueryableBase`1.GetEnumerator()
   at System.Collections.Generic.List`1.AddEnumerable(IEnumerable`1 enumerable)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at MyProject.Controllers.Parameters.CurrencyController.GetList() in C:\projects\MyProject\src\MyProject\Controllers\Parameters\CurrencyController.cs:line 223
   at MyProject.Controllers.Parameters.ParameterController.GetParameters() in C:\projects\MyProject\src\MyProject\Controllers\Parameters\ParameterController.cs:line 168
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.SyncActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at MyProject.Startup.<>c.<<Configure>b__6_1>d.MoveNext() in C:\projects\MyProject\src\MyProject\Startup.cs:line 179
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```
Relevant functions :

CurrencyController.GetList() :
```csharp
public List<dynamic> GetList()
        {
            return _context.Currency
                .Where(a => a.Enabled)
                .Select(c => new
                {
                    c.Id,
                    c.Designation,
                    c.Enabled,
                    c.Code,
                    Name = $"{c.Code} - {c.Designation}"
                }).ToList<dynamic>();
        }
```

ParameterController.GetParameters() :
```csharp
[HttpGet]
public IActionResult GetParameters()
{
	List<dynamic> result = new List<dynamic>();

	// Currency
	string currency = _currencyController.GetType();
	if(moduleAccessLevels[currency])
	{
		result.Add(GetParameterObject(currency, _currencyController.GetList()));
	}
	
	// We do this with a bunch of other controllers
	
	return _responseService.Success(result);
}

private dynamic GetParameterObject(string moduleName, List<dynamic> data)
{
	return new
	{
		ParameterName = moduleName,
		List = data
	};
}
```

Additional information :

- The exception is completely random. Sometimes we don't see it for days, then it throws three times in a row
- It _seems_ that it only throws on Windows 10. I have never seen it on a Windows 7 machine, but take this with a huge pinch of salt as this exception is random
- I cannot be 100% sure, but I think I've seen the same exception since 2.1.0
- Sometimes it throws on really simple code, like ```_context.Something.Where().Select().ToList()``` which is strange

Hope you can make something out of this.

**Comment by benaadams** [comment]
@fschlaef that stack trace looks to be a different issue this time in [re-motion Relinq](https://github.com/re-motion/Relinq)?

It suggests `NodeTypeProviders.Register` is being called concurrently with `NodeTypeProviders.GetNodeType` which causes and issue as the Dictionary is neither a `ConcurrentDictionary` nor used under `lock`

I'd suggest raising an issue in their issue tracker? https://www.re-motion.org/jira/secure/Dashboard.jspa

**Comment by benaadams** [comment]
Ah EF uses `Remotion.Linq`; they might want to raise an issue in their issue tracker then :)

**Comment by benaadams** [comment]
@fschlaef that stack trace looks to be a different issue this time in [re-motion Relinq](https://github.com/re-motion/Relinq)?

It suggests `NodeTypeProviders.Register` is being called concurrently with `NodeTypeProviders.GetNodeType` which causes and issue as the Dictionary is neither a `ConcurrentDictionary` nor used under `lock`

Which is called via `Microsoft.EntityFrameworkCore.Query.Internal.QueryModelGenerator.ParseQuery`

**Comment by benaadams** [comment]
Added an issue to corefx so its easier to find in search https://github.com/dotnet/corefx/issues/31186

**Comment by smitpatel** [comment]
@fschlaef - Your issue looks similar to #12682

**Comment by fschlaef** [comment]
@smitpatel You are right, as @benaadams thought this is a different issue. I moved my comment there to avoid pollution.

**Comment by benaadams** [comment]
> this is not something I need to change in my code

@Ro3A no; this looks like an EF issue

**Comment by divega** [comment]
Once we have the fix we will consider whether we need to include it in a patch.

**Comment by AndriySvyryd** [comment]
Justification: This is a regression without a good workaround (other than just using one thread)
Risk: Low, fix just replaces the dictionary implementation, no functional changes are made

**Comment by ajcvickers** [comment]
#### Description 

A non-thread safe dictionary can be accessed from multiple threads when using an EF model.

#### Customer Impact 

2.1: Occasional exceptions due to this corefx change: https://github.com/dotnet/corefx/issues/28123
Pre 2.0: Presumably even rarer failures due to the unsafe access, but nothing ever reported.

#### Regression? 

 Technically, no. Effectively, yes, since 2.1 apps are now more likely to fail than 2.0 apps.

#### Risk 

Very low; use ConcurrentDictionary instead,.

**Comment by vivmishra** [comment]
Approved for 2.1.4

**Comment by ajcvickers** [comment]
@natemcmaster @ryanbrandenburg Are we okay to start checking things in to a release branch for 2.1.4, or should we hold off for a while?

**Comment by natemcmaster** [comment]
Once https://github.com/aspnet/EntityFrameworkCore/pull/12888 is in, go for it.

**Comment by tomchovanec** [comment]
Is there any temporary workround? Restarting AppPool whenever whis exception occures is not a good solution, I have this exception on every query execution. (Microsoft.EntityFrameworkCore 2.1.1)

**Comment by patriksvensson** [comment]
@natemcmaster Been hitting this as well lately. When is 2.1.3 with the fix expected to be released?

**Comment by natemcmaster** [comment]
@patriksvensson next week.

**Comment by tomchovanec** [comment]
@natemcmaster Thank you, nightly build could help temporary. I was looking for some ungly hack because it's not possible to compile sources or add them to the solution that contains 60+ projects while many other developers works on it.

**Comment by johnnyoshika** [comment]
I ran into this problem as well (which required an AppPool restart to fix). To get around this problem, I'd like to upgrade EF Core. The NuGet package I'm loading is referenced like this:

```
<PackageReference Include="Microsoft.AspNetCore.App" />
```

According to this page https://docs.microsoft.com/en-us/aspnet/core/migration/20_21?view=aspnetcore-2.1, version attribute is no longer recommended. Excerpt:

> Remove the "Version" attribute on the package reference to Microsoft.AspNetCore.App. Projects which use <Project Sdk="Microsoft.NET.Sdk.Web"> do not need to set the version. The version will be implied by the target framework and selected to best match the way ASP.NET Core 2.1 works. (See below for more information.)

A couple of questions:
* How do I know which version of EF Core it's loading?
* How do I upgrade the EF Core version if I'm loading `Microsoft.AspNetCore.App`?

Thanks in advance!

**Comment by roji** [comment]
@stefankip your problem isn't really related to this issue: performing concurrent operations on a DbContext - as you're doing with AsParallel - isn't supported (and there isn't much to be gained from doing so). You'll need to do a simple, non-parallel foreach. See #18148 for a similar discussion on this.

**Comment by stefankip** [comment]
Yeah I already change it to foreach, but the forall was performing **a lot** faster, because the `someItems` collection is a `List`.
I thought the call to `DbContext.Add()` was a simple `Add()`, it's not performing the underlying SQL calls yet right?

**Comment by roji** [comment]
That's right - in almost all cases, Add doesn't do any database traffic. The exception is if you have value generation such as HiLo which contacts the database (in which case you once again cannot parallelize, since a context uses only a single database connection).

**Comment by stefankip** [comment]
So if I'm only doing stuff in-memory at this point, why can't I use parallelization? Using ForAll performs much better on large lists than foreach.

**Comment by roji** [comment]
Operations being in-memory only doesn't mean they're thread-safe: .NET Dictionary itself is in-memory only, and does not allow concurrent updates, since doing so safely would hurt performance for everyone not needing that. The discussion in #18148 has some more details.
