### ISSUE TITLE
Missing ExpressionType.Default in ExpressionComparer.Compare

### ISSUE THREAD

**Issue by jirinalepa** [aspnet/EntityFrameworkCore#12771]
ExpressionEqualityComparer computes hash for DefaultExpression but doesn't implement the comparison which leads to an NotImplementedException when fetching query from cache.

```
Exception message: The method or operation is not implemented.
Stack trace:
System.NotImplementedException
The method or operation is not implemented.
   at Microsoft.EntityFrameworkCore.Query.Internal.ExpressionEqualityComparer.ExpressionComparer.Compare(Expression a, Expression b)
   at Microsoft.EntityFrameworkCore.Query.Internal.ExpressionEqualityComparer.ExpressionComparer.CompareBinary(BinaryExpression a, BinaryExpression b)
   at Microsoft.EntityFrameworkCore.Query.Internal.ExpressionEqualityComparer.ExpressionComparer.Compare(Expression a, Expression b)
   at Microsoft.EntityFrameworkCore.Query.Internal.ExpressionEqualityComparer.ExpressionComparer.CompareLambda(LambdaExpression a, LambdaExpression b)
   at Microsoft.EntityFrameworkCore.Query.Internal.ExpressionEqualityComparer.ExpressionComparer.Compare(Expression a, Expression b)
   at Microsoft.EntityFrameworkCore.Query.Internal.ExpressionEqualityComparer.ExpressionComparer.CompareUnary(UnaryExpression a, UnaryExpression b)
   at Microsoft.EntityFrameworkCore.Query.Internal.ExpressionEqualityComparer.ExpressionComparer.Compare(Expression a, Expression b)
   at Microsoft.EntityFrameworkCore.Query.Internal.ExpressionEqualityComparer.ExpressionComparer.CompareExpressionList(IReadOnlyList`1 a, IReadOnlyList`1 b)
   at Microsoft.EntityFrameworkCore.Query.Internal.ExpressionEqualityComparer.ExpressionComparer.CompareMethodCall(MethodCallExpression a, MethodCallExpression b)
   at Microsoft.EntityFrameworkCore.Query.Internal.ExpressionEqualityComparer.ExpressionComparer.Compare(Expression a, Expression b)
   at Microsoft.EntityFrameworkCore.Query.Internal.ExpressionEqualityComparer.ExpressionComparer.CompareExpressionList(IReadOnlyList`1 a, IReadOnlyList`1 b)
   at Microsoft.EntityFrameworkCore.Query.Internal.ExpressionEqualityComparer.ExpressionComparer.CompareMethodCall(MethodCallExpression a, MethodCallExpression b)
   at Microsoft.EntityFrameworkCore.Query.Internal.ExpressionEqualityComparer.ExpressionComparer.Compare(Expression a, Expression b)
   at Microsoft.EntityFrameworkCore.Query.Internal.ExpressionEqualityComparer.Equals(Expression x, Expression y)
   at Microsoft.EntityFrameworkCore.Query.CompiledQueryCacheKeyGenerator.CompiledQueryCacheKey.Equals(Object obj)
   at Microsoft.EntityFrameworkCore.Query.RelationalCompiledQueryCacheKeyGenerator.RelationalCompiledQueryCacheKey.Equals(RelationalCompiledQueryCacheKey other)
   at Microsoft.EntityFrameworkCore.Query.RelationalCompiledQueryCacheKeyGenerator.RelationalCompiledQueryCacheKey.Equals(Object obj)
   at System.Collections.Generic.ObjectEqualityComparer`1.Equals(T x, T y)
   at System.Collections.Concurrent.ConcurrentDictionary`2.TryGetValue(TKey key, TValue& value)
   at Microsoft.Extensions.Caching.Memory.MemoryCache.TryGetValue(Object key, Object& result)
   at Microsoft.Extensions.Caching.Memory.CacheExtensions.TryGetValue[TItem](IMemoryCache cache, Object key, TItem& value)
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQueryCore[TFunc](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
```

### Further technical details
EF Core version: 2.0.3
Database Provider: Npgsql.EntityFrameworkCore.PostgreSQL
Operating system: Windows 10
IDE: Visual Studio 2017 15.4

**Comment by smitpatel** [comment]
@jirinalepa - Can you also post the linq query you are running?

**Comment by jirinalepa** [comment]
Almost identical older issue #7559

Expression similar to this:
```
var parameter = Expression.Parameter(typeof(Employee));
var defaultExpression =
    Expression.Lambda<Func<Employee, bool>>(
        Expression.NotEqual(
            Expression.Property(
                parameter,
                "ReportsTo"),
            Expression.Default(typeof(uint?))),
        parameter);
```

**Comment by maumar** [comment]
This only happens when expression is constructed using the low level API, otherwise it will get funcletized into constant

**Comment by maumar** [comment]
@ilmax release/2.2 - we will merge it into master afterwards

**Comment by ilmax** [comment]
@maumar I can create a pr for 2.2.tomorrow morning CET time

**Comment by smitpatel** [comment]
@ilmax - we can just cherry-pick the commit from master. Do you need it to be in 2.2 release?

**Comment by ilmax** [comment]
@smitpatel nope, it was because of @maumar [comment](https://github.com/aspnet/EntityFrameworkCore/issues/12771#issuecomment-429052463) if it's not required, I'm fine with it in the next version (3.0?)

**Comment by austindrenski** [comment]
Can this still be considered for 2.2? I'm running into this issue in production and working around it is proving complicated.

**Comment by ajcvickers** [comment]
@smitpatel to move it to 2.2

**Comment by smitpatel** [comment]
@austindrenski - We have added this to 2.2 release.

**Comment by austindrenski** [comment]
Thanks! Much appreciated!
