### ISSUE TITLE
Query: incorrect query plan for query with join, order on inner sequence and inner key selector being property accessed thru navigation

### ISSUE THREAD

**Issue by maumar** [aspnet/EntityFrameworkCore#12804]
query:

```cs
                var query = from e2 in ctx.LevelTwo
                            join e1 in ctx.LevelOne.OrderBy(ll => ll.Id) on e2.Name equals e1.OneToOne_Optional_FK1.Name
                            select new
                            {
                                Id2 = e2.Id,
                                Name2 = e2.Name,
                                Id1 = e1.Id,
                                Name1 = e1.Name
                            };

                var result = query.ToList();
```

query plan:

```
(QueryContext queryContext) => IEnumerable<<>f__AnonymousType38<int, string, int, string>> _InterceptExceptions(
|__ source: IEnumerable<<>f__AnonymousType38<int, string, int, string>> _Select(
|   |__ source: IEnumerable<TransparentIdentifier<ValueBuffer, ValueBuffer>> _Join(
|   |   |__ outer: IEnumerable<ValueBuffer> _ShapedQuery(
|   |   |   |__ queryContext: queryContext, 
|   |   |   |__ shaperCommandContext: SelectExpression: 
|   |   |   |       SELECT [e2].[Name] AS [Name2], [e2].[Id] AS [Id2]
|   |   |   |       FROM [LevelTwo] AS [e2], 
|   |   |   |__ shaper: ValueBufferShaper), 
|   |   |__ inner: IEnumerable<ValueBuffer> _ShapedQuery(
|   |   |   |__ queryContext: queryContext, 
|   |   |   |__ shaperCommandContext: SelectExpression: 
|   |   |   |       SELECT [ll0].[Id]
|   |   |   |       FROM [LevelOne] AS [ll0]
|   |   |   |       ORDER BY [ll0].[Id], 
|   |   |   |__ shaper: ValueBufferShaper), 
|   |   |__ outerKeySelector: (ValueBuffer e2) => string TryReadValue(e2, 0, Level2.Name), 
|   |   |__ innerKeySelector: (ValueBuffer e1) => string FirstOrDefault(IEnumerable<string> _Select(
|   |   |   |__ source: IEnumerable<ValueBuffer> _Where(
|   |   |   |   |__ source: IEnumerable<ValueBuffer> _ShapedQuery(
|   |   |   |   |   |__ queryContext: queryContext, 
|   |   |   |   |   |__ shaperCommandContext: SelectExpression: 
|   |   |   |   |   |       SELECT [subQuery].[Id], [subQuery].[Level1_Optional_Id], [subQuery].[Name]
|   |   |   |   |   |       FROM [LevelTwo] AS [subQuery], 
|   |   |   |   |   |__ shaper: ValueBufferShaper), 
|   |   |   |   |__ predicate: (ValueBuffer subQuery) =>  ?= Nullable<int> TryReadValue(subQuery, 1, Level2.Level1_Optional_Id) == (Nullable<int>)int TryReadValue(e1, 0, Level1.Id) =? ), 
|   |   |   |__ selector: (ValueBuffer subQuery) => string TryReadValue(subQuery, 2, Level2.Name))), 
|   |   |__ resultSelector: (ValueBuffer e2 | ValueBuffer e1) => TransparentIdentifier<ValueBuffer, ValueBuffer> CreateTransparentIdentifier(
|   |       |__ outer: e2, 
|   |       |__ inner: e1)), 
|   |__ selector: (TransparentIdentifier<ValueBuffer, ValueBuffer> t0) => new { 
|           int TryReadValue(t0.Outer, 1, Level2.Id), 
|           string TryReadValue(t0.Outer, 0, Level2.Name), 
|           int TryReadValue(t0.Inner, 0, Level1.Id), 
|           string TryReadValue(t0.Inner, 2, Level1.Name)
|        }), 
|__ contextType: TestModels.ComplexNavigationsModel.ComplexNavigationsContext, 
|__ logger: DiagnosticsLogger<Query>, 
|__ queryContext: queryContext)
```

exception:

```
Index was outside the bounds of the array.
	at Microsoft.EntityFrameworkCore.Storage.ValueBuffer.get_Item(Int32 index)
	at Microsoft.EntityFrameworkCore.Metadata.Internal.EntityMaterializerSource.TryReadValue[TValue](ValueBuffer& valueBuffer, Int32 index, IPropertyBase property)
	at lambda_method(Closure , TransparentIdentifier`2 )
	at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
	at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
	at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
	at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
```

**Comment by maumar** [comment]
this issue is fixed in current bits
