### ISSUE TITLE
Flaky test: Update_on_bytes_concurrency_token_original_value_matches_does_not_throw

### ISSUE THREAD

**Issue by ryanbrandenburg** [aspnet/EntityFrameworkCore#12859]
This test [fails](http://aspnetci/viewLog.html?buildId=521043&buildTypeId=Releases_21Public_UbuntuUniverse) occasionally with the following error:
```
Microsoft.EntityFrameworkCore.DbUpdateConcurrencyException : Conflicts were detected for instance of entity type 'ProductWithBytes' on the concurrency token properties {'Bytes'}. Consider using 'DbContextOptionsBuilder.EnableSensitiveDataLogging' to see the conflicting values.
   at Microsoft.EntityFrameworkCore.InMemory.Storage.Internal.InMemoryTable`1.ThrowUpdateConcurrencyException(IUpdateEntry entry, Dictionary`2 concurrencyConflicts) in /_/src/EFCore.InMemory/Storage/Internal/InMemoryTable.cs:line 179
   at Microsoft.EntityFrameworkCore.InMemory.Storage.Internal.InMemoryTable`1.Update(IUpdateEntry entry) in /_/src/EFCore.InMemory/Storage/Internal/InMemoryTable.cs:line 144
   at Microsoft.EntityFrameworkCore.InMemory.Storage.Internal.InMemoryStore.ExecuteTransaction(IReadOnlyList`1 entries, IDiagnosticsLogger`1 updateLogger) in /_/src/EFCore.InMemory/Storage/Internal/InMemoryStore.cs:line 178
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IReadOnlyList`1 entriesToSave) in /_/src/EFCore/ChangeTracking/Internal/StateManager.cs:line 921
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess) in /_/src/EFCore/ChangeTracking/Internal/StateManager.cs:line 790
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess) in /_/src/EFCore/DbContext.cs:line 431
   at Microsoft.EntityFrameworkCore.UpdatesTestBase`1.<>c__DisplayClass8_0.<Update_on_bytes_concurrency_token_original_value_matches_does_not_throw>b__0(UpdatesContext context) in /_/src/EFCore.Specification.Tests/UpdatesTestBase.cs:line 148
   at Microsoft.EntityFrameworkCore.TestUtilities.TestHelpers.<>c__DisplayClass35_0`1.<ExecuteWithStrategyInTransaction>b__0(TContext context) in /_/src/EFCore.Specification.Tests/TestUtilities/TestHelpers.cs:line 385
   at Microsoft.EntityFrameworkCore.ExecutionStrategyExtensions.<>c__2`1.<Execute>b__2_0(<>f__AnonymousType0`2 s) in /_/src/EFCore/Extensions/ExecutionStrategyExtensions.cs:line 74
   at Microsoft.EntityFrameworkCore.ExecutionStrategyExtensions.Execute[TState](IExecutionStrategy strategy, TState state, Action`1 operation) in /_/src/EFCore/Extensions/ExecutionStrategyExtensions.cs:line 76
   at Microsoft.EntityFrameworkCore.TestUtilities.TestHelpers.ExecuteWithStrategyInTransaction[TContext](Func`1 createContext, Action`2 useTransaction, Action`1 testOperation, Action`1 nestedTestOperation1, Action`1 nestedTestOperation2, Action`1 nestedTestOperation3)
   at Microsoft.EntityFrameworkCore.UpdatesTestBase`1.ExecuteWithStrategyInTransaction(Action`1 testOperation, Action`1 nestedTestOperation1) in /_/src/EFCore.Specification.Tests/UpdatesTestBase.cs:line 458
   at Microsoft.EntityFrameworkCore.UpdatesInMemoryTestBase`1.ExecuteWithStrategyInTransaction(Action`1 testOperation, Action`1 nestedTestOperation1) in /_/test/EFCore.InMemory.FunctionalTests/UpdatesInMemoryTestBase.cs:line 106
   at Microsoft.EntityFrameworkCore.UpdatesTestBase`1.Update_on_bytes_concurrency_token_original_value_matches_does_not_throw() in /_/src/EFCore.Specification.Tests/UpdatesTestBase.cs:line 154
```
Other tests within that build may have failed with a similar message, but they are not listed here. Check the link above for more info.

CC @Eilon,@muratg,@mkArtakMSFT

This issue was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
Please use this workflow to address this flaky test issue, including checking applicable checkboxes and filling in the applicable "TODO" entries:

* Is this actually a flaky test?
  * No, this is a regular test failure, fix the test/product (TODO: Link to commit/PR)
  * Yes, proceed below...

* Is this test failure caused by product code flakiness? (Either this product, or another product this test depends on.)
  * [ ] File a bug against the product (TODO: Link to other bug)
  * Is it possible to change the test to avoid the flakiness?
    * Yes? Go to the "Change the test!" section.
    * No?
      * [ ] Disable the test (TODO: Link to PR/commit)
      * [ ] Wait for other bug to be resolved
      * [ ] Wait for us to get build that has the fix
      * [ ] Re-enable our test (TODO: Link to PR/commit)
      * [ ] Close this bug

* Is it that the test itself is flaky? This includes external transient problems (e.g. remote server problems, file system race condition, etc.)
  * Is there is a way to change our test to avoid this flakiness?
    * Yes? Change the test!
      * [ ] Change the test to avoid the flakiness, for example by using a different test strategy, or by adding retries w/ timeouts (TODO: Link to PR/commit)
      * [ ] Run the test 100 times locally as a sanity check.
      * [ ] Close this bug
    * No?
      * [ ] Delete the test because flaky tests are not useful (TODO: Link to PR/commit)

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by Eilon** [comment]
Tagging @ajcvickers
