### ISSUE TITLE
Query: runtime error when projecting a single nullable unsigned int column inside a subquery

### ISSUE THREAD

**Issue by maumar** [aspnet/EntityFrameworkCore#12942]
repro:

```cs

                var query = ctx.Customers.Select(c => c.Orders.OrderBy(o => o.OrderID).Select(o => o.EmployeeID).FirstOrDefault());
                var result = query.ToList();
```

query plan:
```
(QueryContext queryContext) => IEnumerable<Nullable<uint>> _InterceptExceptions(
|__ source: IEnumerable<Nullable<uint>> _ShapedQuery(
|   |__ queryContext: queryContext, 
|   |__ shaperCommandContext: SelectExpression: 
|   |       SELECT (
|   |           SELECT TOP(1) [o].[EmployeeID]
|   |           FROM [Orders] AS [o]
|   |           WHERE [c].[CustomerID] = [o].[CustomerID]
|   |           ORDER BY [o].[OrderID]
|   |       )
|   |       FROM [Customers] AS [c], 
|   |__ shaper: (QueryContext queryContext | ValueBuffer c) => (Nullable<uint>)Nullable<uint> TryReadValue(c, 0, null)), 
|__ contextType: TestModels.Northwind.NorthwindRelationalContext, 
|__ logger: DiagnosticsLogger<Query>, 
|__ queryContext: Unhandled parameter: queryContext)
```

exception:

```
An exception occurred while reading a database value. The expected type was 'System.Nullable`1[System.UInt32]' but the actual value was of type 'System.Int32'.
---- System.InvalidCastException : Specified cast is not valid.
	at Microsoft.EntityFrameworkCore.Storage.TypedRelationalValueBufferFactoryFactory.ThrowReadValueException[TValue](Exception exception, Object value, IPropertyBase property)
	at lambda_method(Closure , DbDataReader )
	at Microsoft.EntityFrameworkCore.Storage.Internal.TypedRelationalValueBufferFactory.Create(DbDataReader dataReader)
	at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.BufferlessMoveNext(DbContext _, Boolean buffer)
	at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
	at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.MoveNext()
	at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
	at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
	at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
```

**Comment by ajcvickers** [comment]
Possibly related to #12570
