### ISSUE TITLE
Bug: ArgumentOutOfRangeException with many Include()s in table splitting scenario

### ISSUE THREAD

**Issue by ChrisBellew** [aspnet/EntityFrameworkCore#13016]
I appear to have found a peculiar bug when trying to SingleOrDefault() an entity from a database.

All the details are below.

```
Exception message: System.ArgumentOutOfRangeException : Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
Stack trace: at Microsoft.EntityFrameworkCore.Query.Expressions.SelectExpression.BindSubqueryProjectionIndex(Int32 projectionIndex, IQuerySource querySource)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.SqlTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.SqlTranslatingExpressionVisitor.Visit(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor.VisitOrderByClause(OrderByClause orderByClause, QueryModel queryModel, Int32 index)
   at Remotion.Linq.QueryModelVisitorBase.VisitBodyClauses(ObservableCollection`1 bodyClauses, QueryModel queryModel)
   at Remotion.Linq.QueryModelVisitorBase.VisitQueryModel(QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.VisitQueryModel(QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor.VisitQueryModel(QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.RelationalEntityQueryableExpressionVisitor.VisitSubQuery(SubQueryExpression expression)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.ExpressionVisitorBase.VisitLambda[T](Expression`1 node)
   at System.Linq.Expressions.Expression`1.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at System.Linq.Expressions.ExpressionVisitor.VisitUnary(UnaryExpression node)
   at System.Linq.Expressions.UnaryExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at System.Dynamic.Utils.ExpressionVisitorUtils.VisitArguments(ExpressionVisitor visitor, IArgumentProvider nodes)
   at System.Linq.Expressions.ExpressionVisitor.VisitMethodCall(MethodCallExpression node)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at System.Dynamic.Utils.ExpressionVisitorUtils.VisitBlockExpressions(ExpressionVisitor visitor, BlockExpression block)
   at System.Linq.Expressions.ExpressionVisitor.VisitBlock(BlockExpression node)
   at System.Linq.Expressions.BlockExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.ExpressionVisitorBase.VisitLambda[T](Expression`1 node)
   at System.Linq.Expressions.Expression`1.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at System.Dynamic.Utils.ExpressionVisitorUtils.VisitArguments(ExpressionVisitor visitor, IArgumentProvider nodes)
   at System.Linq.Expressions.ExpressionVisitor.VisitMethodCall(MethodCallExpression node)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at System.Dynamic.Utils.ExpressionVisitorUtils.VisitArguments(ExpressionVisitor visitor, IArgumentProvider nodes)
   at System.Linq.Expressions.ExpressionVisitor.VisitMethodCall(MethodCallExpression node)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.ReplaceClauseReferences(Expression expression, IQuerySource querySource, Boolean inProjection)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.VisitSelectClause(SelectClause selectClause, QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor.VisitSelectClause(SelectClause selectClause, QueryModel queryModel)
   at Remotion.Linq.QueryModelVisitorBase.VisitQueryModel(QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.VisitQueryModel(QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor.VisitQueryModel(QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.RelationalEntityQueryableExpressionVisitor.VisitSubQuery(SubQueryExpression expression)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.ExpressionVisitorBase.VisitLambda[T](Expression`1 node)
   at System.Linq.Expressions.Expression`1.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at System.Linq.Expressions.ExpressionVisitor.VisitUnary(UnaryExpression node)
   at System.Linq.Expressions.UnaryExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at System.Dynamic.Utils.ExpressionVisitorUtils.VisitArguments(ExpressionVisitor visitor, IArgumentProvider nodes)
   at System.Linq.Expressions.ExpressionVisitor.VisitMethodCall(MethodCallExpression node)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.ExpressionVisitorBase.VisitLambda[T](Expression`1 node)
   at System.Linq.Expressions.Expression`1.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at System.Linq.Expressions.ExpressionVisitor.Visit(ReadOnlyCollection`1 nodes)
   at System.Linq.Expressions.ExpressionVisitor.VisitNewArray(NewArrayExpression node)
   at System.Linq.Expressions.NewArrayExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at System.Dynamic.Utils.ExpressionVisitorUtils.VisitArguments(ExpressionVisitor visitor, IArgumentProvider nodes)
   at System.Linq.Expressions.ExpressionVisitor.VisitMethodCall(MethodCallExpression node)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at System.Dynamic.Utils.ExpressionVisitorUtils.VisitBlockExpressions(ExpressionVisitor visitor, BlockExpression block)
   at System.Linq.Expressions.ExpressionVisitor.VisitBlock(BlockExpression node)
   at System.Linq.Expressions.BlockExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.ExpressionVisitorBase.VisitLambda[T](Expression`1 node)
   at System.Linq.Expressions.Expression`1.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at System.Dynamic.Utils.ExpressionVisitorUtils.VisitArguments(ExpressionVisitor visitor, IArgumentProvider nodes)
   at System.Linq.Expressions.ExpressionVisitor.VisitMethodCall(MethodCallExpression node)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at System.Dynamic.Utils.ExpressionVisitorUtils.VisitArguments(ExpressionVisitor visitor, IArgumentProvider nodes)
   at System.Linq.Expressions.ExpressionVisitor.VisitMethodCall(MethodCallExpression node)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.ReplaceClauseReferences(Expression expression, IQuerySource querySource, Boolean inProjection)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.VisitSelectClause(SelectClause selectClause, QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor.VisitSelectClause(SelectClause selectClause, QueryModel queryModel)
   at Remotion.Linq.QueryModelVisitorBase.VisitQueryModel(QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.VisitQueryModel(QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor.VisitQueryModel(QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.RelationalEntityQueryableExpressionVisitor.VisitSubQuery(SubQueryExpression expression)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.ExpressionVisitorBase.VisitLambda[T](Expression`1 node)
   at System.Linq.Expressions.Expression`1.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at System.Linq.Expressions.ExpressionVisitor.VisitUnary(UnaryExpression node)
   at System.Linq.Expressions.UnaryExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at System.Dynamic.Utils.ExpressionVisitorUtils.VisitArguments(ExpressionVisitor visitor, IArgumentProvider nodes)
   at System.Linq.Expressions.ExpressionVisitor.VisitMethodCall(MethodCallExpression node)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at System.Dynamic.Utils.ExpressionVisitorUtils.VisitBlockExpressions(ExpressionVisitor visitor, BlockExpression block)
   at System.Linq.Expressions.ExpressionVisitor.VisitBlock(BlockExpression node)
   at System.Linq.Expressions.BlockExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.ExpressionVisitorBase.VisitLambda[T](Expression`1 node)
   at System.Linq.Expressions.Expression`1.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at System.Dynamic.Utils.ExpressionVisitorUtils.VisitArguments(ExpressionVisitor visitor, IArgumentProvider nodes)
   at System.Linq.Expressions.ExpressionVisitor.VisitMethodCall(MethodCallExpression node)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at System.Dynamic.Utils.ExpressionVisitorUtils.VisitArguments(ExpressionVisitor visitor, IArgumentProvider nodes)
   at System.Linq.Expressions.ExpressionVisitor.VisitMethodCall(MethodCallExpression node)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.ReplaceClauseReferences(Expression expression, IQuerySource querySource, Boolean inProjection)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.VisitSelectClause(SelectClause selectClause, QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor.VisitSelectClause(SelectClause selectClause, QueryModel queryModel)
   at Remotion.Linq.QueryModelVisitorBase.VisitQueryModel(QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.VisitQueryModel(QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor.VisitQueryModel(QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.CreateAsyncQueryExecutor[TResult](QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQueryCore[TFunc](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteAsync[TResult](Expression query, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.ExecuteAsync[TResult](Expression expression, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ExecuteAsync[TSource,TResult](MethodInfo operatorMethodInfo, IQueryable`1 source, Expression expression, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ExecuteAsync[TSource,TResult](MethodInfo operatorMethodInfo, IQueryable`1 source, LambdaExpression expression, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.SingleOrDefaultAsync[TSource](IQueryable`1 source, Expression`1 predicate, CancellationToken cancellationToken)
   at Spookfish.AI.ModelService.Tests.BugTest.GetModel(BugContext context, Guid guid, Func`2 includer) in C:\Users\Chris\Documents\GitHub\ai-tools\service\test\Spookfish.AI.ModelService.Tests\Spookfish.AI.ModelService.Tests\BugTest.cs:line 36
   at Spookfish.AI.ModelService.Tests.BugTest.GetModelVersion(BugContext context, Guid modelGuid, Guid versionGuid, Func`2 includer) in C:\Users\Chris\Documents\GitHub\ai-tools\service\test\Spookfish.AI.ModelService.Tests\Spookfish.AI.ModelService.Tests\BugTest.cs:line 29
   at Spookfish.AI.ModelService.Tests.BugTest.Run() in C:\Users\Chris\Documents\GitHub\ai-tools\service\test\Spookfish.AI.ModelService.Tests\Spookfish.AI.ModelService.Tests\BugTest.cs:line 24
--- End of stack trace from previous location where exception was thrown ---
```

### Steps to reproduce
Take this code and run it as a unit test. It should be completely self contained. I tried to make it simpler but it seems a fairly nuanced bug (?) and I couldn't delete much without it becoming a heisenbug.

```c#
public class BugTest
    {
        [Fact]
        public async Task Run()
        {
            var connection = new SqliteConnection("DataSource=:memory:");
            connection.Open();
            var options = new DbContextOptionsBuilder<BugContext>().UseSqlite(connection).Options;
            var context = new BugContext(options);
            await context.Database.EnsureCreatedAsync();
            
            await GetModelVersion(context, Guid.Empty, Guid.Empty, model => model.Include(x => x.EntityTwos).ThenInclude(x => x.EntityFours).ThenInclude(x => x.EntitySixes)); 
        }

        private async Task<EntityTwo> GetModelVersion(BugContext context, Guid modelGuid, Guid versionGuid, Func<IQueryable<EntityOne>, IQueryable<EntityOne>> includer)
        {
            var dbModel = await GetModel(context, modelGuid, model => includer(model.Include(x => x.EntityTwos).ThenInclude(x => x.EntityFive).ThenInclude(x => x.EntitySevens)));
            return dbModel.EntityTwos.SingleOrDefault(x => x.Guid == versionGuid);
        }

        private async Task<EntityOne> GetModel(BugContext context, Guid guid, Func<IQueryable<EntityOne>, IQueryable<EntityOne>> includer)
        {
            var query = context.EntityOnes;
            var model = await includer(query).SingleOrDefaultAsync(x => x.Guid == guid);

            return model;
        }
    }

    public class BugContext : DbContext
    {
        public BugContext(DbContextOptions<BugContext> options) : base(options)
        {
            
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<EntityTwo>().HasOne(x => x.EntityFive).WithOne().HasForeignKey<EntityFive>(x => x.TwoGuid);

        }

        public DbSet<EntityOne> EntityOnes { get; set; }

        public DbSet<EntityTwo> EntityTwos { get; set; }
    }

    public class EntityOne
    {
        [Key]
        public Guid Guid { get; set; }

        public List<EntityTwo> EntityTwos { get; set; } = new List<EntityTwo>();

        public List<EntityThree> EntityThrees { get; set; } = new List<EntityThree>();
    }

    public class EntityTwo
    {
        [Key]
        public Guid Guid { get; set; }

        public Guid OneGuid { get; set; }

        public List<EntityFour> EntityFours { get; set; } = new List<EntityFour>();
        
        public EntityFive EntityFive { get; set; } = new EntityFive();
    }

    public class EntityFour
    {
        [Key]
        public Guid Guid { get; set; }

        public Guid TwoGuid { get; set; }

        public List<EntitySix> EntitySixes { get; set; } = new List<EntitySix>();
    }

    public class EntitySix
    {
        [Key]
        public Guid Guid { get; set; }

        public Guid FourGuid { get; set; }
    }

    [Table("EntityTwos")]
    public class EntityFive
    {
        [Key]
        public Guid TwoGuid { get; set; }

        public List<EntitySeven> EntitySevens { get; set; } = new List<EntitySeven>();
    }

    public class EntityThree
    {
        [Key]
        public Guid Guid { get; set; }
        
        public Guid OneGuid { get; set; }

        public List<EntitySeven> EntitySevens { get; set; } = new List<EntitySeven>();
    }

    public class EntitySeven
    {
        [Key]
        public Guid Guid { get; set; }

        public Guid ThreeGuid { get; set; }
    }
```

### Further technical details
Here is the contents of my project.json
```json
<PropertyGroup>
    <TargetFramework>netcoreapp2.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.TestHost" Version="2.1.1" />
    <PackageReference Include="Microsoft.Data.Sqlite" Version="2.1.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="2.1.1" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="15.8.0" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.4.0" />
    <PackageReference Include="xunit" Version="2.4.0" />
    <PackageReference Include="moq" Version="4.9.0" />
    <DotNetCliToolReference Include="dotnet-xunit" Version="2.4.0-beta.1.build3958" />
  </ItemGroup>
```

**Comment by maumar** [comment]
simplified repro:

```cs
    class Program
    {
        static void Main(string[] args)
        {
            using (var ctx = new MyContext())
            {
                ctx.Database.EnsureDeleted();
                ctx.Database.EnsureCreated();
            }

            using (var ctx = new MyContext())
            {
                var query = ctx.EntityOnes
                    .Include(x => x.EntityTwos).ThenInclude(x => x.EntityFours)
                    .Include(x => x.EntityTwos).ThenInclude(x => x.EntityFive).ThenInclude(x => x.EntitySevens)
                    .ToList();

                Console.WriteLine(query);
            }
        }
    }

    public class MyContext : DbContext
    {
        public DbSet<EntityOne> EntityOnes { get; set; }

        public DbSet<EntityTwo> EntityTwos { get; set; }


        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseSqlServer(@"Server=.;Database=Repro13016;Trusted_Connection=True;MultipleActiveResultSets=True");
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<EntityTwo>().HasOne(x => x.EntityFive).WithOne().HasForeignKey<EntityFive>(x => x.TwoGuid);

        }
    }

    public class EntityOne
    {
        [Key]
        public Guid Guid { get; set; }

        public List<EntityTwo> EntityTwos { get; set; } = new List<EntityTwo>();

        public List<EntityThree> EntityThrees { get; set; } = new List<EntityThree>();
    }

    public class EntityTwo
    {
        [Key]
        public Guid Guid { get; set; }

        public Guid OneGuid { get; set; }

        public List<EntityFour> EntityFours { get; set; } = new List<EntityFour>();

        public EntityFive EntityFive { get; set; } = new EntityFive();
    }

    public class EntityFour
    {
        [Key]
        public Guid Guid { get; set; }

        public Guid TwoGuid { get; set; }
    }

    [Table("EntityTwos")]
    public class EntityFive
    {
        [Key]
        public Guid TwoGuid { get; set; }

        public List<EntitySeven> EntitySevens { get; set; } = new List<EntitySeven>();
    }

    public class EntityThree
    {
        [Key]
        public Guid Guid { get; set; }

        public Guid OneGuid { get; set; }

        public List<EntitySeven> EntitySevens { get; set; } = new List<EntitySeven>();
    }

    public class EntitySeven
    {
        [Key]
        public Guid Guid { get; set; }

        public Guid ThreeGuid { get; set; }
    }
```

**Comment by smitpatel** [comment]
The anonymous object added duplicated columns.

**Comment by maumar** [comment]
Include generates the following subquery model to fetch some related entities:

```
from EntitySeven e.EntityFive.EntitySevens in DbSet<EntitySeven>
join AnonymousObject _e.EntityFive in 
    (from EntityTwo x.EntityTwos in DbSet<EntityTwo>
    join EntityFive e.EntityFive in DbSet<EntityFive>
    on Property([x.EntityTwos], "Guid") equals Property([e.EntityFive], "TwoGuid") into e.EntityFive_group
    from EntityFive e.EntityFive in 
        (from EntityFive e.EntityFive_groupItem in [e.EntityFive_group]
        select [e.EntityFive_groupItem]).DefaultIfEmpty()
    join AnonymousObject _x in 
        from EntityOne x in DbSet<EntityOne>
        select new AnonymousObject(new object[]{ (object)EF.Property(?[x]?, "Guid") })
    on Property([x.EntityTwos], "EntityOneGuid") equals (Nullable<Guid>)object [_x].GetValue(0)
    select new AnonymousObject(new object[]
    { 
        (object)EF.Property(?[e.EntityFive]?, "TwoGuid"), 
        object [_x].GetValue(0), 
        (object)EF.Property(?[x.EntityTwos]?, "Guid") 
    })).Distinct()
on Property([e.EntityFive.EntitySevens], "EntityFiveTwoGuid") equals (Nullable<Guid>)object [_e.EntityFive].GetValue(0)
order by object [_e.EntityFive].GetValue(1) asc, object [_e.EntityFive].GetValue(2) asc, object [_e.EntityFive].GetValue(0) asc
select [e.EntityFive.EntitySevens], 
```

Issue is that EntityTwo.Guid and EntityFive.TwoGuid map to the same column in the database. So, when we generate select expression for this query model, we only add the column once to the projection list. This results in inner select only having 2 columns (EntityTwo.Guid and EntityOnes.Guid, but from query model perspective we are expecting 3 projections. The discrepancy leads to the error - trying to access column at index that doesn't exist.

**Comment by smitpatel** [comment]
Working in 3.1
Single query mode fixed it.
Generated SQL
```SQL
      SELECT [e].[Guid], [t0].[Guid], [t0].[EntityOneGuid], [t0].[OneGuid], [t0].[Guid0], [t0].[Guid1], [t0].[EntityTwoGuid], [t0].[TwoGuid], [t0].[Guid2], [t0].[EntityFiveTwoGuid], [t0].[EntityThreeGuid], [t0].[ThreeGuid]
      FROM [EntityOnes] AS [e]
      LEFT JOIN (
          SELECT [e0].[Guid], [e0].[EntityOneGuid], [e0].[OneGuid], [t].[Guid] AS [Guid0], [e3].[Guid] AS [Guid1], [e3].[EntityTwoGuid], [e3].[TwoGuid], [e4].[Guid] AS [Guid2], [e4].[EntityFiveTwoGuid], [e4].[EntityThreeGuid], [e4].[ThreeGuid]
          FROM [EntityTwos] AS [e0]
          LEFT JOIN (
              SELECT [e1].[Guid], [e2].[Guid] AS [Guid0]
              FROM [EntityTwos] AS [e1]
              INNER JOIN [EntityTwos] AS [e2] ON [e1].[Guid] = [e2].[Guid]
          ) AS [t] ON [e0].[Guid] = [t].[Guid]
          LEFT JOIN [EntityFour] AS [e3] ON [e0].[Guid] = [e3].[EntityTwoGuid]
          LEFT JOIN [EntitySeven] AS [e4] ON [t].[Guid] = [e4].[EntityFiveTwoGuid]
      ) AS [t0] ON [e].[Guid] = [t0].[EntityOneGuid]
      ORDER BY [e].[Guid], [t0].[Guid], [t0].[Guid1], [t0].[Guid2]
```
