### ISSUE TITLE
Async query groupby with sum by nullable property throw ArgumentException

### ISSUE THREAD

**Issue by voronov-maxim** [aspnet/EntityFrameworkCore#13094]
```
Exception message:
Expression of type 'System.Collections.Generic.IEnumerable`1[System.Nullable`1[System.Decimal]]' cannot be used for parameter of type 'System.Threading.Tasks.Task`1[System.Decimal]' of method 'System.Threading.Tasks.Task`1[System.Nullable`1[System.Decimal]] CastToNullable[Decimal](System.Threading.Tasks.Task`1[System.Decimal])'
Parameter name: arg0
Stack trace:
  at System.Dynamic.Utils.ExpressionUtils.ValidateOneArgument(MethodBase method, ExpressionType nodeKind, Expression arguments, ParameterInfo pi, String methodParamName, String argumentParamName, Int32 index)
   at System.Linq.Expressions.Expression.Call(MethodInfo method, Expression arg0)
   at Microsoft.EntityFrameworkCore.Query.Internal.RelationalResultOperatorHandler.HandleSum(HandlerContext handlerContext) in E:\vorona\EntityFrameworkCore\src\EFCore.Relational\Query\Internal\RelationalResultOperatorHandler.cs:line 994
```

### Steps to reproduce
```c#
class OrderItem
{
  public int OrderId { get; set; }
  public Decimal? Price { get; set; }
}
dbContext.OrderItems.GroupBy(i => i.OrderId).Select(g => g.Sum(i => i.Price)).ToListAsync().GetAwaiter().GetResult();
```
All worked well with 2.0.

### Further technical details
EF Core version:2.1.2
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: 
Visual Studio 2017 15.8

**Comment by maumar** [comment]
Problem was introduced in https://github.com/aspnet/EntityFrameworkCore/commit/15bc370703ee500c4c7ff1a4a670c97a829b839b which itself was a fix to a regression. 

Basically we apply special conversion call for async queries with nullable SUM arguments, but we were not taking into account scenario where the query was asynchronous but the underlying aggregate that was supposed to be converted was sync.

**Comment by andrew-hickton** [comment]
@maumar is making a synchronous call the only work around you can see for this issue?   It is affecting our ability to migrate to 2.1, so I just want to understand our options.

**Comment by maumar** [comment]
@andrew-hickton it only affects scenarios where the argument that is passed to the Sum is nullable, so if you can change that, it should also unblock the scenario
