### ISSUE TITLE
Indices with conversions defined should perform comparison in db on converted value

### ISSUE THREAD

**Issue by mqudsi** [aspnet/EntityFrameworkCore#13179]
Given a class with an index set up pointing to a value (of any type) that has a conversion defined, the index comparison should be performed on the converted value in the database and should not rely on the availability of `IEquatable<Foo>`. 

I could probably file a separate bug for this, but additionally, if `IEquatable<Foo>` is required and `Foo` is `Nullable<T>` where T: IEquatable<T>`, EF Core should be able to deduce the comparison between the two `Foo` instances.

Attempting to compile and run the code at the end of this PR results in an exception on the call to `db.SaveChanges()` which complains that `The binary operator Equal is not implemented for the types System.Nullable<SocialSecurityNumber> and System.Nullable<SocialSecurityNumber>`

The stack trace is not helpful and is besides the point, but in all cases:

```
Exception thrown: 'Microsoft.Data.Sqlite.SqliteException' in Microsoft.Data.Sqlite.dll
Exception thrown: 'Microsoft.Data.Sqlite.SqliteException' in Microsoft.EntityFrameworkCore.Relational.dll
Exception thrown: 'System.InvalidOperationException' in System.Linq.Expressions.dll
Exception thrown: 'System.Reflection.TargetInvocationException' in System.Private.CoreLib.dll
Exception thrown: 'System.InvalidOperationException' in Microsoft.EntityFrameworkCore.dll
An unhandled exception of type 'System.InvalidOperationException' occurred in Microsoft.EntityFrameworkCore.dll
```

### Further technical details
EF Core version: 2.1.2
Database Provider: Sqlite 2.1.2
Operating system: Windows 10, N/A
IDE: N/A

### Code

```csharp
namespace EFCoreNullTest
{
    public struct SocialSecurityNumber : IEquatable<SocialSecurityNumber>
    {
        public int Number { get; set; }

        public bool Equals(SocialSecurityNumber other)
        {
            return Number == other.Number;
        }
    }

    public class Person
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public SocialSecurityNumber? SSN { get; set; }
    }

    class Database : DbContext
    {
        public Database(DbContextOptions options)
            : base(options)
        { }

        protected override void OnModelCreating(ModelBuilder builder)
        {
            base.OnModelCreating(builder);

            builder.Entity<Person>()
                .Property(p => p.SSN)
                .HasConversion(ssn => ssn.HasValue ? ssn.Value.Number : new int?(),
                i => i.HasValue ? new SocialSecurityNumber { Number = i.Value } : new SocialSecurityNumber?());
            builder.Entity<Person>()
                .HasIndex(p => p.SSN)
                .IsUnique();
        }
    }

    class Program
    {
        static void Main(string[] args)
        {
            var dbOptions = new DbContextOptionsBuilder().UseSqlite("Data Source=test.db");
            var db = new Database(dbOptions.Options);
            db.Database.EnsureCreated();

            db.Add(new Person()
            {
                Name = "John Doe"
            });

            db.SaveChanges();
        }
    }
}
```

**Comment by ajcvickers** [comment]
@mqudsi Can you post the full stack trace?

**Comment by ajcvickers** [comment]
Stack trace:
```
Unhandled Exception: System.InvalidOperationException: The binary operator Equal is not defined for the types 'System.Nullable`1[SocialSecurityNumber]' and 'System.Nullable`1[SocialSecurityNumber]'.
   at Microsoft.EntityFrameworkCore.Metadata.Internal.ClrAccessorFactory`1.Create(PropertyInfo propertyInfo, IPropertyBase propertyBase)
   at Microsoft.EntityFrameworkCore.Internal.NonCapturingLazyInitializer.EnsureInitialized[TParam,TValue](TValue& target, TParam param, Func`2 valueFactory)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.ReadPropertyValue(IPropertyBase propertyBase)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.ChangeDetector.DetectChanges(InternalEntityEntry entry)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.ChangeDetector.DetectChanges(IStateManager stateManager)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Program.Main(String[] args) in C:\Stuff\TwoOneCore\TwoOneCore\Program.cs:line 54
```

**Comment by mqudsi** [comment]
Thanks, @ajcvickers. I didn't notice I had copied the wrong stack trace in my OP.
