### ISSUE TITLE
SqlException when grouping by IS NOT NULL

### ISSUE THREAD

**Issue by stilettk** [aspnet/EntityFrameworkCore#13231]
I have a following query:
```c#
_context.Objects
    .Select(x => new { x.Region, x.Type, HasParent = x.ParentId != null, x.ObjectId })
    .GroupBy(x => new {x.Region, x.Type, x.HasParent}, x => x.ObjectId)
    .Select(g => new
        {
            g.Key.Region,
            g.Key.Type,
            g.Key.HasParent,
            ObjectCount = g.Count()
    });
```
It throws the following exception when executed:
```
Exception message: System.Data.SqlClient.SqlException: 'Incorrect syntax near the keyword 'IS'.'
Stack trace:    
   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__122_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteAsync(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncQueryingEnumerable`1.AsyncEnumerator.BufferlessMoveNext(DbContext _, Boolean buffer, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncQueryingEnumerable`1.AsyncEnumerator.MoveNext(CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext(CancellationToken cancellationToken)
   at System.Linq.AsyncEnumerable.Aggregate_[TSource,TAccumulate,TResult](IAsyncEnumerable`1 source, TAccumulate seed, Func`3 accumulator, Func`2 resultSelector, CancellationToken cancellationToken)
...
```

### Steps to reproduce

Use the query from above with this model:
```c#
public class MyObject 
{
    public int Id { get; set; }
    public ObjectType Type { get; set; }
    public string Region { get; set; }
    public string ParentId { get; set; }
    public string ObjectId { get; set; }
}
```
The following sql is generated:
```sql
SELECT [x].[Region], [x].[Type], CASE
    WHEN [x].[ParentId] IS NOT NULL
    THEN CAST(1 AS BIT) ELSE CAST(0 AS BIT)
END AS [HasParent], COUNT(*) AS [ObjectCount]
FROM [Objects] AS [x]
GROUP BY [x].[Region], [x].[Type], [x].[ParentId] IS NOT NULL
```

### Further technical details
EF Core version: 2.1.2
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10
IDE: Visual Studio 2017 15.8.2

**Comment by smitpatel** [comment]
GroupBy terms needs to be value type. Same as Order By.
As a work around, you should be able to write ternary `HasParent = x.ParentId != null ? true : false`
