### ISSUE TITLE
Add-Migration when a model class has a 2D array property gives a NullReferenceException in the package manager console.

### ISSUE THREAD

**Issue by ajcvickers** [aspnet/EntityFrameworkCore#13240]
From VS Feedback:

Create a model class with a 2D array property, e.g.
```C#
public Tile[,] Tiles { get; set; }
```
Run Add-Migration NewMigration in the package manager console.

Get a null reference exception.

**Comment by ajcvickers** [comment]
```
Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.EntityFrameworkCore.Metadata.Internal.PropertyParameterBindingFactory.GetCandidatePropertyNames(String parameterName)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.PropertyParameterBindingFactory.TryBindParameter(IMutableEntityType entityType, Type parameterType, String parameterName)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.ConstructorBindingFactory.<>c__DisplayClass3_0.<TryBindConstructor>b__0(ParameterInfo p)
   at System.Linq.Enumerable.SelectArrayIterator`2.ToList()
   at Microsoft.EntityFrameworkCore.Metadata.Internal.ConstructorBindingFactory.TryBindConstructor(IMutableEntityType entityType, ConstructorInfo constructor, ConstructorBinding& binding, IEnumerable`1& failedBindings)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConstructorBindingConvention.Apply(InternalModelBuilder modelBuilder)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ImmediateConventionScope.OnModelBuilt(InternalModelBuilder modelBuilder)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.CreateModel(DbContext context, IConventionSetBuilder conventionSetBuilder, IModelValidator validator)
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.Internal.InternalAccessorExtensions.GetService[TService](IInfrastructure`1 accessor)
   at Microsoft.EntityFrameworkCore.Infrastructure.DatabaseFacade.get_DatabaseCreator()
   at Microsoft.EntityFrameworkCore.Infrastructure.DatabaseFacade.EnsureDeleted()
   at Program.Main() in C:\Stuff\TwoOneCore\TwoOneCore\Program.cs:line 65
   at Program.<Main>()
```
