### ISSUE TITLE
Test failure: Applied_to_multiple_body_clauses

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/EntityFrameworkCore#13301]
This test [fails](http://aspnetci/viewLog.html?buildId=552086&buildTypeId=Lite_UniverseTest) occasionally with the following error:
```
System.AggregateException : One or more errors occurred. (Cannot open database "Northwind" requested by the login. The login failed.
Login failed for user 'REDMOND\asplab'.) (The following constructor parameters did not have matching fixture data: NorthwindQuerySqlServerFixture`1 fixture)
---- System.Data.SqlClient.SqlException : Cannot open database "Northwind" requested by the login. The login failed.
Login failed for user 'REDMOND\asplab'.
---- The following constructor parameters did not have matching fixture data: NorthwindQuerySqlServerFixture`1 fixture
----- Inner Stack Trace #1 (System.Data.SqlClient.SqlException) -----
   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, Boolean applyTransientFaultHandling, String accessToken)
   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at Microsoft.EntityFrameworkCore.TestUtilities.SqlServerTestStore.OpenConnection() in /_/test/EFCore.SqlServer.FunctionalTests/TestUtilities/SqlServerTestStore.cs:line 247
   at Microsoft.EntityFrameworkCore.TestUtilities.RelationalTestStore.Initialize(IServiceProvider serviceProvider, Func`1 createContext, Action`1 seed) in /_/src/EFCore.Relational.Specification.Tests/TestUtilities/RelationalTestStore.cs:line 36
   at Microsoft.EntityFrameworkCore.SharedStoreFixtureBase`1..ctor() in /_/src/EFCore.Specification.Tests/SharedStoreFixtureBase.cs:line 56
   at Microsoft.EntityFrameworkCore.Query.NorthwindQueryFixtureBase`1..ctor() in /_/src/EFCore.Specification.Tests/Query/NorthwindQueryFixtureBase.cs:line 18
   at Microsoft.EntityFrameworkCore.Query.NorthwindQueryRelationalFixture`1..ctor()
   at Microsoft.EntityFrameworkCore.Query.NorthwindQuerySqlServerFixture`1..ctor()
----- Inner Stack Trace #2 (Xunit.Sdk.TestClassException) -----
```
Other tests within that build may have failed with a similar message, but they are not listed here. Check the link above for more info.

This test failed on master.

CC @ajcvickers

This issue was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by aspnet-hello** [comment]
Please use this workflow to address this flaky test issue, including checking applicable checkboxes and filling in the applicable "TODO" entries:

* Is this actually a flaky test?
  * No, this is a regular test failure, fix the test/product (TODO: Link to commit/PR)
  * Yes, proceed below...

* Is this test failure caused by product code flakiness? (Either this product, or another product this test depends on.)
  * [ ] File a bug against the product (TODO: Link to other bug)
  * Is it possible to change the test to avoid the flakiness?
    * Yes? Go to the "Change the test!" section.
    * No?
      * [ ] Disable the test (TODO: Link to PR/commit)
      * [ ] Wait for other bug to be resolved
      * [ ] Wait for us to get build that has the fix
      * [ ] Re-enable our test (TODO: Link to PR/commit)
      * [ ] Close this bug

* Is it that the test itself is flaky? This includes external transient problems (e.g. remote server problems, file system race condition, etc.)
  * Is there is a way to change our test to avoid this flakiness?
    * Yes? Change the test!
      * [ ] Change the test to avoid the flakiness, for example by using a different test strategy, or by adding retries w/ timeouts (TODO: Link to PR/commit)
      * [ ] Run the test 100 times locally as a sanity check.
      * [ ] Close this bug
    * No?
      * Is there any logging or extra information that we could add to make this more diagnosable when it happens again?
        * Yes?
            * [ ] Add the logging (TODO: Link to PR/commit)
        * No?
            * [ ] Delete the test because flaky tests are not useful (TODO: Link to PR/commit)

This comment was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by aspnet-hello** [comment]
Applied_to_body_clause_with_projection [failed with about the same error](http://aspnetci/viewLog.html?buildId=552086&buildTypeId=Lite_UniverseTest) on master.

This comment was made automatically. If there is a problem contact ryanbrandenburg.
