### ISSUE TITLE
Adding Same Id to Multiple Entities' Owned Collection Fails

### ISSUE THREAD

**Issue by xKloc** [aspnet/EntityFrameworkCore#13321]
I am trying to add immutable objects to different entities and cannot because their "Id" is the same. It looks like the shadow foreign key for the owned collection isn't being considered.

```
fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
System.Exception: Encountered exception. ---> System.InvalidOperationException: The instance of entity type 'AssociatedKeyword' cannot be tracked because another instance with the same key value for {'Id'} is already being tracked. When replacing owned entities modify the properties without changing the instance or detach the previous owned entity entry first. Consider using 'DbContextOptionsBuilder.EnableSensitiveDataLogging' to see the conflicting key values.
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.IdentityMap`1.ThrowIdentityConflict(InternalEntityEntry entry)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.IdentityMap`1.Add(TKey key, InternalEntityEntry entry, Boolean updateDuplicate)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.StartTracking(InternalEntityEntry entry)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.SetEntityState(EntityState oldState, EntityState newState, Boolean acceptChanges)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityGraphAttacher.PaintAction(EntityEntryGraphNode node, Boolean force)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityEntryGraphIterator.TraverseGraph[TState](EntityEntryGraphNode node, TState state, Func`3 handleNode)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.NavigationFixer.NavigationCollectionChanged(InternalEntityEntry entry, INavigation navigation, IEnumerable`1 added, IEnumerable`1 removed)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntryNotifier.NavigationCollectionChanged(InternalEntityEntry entry, INavigation navigation, IEnumerable`1 added, IEnumerable`1 removed)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.ChangeDetector.DetectNavigationChange(InternalEntityEntry entry, INavigation navigation)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.ChangeDetector.DetectChanges(InternalEntityEntry entry)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.ChangeDetector.DetectChanges(IStateManager stateManager)
   at Microsoft.EntityFrameworkCore.ChangeTracking.ChangeTracker.Entries[TEntity]()
   at Kloc.Common.Data.EntityFrameworkCore.UnitOfWorkBase.CommitAsync() in C:\Users\admin\Source\Repos\Kloc.Common\Data.EntityFrameworkCore\UnitOfWorkBase.cs:line 35
   at Kloc.Crashtags.Core.Service.Commands.Handlers.AssociateKeywordsCommandHandler.HandleAsync(AssociateKeywordsCommand command) in C:\Users\admin\Source\Repos\Kloc.Crashtags\Core.Service\Commands\Handlers\AssociateKeywordsCommandHandler.cs:line 39
   at Kloc.Common.Domain.Cqrs.CommandDispatcher.SendAsync[TCommand](TCommand command) in C:\Users\admin\Source\Repos\Kloc.Common\Domain.Cqrs\CommandDispatcher.cs:line 26
   --- End of inner exception stack trace ---
   at Kloc.Common.Excepting.DefaultExceptionHandler.HandleAsync(Exception exception, Object[] args) in C:\Users\admin\Source\Repos\Kloc.Common\Excepting\DefaultExceptionHandler.cs:line 10
   at Kloc.Common.Domain.Cqrs.CommandDispatcher.SendAsync[TCommand](TCommand command) in C:\Users\admin\Source\Repos\Kloc.Common\Domain.Cqrs\CommandDispatcher.cs:line 30
   at Kloc.Crashtags.Core.Service.CoreController.AssociateKeywords(String[] keywords) in C:\Users\admin\Source\Repos\Kloc.Crashtags\Core.Service\CoreController.cs:line 40
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

### Steps to reproduce
```c#
    public class Keyword : AggregateRootBase<string>
    {
        private readonly HashSet<AssociatedKeyword> _associatedKeywords = new HashSet<AssociatedKeyword>();

        public Keyword(string id) : base(id)
        {
            Guard.ForNullOrWhitespace(id, nameof(id));
        }

        public IReadOnlyCollection<AssociatedKeyword> AssociatedKeywords => _associatedKeywords;

        public void AssociateKeyword(string id)
        {
            var tag = _associatedKeywords.SingleOrDefault(e => e.Id == id);

            if (tag is null)
            {
                tag = new AssociatedKeyword(id);
                _associatedKeywords.Add(tag);
            }
            else
            {
                tag.IncrementAssociationsCount();
            }
        }
    }

    public class AssociatedKeyword : EntityBase
    {
        internal AssociatedKeyword(string id)
        {
            Guard.ForNullOrWhitespace(id, nameof(id));

            Id = id;
            AssociationsCount = 1;
        }

        public string Id { get; private set; }
        public int AssociationsCount { get; private set; }

        protected override IEnumerable<object> GetIdentity()
        {
            yield return Id;
        }

        internal void IncrementAssociationsCount()
        {
            AssociationsCount++;
        }
    }

    public class KeywordConfiguration : IEntityTypeConfiguration<Keyword>
    {
        public void Configure(EntityTypeBuilder<Keyword> builder)
        {
            builder.HasKey(e => e.Id);
            builder.OwnsMany(e => e.AssociatedKeywords);
        }
    }

    public class AssociateKeywordsCommandHandler : ICommandHandler<AssociateKeywordsCommand>
    {
        private readonly ICoreUnitOfWork _coreUow;
        private readonly ILogger _logger;

        public AssociateKeywordsCommandHandler(ICoreUnitOfWork coreUow, ILogger<AssociateKeywordsCommandHandler> logger)
        {
            _coreUow = coreUow ?? throw new ArgumentNullException(nameof(coreUow));
            _logger = logger ?? throw new ArgumentNullException(nameof(logger));
        }

        public async Task HandleAsync(AssociateKeywordsCommand command)
        {
            foreach (var keyword in command.Keywords)
            {
                var storedKeyword = await _coreUow.KeywordRepository.GetByIdAsync(keyword);

                if (storedKeyword == null)
                {
                    storedKeyword = new Keyword(keyword);
                    _coreUow.KeywordRepository.Add(storedKeyword);
                }

                foreach (var word in command.Keywords.Where(e => e != keyword))
                {
                    storedKeyword.AssociateKeyword(word);
                }
                _logger.LogInformation("Keyword: {0}, Associated Keywords: {1}", storedKeyword.Id, string.Join(", ", storedKeyword.AssociatedKeywords));
            }
            // commit calls SaveChanges();
            await _coreUow.CommitAsync();
        }
    }
```

### Further technical details
EF Core version: 2.2 preview 2
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10
IDE: Visual Studio 2017 15.9.0 Preview 2

**Comment by xKloc** [comment]
Current Workaround is to define the key manually.

```C#
    public class KeywordConfiguration : IEntityTypeConfiguration<Keyword>
    {
        public void Configure(EntityTypeBuilder<Keyword> builder)
        {
            builder.HasKey(e => e.Id);
            builder.OwnsMany(e => e.AssociatedKeywords, oc => oc.HasKey("Id", "KeywordId"));
        }
    }
```

**Comment by AndriySvyryd** [comment]
In 2.2 we won't configure PK by convention in collection owned types to avoid giving the impression that this scenario would just work.
But afterwards we'll work on a better experience, tracked in https://github.com/aspnet/EntityFrameworkCore/issues/1985
