### ISSUE TITLE
The annotation 'SqlServer:Include' was not found. Ensure that the annotation has been added

### ISSUE THREAD

**Issue by per3ian** [aspnet/EntityFrameworkCore#13417]
I am going to make a null field in database,
I changed long? to long

this is my field : 
        `public long Size { get; set; }`

and this is my configuration :
```
            b.Property(x => x.Size)
                .IsRequired();
```

and table is empty

and when I want to update database I got this error :

`The annotation 'SqlServer:Include' was not found. Ensure that the annotation has been added.`

### Further technical details
EF Core version: 2.2
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10
IDE: Visual Studio 2017 15.8.2

**Comment by ajcvickers** [comment]
@per3ian Please post a runnable project/solution or complete code listing that demonstrates the behavior you are seeing.

**Comment by gabrielRibeiroCamargoFerreira** [comment]
I do not know if it helps.
I had the same problem, but in my case I was changing the IdentityDbContext, I ended up having to remove all the migrations and generate the initial again, which I saw was that in the creation of the project in the Migrations folder XXX.Designer. cs, ProductVersion was on preview1  and the new migrations were as preview2

**Comment by smitpatel** [comment]
This annotation is about include filter on an index. Changing nullability of a column would change filter defined on index associated with such column.

**Comment by cculver** [comment]
I just received this as well. On 2.2.0-preview2-35157.
In OnModelCreating, I am calling the following:
`modelBuilder.Entity<Company>().HasIndex(t => t.EIN).IsUnique(true).ForSqlServerInclude("LegalName", "Website", "AddressId", "AlternateNames", "ReturnType");`
I subsequently increased the length of the LegalName field and am now receiving the same error as reported above.
In the initial migration, I see the entity has
`b.HasIndex("EIN").IsUnique().HasAnnotation("SqlServer:Include", new[] { "LegalName", "Website", "AddressId", "AlternateNames", "ReturnType" });`
This appears in the field length increase migration file as well, so I'm not sure why it's reporting that SqlServer:Include was not found. Not sure what else I can provide that might be helpful. 

I have since removed all (2) migrations and recreated the database with a newly created migration. The issue has not reappeared.

**Comment by ajcvickers** [comment]
@per3ian @gabrielRibeiroCamargoFerreira @olaeld @cculver What is the full stack trace of the exception?

**Comment by joshmouch** [comment]
I just started getting this exception, too.  I did a search in my solution for "SqlServer:Include", and there are 0 matches.

The stack trace is:

```
	
0
	
{"assembly":"Microsoft.EntityFrameworkCore, Version=2.2.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60","method":"Microsoft.EntityFrameworkCore.Infrastructure.AnnotatableExtensions.GetAnnotation","level":0,"line":0}
	
1
	
{"assembly":"Microsoft.EntityFrameworkCore.SqlServer, Version=2.2.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60","method":"Microsoft.EntityFrameworkCore.Migrations.SqlServerMigrationsSqlGenerator+<GetIndexesToRebuild>d__48.MoveNext","level":1,"line":0}
	
2
	
{"assembly":"mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089","method":"System.Collections.Generic.List`1..ctor","level":2,"line":0}
	
3
	
{"assembly":"System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089","method":"System.Linq.Enumerable.ToList","level":3,"line":0}
	
4
	
{"assembly":"Microsoft.EntityFrameworkCore.SqlServer, Version=2.2.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60","method":"Microsoft.EntityFrameworkCore.Migrations.SqlServerMigrationsSqlGenerator.Generate","level":4,"line":0}
	
5
	
{"assembly":"Microsoft.EntityFrameworkCore.Relational, Version=2.2.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60","method":"Microsoft.EntityFrameworkCore.Migrations.MigrationsSqlGenerator.Generate","level":5,"line":0}
	
6
	
{"assembly":"Microsoft.EntityFrameworkCore.Relational, Version=2.2.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60","method":"Microsoft.EntityFrameworkCore.Migrations.MigrationsSqlGenerator.Generate","level":6,"line":0}
	
7
	
{"assembly":"Microsoft.EntityFrameworkCore.SqlServer, Version=2.2.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60","method":"Microsoft.EntityFrameworkCore.Migrations.SqlServerMigrationsSqlGenerator.Generate","level":7,"line":0}
	
8
	
{"assembly":"Microsoft.EntityFrameworkCore.Relational, Version=2.2.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60","method":"Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.GenerateUpSql","level":8,"line":0}
	
9
	
{"assembly":"Microsoft.EntityFrameworkCore.Relational, Version=2.2.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60","method":"Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate","level":9,"line":0}
	
10
	
...
	
11
	
{"assembly":"mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089","method":"System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw","level":11,"line":0}
	
12
	
{"assembly":"Microsoft.AspNetCore.Hosting, Version=2.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60","method":"Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure","level":12,"line":0}
	
13
	
{"assembly":"Microsoft.AspNetCore.Hosting, Version=2.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60","method":"Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication","level":13,"line":0}


```

**Comment by joshmouch** [comment]
Here's a better stack trace:

```

Application startup exception: System.InvalidOperationException: The annotation 'SqlServer:Include' was not found. Ensure that the annotation has been added.
   at Microsoft.EntityFrameworkCore.Infrastructure.AnnotatableExtensions.GetAnnotation(IAnnotatable annotatable, String annotationName)
   at Microsoft.EntityFrameworkCore.Migrations.SqlServerMigrationsSqlGenerator.<GetIndexesToRebuild>d__48.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Microsoft.EntityFrameworkCore.Migrations.SqlServerMigrationsSqlGenerator.Generate(AlterColumnOperation operation, IModel model, MigrationCommandListBuilder builder)
   at Microsoft.EntityFrameworkCore.Migrations.MigrationsSqlGenerator.Generate(MigrationOperation operation, IModel model, MigrationCommandListBuilder builder)
   at Microsoft.EntityFrameworkCore.Migrations.MigrationsSqlGenerator.Generate(IReadOnlyList`1 operations, IModel model)
   at Microsoft.EntityFrameworkCore.Migrations.SqlServerMigrationsSqlGenerator.Generate(IReadOnlyList`1 operations, IModel model)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.GenerateUpSql(Migration migration)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
   ...
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()

```

**Comment by cculver** [comment]
Mine's basically the same.
`System.InvalidOperationException: The annotation 'SqlServer:Include' was not found. Ensure that the annotation has been added.
   at Microsoft.EntityFrameworkCore.Infrastructure.AnnotatableExtensions.GetAnnotation(IAnnotatable annotatable, String annotationName)
   at Microsoft.EntityFrameworkCore.Migrations.SqlServerMigrationsSqlGenerator.GetIndexesToRebuild(IProperty property, MigrationOperation currentOperation)+MoveNext()
   at System.Collections.Generic.List`1.AddEnumerable(IEnumerable`1 enumerable)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Microsoft.EntityFrameworkCore.Migrations.SqlServerMigrationsSqlGenerator.Generate(AlterColumnOperation operation, IModel model, MigrationCommandListBuilder builder)
   at Microsoft.EntityFrameworkCore.Migrations.MigrationsSqlGenerator.<>c.<.cctor>b__73_4(MigrationsSqlGenerator g, MigrationOperation o, IModel m, MigrationCommandListBuilder b)
   at Microsoft.EntityFrameworkCore.Migrations.MigrationsSqlGenerator.Generate(MigrationOperation operation, IModel model, MigrationCommandListBuilder builder)
   at Microsoft.EntityFrameworkCore.Migrations.SqlServerMigrationsSqlGenerator.Generate(MigrationOperation operation, IModel model, MigrationCommandListBuilder builder)
   at Microsoft.EntityFrameworkCore.Migrations.MigrationsSqlGenerator.Generate(IReadOnlyList`1 operations, IModel model)
   at Microsoft.EntityFrameworkCore.Migrations.SqlServerMigrationsSqlGenerator.Generate(IReadOnlyList`1 operations, IModel model)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.GenerateUpSql(Migration migration)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.<>c__DisplayClass13_2.<GetMigrationCommandLists>b__2()
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.UpdateDatabase(String targetMigration, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabaseImpl(String targetMigration, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabase.<>c__DisplayClass0_1.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)`

**Comment by klawingco** [comment]
It's also happening to me. 
I need to increase the max length of a property from 255 to 500.
I spinned a migration that change the maxLength.
Then when I run the update-database. It throws error
here is the stack trace

```
System.InvalidOperationException: The annotation 'SqlServer:Include' was not found. Ensure that the annotation has been added.
   at Microsoft.EntityFrameworkCore.Infrastructure.AnnotatableExtensions.GetAnnotation(IAnnotatable annotatable, String annotationName)
   at Microsoft.EntityFrameworkCore.Migrations.SqlServerMigrationsSqlGenerator.GetIndexesToRebuild(IProperty property, MigrationOperation currentOperation)+MoveNext()
   at System.Collections.Generic.List`1.AddEnumerable(IEnumerable`1 enumerable)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Microsoft.EntityFrameworkCore.Migrations.SqlServerMigrationsSqlGenerator.Generate(AlterColumnOperation operation, IModel model, MigrationCommandListBuilder builder)
   at Microsoft.EntityFrameworkCore.Migrations.MigrationsSqlGenerator.Generate(MigrationOperation operation, IModel model, MigrationCommandListBuilder builder)
   at Microsoft.EntityFrameworkCore.Migrations.MigrationsSqlGenerator.Generate(IReadOnlyList`1 operations, IModel model)
   at Microsoft.EntityFrameworkCore.Migrations.SqlServerMigrationsSqlGenerator.Generate(IReadOnlyList`1 operations, IModel model)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.GenerateUpSql(Migration migration)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.UpdateDatabase(String targetMigration, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
The annotation 'SqlServer:Include' was not found. Ensure that the annotation has been added.
```

Environment : Visual Studio 2018 15.8.4
OS : Windows 7 Professional SP1
EF : EntityFrameworkCore.SqlServer (2.2.0 preview1-3509)
Net Core : 2.1
