### ISSUE TITLE
Cosmos.Sql -- JObject/JToken Property

### ISSUE THREAD

**Issue by espray** [aspnet/EntityFrameworkCore#13423]
Type not supported exception for JObject or JToken property.

Are JObject/JToken properties not supported for the Cosmos.Sql provider???

**Comment by espray** [comment]
@AndriySvyryd I am a little on the fence on this one now. :)
Although a JObject property would be handy, but this JObject property would only be supported with the Cosmos.Sql provider. An owned entity types would probably be the correct solution that would work across all providers.

Fixing: https://github.com/aspnet/EntityFrameworkCore/issues/13288 is a must. Also implementing value-conversions could also support a JObject property.

```
public class FooBar
{
    public int Id { get; set; }
    public JObject Body { get; set; }
}
```

**Comment by AndriySvyryd** [comment]
@espray In addition to the features you mentioned I added a shadow property on the root entity named `__jObject` (naming can still change) that will contain the whole document. It will only be present when the model is built for Cosmos. You can make changes to it and they will be persisted as long as the entity is marked as modified and other properties don't override your changes.

**Comment by espray** [comment]
@AndriySvyryd I tried a shadow property with `2.2.0-preview2-35157` and got the below exception. But I see you just added `__jobject` a few days ago. :)

Maybe I will just need to switch to the using Nightly Builds until preview3 :)

```
modelBuilder.Entity<Blog>().Property(typeof(JObject), "metadata");

Unhandled Exception: System.InvalidOperationException: The property 'Blog.metadata' is of type 'JObject' which is not supported by current database provider. Either change the property CLR type or ignore the property using the '[NotMapped]' attribute or by using 'EntityTypeBuilder.Ignore' in 'OnModelCreating'.
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.PropertyMappingValidationConvention.Apply(InternalModelBuilder modelBuilder)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ImmediateConventionScope.OnModelBuilt(InternalModelBuilder modelBuilder)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.CreateModel(DbContext context, IConventionSetBuilder conventionSetBuilder, IModelValidator validator)
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.Internal.InternalAccessorExtensions.GetService[TService](IInfrastructure`1 accessor)
   at Microsoft.EntityFrameworkCore.Infrastructure.DatabaseFacade.get_DatabaseCreator()
   at Microsoft.EntityFrameworkCore.Infrastructure.DatabaseFacade.EnsureDeletedAsync(CancellationToken cancellationToken)
   at EfCoreCosmosDb.Program.Main(String[] args) in C:\Users\erics\Source\Repos\EfCoreCosmosDb\EfCoreCosmosDb\Program.cs:line 23
Press any key to continue . . .
```

**Comment by AndriySvyryd** [comment]
@espray Yes, sorry that I forgot to mention that small detail. Please let me know if that plus the above mentioned features would be enough for your scenario.

**Comment by AndriySvyryd** [comment]
@espray Yes, `__jObject` is special. I don't think we'll allow mapping any `JObject` for the initial release. But it sounds like it won't be necessary once we fix the bugs with the discriminator and the owned type.

**Comment by espray** [comment]
@AndriySvyryd Yup I agree fixing the discriminator and the owned type would work. Do what you want with this issue if the discriminator and the owned type are tracked somewhere else.

Thanks! Keep up the amazing work! Looking forward to the final release!!!!

**Comment by espray** [comment]
@AndriySvyryd @smitpatel 
Below are 2 usecases. Goal would be to store in single document for best performance. In a relational database I would be fine with multiple tables. But, NoSql the more data I can pack on the document the better the performance.

1. 
```
public class CosmosDbContext : DbContext
{
  public DbSet<Enclosure> Enclosures { get; set; }
}

public abstract class Animal
{ }

public class Lion: Animal
{ }

public class Bear: Animal
{ }

public class Enclosure
{
   public Animal Animal { get; set; }
}
```

2. This one is more complex. Same goal would be to stored in single document.
```
public class CosmosDbContext : DbContext
{
  public DbSet<Transaction> Transactions { get; set; }
}

public abstract class Transaction 
{ }

public class SaleTransaction
  : Transaction
{
  public PaymentMethod { get; set; } 
}

public class AuthorizationTransaction
  : Transaction
{
  public CreditCard { get; set; }
}

public abstract class PaymentMethod
{ }

public class CreditCard
 : PaymentMethod
{ }

public class BankAccount
 : PaymentMethod
{ }
```
