### ISSUE TITLE
Sorting by included child collection property causes exception

### ISSUE THREAD

**Issue by Danielku15** [aspnet/EntityFrameworkCore#13486]
If you have an entity with a child collection and in your query you attempt to sort by a "joined" value the query fails with a NullReferenceException. 

```
Exception message: Object reference not set to an instance of an object.
Stack trace:
   at lambda_method(Closure , AnonymousObject )
   at System.Linq.Lookup`2.CreateForJoin(IEnumerable`1 source, Func`2 keySelector, IEqualityComparer`1 comparer)
   at System.Linq.Enumerable.<JoinIterator>d__38`4.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.OrderedEnumerable`1.<GetEnumerator>d__1.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryBuffer.IncludeCollection[TEntity,TRelated,TElement](Int32 includeId, INavigation navigation, INavigation inverseNavigation, IEntityType targetEntityType, IClrCollectionAccessor clrCollectionAccessor, IClrPropertySetter inverseClrPropertySetter, Boolean tracking, TEntity entity, Func`1 relatedEntitiesFactory, Func`3 joinPredicate)
   at lambda_method(Closure , QueryContext , MyObject , Object[] )
   at Microsoft.EntityFrameworkCore.Query.Internal.IncludeCompiler._Include[TEntity](QueryContext queryContext, TEntity entity, Object[] included, Action`3 fixup)
   at lambda_method(Closure , MyObject )
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.<_TrackEntities>d__17`2.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at ODataDynamicModel.Controllers.DynamicEntityController.Get()
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.SyncActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__12.MoveNext()
```

### Steps to reproduce

```c#
// Models: 
public class MyObject
{
    [Key, DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int Id { get; set; }

    public string Name { get; set; }
    public List<MyMeta> Meta { get; set; }
}

public class MyMeta
{
    [Key, DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int Id { get; set; }
    public string Key { get; set; }
    public string Value { get; set; }
}

// Query: 
var orderByNavigation = _db.MyObject
    .Include(o => o.Meta)
    .OrderBy(z => z.Meta.Single(m => m.Key == "Order").Value)
    .ToArray();
```

**Testdata:** 
_MyObject_

| Id | Name |
| --- | ----------
| 1 | Test1 | 
| 2 | test2 |

_MyMeta_

| Id | Key | Value | MyObjectId |
|---|-----|--------|--------------|
| 1 | Meta1 | Value1 | 1
| 2 | Order | Value2 | 1
| 3 | Meta2 | Test | 2
| 4 | Order | Value3 | 2

### Further technical details
EF Core version: 2.1.4
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10 Pro x64
IDE: Visual Studio 2017 15.8

#### Current Behavior
It seems that the "include" and "order by" is happening not as part of the initial query to the "parent" entity. EF first loads all entities and then per loaded entity it does an additional query: 

```sql
-- 1. Query: Loading the entities unsorted (returns 2 records)
SELECT [o].[Id], [o].[Name]
FROM [MyObject] AS [o]
-- 2. Query: Loads the navigation property of first entity for sorting
exec sp_executesql N'SELECT TOP(2) [m0].[Value]
FROM [MyMeta] AS [m0]
WHERE ([m0].[Key] = N''Order'') AND (@_outer_Id = [m0].[MyObjectId])',N'@_outer_Id int',@_outer_Id=1
-- 3. Query: Loads the navigation property of second entity for sorting
exec sp_executesql N'SELECT TOP(2) [m0].[Value]
FROM [MyMeta] AS [m0]
WHERE ([m0].[Key] = N''Order'') AND (@_outer_Id = [m0].[MyObjectId])',N'@_outer_Id int',@_outer_Id=2
```

For me it looks like that EF attempts to do the ordering in-memory and accesses the Meta collection of the parent entities before the child entites are filled into the overall object graph. If you have a simple (non-collection) navigation property you will already today find a join for this child entity. 

The issue seems directly related to the `.Include(o=>o.Meta)`. If I remove include call it works just that the Meta collection is not filled. From a performance perspective it is also terrible that for each loaded entity again a query to load the sub-records is performed. 

#### Expected Behavior
The initial query should do a join to the MyMeta table and order by the selected value from there instead of attempting to do it in memory after delayed queries. Unfortunately I cannot rephrase my queries as they the result of OData query expression construction.

**Comment by maumar** [comment]
this issue is fixed in current bits
