### ISSUE TITLE
NullReferenceException in IdentityMap<>.TryGetValue

### ISSUE THREAD

**Issue by markgould** [aspnet/EntityFrameworkCore#13662]
Mapping from a table to a view does not appear to be working correctly. A table with a one to many relationship with a view works when querying the view and including the parent table. When querying the parent table and including the view, a null reference exception happens. It appears to be related to the Foreign Key.

```
{System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.IdentityMap`1.TryGetEntry(IForeignKey foreignKey, InternalEntityEntry dependentEntry)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.NavigationFixer.InitialFixup(InternalEntityEntry entry, ISet`1 handledForeignKeys, Boolean fromQuery)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.NavigationFixer.TrackedFromQuery(InternalEntityEntry entry, ISet`1 handledForeignKeys)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntryNotifier.TrackedFromQuery(InternalEntityEntry entry, ISet`1 handledForeignKeys)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.StartTrackingFromQuery(IEntityType baseEntityType, Object entity, ValueBuffer& valueBuffer, ISet`1 handledForeignKeys)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryBuffer.StartTracking(Object entity, IEntityType entityType)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryBuffer.IncludeCollection[TEntity,TRelated,TElement](Int32 includeId, INavigation navigation, INavigation inverseNavigation, IEntityType targetEntityType, IClrCollectionAccessor clrCollectionAccessor, IClrPropertySetter inverseClrPropertySetter, Boolean tracking, TEntity entity, Func`1 relatedEntitiesFactory, Func`3 joinPredicate)
   at lambda_method(Closure , QueryContext , Account , Object[] )
   at Microsoft.EntityFrameworkCore.Query.Internal.IncludeCompiler._Include[TEntity](QueryContext queryContext, TEntity entity, Object[] included, Action`3 fixup)
   at lambda_method(Closure , Account )
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
   at System.Collections.Generic.List`1.AddEnumerable(IEnumerable`1 enumerable)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at EFCoreRepro.Program.Main(String[] args) in C:\Users\mgould\source\repos\EFCoreRepro\Program.cs:line 49}	System.NullReferenceException

```

### Steps to reproduce
Code:
[repro.txt](https://github.com/aspnet/EntityFrameworkCore/files/2489885/repro.txt)

Database script:
[script.txt](https://github.com/aspnet/EntityFrameworkCore/files/2489889/script.txt)

If you change the View to use a DbSet/Entity definition instead of the DbQuery method, it runs successfully. Let me know if I can provide any further information. 

### Further technical details
EF Core version: 2.1.4
Database Provider:  Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10 x64
IDE: Visual Studio 2017 15.8.7

**Comment by markgould** [comment]
Upgrading to 2.2.0-preview3-35497 appears to have resolved this.

**Comment by markgould** [comment]
Based on that documentation, I would say you are correct. However, my use case (and I'm sure others?) is to use query types for read only views. 

It's very common to join from a table to a view - how would this be expressed in EF Core? I can change it back to a DbSet, but most of the views are meant to be read only.

**Comment by ajcvickers** [comment]
@smitpatel Query types are allowed to be at the dependent end of a relationship since this doesn't require that each instance of the query type has a unique key value.

@markgould Query types are intended to be used for query results that do not have any primary key defined. These are by there nature read-only, but that does not mean that any read-only type should use query types. Configuring types as read-only is tracked by #7586
