### ISSUE TITLE
InvalidOperationException: Nullable object must have a value - how to debug?

### ISSUE THREAD

**Issue by NetTecture** [aspnet/EntityFrameworkCore#13966]
2.1.4, 2.2-preview-3 (tried both).

I have a complex query (aha-  select with one include) which throws the following error:

System.InvalidOperationException: 'Nullable object must have a value.'

The stack trace is:

   at lambda_method(Closure , QueryContext , TransparentIdentifier`2 )
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.ProjectionShaper.TypedProjectionShaper`3.Shape(QueryContext queryContext, ValueBuffer& valueBuffer)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.BufferlessMoveNext(DbContext _, Boolean buffer)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.MoveNext()
   at 

What is the appropriate way to debug this? There is zero relevant information given.- Field, Lambda, primary key, table - nothing. So, at the end I have now to go through the whole database. and try to figure out what goes wrong. This takes time - particualrly in a larger query with let's say 20 joins).

This exception should have more details or a relevant inner exception and provide enough context to actually allow decent fast debugging.

**Comment by ajcvickers** [comment]
@NetTecture One way this kind of exception can happen is when attempting to write a null value to a non-nullable property in a projection. One thing to try is to add a `.ToList()` to the query just before the projection so that the projection is done entirely in LINQ-to-Objects. If this throws it won't be doing so in dynamically compiled code, which means that it may be easier to see where the null assignment is coming from.

We will consider if it's possible to add additional code to get more data here, but even if it can be done there will likely be a big perf impact, so it will probably not get switched on by default.

**Comment by NetTecture** [comment]
@ajcvickers Yes, I actually do know. If you read the bug report, it is not about threasons - it is that I have ZERO help in FINDING WHICH DATA, heck, even which FIELD is the problem. See, my problem starts with my data context being GENERATED. As such, this should not be possible. So, there is one specific column possibly in one specific row that misbehaves and this may well be a generator issue. Sadly the exception does not contain the primary key, it also does not contain the column name. So, I have ZERO help in finding out the actual bug. If you work on non trivial databases (let's say 80 columns, millions of rows) that easily means a significant amount of debugging as I can not sensibly extract the pk and load every single item to find the one failing. So, the bug report is to ENCHANCE THE ERROR MESSAGE. I am well aware of the core problem, I just have now to spend some days trying to find out which data fails, and this should not happen. As in: all code there is generated, so I am at a loss. I already compared the tables involved and the schema definition and I see no difference.

**Comment by bartdk-be** [comment]
* Small bump.
Would be nice if you could add a little more detail (or at lease some documentation on how to debug this issue). Thanks
