### ISSUE TITLE
Problem with LazyLoading and TPH

### ISSUE THREAD

**Issue by Arikael** [aspnet/EntityFrameworkCore#14039]
If you enable lazy loading, use TPH (Base, Entity1, Entity2) and have a navigational property from Entity1 to Entity2 the exception below occurs.

This is further described here
https://stackoverflow.com/questions/4811194/what-is-the-syntax-for-self-referencing-foreign-keys-in-ef-code-first

and can be reproduced here
https://github.com/Arikael/EfTest/tree/master/EfTest

as a workaround you can introduce the foreign key property yourself

```
public Guid? CompanyId { get; set; }
```

```
Exception message:
Unable to cast object of type 'System.DateTime' to type 'System.Nullable`1[System.Guid]'.
Stack trace:
   at lambda_method(Closure , ValueBuffer )
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalMixedEntityEntry..ctor(IStateManager stateManager, IEntityType entityType, Object entity, ValueBuffer& valueBuffer)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntryFactory.NewInternalEntityEntry(IStateManager stateManager, IEntityType entityType, Object entity, ValueBuffer& valueBuffer)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.StartTrackingFromQuery(IEntityType baseEntityType, Object entity, ValueBuffer& valueBuffer, ISet`1 handledForeignKeys)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityTrackingInfo.StartTracking(IStateManager stateManager, Object entity, ValueBuffer& valueBuffer)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryBuffer.StartTracking(Object entity, EntityTrackingInfo entityTrackingInfo)
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider._TrackEntities[TOut,TIn](IEnumerable`1 results, QueryContext queryContext, IList`1 entityTrackingInfos, IList`1 entityAccessors)+MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
   at System.Collections.Generic.List`1.AddEnumerable(IEnumerable`1 enumerable)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at EfTest.Program.Main(String[] args) in C:\Users\haehadmin\Documents\Projects\EfTest\EfTest\Program.cs:line 16
```
### Steps to reproduce
clone https://github.com/Arikael/EfTest/tree/master/EfTest
change the ConnectionString to your local DB and run the application

### Further technical details
EF Core version: 2.1.4.
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Win 10
IDE: Visual Studio 2017 15.3.9

**Comment by ajcvickers** [comment]
Repros on 2.1 and 2.2 preview3.
Model:
```
  EntityType: Base Abstract
    Properties: 
      Id (Guid) Required PK AfterSave:Throw ValueGenerated.OnAdd 0 0 0 -1 0
      Discriminator (no field, string) Shadow Required AfterSave:Throw 1 1 -1 0 -1
    Keys: 
      Id PK
    Annotations: 
      NavigationAccessMode: Field
      Relational:DiscriminatorProperty: Discriminator
      Relational:DiscriminatorValue: Base
      Relational:TableName: Bases
  EntityType: Company Base: Base
    Properties: 
      CompanyName (string) 2 2 -1 -1 -1
    Service properties: 
      LazyLoader (no field, ILazyLoader)
    Annotations: 
      NavigationAccessMode: Field
      Relational:DiscriminatorValue: Company
  EntityType: Person Base: Base
    Properties: 
      Birthday (DateTime) Required 2 2 -1 -1 -1
      CompanyId (no field, Nullable<Guid>) Shadow FK Index 3 3 1 1 1
    Navigations: 
      Company (<Company>k__BackingField, Company) ToPrincipal Company PropertyAccessMode.Field 0 -1 2 -1 -1
        Annotations: 
          PropertyAccessMode: Field
    Service properties: 
      LazyLoader (no field, ILazyLoader)
    Foreign keys: 
      Person {'CompanyId'} -> Company {'Id'} ToPrincipal: Company
    Annotations: 
      NavigationAccessMode: Field
      Relational:DiscriminatorValue: Person
```
Minimal repro:
```C#
using System;
using System.Linq;
using Microsoft.EntityFrameworkCore;

public abstract class Base
{
    public Guid Id { get; set; }
}

public class Company : Base
{
    public string CompanyName { set; get; }
}

public class Person : Base
{
    public DateTime Birthday { set; get; }

    public virtual Company Company { set; get; }
}

public class BloggingContext : DbContext
{
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder
            .UseLazyLoadingProxies()
            .UseSqlServer(@"Server=(localdb)\mssqllocaldb;Database=Test;ConnectRetryCount=0");

    public DbSet<Person> Persons { set; get; }
    public DbSet<Company> Companies { set; get; }
    public DbSet<Base> Bases { set; get; }


public class Program
{
    public static void Main()
    {
        using (var context = new BloggingContext())
        {
            context.Database.EnsureDeleted();
            context.Database.EnsureCreated();

            context.Add(new Person());
            context.SaveChanges();
        }

        using (var context = new BloggingContext())
        {
            var test = context.Bases.ToList();
        }
   }
}
```
