### ISSUE TITLE
EFCore Design Tool - Unable to reverse previous migrations with entity has unique index

### ISSUE THREAD

**Issue by tmvan** [aspnet/EntityFrameworkCore#14052]
Recreating a INDEX field while reversing migrations cause this exception:
```
Failed executing DbCommand (4ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
CREATE INDEX [IX_TestEntities_Code] ON [TestEntities] ([Code]);
System.Data.SqlClient.SqlException (0x80131904): Column 'Code' in table 'TestEntities' is of a type that is invalid for use as a key column in an index.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, Boolean sendToPipe, Int32 timeout, Boolean asyncWrite, String methodName)
   at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteNonQuery(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.ExecuteNonQuery(IEnumerable`1 migrationCommands, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.UpdateDatabase(String targetMigration, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
ClientConnectionId:2e206044-713f-4673-b512-efc9e43d1bc0
Error Number:1919,State:1,Class:16
Column 'Code' in table 'TestEntities' is of a type that is invalid for use as a key column in an index.
```
## Steps to reproduce:
* Prepare a .NET Core Console project has these packages:
  * Microsoft.EntityFrameworkCore.Design@2.1.4
  * Microsoft.EntityFrameworkCore.SqlServer@2.1.4
* Create these objects:
  ```cs
  public class TestEntity
  {
      public long Id { get; set; }

      public string Code { get; set; }
  }
  ```

  ```cs
  public class TestEntityConfiguration : IEntityTypeConfiguration<TestEntity>
  {
      public void Configure(EntityTypeBuilder<TestEntity> builder)
      {
          builder.HasKey(x => x.Id);

          builder.HasIndex(x => x.Code);
      }
  }
  ```

  ```cs
  public class TestDbContext : DbContext
  {
      public TestDbContext(DbContextOptions<TestDbContext> options) : base(options)
      { }

      public DbSet<TestEntity> TestEntities { get; set; }

      protected override void OnModelCreating(ModelBuilder modelBuilder)
      {
          base.OnModelCreating(modelBuilder);

          modelBuilder.ApplyConfiguration(new TestEntityConfiguration());
      }
  }
  ```

  ```cs
  public class DesignTimeTestDbContextFactory : IDesignTimeDbContextFactory<TestDbContext>
  {
      public TestDbContext CreateDbContext(string[] args)
      {
          var optionsBuilder = new DbContextOptionsBuilder<TestDbContext>();

          optionsBuilder
              .UseSqlServer("Data Source=(LocalDB)\\MSSQLLocalDB;Initial Catalog=EfCoreIndexIssueDb;Trusted_Connection=True;MultipleActiveResultSets=True");

          return new TestDbContext(optionsBuilder.Options);
      }
  }
  ```
* Open `cmd` or `PowerShell` at project location, then run comand: `dotnet ef migrations add InitialMigration`. This will generate a migration, assume `xxxxxxxxxxxxxx_InitialMigration`.
* Remove property `Code` from `TestEntity` class:
  ```cs
  public class TestEntity
  {
      public long Id { get; set; }

      //public string Code { get; set; }
  }
  ```
  and in `TestEntityConfiguration` class too:

  ```cs
  public class TestEntityConfiguration : IEntityTypeConfiguration<TestEntity>
  {
      public void Configure(EntityTypeBuilder<TestEntity> builder)
      {
          builder.HasKey(x => x.Id);

          //builder.HasIndex(x => x.Code);
      }
  }
  ```
* Open `cmd` or `PowerShell` at project location, then run these following comands:
  * `dotnet ef migrations add RemoveCodeField`
  * `dotnet ef database update`
  * `dotnet ef database update xxxxxxxxxxxxxx_InitialMigration`
* An error will be thrown with message: **Column 'Code' in table 'TestEntities' is of a type that is invalid for use as a key column in an index**.

## Further technical details

* **EF Core version:** 2.1.4
* **Database Provider:** Microsoft.EntityFrameworkCore.SqlServer
* **Operating system:** Windows 10 Pro
* **IDE:** Visual Studio 2017 15.9.3

**Comment by bricelam** [comment]
Looks like this go fixed in 2.2
