### ISSUE TITLE
Error with nullable Foreign Key after migration from 2.1 to 2.2 

### ISSUE THREAD

**Issue by hugoterelle** [aspnet/EntityFrameworkCore#14126]
I have a working code in EF Core 2.1.  After migration to 2.2, I get an exception when the database is generated (using SQLite for local development)

```
Exception message:
The property 'TagId' on entity type 'OwnerTag' cannot be marked as nullable/optional because the type of the property is 'Guid' which is not a nullable type. Any property can be marked as non-nullable/required, but only properties of nullable types and which are not part of primary key can be marked as nullable/optional.

Stack trace:
   at Microsoft.EntityFrameworkCore.Metadata.Internal.Property.SetIsNullable(Boolean nullable, ConfigurationSource configurationSource)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.InternalPropertyBuilder.IsRequired(Boolean isRequired, ConfigurationSource configurationSource)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.InternalPropertyBuilder.Attach(InternalEntityTypeBuilder entityTypeBuilder)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.PropertiesSnapshot.Attach(InternalEntityTypeBuilder entityTypeBuilder)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.InternalEntityTypeBuilder.Property(Property existingProperty, String propertyName, Type propertyType, MemberInfo clrProperty, Nullable`1 configurationSource, Nullable`1 typeConfigurationSource)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.InternalEntityTypeBuilder.Property(String propertyName, Type propertyType, MemberInfo memberInfo, Nullable`1 configurationSource, Nullable`1 typeConfigurationSource)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.InternalEntityTypeBuilder.Property(String propertyName, Type propertyType, ConfigurationSource configurationSource, Nullable`1 typeConfigurationSource)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ForeignKeyPropertyDiscoveryConvention.DiscoverProperties(InternalRelationshipBuilder relationshipBuilder)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ForeignKeyPropertyDiscoveryConvention.Apply(InternalRelationshipBuilder relationshipBuilder)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ImmediateConventionScope.OnPrincipalEndChanged(InternalRelationshipBuilder relationshipBuilder)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.RunVisitor.VisitOnPrincipalEndChanged(OnPrincipalEndChangedNode node)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.OnPrincipalEndChangedNode.Accept(ConventionVisitor visitor)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ConventionVisitor.Visit(ConventionNode node)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ConventionVisitor.VisitConventionScope(ConventionScope node)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ConventionBatch.Run()
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ConventionBatch.Run(ForeignKey foreignKey)
   at Microsoft.EntityFrameworkCore.Metadata.Builders.ReferenceReferenceBuilder.HasForeignKeyBuilder(EntityType dependentEntityType, String dependentEntityTypeName, Func`3 hasForeignKey)
   at Microsoft.EntityFrameworkCore.Metadata.Builders.ReferenceReferenceBuilder.HasForeignKeyBuilder(EntityType dependentEntityType, String dependentEntityTypeName, IReadOnlyList`1 foreignKeyPropertyNames)
   at Microsoft.EntityFrameworkCore.Metadata.Builders.ReferenceReferenceBuilder`2.HasForeignKey(Type dependentEntityType, String[] foreignKeyPropertyNames)
   at Microsoft.EntityFrameworkCore.Metadata.Builders.ReferenceReferenceBuilder`2.HasForeignKey[TDependentEntity](String[] foreignKeyPropertyNames)
   at Api.Data.Owners.OwnerTagMapping.Configure(EntityTypeBuilder`1 builder) in C:\Users\hugot\devel\corellia\doxfreezer\Api.Data\Owners\OwnerTagMapping.cs:line 13
   at Microsoft.EntityFrameworkCore.ModelBuilder.ApplyConfiguration[TEntity](IEntityTypeConfiguration`1 configuration)
   at Api.Data.ApiDataContext.OnModelCreating(ModelBuilder modelBuilder) in C:\Users\hugot\devel\corellia\doxfreezer\Api.Data\ApiDataContext.cs:line 33
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelCustomizer.Customize(ModelBuilder modelBuilder, DbContext context)
   at Microsoft.EntityFrameworkCore.Infrastructure.RelationalModelCustomizer.Customize(ModelBuilder modelBuilder, DbContext context)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.CreateModel(DbContext context, IConventionSetBuilder conventionSetBuilder, IModelValidator validator)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.<>c__DisplayClass5_0.<GetModel>b__1()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
```

### Steps to reproduce

Here is the model (simplified) that we use:

```c#
 public class OwnerTag
    {
        public Tag Tag { get; set; } = new Tag();
    }

 public class Tag 
    {
        public Guid Id { get; set; }
        public virtual MetaTag MetaTag { get; set; } = new MetaTag();
        public int Order { get; set; }
        public string Name { get; set; }
        public bool Default { get; set; }
    }

public class MetaTag : RootEntity, IDisabledEntity
    {
        public Guid Id { get; set; }
        public string ReferenceName { get; set; }
        public int ReferenceOrder { get; set; }
    }

 public class Owner : RootEntity, IDisabledEntity
    {
		public Guid Id { get; set; }
        public string Email { get; set; }

        public virtual ICollection<OwnerTag> OwnerTags { get; set; } = new HashSet<OwnerTag>();
    }

// fluent mappings
 public class OwnerTagMapping : IEntityTypeConfiguration<OwnerTag>
    {
        public void Configure(EntityTypeBuilder<OwnerTag> builder)
        {
            builder.HasKey("TagId");

            builder.HasOne(t => t.Tag)
                .WithOne()
                .HasForeignKey<OwnerTag>("TagId") // the exception is thrown HERE
                .IsRequired(); 
        }
    }

    public class TagMapping : IEntityTypeConfiguration<Tag>
    {
        public void Configure(EntityTypeBuilder<Tag> builder)
        {
            builder.HasKey(t => t.Id);

            builder.HasOne(t => t.MetaTag)
                .WithMany()
                .HasForeignKey("MetaTagId");
        }
    }

    public class MetaTagMapping : IEntityTypeConfiguration<MetaTag>
    {
        public void Configure(EntityTypeBuilder<MetaTag> builder)
        {
            builder.HasKey(t => t.Id);
        }
    }

    public class OwnerMapping : IEntityTypeConfiguration<Owner>
    {
        public void Configure(EntityTypeBuilder<Owner> builder)
        {
            builder.HasKey(t => t.Id);

            builder.HasMany(t => t.OwnerTags)
                .WithOne()
                .HasForeignKey("OwnerId")
                .IsRequired();
        }
    }
```

### Further technical details
EF Core version: 2.2.0 (nuget package)
Database Provider: Microsoft.EntityFrameworkCore.Sqlite
Operating system: Windows 10
IDE: Visual Studio 2017 15.9.3

**Comment by hugoterelle** [comment]
I would like to give some more details:
Instead of using implicit keys like "TagId" in my mappings, I tried with real properties in my model. 

```c#
    public class OwnerTag
    {
        public Guid TagId { get; set; }
        public Tag Tag { get; set; } = new Tag();
    }

    public class OwnerTagMapping : IEntityTypeConfiguration<OwnerTag>
    {
        public void Configure(EntityTypeBuilder<OwnerTag> builder)
        {
            builder.HasKey(x => x.TagId);

            builder.HasOne(t => t.Tag)
                .WithOne()
                .HasForeignKey<OwnerTag>(x => x.TagId)
                .IsRequired();
        }
    }
```

 And this solution was working.  But it can't be a readl solution for me as I don't want my model to be too much "data oriented"

**Comment by ajcvickers** [comment]
@AndriySvyryd Looks like a regression in 2.2. Can you investigate?

**Comment by AndriySvyryd** [comment]
Impact: This only affects non-owned types with shadow keys, but the workaround isn't obvious.
Risk: Low, only models that explicitly configure a shadow key are affected.
