### ISSUE TITLE
context.Model.FindEntityType(Type type) throws "The string argument 'name' cannot be empty."

### ISSUE THREAD

**Issue by douglasg14b** [aspnet/EntityFrameworkCore#14267]
I'm retrieving a generic argument (that is an Entity type) for a DTO, and then passing that into `context.Model.FindEntityType()` to retrieve the entity type.

Instead of providing me with the Type, it throws the following exception:

```
System.ArgumentException
  HResult=0x80070057
  Message=The string argument 'name' cannot be empty.
  Source=Microsoft.EntityFrameworkCore
  StackTrace:
   at Microsoft.EntityFrameworkCore.Utilities.Check.NotEmpty(String value, String parameterName)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.Model.FindEntityType(String name)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.Model.FindEntityType(Type type)
   at Microsoft.EntityFrameworkCore.ModelExtensions.FindEntityType(IModel model, Type type)
   at Finance.Common.Extensions.TypeDescriptionExtensions.GetEntityType(DbContextBase context, Type entityOrDto) 
   at Finance.Services.CrudService`1.ReadSingle[T](Object key)
   at Finance.Web.Controllers.AccountController.Index(Int32 Id) 
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__12.MoveNext()
```

### Steps to reproduce

**Note**: I am providing code snippets, if this doens't stand out as an obvious problem to you, and requires deeper investigation that needs a full runnable project, please let me know and I will create one. 

I have an Entity and a DTO:
```c#
    [Table("accounts")]
    public class AccountEntity : IEntity
    {
        [Key]
        [Column("id")]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }

        [Required]
        [Column("name")]
        public string Name { get; set; }
    }
```

```c#
    public class Account : ILinkToEntity<AccountEntity>
    {
        public int Id { get; set; }
        public string Name { get; set; }
    }
```

The DTO implements `ILinkToEntity<TEntity>` which acts as a marker interface, and a way to find the entity the DTO is associated with in a generic way.

I have a generic `ReadSingle<T>` method. `T` can either be an entity or a DTO. `IModel` is just a marker interface. Since I don't know the entity type I'm working with (As T can be an entity or a dto), I need to retrieve it.

```c#
        public T ReadSingle<T>(object key) where T : class, IModel
        {
            T result;
            Type entityType = _context.GetEntityType(typeof(T));
        }
```

This calls `GetEntityType`. Which will call `GetLinkedEntityFromDto. If T was a DTO then this extracts the generic argument for the `ILinkToEntity<TEntity>`, otherwise it will return `null` and the process will continue assuming `T` was an entity type and all is well.

```c#
        public static Type GetEntityType(this DbContextBase context, Type entityOrDto)
        {
            Type entityType = entityOrDto.GetLinkedEntityFromDto() ?? entityOrDto;
            IEntityType efEntityType = context.Model.FindEntityType(entityType);
            if(efEntityType is null)
            {
                throw new InvalidOperationException($"The class {entityType.Name}is not registered as an entity class in your DbContext {context.GetType().Name}");
            }
            return entityType;
        }

        public static Type GetLinkedEntityFromDto(this Type entityOrDto)
        {
            Type[] interfaceTypes = entityOrDto.GetInterfaces();
            if (interfaceTypes.Length == 0)
            {
                throw new ArgumentException($"The class {entityOrDto.Name} does not impliment any interfaces. Expected one of IEntity or ILinkToEntity");
            }

            foreach (Type type in interfaceTypes)
            {
                if (type.IsGenericType)
                {
                    Type genericType = type.GetGenericTypeDefinition();
                    if (genericType == typeof(ILinkToEntity<>))
                    {
                        return genericType.GetGenericArguments().Single();
                    }
                }
            }
            return null;
        }
```

The exception is thrown on line 2 of the `GetEntityType()` method. This only occures when a DTO such as `Account` is passed in. `GetLinkedEntityFromDto` will successfully return the `TEntity` generic argument for the DTO.

### Further technical details
EF Core version: 2.2.0
Database Provider: SQLite in memory
Operating system: Windows Server 2016
IDE: Visual Studio 2017 15.9.4

**Comment by douglasg14b** [comment]
Well.

The problem was that I was using `genericType.GetGenericArguments().Single();` instead of using `type.GetGenericArguments().Single();'. I should get myself a rubber duck already.

However, could the scenario that causes FindEntityType()` to thro the exception be identified early and a more descriptive error provided?

**Comment by ajcvickers** [comment]
Note for triage. Looks like this code is generating an empty string for the type name:

```C#
public static string DisplayName([NotNull] this Type type, bool fullName = true)
{
    var stringBuilder = new StringBuilder();
    ProcessType(stringBuilder, type, fullName);
    return stringBuilder.ToString();
}

private static void ProcessType(StringBuilder builder, Type type, bool fullName)
{
    if (type.IsGenericType)
    {
        var genericArguments = type.GetGenericArguments();
        ProcessGenericType(builder, type, genericArguments, genericArguments.Length, fullName)
    }
    else if (type.IsArray)
    {
        ProcessArrayType(builder, type, fullName);
    }
    else if (_builtInTypeNames.TryGetValue(type, out var builtInName))
    {
        builder.Append(builtInName);
    }
    else if (!type.IsGenericParameter)
    {
        builder.Append(fullName ? type.FullName : type.Name);
    }
}
```
