### ISSUE TITLE
System.InvalidOperationException with Nullable Navigation Property

### ISSUE THREAD

**Issue by marcellangmaier** [aspnet/EntityFrameworkCore#14269]
When I am querying the asset entities, the InvalidOperation exception occurs.
The same model worked with EF 2.1 without any problems, but not in 2.2 or 3.0.
The problem appears when selecting assets where the device_guid is null.
If the device navigation property in the asset class is commented out, the query works again.

```
System.InvalidOperationException
  HResult=0x80131509
  Nachricht = An exception occurred while reading a database value for property 'Asset.DeviceGuid'. The expected type was 'System.Nullable`1[System.Guid]' but the actual value was null.
  Quelle = Microsoft.EntityFrameworkCore.Relational
  Stapelüberwachung:
   at Microsoft.EntityFrameworkCore.Storage.TypedRelationalValueBufferFactoryFactory.ThrowReadValueException[TValue](Exception exception, Object value, IPropertyBase property)
   at Microsoft.EntityFrameworkCore.Storage.Internal.TypedRelationalValueBufferFactory.Create(DbDataReader dataReader)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.BufferlessMoveNext(DbContext _, Boolean buffer)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.<_TrackEntities>d__17`2.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
   at System.Collections.Generic.List`1.AddEnumerable(IEnumerable`1 enumerable)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at ConsoleApp2.Program.Main(String[] args) in C:\Users\mlangmaier\source\repos\ConsoleApp2\Program.cs:line 22

Innere Ausnahme 1:
SqlNullValueException: Data is Null. This method or property cannot be called on Null values.
```

### Steps to reproduce
Include a complete code listing (or project/solution) that we can run to reproduce the issue.

Partial code listings, or multiple fragments of code, will slow down our response or cause us to push the issue back to you to provide code to reproduce the issue.

```c#
            var optionsBuilder = new DbContextOptionsBuilder<Context>();
            optionsBuilder.UseSqlServer("Server=xxx;Database=yyy;User Id=aaa;Password=bbb;");
            optionsBuilder.EnableDetailedErrors();

            var context = new Context(optionsBuilder.Options);
            var assets = context.Assets.ToList();
```
The model is:
```c#
   public class BaseEntity
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Column("ciid")]
        public int CIID { get; set; }

        [Key]
        [Column("guid")]
        public Guid Guid { get; set; } = System.Guid.NewGuid();
    }
    [Table("customer")]
    public class Customer : BaseEntity
    {
        [Column("name")]
        public string Name { get; set; }
    }
    [Table("truck")]
    public class Asset : BaseEntity
    {
        [Column("name")]
        public string Name { get; set; }

        [Column("customer_guid")]
        public Guid? CustomerGuid { get; set; }

        [ForeignKey(nameof(CustomerGuid))]
        public Customer Customer { get; set; }

        [Column("device_guid")]
        public Guid? DeviceGuid { get; set; }

        // works if this navigation property is disabled
        [ForeignKey(nameof(DeviceGuid))]
        public Device Device { get; set; }
    }
    [Table("device")]
    public class Device : BaseEntity
    {
        [Column("name")]
        public string Name { get; set; }

        [Column("customer_guid")]
        public Guid? CustomerGuid { get; set; }

        [ForeignKey(nameof(CustomerGuid))]
        public Customer Customer { get; set; }
    }

    public class Context : DbContext
    {
        public DbSet<Customer> Customers { get; set; }
        public DbSet<Asset> Assets { get; set; }
        public DbSet<Device> Devices { get; set; }

        public Context(DbContextOptions<Context> options) : base(options) { }
    }```


### Further technical details
EF Core version: any above 2.1
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10
IDE: Visual Studio 2019 preview

**Comment by AndriySvyryd** [comment]
@ajcvickers No, this is a different issue

**Comment by AndriySvyryd** [comment]
@IkramShah65 2.2.2 will likely be released in February. Meanwhile you can try a nightly build https://dotnet.myget.org/feed/aspnetcore-dev/package/nuget/Microsoft.EntityFrameworkCore.SqlServer/2.2.2-servicing-35827
