### ISSUE TITLE
EF fromSQL throws ArgumentNullException

### ISSUE THREAD

**Issue by Copyleaks** [aspnet/EntityFrameworkCore#14969]
I'm using C# (.net core v2.2) and EF core. I have pretty old code that is retrieving a row from the database:
``` c#
string id = "123";
using (var context = new UsersDb())
{
    var req = context.ScanRequests.FromSql($"EXEC GetById {id}").FirstOrDefault();
    // ...
}
```
GetById is a stored procedure, written in Azure SQL (basically - SQL Server).

This code started to throw an exception recently:

```
System.ArgumentNullException: Value cannot be null.
Parameter name: key
   at System.Collections.Generic.Dictionary`2.FindEntry(TKey key)
   at System.Collections.Generic.Dictionary`2.TryGetValue(TKey key, TValue& value)
   at lambda_method(Closure , ServiceProviderEngineScope )
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_Model()
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.get_EntityType()
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.get_EntityQueryable()
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.System.Linq.IQueryable.get_Provider()
   at Microsoft.EntityFrameworkCore.RelationalQueryableExtensions.FromSql[TEntity](IQueryable`1 source, FormattableString sql)
   at ***.***Factory.<>c__DisplayClass0_0.<GetById>b__0() in /tmp/sources/SystemLayer/***/***.cs:line 29
```
This issue doesn't happen to me when I run the same code with the same parameters in a local environment. Also, in most cases it's also working on production servers. I guess it's at least 99.9% success rate.

The problematic line (line 29 from stacktrace) is this line: 
```c#
var req = context.ScanRequests.FromSql($"EXEC GetById {id}").FirstOrDefault();
```

What to do? What else should I check?

### Further technical details
EF Core version: netcoreapp2.2
Database Provider: Azure Sql
Operating system: Linux debian
IDE: Visual Studio 2017 15.9.4

**Comment by ajcvickers** [comment]
@Eilon Moving this to D.I. area since this looks like a concurrency issue in D.I.
