### ISSUE TITLE
Test: SqlAzureFundamentalsTest are broken

### ISSUE THREAD

**Issue by smitpatel** [aspnet/EntityFrameworkCore#15004]
Something related to `PoolableDbContext`
```
Test Name:	Microsoft.EntityFrameworkCore.SqlAzure.SqlAzureFundamentalsTest.CanAdd
Test FullName:	Microsoft.EntityFrameworkCore.SqlAzure.SqlAzureFundamentalsTest.CanAdd
Test Source:	D:\code\SecondEF\EntityFrameworkCore\test\EFCore.SqlServer.FunctionalTests\SqlAzure\SqlAzureFundamentalsTest.cs : line 30
Test Outcome:	Failed
Test Duration:	0:00:00.001

Result StackTrace:	
at Microsoft.EntityFrameworkCore.SharedStoreFixtureBase`1.CreateContext() in D:\code\SecondEF\EntityFrameworkCore\test\EFCore.Specification.Tests\SharedStoreFixtureBase.cs:line 62
   at Microsoft.EntityFrameworkCore.SqlAzure.SqlAzureFundamentalsTest.CreateContext() in D:\code\SecondEF\EntityFrameworkCore\test\EFCore.SqlServer.FunctionalTests\SqlAzure\SqlAzureFundamentalsTest.cs:line 92
   at Microsoft.EntityFrameworkCore.SqlAzure.SqlAzureFundamentalsTest.CanAdd() in D:\code\SecondEF\EntityFrameworkCore\test\EFCore.SqlServer.FunctionalTests\SqlAzure\SqlAzureFundamentalsTest.cs:line 32
Result Message:	System.InvalidCastException : Unable to cast object of type 'Microsoft.EntityFrameworkCore.SqlAzure.Model.AdventureWorksContext' to type 'Microsoft.EntityFrameworkCore.TestUtilities.PoolableDbContext'.
```

**Comment by ajcvickers** [comment]
Note for triage: tests are currently skipped.

**Comment by ajcvickers** [comment]
See also #15016
