### ISSUE TITLE
When selecting a field through not required one-to-one relation it's type is not converted.

### ISSUE THREAD

**Issue by xiety** [aspnet/EntityFrameworkCore#15200]
Column defined as:
```c#
[Column(TypeName = "int")]
public bool BoolField { get; set; }
```

Simple query works normally:
```c#
var query = db.TableChild.Select(a => new { a.BoolField }).ToList();
```

But this query throws an exception:
```c#
var query = db.TableParent
    .Where(a => a.Child != null)
    .Select(a => new { a.Child.BoolField })
    .ToList();
```

Exception:
> Unhandled Exception: System.InvalidCastException: Unable to cast object of type 'System.Int32' to type 'System.Boolean'.
   at System.Data.SqlClient.SqlBuffer.get_Boolean()
   at lambda_method(Closure , DbDataReader )
   at Microsoft.EntityFrameworkCore.Storage.Internal.TypedRelationalValueBufferF
actory.Create(DbDataReader dataReader)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerat
or.BufferlessMoveNext(DbContext _, Boolean buffer)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutio
nStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifyS
ucceeded)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerat
or.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.Exceptio
nInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
   at System.Collections.Generic.List`1.AddEnumerable(IEnumerable`1 enumerable)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)

### Steps to reproduce

```c#
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Diagnostics;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace EFBug
{
    class Program
    {
        static void Main(string[] args)
        {
            var db = new BugContext();
            db.Database.EnsureDeleted();
            db.Database.EnsureCreated();

            var query = db.TableParent
                .Where(a => a.Child != null)
                .Select(a => new { a.Child.BoolField })
                .ToList();
        }
    }

    class BugContext : DbContext
    {
        public DbSet<TableParent> TableParent { get; set; }
        public DbSet<TableChild> TableChild { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            base.OnConfiguring(optionsBuilder.UseSqlServer(@"Server=(localdb)\mssqllocaldb;Database=EFBug1;Trusted_Connection=True;MultipleActiveResultSets=true"));
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            var entityTypeParent = modelBuilder.Entity<TableParent>();

            entityTypeParent.HasData(
                new TableParent { Id = 1, RefId = "Pos1" },
                new TableParent { Id = 2, RefId = "Pos2" }
            );

            var entityTypeChild = modelBuilder.Entity<TableChild>();

            entityTypeChild.HasData(
                new TableChild { Id = 3, ParentRefId = "Pos2", BoolField = true }
            );

            entityTypeChild
                .HasOne(b => b.Parent)
                .WithOne(a => a.Child)
                .HasForeignKey<TableChild>(b => b.ParentRefId)
                .HasPrincipalKey<TableParent>(a => a.RefId);
        }
    }

    class TableParent
    {
        [Key]
        public long Id { get; set; }
        [Required]
        public string RefId { get; set; }

        public TableChild Child { get; set; }
    }

    class TableChild
    {
        [Key]
        public long Id { get; set; }
        [Required]
        public string ParentRefId { get; set; }
        [Column(TypeName = "int")]
        public bool BoolField { get; set; }

        public TableParent Parent { get; set; }
    }
}
```

When using Join, Include, one-to-many relation or one-to-one relation with different direction it works normally.

### Further technical details
EF Core version: 2.2.3
Database Provider: Microsoft.EntityFrameworkCore.SqlServer

**Comment by smitpatel** [comment]
Seems like bug in identifying the property for projection (hence no value converter was used).
