### ISSUE TITLE
Detaching a DbContext entry with Added state does not successfully stop tracking

### ISSUE THREAD

**Issue by bugged84** [aspnet/EntityFrameworkCore#15500]
Consider the following code from the `InternalEntityEntry.SetEntityState(EntityState oldState, EntityState newState, bool acceptChanges)` method.

![image](https://user-images.githubusercontent.com/23638686/56761355-c0c36e80-6762-11e9-8aca-a4c189ec187c.png)

As depicted, an entity transitioning from the Added state to the Detached state will have certain properties reset to default values. Unfortunately, one of these properties is my primary key for the entity. Since the primary key is reset to a default value, then the call to `StateManager.StopTracking(this)` does not successfully remove the entity from its identity map.

![image](https://user-images.githubusercontent.com/23638686/56761566-4810e200-6763-11e9-8d66-1f6e731ea25f.png)

As a result, if later another instance of the entity (with a populated primary key) is attempted to be tracked by the context, then the call to `StateManager.StartTracking(this)` fails because the identity map already contains the key which was not removed during the call to `StateManager.StopTracking(this)`.

This results in the following exception.

```
System.InvalidOperationException: The instance of entity type 'MyEntity' cannot be tracked because another instance with the key value '{Id: 8962cb17-bef4-4ae9-a247-494129381fe2}' is already being tracked. When attaching existing entities, ensure that only one entity instance with a given key value is attached.
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.IdentityMap`1.ThrowIdentityConflict(InternalEntityEntry entry)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.IdentityMap`1.Add(TKey key, InternalEntityEntry entry, Boolean updateDuplicate)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.IdentityMap`1.Add(TKey key, InternalEntityEntry entry)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.IdentityMap`1.Add(InternalEntityEntry entry)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.StartTracking(InternalEntityEntry entry)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.SetEntityState(EntityState oldState, EntityState newState, Boolean acceptChanges)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityGraphAttacher.PaintAction(EntityEntryGraphNode node, Boolean force)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityEntryGraphIterator.TraverseGraph[TState](EntityEntryGraphNode node, TState state, Func`3 handleNode)
   at Microsoft.EntityFrameworkCore.DbContext.SetEntityState[TEntity](TEntity entity, EntityState entityState)
```
### Further technical details
EF Core version: Microsoft.EntityFrameworkCore.SqlServer v2.2.4
Database Provider: Microsoft.EntityFrameworkCore.SqlServer

**Comment by ajcvickers** [comment]
This is fixed in the 3.0 code because temporary values are no longer stored in entity instances. Will add test.
