### ISSUE TITLE
Using a deep Owned Entity graph raises exception

### ISSUE THREAD

**Issue by altmann** [aspnet/EntityFrameworkCore#15839]
I have two Entities:
- Antrag
- AntragVersion

Both have an Owned Entity Einstellung. 
Antrag has also the Owned Entity Ablehnung. 

See attached code sample. If you execute it then I get an exception. I'am very sure that I configured it correctly. 

If I replace in class ErstePruefung the property Pruefer with Type Fachmitarbeiter with a simple DateTime property (and adapt the modelbuilder configuration) then it is working. So the reason why it is failing is the Owned Entity Fachmitarbeiter. 

Another case: If I remove from the class Antrag the property Ablehnung (and the modelbuilder configuration) then it is also working fine. 

```
Exception message: System.InvalidOperationException: 'Unable to determine the relationship represented by navigation property 'Ablehnung.ErstePruefung#ErstePruefung.Pruefer' of type 'Fachmitarbeiter'. Either manually configure the relationship, or ignore this property using the '[NotMapped]' attribute or by using 'EntityTypeBuilder.Ignore' in 'OnModelCreating'.'

Stack trace: at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.PropertyMappingValidationConvention.Apply(InternalModelBuilder modelBuilder)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ImmediateConventionScope.OnModelBuilt(InternalModelBuilder modelBuilder)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.OnModelBuilt(InternalModelBuilder modelBuilder)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.Model.Validate()
   at Microsoft.EntityFrameworkCore.ModelBuilder.FinalizeModel()
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.CreateModel(DbContext context, IConventionSetBuilder conventionSetBuilder, IModelValidator validator)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.<>c__DisplayClass5_0.<GetModel>b__1()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at System.Lazy`1.get_Value()
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.GetModel(DbContext context, IConventionSetBuilder conventionSetBuilder, IModelValidator validator)
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()
   at Microsoft.EntityFrameworkCore.Infrastructure.EntityFrameworkServicesBuilder.<>c.<TryAddCoreServices>b__7_2(IServiceProvider p)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass1_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.Microsoft.EntityFrameworkCore.Infrastructure.IInfrastructure<System.IServiceProvider>.get_Instance()
   at Microsoft.EntityFrameworkCore.Infrastructure.DatabaseFacade.Microsoft.EntityFrameworkCore.Infrastructure.IInfrastructure<System.IServiceProvider>.get_Instance()
   at Microsoft.EntityFrameworkCore.Internal.InternalAccessorExtensions.GetService[TService](IInfrastructure`1 accessor)
   at Microsoft.EntityFrameworkCore.Infrastructure.AccessorExtensions.GetService[TService](IInfrastructure`1 accessor)
   at EfCoreSample.DatabaseFacadeExtensions.DatabaseExists(DatabaseFacade database) in C:\ALTMANN\Archive\EfCoreSample\EfCoreSample\Program.cs:line 18
   at EfCoreSample.Program.Main(String[] args) in C:\ALTMANN\Archive\EfCoreSample\EfCoreSample\Program.cs:line 41

```

### Steps to reproduce
[EfCoreSample.zip](https://github.com/aspnet/EntityFrameworkCore/files/3232214/EfCoreSample.zip)

Execute EfCoreSample project

### Further technical details
EF Core version: 2.2.4
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10
IDE: Visual Studio 2017 15.9.12

**Comment by ajcvickers** [comment]
@altmann I took a look at the repro code and I can see that you are overriding Equals and GetHashCode in a non-stable way. See [my comment here](https://github.com/aspnet/EntityFrameworkCore/issues/15687#issuecomment-492280606) for more details.

If you're still seeing issues after fixing this, then please post a new sample project with the changes made.

**Comment by altmann** [comment]
@ajcvickers Thanks for your answer. I commented the custom Equals and GetHashCode() logic out, but the exception is still throwed. 

The exception is already throwed in line 14 during if (!(database.GetService<IDatabaseCreator>() is RelationalDatabaseCreator databaseCreator)).

Here is the sample project. 
[EfCoreSampleWithoutOverrridedEquals.zip](https://github.com/aspnet/EntityFrameworkCore/files/3255765/EfCoreSampleWithoutOverrridedEquals.zip)

**Comment by ajcvickers** [comment]
@altmann Thanks.

Note for triage: this appears to be an issue with a nested owned type being re-used (i.e. becoming weak) at multiple levels. More minimal repro below:
```C#
namespace EfCoreSample
{
    public class Program
    {
        public static void Main()
        {
            using (var appContext = new AppContext())
            {
                appContext.Database.EnsureDeleted();
                appContext.Database.EnsureCreated();
            }
        }
    }

    public class Antrag
    {
        public Guid Id { get; protected set; }
        public Einstellung Einstellung { get; set; }
        public Ablehnung Ablehnung { get; set; }

    }

    public class AntragVersion
    {
        public Guid Id { get; protected set; }
        public Einstellung Einstellung { get; set; }
    }

    public class Ablehnung
    {
        public ErstePruefung ErstePruefung { get; set; }
    }

    public class Fachmitarbeiter
    {
    }

    public class ErstePruefung
    {
        public Fachmitarbeiter Pruefer { get; set; }
    }

    public class Einstellung
    {
        public ErstePruefung ErstePruefung { get; set; }
    }

    public class AppContext : DbContext
    {
        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder) 
            => optionsBuilder.UseSqlServer(@"Server=(localdb)\mssqllocaldb;Database=Test;ConnectRetryCount=0");

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Antrag>(entity =>
            {
                entity.OwnsOne(x => x.Einstellung,
                    amb =>
                    {
                        amb.OwnsOne(x => x.ErstePruefung, mb =>
                        {
                            mb.OwnsOne(a => a.Pruefer);
                        });
                    });

                entity.OwnsOne(x => x.Ablehnung,
                    amb =>
                    {
                        amb.OwnsOne(x => x.ErstePruefung, mb =>
                        {
                            mb.OwnsOne(a => a.Pruefer);
                        });
                    });
            });

            modelBuilder.Entity<AntragVersion>(entity =>
            {
                entity.OwnsOne(x => x.Einstellung,
                    amb =>
                    {
                        amb.OwnsOne(x => x.ErstePruefung, mb =>
                        {
                            mb.OwnsOne(a => a.Pruefer);
                        });
                    });
            });
        }
    }
}
```

**Comment by Cogax** [comment]
Is there a workaround we can implement?

**Comment by altmann** [comment]
@Cogax I don't know a workaround. Luckily now we don't need this kind of reusing of owned entities any more in our project. 

If you know a workaround, let me know.
