### ISSUE TITLE
NRE in SelectionExpression

### ISSUE THREAD

**Issue by roji** [aspnet/EntityFrameworkCore#15946]
After entity equality is implemented, test `Join_on_entity_qsre_keys_inner_key_is_nested_navigation` fails with the following:

```
System.NullReferenceException : Object reference not set to an instance of an object.
   at Microsoft.EntityFrameworkCore.Relational.Query.Pipeline.SqlExpressions.SelectExpression.Update(List`1 projections, List`1 tables, SqlExpression predicate, List`1 orderings, SqlExpression limit, SqlExpression offset, Boolean distinct, String alias) in /home/roji/projects/EFCore/src/EFCore.Relational/Query/Pipeline/SqlExpressions/SelectExpression.cs:line 859
   at Microsoft.EntityFrameworkCore.SqlServer.Query.Pipeline.SearchConditionConvertingExpressionVisitor.VisitSelect(SelectExpression selectExpression) in /home/roji/projects/EFCore/src/EFCore.SqlServer/Query/Pipeline/SearchConditionConvertingExpressionVisitor.cs:line 167
```

Entity equality seems to do the correct transformation:

Input: 
```
value(Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1[Microsoft.EntityFrameworkCore.TestModels.GearsOfWarModel.Squad]).Join(value(Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1[Microsoft.EntityFrameworkCore.TestModels.GearsOfWarModel.Weapon]).Where(ww => ww.IsAutomatic), s => s, w => w.Owner.Squad, (s, w) => new <>f__AnonymousType218`2(SquadName = s.Name, WeaponName = w.Name))
```

Output:
```
value(Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1[Microsoft.EntityFrameworkCore.TestModels.GearsOfWarModel.Squad]).Join(value(Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1[Microsoft.EntityFrameworkCore.TestModels.GearsOfWarModel.Weapon]).Where(ww => ww.IsAutomatic), s => Property(s, "Id"), w => Property(w.Owner.Squad, "Id"), (s, w) => new <>f__AnonymousType218`2(SquadName = s.Name, WeaponName = w.Name))
```

/cc @smitpatel

**Comment by maumar** [comment]
issue has been fixed in d2b195a2cafabda2bd5ed67310044b2a2cd47545, test re-enabled in 458f4a03a37e030edf1bbb0f7a4e58bf3997c4a5
