### ISSUE TITLE
IN statement (Contains) with Queryable throws not implemented exception

### ISSUE THREAD

**Issue by hkoestin** [aspnet/EntityFrameworkCore#15974]
I am using Dynamic LINQ to generate parts of a WHERE clause. Certain parts should be translated to a SQL IN statement. However, generation fails with a Not Implemented Exception.

```
Microsoft.EntityFrameworkCore.Query:Error: An exception occurred in the database while iterating the results of a query for context type 'AOQN.Evaluations.Persistence.AOQNEvaluationsContext'.
System.NotImplementedException: The method or operation is not implemented.
   at Microsoft.EntityFrameworkCore.Query.Internal.NullAsyncQueryProvider.System.Linq.IQueryProvider.Execute[TResult1](Expression expression)
   at Remotion.Linq.QueryableBase`1.GetEnumerator()
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at System.Collections.Generic.List`1.AddEnumerable(IEnumerable`1 enumerable)
   at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
   at Microsoft.EntityFrameworkCore.Query.Sql.DefaultQuerySqlGenerator.InExpressionValuesExpandingVisitor.AddInExpressionValues(Object value, List`1 inConstants, Expression expression)
   at Microsoft.EntityFrameworkCore.Query.Sql.DefaultQuerySqlGenerator.InExpressionValuesExpandingVisitor.ProcessInExpressionValues(IEnumerable`1 inExpressionValues)
   at Microsoft.EntityFrameworkCore.Query.Sql.DefaultQuerySqlGenerator.InExpressionValuesExpandingVisitor.VisitExtension(Expression node)
   at System.Linq.Expressions.Expression.Accept(ExpressionVisitor visitor)
   at Microsoft.EntityFrameworkCore.Query.Expressions.InExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at System.Linq.Expressions.ExpressionVisitor.VisitBinary(BinaryExpression node)
   at System.Linq.Expressions.BinaryExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at System.Linq.Expressions.ExpressionVisitor.VisitBinary(BinaryExpression node)
   at System.Linq.Expressions.BinaryExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.Sql.DefaultQuerySqlGenerator.ApplyOptimizations(Expression expression, Boolean searchCondition, Boolean joinCondition)
   at Microsoft.EntityFrameworkCore.Query.Sql.DefaultQuerySqlGenerator.GeneratePredicate(Expression predicate)
   at Microsoft.EntityFrameworkCore.Query.Sql.DefaultQuerySqlGenerator.VisitSelect(SelectExpression selectExpression)
   at Microsoft.EntityFrameworkCore.Query.Expressions.SelectExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Remotion.Linq.Parsing.ThrowingExpressionVisitor.Visit(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.Sql.DefaultQuerySqlGenerator.GenerateSql(IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Query.Internal.ShaperCommandContext.GetRelationalCommand(IReadOnlyDictionary`2 parameters)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.BufferlessMoveNext(DbContext _, Boolean buffer)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.MoveNext()
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
```

### Steps to reproduce
Basically, what I do, is to add the following Where() call to my queryable.

```c#
DbSet.Where(" @0.Contains(it.Case.Id) ", DbSet
                     .Where(x => x.Attribute.Id == 'some-id')
                     .Select(x => x.Case.Id)
                     .Distinct())
```

What I would expect, is that EF does generate a WHERE statement like the following:
```sql
SELECT ...
FROM ... x
WHERE x.CaseId IN (
    SELECT DISTINCT [inner].[CaseId]
    FROM [ContextItem] AS [inner]
    WHERE [inner].[MrAttributeId] = N'some-id'
)
```

What comes to my mind when having a look at the stack-trace:
Why is it navigating via the Enumerable and not the Queryable?

```
at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
```

### Further technical details
EF Core version: 2.1.1
Database Provider:  Microsoft.EntityFrameworkCore.SqlServer
Operating system: Win10-x64
IDE: Visual Studio 2017 15.9.12

**Comment by ajcvickers** [comment]
@hkoestin Please post a project/solution or complete code listing that demonstrates the behavior you are seeing. Ideally, please remove Dynamic LINQ from the repro code so that we can focus on the potential underlying bug in EF.

**Comment by hkoestin** [comment]
@ajcvickers I did try to reproduce that error with just plain expressions etc. on IQueryable and it works.

So it seems, that the exception is maybe related to a wrong expression tree coming from Dynamic LINQ, which cannot be translated correctly into SQL.

Don't know, if it worth now, to try and reproduce that exact same problem. Maybe I can close the issue again.

**Comment by divega** [comment]
@hkoestin and what about a small repro using Dynamic LINQ? We should be able to look at the expression tree generated.

**Comment by hkoestin** [comment]
@divega I succeeded to provide a very short sample, which reproduces the error.

Basically, what I have:
 * a ContextItem has an attribute and belongs to a Case
 * an Attribute has a name

I want to query all ContextItems, where cases have mapped a certain attribute

Code to reproduce:
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="2.1.11" />
    <PackageReference Include="System.Linq.Dynamic.Core" Version="1.0.15" />
  </ItemGroup>

</Project>
```

C# code to reproduce:
```c#
class Program
{
    static void Main(string[] args)
    {
        Console.WriteLine("Hello World!");

        var context = GetSqliteContext();

        var one = new Attribute { ID = "1", Name = "one" };
        var two = new Attribute { ID = "2", Name = "two" };
        context.Add(one);
        context.Add(two);

        context.Add(new ContextItem { ID = "1", Attribute = one, CaseId = "c1" });
        context.Add(new ContextItem { ID = "2", Attribute = two, CaseId = "c1" });
        context.Add(new ContextItem { ID = "3", Attribute = two, CaseId = "c2" });

        context.SaveChanges();

        // working -> direct IN with an enumeration (c1 and c2 have "two")
        var cases = new[] { "c1", "c2" };
        var lambda = DynamicExpressionParser.ParseLambda(ParsingConfig.Default, false, 
                typeof(ContextItem), null,
                $" @0.Contains(it.CaseId) ", cases);
        Console.WriteLine(lambda);
        var result = context.Set<ContextItem>().Where(lambda).Cast<ContextItem>().ToList();

        // not working -> sub-query for the IN statement using a queryable to get the 
        // case-ids, which have the attribute "two" applied
        var queryable = context.FindCaseIdsByAttribute("two");
        lambda = DynamicExpressionParser.ParseLambda(ParsingConfig.Default, false, 
                typeof(ContextItem), null,
                $" it.CaseId IN @0 ", queryable);

        Console.WriteLine(lambda);
        result = context.Set<ContextItem>().Where(lambda).Cast<ContextItem>().ToList();

        Console.WriteLine("Done!");
        Console.ReadLine();
    }

    private static Context GetSqliteContext()
    {
        DbContextOptions<Context> options;

        var builder = new DbContextOptionsBuilder<Context>();
        var connection = "Filename=" + Path.Combine(Environment.CurrentDirectory, "TestDB.db");
        builder.UseSqlite(connection);

        options = builder.Options;

        var context = new Context(options);
        context.Database.EnsureDeleted();
        context.Database.EnsureCreated();

        return context;
    }
}

public class ContextItem
{
    [Key]
    public string ID { get; set; }
    public string CaseId { get; set; }

    public Attribute Attribute { get; set; }
}

public class Attribute
{
    [Key]
    public string ID { get; set; }
    public string Name { get; set; }
}

public class Context : DbContext
{
    public Context(DbContextOptions<Context> options) : base(options)
    {
    }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Attribute>().ToTable(nameof(Attribute));
        modelBuilder.Entity<Attribute>().HasIndex(m => m.Name);

        modelBuilder.Entity<ContextItem>().ToTable(nameof(ContextItem));
        modelBuilder.Entity<ContextItem>().HasOne(m => m.Attribute);
    }

    public IQueryable<string> FindCaseIdsByAttribute(string attribute)
    {
        return Set<ContextItem>()
            .Where(x => x.Attribute.Name == attribute)
            .Select(x => x.CaseId)
            .Distinct();
    }
}
```

Output:
```
Hello World!
Param_0 => "c1".Contains(Param_0.CaseId)
Param_0 => value(Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1[System.String]).Contains(Param_0.CaseId)

Unhandled Exception: System.NotImplementedException: The method or operation is not implemented.
   at Microsoft.EntityFrameworkCore.Query.Internal.NullAsyncQueryProvider.System.Linq.IQueryProvider.Execute[TResult1](Expression expression)
   at Remotion.Linq.QueryableBase`1.GetEnumerator()
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at System.Collections.Generic.List`1.AddEnumerable(IEnumerable`1 enumerable)
   at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
   at Microsoft.EntityFrameworkCore.Query.Sql.DefaultQuerySqlGenerator.InExpressionValuesExpandingVisitor.ProcessInExpressionValues(IEnumerable`1 inExpressionValues)
   at Microsoft.EntityFrameworkCore.Query.Sql.DefaultQuerySqlGenerator.InExpressionValuesExpandingVisitor.VisitExtension(Expression node)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.Sql.DefaultQuerySqlGenerator.ApplyOptimizations(Expression expression, Boolean searchCondition, Boolean joinCondition)
   at Microsoft.EntityFrameworkCore.Query.Sql.DefaultQuerySqlGenerator.GeneratePredicate(Expression predicate)
   at Microsoft.EntityFrameworkCore.Query.Sql.DefaultQuerySqlGenerator.VisitSelect(SelectExpression selectExpression)
   at Microsoft.EntityFrameworkCore.Query.Sql.DefaultQuerySqlGenerator.GenerateSql(IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Query.Internal.ShaperCommandContext.GetRelationalCommand(IReadOnlyDictionary`2 parameters)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.BufferlessMoveNext(DbContext _, Boolean buffer)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider._TrackEntities[TOut,TIn](IEnumerable`1 results, QueryContext queryContext, IList`1 entityTrackingInfos, IList`1 entityAccessors)+MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
   at System.Collections.Generic.List`1.AddEnumerable(IEnumerable`1 enumerable)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at EFC_IN_statement.Program.Main(String[] args) in C:\Users\dev12\Documents\Visual Studio 2017\Projects\EFC_IN_statement\EFC_IN_statement\Program.cs:line 46
Press any key to continue . . .
```

@divega Would this be enough for you?

**Comment by smitpatel** [comment]
I got repro. Happens in preview5 too. Difference is, generally the external queryable is from closure and we evaluate it. In this case it is constant and we did not evaluate it. Investigating.

**Comment by smitpatel** [comment]
I investigated this.
Whenever a Queryable is referenced inside another expression tree,
- Either it is coming from closure member or instance method/member in which case it would be member/method access on constant expression
- or if not in above case, then it would be fully inlined, expanding the inner expression tree which has the query root as constant.

In above case, dynamic linq is generating an expression tree which compiler would not generate. It is injecting constant of queryable in the tree directly rather than via member access but not flattening out expression tree which compiler would do. Anything not captured from closure or instance is evaluated by compiler right away. (that is how skip/take also worked). Since the expression tree is not properly evaluated, it runs into above issue at runtime.

**Comment by ajcvickers** [comment]
Notes from triage: putting this on the backlog to look at translating this. However, in general we focus translation on those expression trees that can be generated by the compiler. This helps constrain what is a huge space of possibly valid expression trees to something, while still huge, is not quite _as _huge_. Ideally, dynamic LINQ should only generate queries in the form that the compiler generates. As far as we can tell, there doesn't seem to be any fundamental reason why dynamic LINQ can't do this.
