### ISSUE TITLE
Query: Include after FromSql throws

### ISSUE THREAD

**Issue by smitpatel** [aspnet/EntityFrameworkCore#15991]
```C#
        [Fact]
        public virtual async Task FromSqlRaw_queryable_simple_include()
        {
            using (var context = CreateContext())
            {
                var actual = await context.Set<Customer>().FromSqlRaw(NormalizeDelimetersInRawString("SELECT * FROM [Customers]"))
                    .Include(c => c.Orders)
                    .ToArrayAsync();

                Assert.Equal(830, actual.SelectMany(c => c.Orders).Count());
            }
        }
```
Include after FromSqlRaw fails with
```
Message: 
    System.InvalidOperationException : Incorrect include argument: c => c.Orders
  Stack Trace: 
    at NavigationExpandingVisitor.ProcessInclude(MethodCallExpression methodCallExpression) in NavigationExpandingVisitor_MethodCall.cs line: 1073
    at NavigationExpandingVisitor.VisitMethodCall(MethodCallExpression methodCallExpression) in NavigationExpandingVisitor_MethodCall.cs line: 100
    at MethodCallExpression.Accept(ExpressionVisitor visitor)
    at ExpressionVisitor.Visit(Expression node)
    at NavigationExpandingVisitor.VisitSourceExpression(Expression sourceExpression) in NavigationExpandingVisitor_MethodCall.cs line: 116
    at NavigationExpandingVisitor.ProcessWhere(MethodCallExpression methodCallExpression) in NavigationExpandingVisitor_MethodCall.cs line: 160
    at NavigationExpandingVisitor.VisitMethodCall(MethodCallExpression methodCallExpression) in NavigationExpandingVisitor_MethodCall.cs line: 39
    at MethodCallExpression.Accept(ExpressionVisitor visitor)
    at ExpressionVisitor.Visit(Expression node)
    at NavigationExpander.ExpandNavigations(Expression expression) in NavigationExpander.cs line: 25
    at QueryOptimizer.Visit(Expression query) in QueryOptimizingExpressionVisitor.cs line: 26
    at QueryCompilationContext.CreateQueryExecutor[TResult](Expression query) in QueryCompilationContext2.cs line: 58
    at Database.CompileQuery2[TResult](Expression query, Boolean async) in Database.cs line: 72
    at QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async) in QueryCompiler.cs line: 108
    at <>c__DisplayClass12_0`1.<ExecuteAsync>b__0() in QueryCompiler.cs line: 141
    at CompiledQueryCache.GetOrAddQueryCore[TFunc](Object cacheKey, Func`1 compiler) in CompiledQueryCache.cs line: 84
    at CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler) in CompiledQueryCache.cs line: 59
    at QueryCompiler.ExecuteAsync[TResult](Expression query, CancellationToken cancellationToken) in QueryCompiler.cs line: 137
    at EntityQueryProvider.ExecuteAsync[TResult](Expression expression, CancellationToken cancellationToken) in EntityQueryProvider.cs line: 98
    at EntityQueryable`1.GetAsyncEnumerator(CancellationToken cancellationToken) in EntityQueryable`.cs line: 112
    at ConfiguredCancelableAsyncEnumerable`1.GetAsyncEnumerator()
    at EntityFrameworkEnumerableExtensions.ToListAsync[TSource](IAsyncEnumerable`1 source, CancellationToken cancellationToken) in EntityFrameworkEnumerableExtensions.cs line: 46
    at EntityFrameworkEnumerableExtensions.ToArrayAsync[TSource](IAsyncEnumerable`1 source, CancellationToken cancellationToken) in EntityFrameworkEnumerableExtensions.cs line: 77
    at AsyncFromSqlQueryTestBase`1.FromSqlRaw_queryable_simple_composed_include() in AsyncFromSqlQueryTestBase.cs line: 324
    at --- End of stack trace from previous location where exception was thrown ---
```

**Comment by maumar** [comment]
issue has already been fixed, tests enabled in 9b52248189e940eff2b0477833f83120b80b3805 - closing
