### ISSUE TITLE
Query: Nav rewrite type mismatch

### ISSUE THREAD

**Issue by smitpatel** [aspnet/EntityFrameworkCore#16076]
``` Microsoft.EntityFrameworkCore.Query.AsyncSimpleQuerySqlServerTest.ToArray_on_nav_subquery_in_projection
System.ArgumentException : Method 'Microsoft.EntityFrameworkCore.TestModels.Northwind.Order[] ToArray()' declared on type 'System.Collections.Generic.List`1[Microsoft.EntityFrameworkCore.TestModels.Northwind.Order]' cannot be called with instance of type 'System.Linq.IQueryable`1[Microsoft.EntityFrameworkCore.TestModels.Northwind.Order]'
   at System.Linq.Expressions.Expression.ValidateCallInstanceType(Type instanceType, MethodInfo method)
   at System.Linq.Expressions.Expression.ValidateMethodAndGetParameters(Expression instance, MethodInfo method)
   at System.Linq.Expressions.Expression.Call(Expression instance, MethodInfo method)
   at System.Linq.Expressions.Expression.Call(Expression instance, MethodInfo method, IEnumerable`1 arguments)
   at Microsoft.EntityFrameworkCore.Query.NavigationExpansion.Visitors.CollectionNavigationRewritingVisitor.VisitMethodCall(MethodCallExpression methodCallExpression) in D:\code\EntityFrameworkCore\src\EFCore\Query\NavigationExpansion\Visitors\CollectionNavigationRewritingVisitor.cs:line 110
   at System.Dynamic.Utils.ExpressionVisitorUtils.VisitArguments(ExpressionVisitor visitor, IArgumentProvider nodes)
   at System.Linq.Expressions.ExpressionVisitor.VisitNew(NewExpression node)
   at Microsoft.EntityFrameworkCore.Query.NavigationExpansion.Visitors.NavigationExpandingVisitor.FindAndApplyNavigations(Expression source, LambdaExpression lambda, NavigationExpansionExpressionState state) in D:\code\EntityFrameworkCore\src\EFCore\Query\NavigationExpansion\Visitors\NavigationExpandingVisitor_MethodCall.cs:line 1238
   at Microsoft.EntityFrameworkCore.Query.NavigationExpansion.Visitors.NavigationExpandingVisitor.ProcessSelectCore(Expression source, NavigationExpansionExpressionState state, LambdaExpression selector, Type resultType) in D:\code\EntityFrameworkCore\src\EFCore\Query\NavigationExpansion\Visitors\NavigationExpandingVisitor_MethodCall.cs:line 215
   at Microsoft.EntityFrameworkCore.Query.NavigationExpansion.Visitors.NavigationExpandingVisitor.ProcessSelect(MethodCallExpression methodCallExpression) in D:\code\EntityFrameworkCore\src\EFCore\Query\NavigationExpansion\Visitors\NavigationExpandingVisitor_MethodCall.cs:line 210
   at Microsoft.EntityFrameworkCore.Query.NavigationExpansion.Visitors.NavigationExpandingVisitor.VisitMethodCall(MethodCallExpression methodCallExpression) in D:\code\EntityFrameworkCore\src\EFCore\Query\NavigationExpansion\Visitors\NavigationExpandingVisitor_MethodCall.cs:line 42
   at Microsoft.EntityFrameworkCore.Query.NavigationExpansion.NavigationExpander.ExpandNavigations(Expression expression) in D:\code\EntityFrameworkCore\src\EFCore\Query\NavigationExpansion\NavigationExpander.cs:line 25
   at Microsoft.EntityFrameworkCore.Query.Pipeline.QueryOptimizer.Visit(Expression query) in D:\code\EntityFrameworkCore\src\EFCore\Query\Pipeline\QueryOptimizingExpressionVisitor.cs:line 26
   at Microsoft.EntityFrameworkCore.Query.Pipeline.QueryCompilationContext.CreateQueryExecutor[TResult](Expression query) in D:\code\EntityFrameworkCore\src\EFCore\Query\Pipeline\QueryCompilationContext2.cs:line 58
   at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](Expression query, Boolean async) in D:\code\EntityFrameworkCore\src\EFCore\Storage\Database.cs:line 72
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async) in D:\code\EntityFrameworkCore\src\EFCore\Query\Internal\QueryCompiler.cs:line 108
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass12_0`1.<ExecuteAsync>b__0() in D:\code\EntityFrameworkCore\src\EFCore\Query\Internal\QueryCompiler.cs:line 141
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQueryCore[TFunc](Object cacheKey, Func`1 compiler) in D:\code\EntityFrameworkCore\src\EFCore\Query\Internal\CompiledQueryCache.cs:line 84
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler) in D:\code\EntityFrameworkCore\src\EFCore\Query\Internal\CompiledQueryCache.cs:line 59
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteAsync[TResult](Expression query, CancellationToken cancellationToken) in D:\code\EntityFrameworkCore\src\EFCore\Query\Internal\QueryCompiler.cs:line 137
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.ExecuteAsync[TResult](Expression expression, CancellationToken cancellationToken) in D:\code\EntityFrameworkCore\src\EFCore\Query\Internal\EntityQueryProvider.cs:line 98
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1.GetAsyncEnumerator(CancellationToken cancellationToken) in D:\code\EntityFrameworkCore\src\EFCore\Query\Internal\EntityQueryable`.cs:line 112
   at System.Runtime.CompilerServices.ConfiguredCancelableAsyncEnumerable`1.GetAsyncEnumerator()
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken) in D:\code\EntityFrameworkCore\src\EFCore\Extensions\EntityFrameworkQueryableExtensions.cs:line 2133
   at Microsoft.EntityFrameworkCore.Query.AsyncSimpleQueryTestBase`1.ToArray_on_nav_subquery_in_projection() in D:\code\EntityFrameworkCore\test\EFCore.Specification.Tests\Query\AsyncSimpleQueryTestBase.cs:line 86
--- End of stack trace from previous location where exception was thrown ---
```

**Comment by maumar** [comment]
problem here is that when we rewrite collection navigations into subqueries, we remove MaterializeCollectionNavigation metadata (effectively making it IQueryable<T>) if the collection is wrapped around a method call. We should only do that if the caller/argument slot for which the collection is used is IQueryable itself, otherwise we should materialize the collection to keep the types consistent.
