### ISSUE TITLE
Loading owned object fails

### ISSUE THREAD

**Issue by IvanZheng** [aspnet/EntityFrameworkCore#16188]
Lazy Loading owned object and `Entry(entity).Reference(e => e.OwnedObject).LoadAsync()` are failed.  Only `dbContext.DbSet.Include(e => e.OwnedObject).FirstOrDefaultAsync()` works.

BTW, they fail on  EF Core version: 3.0.0-preview6.19304.10 but work on EntityFramerworkCore 3.0.0-preview5.19227.1.

```
Exception message:
Cannot create a DbSet for 'UserProfile' because it is configured as an owned entity type and should be accessed through the defining entities.
Stack trace:
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.get_EntityType()
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.get_EntityQueryable()
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.System.Linq.IQueryable.get_Provider()
   at System.Linq.Queryable.Where[TSource](IQueryable`1 source, Expression`1 predicate)
   at Microsoft.EntityFrameworkCore.Internal.EntityFinder`1.Query(INavigation navigation, Object[] keyValues)
   at Microsoft.EntityFrameworkCore.Internal.EntityFinder`1.Load(INavigation navigation, InternalEntityEntry entry)
   at Microsoft.EntityFrameworkCore.Internal.LazyLoader.Load(Object entity, String navigationName)
   at Microsoft.EntityFrameworkCore.Proxies.Internal.LazyLoadingInterceptor.Intercept(IInvocation invocation)
   at Castle.DynamicProxy.AbstractInvocation.Proceed()
   at Castle.Proxies.UserProxy.get_UserProfile()
```

### Further technical details
EF Core version: 3.0.0-preview6.19304.10
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: 
IDE: (e.g. Visual Studio 2019 16.1.3)

**Comment by ibasin** [comment]
I ran into the same issue and am waiting for the resolution (hopefully soon).

While at it, I think it might be useful to remove the current requirement (which I think is a bug) to mark Owned type properties as virtual if Lazy Loading is enabled. I think the bug might even be related to treating Owned properties as Nav properties when lazy loading is enabled.

Just my 2 cents...

**Comment by ibasin** [comment]
Just wondering if this issue has been fixed. It seems to be still open.

**Comment by AndriySvyryd** [comment]
@ibasin This hasn't been fixed yet and we currently can't provide an estimate as to when it will be.

**Comment by AndriySvyryd** [comment]
Related to https://github.com/aspnet/EntityFrameworkCore/issues/16186

**Comment by IvanZheng** [comment]
@AndriySvyryd It works with "EF Core 3.0.0-rc1.19456.14" .  But Entry.Reload doesn't reload owned objects #16186 .

**Comment by AndriySvyryd** [comment]
Good to hear

**Comment by ibasin** [comment]
Thank you!
