### ISSUE TITLE
Query: conditional operator with type check throws InvalidOperationException

### ISSUE THREAD

**Issue by roji** [aspnet/EntityFrameworkCore#16335]
The following throws InvalidOperationException:

```c#
var rssBlog = context.Set<Blog>()
    .Where(x => x is Blog ? false : true)
    .ToList();
```

Exception:

```
System.InvalidOperationException : Operation is not valid due to the current state of the object.
   at Microsoft.EntityFrameworkCore.Relational.Query.Pipeline.RelationalQueryableMethodTranslatingExpressionVisitor.TranslateWhere(ShapedQueryExpression source, LambdaExpression predicate) in /home/roji/projects/EFCore/src/EFCore.Relational/Query/Pipeline/RelationalQueryableMethodTranslatingExpressionVisitor.cs:line 814
   at Microsoft.EntityFrameworkCore.Query.Pipeline.QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression) in /home/roji/projects/EFCore/src/EFCore/Query/Pipeline/QueryableMethodTranslatingExpressionVisitor.cs:line 425
   at Microsoft.EntityFrameworkCore.Relational.Query.Pipeline.RelationalQueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression) in /home/roji/projects/EFCore/src/EFCore.Relational/Query/Pipeline/RelationalQueryableMethodTranslatingExpressionVisitor.cs:line 61
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.Pipeline.QueryCompilationContext.CreateQueryExecutor[TResult](Expression query) in /home/roji/projects/EFCore/src/EFCore/Query/Pipeline/QueryCompilationContext.cs:line 58
   at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](Expression query, Boolean async) in /home/roji/projects/EFCore/src/EFCore/Storage/Database.cs:line 72
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async) in /home/roji/projects/EFCore/src/EFCore/Query/Internal/QueryCompiler.cs:line 108
```

Confirmed on 4f1f0191f5c4ed86aeab5e5f590a4c8323bf90db

**Comment by smitpatel** [comment]
Assigning to @roji 
`x is Blog` is EntityReferenceExpression in the tree at translation pipeline. It should have been removed earlier.

**Comment by smitpatel** [comment]
```C#
[ConditionalTheory]
        [MemberData(nameof(IsAsyncData))]
        public virtual Task Where_is_conditional(bool isAsync)
        {
            var customer = new Customer();

            return AssertQuery<Product>(
                isAsync,
                ps => ps.Where(p => p is Product ? false : true));
        }
```
