### ISSUE TITLE
Translate array access on array mapped as property

### ISSUE THREAD

**Issue by ajcvickers** [aspnet/EntityFrameworkCore#16428]
Query
```C#
productPhotos.Single(e => e.Photo[0] == 101);
```

where `Photo` is a `byte[]` property.

See `MonsterFixupTestBase`

Currently throws:
```
Microsoft.EntityFrameworkCore.MonsterFixupChangedChangingSqlServerTest.Can_build_monster_model_and_seed_data_using_FKs

System.InvalidOperationException : Unsupported Binary operator type specified.
   at Microsoft.EntityFrameworkCore.Relational.Query.Pipeline.SqlExpressions.SqlBinaryExpression.VerifyOperator(ExpressionType operatorType) in C:\aspnet\EntityFrameworkCore\src\EFCore.Relational\Query\Pipeline\SqlExpressions\SqlBinaryExpression.cs:line 41
   at Microsoft.EntityFrameworkCore.Relational.Query.Pipeline.SqlExpressions.SqlBinaryExpression..ctor(ExpressionType operatorType, SqlExpression left, SqlExpression right, Type type, RelationalTypeMapping typeMapping) in C:\aspnet\EntityFrameworkCore\src\EFCore.Relational\Query\Pipeline\SqlExpressions\SqlBinaryExpression.cs:line 56
   at Microsoft.EntityFrameworkCore.Relational.Query.Pipeline.SqlExpressionFactory.MakeBinary(ExpressionType operatorType, SqlExpression left, SqlExpression right, RelationalTypeMapping typeMapping) in C:\aspnet\EntityFrameworkCore\src\EFCore.Relational\Query\Pipeline\SqlExpressionFactory.cs:line 231
   at Microsoft.EntityFrameworkCore.Relational.Query.Pipeline.RelationalSqlTranslatingExpressionVisitor.VisitBinary(BinaryExpression binaryExpression) in C:\aspnet\EntityFrameworkCore\src\EFCore.Relational\Query\Pipeline\RelationalSqlTranslatingExpressionVisitor.cs:line 438
   at Microsoft.EntityFrameworkCore.SqlServer.Query.Pipeline.SqlServerSqlTranslatingExpressionVisitor.VisitBinary(BinaryExpression binaryExpression) in C:\aspnet\EntityFrameworkCore\src\EFCore.SqlServer\Query\Pipeline\SqlServerSqlTranslatingExpressionVisitor.cs:line 50
   at System.Linq.Expressions.BinaryExpression.Accept(ExpressionVisitor visitor)
   at Microsoft.EntityFrameworkCore.Relational.Query.Pipeline.RelationalSqlTranslatingExpressionVisitor.VisitBinary(BinaryExpression binaryExpression) in C:\aspnet\EntityFrameworkCore\src\EFCore.Relational\Query\Pipeline\RelationalSqlTranslatingExpressionVisitor.cs:line 429
   at Microsoft.EntityFrameworkCore.SqlServer.Query.Pipeline.SqlServerSqlTranslatingExpressionVisitor.VisitBinary(BinaryExpression binaryExpression) in C:\aspnet\EntityFrameworkCore\src\EFCore.SqlServer\Query\Pipeline\SqlServerSqlTranslatingExpressionVisitor.cs:line 50
   at System.Linq.Expressions.BinaryExpression.Accept(ExpressionVisitor visitor)
   at Microsoft.EntityFrameworkCore.Relational.Query.Pipeline.RelationalSqlTranslatingExpressionVisitor.Translate(Expression expression) in C:\aspnet\EntityFrameworkCore\src\EFCore.Relational\Query\Pipeline\RelationalSqlTranslatingExpressionVisitor.cs:line 46
   at Microsoft.EntityFrameworkCore.Relational.Query.Pipeline.RelationalQueryableMethodTranslatingExpressionVisitor.TranslateExpression(Expression expression) in C:\aspnet\EntityFrameworkCore\src\EFCore.Relational\Query\Pipeline\RelationalQueryableMethodTranslatingExpressionVisitor.cs:line 872
   at Microsoft.EntityFrameworkCore.Relational.Query.Pipeline.RelationalQueryableMethodTranslatingExpressionVisitor.TranslateLambdaExpression(ShapedQueryExpression shapedQueryExpression, LambdaExpression lambdaExpression) in C:\aspnet\EntityFrameworkCore\src\EFCore.Relational\Query\Pipeline\RelationalQueryableMethodTranslatingExpressionVisitor.cs:line 880
   at Microsoft.EntityFrameworkCore.Relational.Query.Pipeline.RelationalQueryableMethodTranslatingExpressionVisitor.TranslateWhere(ShapedQueryExpression source, LambdaExpression predicate) in C:\aspnet\EntityFrameworkCore\src\EFCore.Relational\Query\Pipeline\RelationalQueryableMethodTranslatingExpressionVisitor.cs:line 859
   at Microsoft.EntityFrameworkCore.Query.Pipeline.QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression) in C:\aspnet\EntityFrameworkCore\src\EFCore\Query\Pipeline\QueryableMethodTranslatingExpressionVisitor.cs:line 424
   at Microsoft.EntityFrameworkCore.Relational.Query.Pipeline.RelationalQueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression) in C:\aspnet\EntityFrameworkCore\src\EFCore.Relational\Query\Pipeline\RelationalQueryableMethodTranslatingExpressionVisitor.cs:line 61
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at Microsoft.EntityFrameworkCore.Query.Pipeline.QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression) in C:\aspnet\EntityFrameworkCore\src\EFCore\Query\Pipeline\QueryableMethodTranslatingExpressionVisitor.cs:line 33
   at Microsoft.EntityFrameworkCore.Relational.Query.Pipeline.RelationalQueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression) in C:\aspnet\EntityFrameworkCore\src\EFCore.Relational\Query\Pipeline\RelationalQueryableMethodTranslatingExpressionVisitor.cs:line 61
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at Microsoft.EntityFrameworkCore.Query.Pipeline.QueryCompilationContext.CreateQueryExecutor[TResult](Expression query) in C:\aspnet\EntityFrameworkCore\src\EFCore\Query\Pipeline\QueryCompilationContext.cs:line 65
   at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](Expression query, Boolean async) in C:\aspnet\EntityFrameworkCore\src\EFCore\Storage\Database.cs:line 72
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async) in C:\aspnet\EntityFrameworkCore\src\EFCore\Query\Internal\QueryCompiler.cs:line 108
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass9_0`1.<Execute>b__0() in C:\aspnet\EntityFrameworkCore\src\EFCore\Query\Internal\QueryCompiler.cs:line 97
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQueryCore[TFunc](Object cacheKey, Func`1 compiler) in C:\aspnet\EntityFrameworkCore\src\EFCore\Query\Internal\CompiledQueryCache.cs:line 84
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler) in C:\aspnet\EntityFrameworkCore\src\EFCore\Query\Internal\CompiledQueryCache.cs:line 59
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query) in C:\aspnet\EntityFrameworkCore\src\EFCore\Query\Internal\QueryCompiler.cs:line 93
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression) in C:\aspnet\EntityFrameworkCore\src\EFCore\Query\Internal\EntityQueryProvider.cs:line 79
   at System.Linq.Queryable.Single[TSource](IQueryable`1 source, Expression`1 predicate)
   at Microsoft.EntityFrameworkCore.MonsterFixupTestBase`1.FkVerification() in C:\aspnet\EntityFrameworkCore\test\EFCore.Specification.Tests\MonsterFixupTestBase.cs:line 1038
   at Microsoft.EntityFrameworkCore.MonsterFixupTestBase`1.Can_build_monster_model_and_seed_data_using_FKs() in C:\aspnet\EntityFrameworkCore\test\EFCore.Specification.Tests\MonsterFixupTestBase.cs:line 37

```

**Comment by smitpatel** [comment]
@ajcvickers - What should be SQL translation of this?

**Comment by ajcvickers** [comment]
@smitpatel You're asking the wrong person! @roji? @bricelam? @maumar? (Ideally I would be pinging Diego!)

**Comment by bricelam** [comment]
SQLite:
```sql
substr(e.Photo, 0, 1) = x'65'
```

**Comment by roji** [comment]
[SUBSTRING also works on binary/varbinary](https://docs.microsoft.com/en-us/sql/t-sql/functions/substring-transact-sql?view=sql-server-ver15) (although a cast/convert may need to be applied to get a tinyint out.

(am I an SQL Server guy now??)

**Comment by smitpatel** [comment]
@bricelam - I tried producing following SQL both of them failed.
```SQL
SELECT "p"."PhotoId", "p"."Photo", "p"."ProductId"
FROM "ProductPhoto" AS "p"
WHERE substr("p"."Photo", 0 + 1, 1) = 101
LIMIT 2
```
found no matching records
```SQL
SELECT "p"."PhotoId", "p"."Photo", "p"."ProductId"
FROM "ProductPhoto" AS "p"
WHERE substr("p"."Photo", 0 + 1, 1) = x'101'
LIMIT 2
```
invalid token x'101'
There is matching record at least when evaluated on client. What could be going wrong?

**Comment by smitpatel** [comment]
@roji - You are SqlServer guy now since your tip helped resolve this issue for SqlServer.

**Comment by bricelam** [comment]
Blob literals are hex encoded:

```sql
SELECT "p"."PhotoId", "p"."Photo", "p"."ProductId"
FROM "ProductPhoto" AS "p"
WHERE substr("p"."Photo", 0 + 1, 1) = x'65'
LIMIT 2
```

**Comment by bricelam** [comment]
Unfortunately, casting either side doesn't seem to work.
```
sqlite> SELECT CAST(101 AS BLOB) = x'65';
0
sqlite> SELECT 101 = CAST(x'65' AS INTEGER);
0
```

**Comment by bricelam** [comment]
`unicode` kind of works, until it tries to interpret 2-byte characters:
```
sqlite> SELECT unicode(x'65') = 101;
1
sqlite> SELECT unicode(substr(x'c0', 1, 1)) = 192;
0
```

**Comment by smitpatel** [comment]
@bricelam - What would be solution? I updated SqlServer. SUBSTR gives byte[] and conversion to byte on top of it works fine.
Sqlite - I indeed tried same conversion and even unicode but unicode failed as you said in a different place in the test. there is hex function which can give hex code but how to convert that to int?

**Comment by bricelam** [comment]
I think we’d need to translate the specific pattern—not just the array access. Like a binary operation with array access on one side and a constant on the other.

**Comment by bricelam** [comment]
We could also add our own UDF to convert from BLOB correctly.

**Comment by smitpatel** [comment]
The pattern match can be done but it would only work for constants. It won't work for parameters or a byte column. Hence I was looking into making the return value of substr byte rather than making both side byte[].
