### ISSUE TITLE
Index was outside the bounds of the array.

### ISSUE THREAD

**Issue by sam-wheat** [aspnet/EntityFrameworkCore#16756]
Index was outside the bounds of the array.

EF Core 2.2.6
.net Framework 4.7.2
MS Sql Server
Windows 10
Visual Studio 2017 latest

Please let me know if you need more info I will provide a project.

	public async Task<List<WatchList>> GetWatchListGraphsForUser(int userID)
        {
        
            var subQuery = from wli in db.WatchListItems
                           join s in db.Series on new { n = wli.NativeID, d = wli.DataProviderID } equals new { n = s.Symbol, d = s.DataProviderID }
                         
                           select new WatchListItem
                           {
                               ID = wli.ID,
                               DataProviderID = wli.DataProviderID,
                               NativeID = wli.NativeID,
                               WatchListID = wli.WatchListID,
                               DataProvider = wli.DataProvider,
                               Series = s
                           };

            var query = from wl in db.WatchLists.Include(x => x.DataProvider)
                        join wli in subQuery on wl.ID equals wli.WatchListID
                        where wl.UserID == userID
                        orderby wl.Name
                        select wl;

            return await query.ToListAsync();

        }

		at lambda_method(Closure , ValueBuffer )
		at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.SimplePrincipalKeyValueFactory`1.CreateFromBuffer(ValueBuffer valueBuffer)
		at Microsoft.EntityFrameworkCore.Query.Internal.WeakReferenceIdentityMap`1.TryGetEntity(ValueBuffer& valueBuffer, Boolean throwOnNullKey, Boolean& hasNullKey)
		at Microsoft.EntityFrameworkCore.Query.Internal.WeakReferenceIdentityMap`1.Microsoft.EntityFrameworkCore.Query.Internal.IWeakReferenceIdentityMap.TryGetEntity(ValueBuffer& valueBuffer, Boolean throwOnNullKey, Boolean& hasNullKey)
		at Microsoft.EntityFrameworkCore.Query.Internal.QueryBuffer.GetEntity(IKey key, EntityLoadInfo entityLoadInfo, Boolean queryStateManager, Boolean throwOnNullKey)
		at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.BufferedEntityShaper`1.Shape(QueryContext queryContext, ValueBuffer& valueBuffer)
		at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.BufferedOffsetEntityShaper`1.Shape(QueryContext queryContext, ValueBuffer& valueBuffer)
		at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.CompositeShaper.TypedCompositeShaper`5.Shape(QueryContext queryContext, ValueBuffer& valueBuffer)
		at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.CompositeShaper.TypedCompositeShaper`5.Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.IShaper<TResult>.Shape(QueryContext queryContext, ValueBuffer& valueBuffer)
		at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.CompositeShaper.TypedCompositeShaper`5.Shape(QueryContext queryContext, ValueBuffer& valueBuffer)
		at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.CompositeShaper.TypedCompositeShaper`5.Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.IShaper<TResult>.Shape(QueryContext queryContext, ValueBuffer& valueBuffer)
		at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.ProjectionShaper.TypedProjectionShaper`3.Shape(QueryContext queryContext, ValueBuffer& valueBuffer)
		at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.ProjectionShaper.TypedProjectionShaper`3.Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.IShaper<TOut>.Shape(QueryContext queryContext, ValueBuffer& valueBuffer)
		at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.CompositeShaper.TypedCompositeShaper`5.Shape(QueryContext queryContext, ValueBuffer& valueBuffer)
		at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.CompositeShaper.TypedCompositeShaper`5.Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.IShaper<TResult>.Shape(QueryContext queryContext, ValueBuffer& valueBuffer)
		at Microsoft.EntityFrameworkCore.Query.Internal.AsyncQueryingEnumerable`1.AsyncEnumerator.<BufferlessMoveNext>d__12.MoveNext()
		--- End of stack trace from previous location where exception was thrown ---
		at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
		at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
		at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.<ExecuteAsync>d__7`2.MoveNext()
		--- End of stack trace from previous location where exception was thrown ---
		at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
		at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
		at Microsoft.EntityFrameworkCore.Query.Internal.AsyncQueryingEnumerable`1.AsyncEnumerator.<MoveNext>d__11.MoveNext()
		--- End of stack trace from previous location where exception was thrown ---
		at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
		at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
		at System.Linq.AsyncEnumerable.SelectEnumerableAsyncIterator`2.<MoveNextCore>d__7.MoveNext() in D:\a\1\s\Ix.NET\Source\System.Interactive.Async\Select.cs:line 106
		--- End of stack trace from previous location where exception was thrown ---
		at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
		at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
		at System.Linq.AsyncEnumerable.AsyncIterator`1.<MoveNext>d__10.MoveNext() in D:\a\1\s\Ix.NET\Source\System.Interactive.Async\AsyncIterator.cs:line 109
		--- End of stack trace from previous location where exception was thrown ---
		at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
		at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
		at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.<MoveNext>d__5.MoveNext()
		--- End of stack trace from previous location where exception was thrown ---
		at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
		at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
		at System.Linq.AsyncEnumerable.<Aggregate_>d__6`3.MoveNext() in D:\a\1\s\Ix.NET\Source\System.Interactive.Async\Aggregate.cs:line 120
		--- End of stack trace from previous location where exception was thrown ---
		at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
		at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
		at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
		at LeaderAnalytics.FF.Services.WatchListService.<GetWatchListGraphsForUser>d__1.MoveNext() in C:\Git\LeaderAnalytics.ForecastFramework\LeaderAnalytics.FF.Services\WatchListService.cs:line 59
		--- End of stack trace from previous location where exception was thrown ---
		at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
		at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
		at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
		at LeaderAnalytics.AdaptiveClient.Autofac.AdaptiveClient`1.<CallAsync>d__9`1.MoveNext()
		--- End of stack trace from previous location where exception was thrown ---
		at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
		at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
		at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
		at LeaderAnalytics.WPF.FF.DataManager.VVM.WatchListEditorViewModel.<Initialize>d__10.MoveNext() in C:\Git\LeaderAnalytics.ForecastFramework\LeaderAnalytics.WPF.FF.Vintages.DataManager\VVM\WatchListEditorViewModel.cs:line 63
		--- End of stack trace from previous location where exception was thrown ---
		at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
		at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
		at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
		at LeaderAnalytics.WPF.FF.DataManager.VVM.WatchListEditor.<Initialize>d__2.MoveNext() in C:\Git\LeaderAnalytics.ForecastFramework\LeaderAnalytics.WPF.FF.Vintages.DataManager\VVM\WatchListEditor.xaml.cs:line 41
		--- End of stack trace from previous location where exception was thrown ---
		at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
		at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
		at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
		at LeaderAnalytics.WPF.FF.DataManager.MainWindowViewModel.<WatchlistCommandHandler>d__76.MoveNext() in C:\Git\LeaderAnalytics.ForecastFramework\LeaderAnalytics.WPF.FF.Vintages.DataManager\MainWindowViewModel.cs:line 182
		--- End of stack trace from previous location where exception was thrown ---
		at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
		at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
		at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
		at LeaderAnalytics.FF.Vintages.Components.DelegateCommandAsync`1.<ExecuteAsync>d__7.MoveNext() in C:\Git\LeaderAnalytics.ForecastFramework\LeaderAnalytics.FF.Vintages.Components\DelegateCommandAsync.cs:line 53
		--- End of stack trace from previous location where exception was thrown ---
		at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
		at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
		at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
		at LeaderAnalytics.FF.Vintages.Components.DelegateCommandAsync`1.<Execute>d__12.MoveNext() in C:\Git\LeaderAnalytics.ForecastFramework\LeaderAnalytics.FF.Vintages.Components\DelegateCommandAsync.cs:line 78

**Comment by ajcvickers** [comment]
@sam-wheat Please post a small, runnable project/solution or complete code listing that reproduces the behavior you are seeing.

**Comment by sam-wheat** [comment]
@ajcvickers 
Thanks Arthur -   Attached project illustrates a couple different errors I ran into.  [This is not my first time in the ring](https://github.com/aspnet/EntityFrameworkCore/issues/13787) with this query.  I continue to struggle with it.  I cannot find any reasonable way to produce a fully populated `WatchList` entity.

Thanks for your help.


[WatchListQuery.zip](https://github.com/aspnet/EntityFrameworkCore/files/3438561/WatchListQuery.zip)

**Comment by ajcvickers** [comment]
Closing as the exception is no longer thrown with EF Core 3.1 preview 3.
