### ISSUE TITLE
Error comparing byte array of different size in primary key with Add or Update then SaveChanges

### ISSUE THREAD

**Issue by jjxtra** [aspnet/EntityFrameworkCore#16888]
### Problem
I am unable to Add and/or Update multiple entity objects when there are byte array primary key columns and the data in those columns have different lengths.

### Exception
```
2019-08-01 09:35:36.3451|WARN|DigitalRuby.IPBan.IPBanLog|DB error, ip 99.99.99.99, source RDP, user: , source ip: 2001:3ba0:cafe:44c::1 System.InvalidOperationException: Failed to compare two elements in the array. ---> System.ArgumentException: Object is not a array with the same number of elements as the array to compare it to.
Parameter name: other
   at System.Array.System.Collections.IStructuralComparable.CompareTo(Object other, IComparer comparer)
   at System.Collections.StructuralComparer.Compare(Object x, Object y)
   at Microsoft.EntityFrameworkCore.Update.Internal.ModificationCommandComparer.CompareStructureValue[T](T x, T y)
   at lambda_method(Closure , Object , Object )
   at Microsoft.EntityFrameworkCore.Update.Internal.ModificationCommandComparer.Compare(ModificationCommand x, ModificationCommand y)
   at System.Collections.Generic.ArraySortHelper`1.SwapIfGreater(T[] keys, Comparison`1 comparer, Int32 a, Int32 b)
   at System.Collections.Generic.ArraySortHelper`1.IntroSort(T[] keys, Int32 lo, Int32 hi, Int32 depthLimit, Comparison`1 comparer)
   at System.Collections.Generic.ArraySortHelper`1.IntrospectiveSort(T[] keys, Int32 left, Int32 length, Comparison`1 comparer)
   at System.Collections.Generic.ArraySortHelper`1.Sort(T[] keys, Int32 index, Int32 length, IComparer`1 comparer)
   --- End of inner exception stack trace ---
   at System.Collections.Generic.ArraySortHelper`1.Sort(T[] keys, Int32 index, Int32 length, IComparer`1 comparer)
   at System.Array.Sort[T](T[] array, Int32 index, Int32 length, IComparer`1 comparer)
   at System.Collections.Generic.List`1.Sort(Int32 index, Int32 count, IComparer`1 comparer)
   at Microsoft.EntityFrameworkCore.Update.Internal.CommandBatchPreparer.BatchCommands(IReadOnlyList`1 entries)+MoveNext()
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(DbContext _, ValueTuple`2 parameters, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IReadOnlyList`1 entriesToSave, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
```

### Details
The primary key has a timestamp, blob and blob field (datetime, ip, source ip). Both columns in the database have blobs of 4 and 16 byte lengths from a previous data import. So it's either having the two columns being inserted be different lengths, or having existing data in the database that has blobs of different lengths from that which is being inserted. Either way I see no way to get at this compare method and change it which is frustrating.

### Steps to reproduce
Attempt to insert two entity framework object with a primary key that has byte arrays. Set the byte arrays to different lengths in the two objects. Using sqlite provider but also reproduces with sql server.

Using latest .NET core 2.2 as of 2019-07-30.

### Expected behavior
Different array lengths should compare just fine when multiple objects are Added or Updated, this seems like a serious bug.

### Workaround
Calling SaveChanges for each individual object after each add/update seems to resolve the issue. Having them all Added or Updated without calling SaveChanges appears to be the source of the bug.

**Comment by jjxtra** [comment]
My primary key:

```
        public DateTime Timestamp { get; set; }

        [MinLength(4)]
        [MaxLength(16)]
        public byte[] IPAddressId { get; set; }

        [MinLength(4)]
        [MaxLength(16)]
        public byte[] SourceIPAddressId { get; set; }
```

**Comment by ajcvickers** [comment]
Note for triage: didn't occur to me that this would throw...
```C#
var x = new byte[4];
var y = new byte[5];
StructuralComparisons.StructuralComparer.Compare(x, y);
```

**Comment by jjxtra** [comment]
You got it, the bug is that simple I believe
