### ISSUE TITLE
ArgumentException when querying entity with nested owned entities

### ISSUE THREAD

**Issue by langebo** [aspnet/EntityFrameworkCore#17207]
Using preview8 of ASP.NET Core and EF Core I am getting an ArgumentException when I try to query an entity, that has owned entities, which has owned entities itself. While I am able to create this kind of entity, and insert it into the database, I can't retrieve it from the database, or even query for existence using `.AnyAsync()` / `FirstOrDefaultAsync()` or even `Meetings.ToListAsync()` or their synchronous counterparts.

In case you want to try out the whole project, it can be found here: https://github.com/langebo/meetme

Exception message:
```c#
Expression of type 'System.Collections.Generic.List`1[MeetMe.Domain.Models.Proposal]' cannot be used for parameter of type 'System.Linq.IQueryable`1[MeetMe.Domain.Models.Proposal]' of method 'System.Linq.IQueryable`1[MeetMe.Domain.Models.Proposal] Select[Proposal,Proposal](System.Linq.IQueryable`1[MeetMe.Domain.Models.Proposal], System.Linq.Expressions.Expression`1[System.Func`2[MeetMe.Domain.Models.Proposal,MeetMe.Domain.Models.Proposal]])' (Parameter 'arg0')
```

Stack trace:
```c#
at System.Dynamic.Utils.ExpressionUtils.ValidateOneArgument(MethodBase method, ExpressionType nodeKind, Expression arguments, ParameterInfo pi, String methodParamName, String argumentParamName, Int32 index)
   at System.Linq.Expressions.Expression.Call(MethodInfo method, Expression arg0, Expression arg1)
   at Microsoft.EntityFrameworkCore.Query.NavigationExpansion.Internal.NavigationExpansionReducingVisitor.VisitExtension(Expression extensionExpression)
   at System.Linq.Expressions.Expression.Accept(ExpressionVisitor visitor)
   at Microsoft.EntityFrameworkCore.Query.NavigationExpansion.Internal.NavigationPropertyUnbindingVisitor.VisitExtension(Expression extensionExpression)
   at System.Linq.Expressions.Expression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.IncludeExpression.VisitChildren(ExpressionVisitor visitor)
   at System.Linq.Expressions.Expression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at System.Linq.Expressions.ExpressionVisitor.VisitLambda[T](Expression`1 node)
   at System.Linq.Expressions.Expression`1.Accept(ExpressionVisitor visitor)
   at Microsoft.EntityFrameworkCore.Query.NavigationExpansion.Internal.NavigationExpansionReducingVisitor.VisitExtension(Expression extensionExpression)
   at System.Linq.Expressions.Expression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at System.Dynamic.Utils.ExpressionVisitorUtils.VisitArguments(ExpressionVisitor visitor, IArgumentProvider nodes)
   at System.Linq.Expressions.ExpressionVisitor.VisitMethodCall(MethodCallExpression node)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.QueryOptimizer.Visit(Expression query)
   at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.CreateQueryExecutor[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](Expression query, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass12_0`1.<ExecuteAsync>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQueryCore[TFunc](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteAsync[TResult](Expression query, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.ExecuteAsync[TResult](Expression expression, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ExecuteAsync[TSource,TResult](MethodInfo operatorMethodInfo, IQueryable`1 source, Expression expression, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ExecuteAsync[TSource,TResult](MethodInfo operatorMethodInfo, IQueryable`1 source, LambdaExpression expression, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.AnyAsync[TSource](IQueryable`1 source, Expression`1 predicate, CancellationToken cancellationToken)
   at MeetMe.Application.Validators.GetMeetingValidator.<MeetingExists>d__2.MoveNext() in C:\dev\private\MeetMe\MeetMe.Application\Validators\GetMeetingValidator.cs:line 23
```

### Steps to reproduce
These are the entities:
```c#
    public class Meeting
    {
        public Guid Id { get; set; }
        public string Title { get; set; }
        public List<Proposal> Proposals { get; set; }

        public Meeting()
        {
            Proposals = new List<Proposal>();
        }
    }
```
```c#
    public class Proposal
    {
        public Guid Id { get; set; }
        public DateTimeOffset Time { get; set; }
        public List<Vote> Votes { get; set; }

        public Proposal()
        {
            Votes = new List<Vote>();
        }
    }
```
```c#
    public class Vote
    {
        public Guid Id { get; set; }
        public string Username { get; set; }
    }
```

This is the DbContext:
```c#
    public class MeetingsContext : DbContext
    {
        public DbSet<Meeting> Meetings { get; set; }

        public MeetingsContext(DbContextOptions<MeetingsContext> options) : base(options) { }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Meeting>()
                .OwnsMany(
                    m => m.Proposals, 
                    mp => mp.OwnsMany(p => p.Votes));
        }
    }
```
These calls will lead to the aforementioned exception:
```c#
    public async Task<Meeting> Handle(GetMeetingQuery request, CancellationToken cancellationToken)
    {
        return await db.Meetings
            .Include(m => m.Proposals)
            .ThenInclude(p => p.Votes)
            .AsNoTracking()
            .FirstOrDefaultAsync(m => m.Id == request.Id, cancellationToken);
    }
```
```c#
    private async Task<bool> MeetingExists(Guid id, CancellationToken ct) => 
        await db.Meetings
            .AsNoTracking()
            .AnyAsync(m => m.Id == id, ct);
```

### Further technical details
EF Core version: 3.0.0-preview8.19405.11
Database Provider: Npgsql.EntityFrameworkCore.PostgreSQL 3.0.0-preview8 (also tested with Microsoft.EntityFrameworkCore.SqlServer 3.0.0-preview8.19405.11)
Operating system: Windows 10 Pro 1903 18362.295 (also tested on macOS Mojave 10.14.6)
IDE: Visual Studio 2019 16.2.2 (also tested with Visual Studio Code 1.37.0)

**Comment by Oposow** [comment]
I've got a similar error.

`public class User
	{
		public int Id { get; set; }

		public int? PartnerId { get; set; }
		public virtual Partner Partner { get; set; }

		public string FirstName { get; set; }
		public string LastName { get; set; }
	}`

`public class Partner
	{ 
		public int Id { get; set; }
		public string Name { get; set; }
		public Address Address { get; set; }
	}`

`	[Owned]
	public class Address
	{
		public string Street { get; set; }
		public string City { get; set; }
		public string PostalCode { get; set; }
	}`

When I try to create query 

`db.Users.Include(x => x.Partner)`
I got an error 
`'Address' is not a member of type 'RentChain.DAL.Entities.Users.RefreshToken' (Parameter 'propertyOrFieldName')`

Address it's a member of Partner which is included. If I remove this Include statement, the query compiles and executes successfully.

Full stack trace:

`2019-08-19 11:54:41.6775 ERROR RentChain.Base.NlogLogger Login: --- System.ArgumentException: 'Address' is not a member of type 'RentChain.DAL.Entities.Users.User' (Parameter 'propertyOrFieldName')
   at System.Linq.Expressions.Expression.PropertyOrField(Expression expression, String propertyOrFieldName)
   at Microsoft.EntityFrameworkCore.Internal.ExpressionExtensions.BuildPropertyAccess(Expression root, List`1 path, List`1 navigations)
   at Microsoft.EntityFrameworkCore.Query.NavigationExpansion.Internal.NavigationPropertyUnbindingVisitor.VisitExtension(Expression extensionExpression)
   at System.Linq.Expressions.Expression.Accept(ExpressionVisitor visitor)
   at Microsoft.EntityFrameworkCore.Query.IncludeExpression.VisitChildren(ExpressionVisitor visitor)
   at System.Linq.Expressions.Expression.Accept(ExpressionVisitor visitor)
   at Microsoft.EntityFrameworkCore.Query.IncludeExpression.VisitChildren(ExpressionVisitor visitor)
   at System.Linq.Expressions.Expression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.VisitLambda[T](Expression`1 node)
   at System.Linq.Expressions.Expression`1.Accept(ExpressionVisitor visitor)
   at Microsoft.EntityFrameworkCore.Query.NavigationExpansion.Internal.NavigationExpansionReducingVisitor.VisitExtension(Expression extensionExpression)
   at System.Linq.Expressions.Expression.Accept(ExpressionVisitor visitor)
   at Microsoft.EntityFrameworkCore.Query.QueryOptimizer.Visit(Expression query)
   at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.CreateQueryExecutor[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](Expression query, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass9_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQueryCore[TFunc](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
   at System.Linq.Queryable.FirstOrDefault[TSource](IQueryable`1 source, Expression`1 predicate)
   at RentChain.Base.Security.AuthorizationProvider.LoginUser(String login, String password) in C:\Projects\RentChain\rcc-api\Base\RentChain.Base\Security\AuthorizationProvider.cs:line 87
   at RentChain.API.Controllers.Authentication.JwtAuthenticationController.Login(LoginParams input) in C:\Projects\RentChain\rcc-api\API\RentChain.API\Controllers\Authentication\JwtAuthenticationController.cs:line 26
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at NSwag.AspNetCore.Middlewares.SwaggerUiIndexMiddleware.Invoke(HttpContext context)
   at NSwag.AspNetCore.Middlewares.RedirectToIndexMiddleware.Invoke(HttpContext context)
   at NSwag.AspNetCore.Middlewares.OpenApiDocumentMiddleware.Invoke(HttpContext context)
   at RentChain.API.Middlewares.OptionsMiddleware.Invoke(HttpContext context) in C:\Projects\RentChain\rcc-api\API\RentChain.API\Middlewares\OptionsMiddleware.cs:line 25
   at NSwag.AspNetCore.Middlewares.OpenApiDocumentMiddleware.Invoke(HttpContext context)
   at RentChain.API.Middlewares.ErrorHandlingMiddleware.Invoke(HttpContext context) in C:\Projects\RentChain\rcc-api\API\RentChain.API\Middlewares\ErrorHandlingMiddleware.cs:line 34 | AsyncMethodBuilderCore.Start => <Invoke>d__5.MoveNext => NlogLogger.Error`

**Comment by MattEllig** [comment]
Having the same issue as @Oposow with a very similar setup, also in the latest preview build.

**Comment by smitpatel** [comment]
2nd issue is certainly fixed in nightly builds. First may also been fixed.

**Comment by ajcvickers** [comment]
Both issues no longer repro against daily builds when using SQL Server.
