### ISSUE TITLE
Nullable object must have a value on optional foreign relationship.

### ISSUE THREAD

**Issue by xKloc** [aspnet/EntityFrameworkCore#17208]
I am trying to create a projection that contains an optional object that might not exist due to a nullable foreign key property.

When I create this projection with a null relationship, I am getting an exception.

```
Unhandled Exception: System.InvalidOperationException: Nullable object must have a value.
   at lambda_method(Closure , QueryContext , TransparentIdentifier`2 )
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.ProjectionShaper.TypedProjectionShaper`3.Shape(QueryContext queryContext, ValueBuffer& valueBuffer)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.BufferlessMoveNext(DbContext _, Boolean buffer)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
   at System.Collections.Generic.List`1.AddEnumerable(IEnumerable`1 enumerable)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at EFCoreNullableObject.Program.Main(String[] args) in C:\Users\admin\Source\Local\EFCoreNullableObject\EFCoreNullableObject\Program.cs:line 31
```

I would like the `Projection.Child.SubChild` object to be null when the relationship doesn't exist.

My entity is configured with a nullable foreign key Id, so I'm not sure why this isn't working. Also, I've tried checking if the `SubChildId` is null instead of the `SubChild` navigation property and that didn't work either.

### Steps to reproduce
```c#
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;

namespace EFCoreNullableObject
{
    class Program
    {
        static void Main(string[] args)
        {
            using(var context = new Context())
            {
                if (!context.Parents.Any())
                {
                    var child = new Child
                    {
                        ChildId = 1
                    };
                    var parent = new Parent
                    {
                        ParentId = 1,
                        ChildId = child.ChildId,
                        Child = child
                    };
                    context.Children.Add(child);
                    context.Parents.Add(parent);
                    context.SaveChanges();
                }

                var projection = context.Parents.Select(e => new Projection
                {
                    ParentId = e.ParentId,
                    Child = new Projection.ChildInfo
                    {
                        ChildId = e.ChildId,
                        SubChild = e.SubChild == null ? null : new Projection.SubChildInfo
                        {
                            ChildId = e.SubChild.ChildId,
                            SubChildId = e.SubChild.SubChildId
                        }
                    }
                }).ToList();
            }
        }
    }

    public class Parent
    {
        public int ParentId { get; set; }
        public int ChildId { get; set; }
        public int? SubChildId { get; set; }

        public Child Child { get; set; }
        public SubChild SubChild { get; set; }
    }

    public class Child
    {
        public Child()
        {
            SubChildren = new HashSet<SubChild>();
        }

        public int ChildId { get; set; }
        public ICollection<SubChild> SubChildren { get; set; }
    }

    public class SubChild
    {
        public int ChildId { get; set; }
        public int SubChildId { get; set; }
    }

    public class Context : DbContext
    {
        public DbSet<Parent> Parents { get; set; }
        public DbSet<Child> Children { get; set; }
        public DbSet<Parent> SubChildren { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseSqlServer(@"Server=(localdb)\mssqllocaldb;Database=EfCoreNullableObject;Integrated Security=True");
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Parent>(b =>
            {
                b.ToTable("Parents");
                b.HasOne(e => e.Child).WithMany().HasForeignKey(e => e.ChildId);
                b.HasOne(e => e.SubChild).WithMany().HasForeignKey(e => new { e.ChildId, e.SubChildId });
            });

            modelBuilder.Entity<Child>(b =>
            {
                b.ToTable("Children");
                b.HasMany(e => e.SubChildren).WithOne().HasForeignKey(e => e.ChildId);
            });

            modelBuilder.Entity<SubChild>(b =>
            {
                b.ToTable("SubChildren");
                b.HasKey(e => new { e.ChildId, e.SubChildId });
            });
        }
    }

    public class Projection
    {
        public int ParentId { get; set; }
        public ChildInfo Child { get; set; }

        public class ChildInfo
        {
            public int ChildId { get; set; }
            public SubChildInfo SubChild { get; set; }
        }

        public class SubChildInfo
        {
            public int ChildId { get; set; }
            public int SubChildId { get; set; }
        }
    }
}
```

### Further technical details
EF Core version: 2.2.6
Database Provider: Microsoft.EntityFrameworkCore.SqlServer

**Comment by smitpatel** [comment]
Possible cause of error
`e.SubChild == null` gets re-written into PK access. Since it is null comparison, we take only first property which gives us `e.SubChild.ChildId == null`
This in turn gets converted to FK access giving us, `e.ChildId == null` which is always false since the other FK property is null and not this one.

cc: @roji @ajcvickers @maumar 
When comparing only first property for PK & navigation.PK => FK optimization can cause error when combined together.

This works in "daily builds" as we have removed the latter optimization.
