### ISSUE TITLE
Concurrency Exception In Multithreaded API

### ISSUE THREAD

**Issue by TomNaN0** [aspnet/EntityFrameworkCore#17274]
### Description
Reading queries through EntityFrameworkCore crashes on concurrency exception even when dbContext is injected through Dependency Injection and each dependency is injected with new instance
```
Exception message: Operations that change non-concurrent collections must have exclusive access. A concurrent update was performed on this collection and corrupted its state. The collection's state is no longer correct.
Stack trace:    at System.Collections.Generic.HashSet`1.Contains(T item)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryCompilationContext.CreateUniqueTableAlias(String currentAlias)
   at Microsoft.EntityFrameworkCore.Query.Expressions.SelectExpression.PushDownSubquery()
   at   .(SelectExpression )
   at   .(SelectExpression )
   at   .      (SelectExpression )
   at   .      (SelectExpression )
   at System.Linq.Expressions.ExpressionVisitor.VisitAndConvert[T](T node, String callerName)
   at   .CreateDefault(SelectExpression )
   at Microsoft.EntityFrameworkCore.Query.Internal.ShaperCommandContext.GetRelationalCommand(IReadOnlyDictionary`2 parameters)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.BufferlessMoveNext(DbContext _, Boolean buffer)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
   at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
```

### Steps to reproduce
This can be reproduced by running a multithreaded api and calling the api multiple times simultaneously. I was able to reproduce it by looping a query and calling it multiple times to maximize the chance of collision. This rarely crashes in production when there are multiple users using the application at the same time.

This is the code line where it crashes for us
```
var ids = _context.Table
                .Where(predicate)
                .OrderBy(p => p.NavigationProperty.Id)
                .Select(p => p.NavigationProperty.Id)
                .Distinct()
                .Take(limit)
                .ToArray()
```

### Further technical details
EF Core version: 2.2.4
Database Provider: Devart.Data.Oracle
Operating system: Multiple

**Comment by TomNaN0** [comment]
This might be some really weird corner case.
I added another ToArray() evaluation directly after the select and moved the Order by below it and the issue seems to have disappeared.

Also when this issue happens it makes all requests with the exact same predicate fail to the concurrency error but if the same method is called with different predicate then that one worked correctly.

Also optimizing the predicate removed the issue for those calls but more complex predicates still crashed so it might be combination with longer running evaluation with exactly same predicates that causes them to use same HashSet in the CreateUniqueTableAlias method even when they are running in different instances of dbContext?
