### ISSUE TITLE
NullReferenceException FromSql with string interpolation and Guid

### ISSUE THREAD

**Issue by michaeljfarr** [aspnet/EntityFrameworkCore#17399]
Describe what is not working as expected.

When running FromSql with a CTE and string interpolation and projecting to a separate type, efcore 2.2.6 throws a NullReferenceException exception.  It is quite a specific situation, so I have provided a complete example below.  Changing the guid on the projected type avoids the issue - as does using a simpler query or not using query/string interpolation.  

```
Exception message:
System.NullReferenceException: 'Object reference not set to an instance of an object.'
Stack trace:
```
   at Microsoft.EntityFrameworkCore.Storage.TypedRelationalValueBufferFactoryFactory.CacheKey.<>c.<GetHashCode>b__6_0(Int32 t, TypeMaterializationInfo v)
   at System.Linq.Enumerable.Aggregate[TSource,TAccumulate](IEnumerable`1 source, TAccumulate seed, Func`3 func)
   at Microsoft.EntityFrameworkCore.Storage.TypedRelationalValueBufferFactoryFactory.CacheKey.GetHashCode()
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.EntityFrameworkCore.Storage.TypedRelationalValueBufferFactoryFactory.Create(IReadOnlyList`1 types)
   at Microsoft.EntityFrameworkCore.Query.Sql.Internal.FromSqlNonComposedQuerySqlGenerator.CreateValueBufferFactory(IRelationalValueBufferFactoryFactory relationalValueBufferFactoryFactory, DbDataReader dataReader)
   at Microsoft.EntityFrameworkCore.Query.Internal.ShaperCommandContext.<NotifyReaderCreated>b__14_0(FactoryAndReader s)
   at Microsoft.EntityFrameworkCore.Internal.NonCapturingLazyInitializer.EnsureInitialized[TParam,TValue](TValue& target, TParam param, Func`2 valueFactory)
   at Microsoft.EntityFrameworkCore.Query.Internal.ShaperCommandContext.NotifyReaderCreated(DbDataReader dataReader)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at GuidInProjection.Program.Main(String[] args) in C:\Users\Micha\Source\Repos\GuidInProjection\GuidInProjection\Program.cs:line 48

### Steps to reproduce
Run the code here, it should throw a NullReferenceException on the last line
https://github.com/michaeljfarr/GuidInProjection

### Further technical details
EF Core version: 2.2.6
Database Provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)
Operating system: Windows 10 Pro (10.0.18362)
IDE: (e.g. Visual Studio 2019 16.1.6)

**Comment by michaeljfarr** [comment]
Thanks Arthur.  Does this mean that we should not expect a fix for EF Core 2.2 and need to wait for the release of netcore 3.0?
