### ISSUE TITLE
Projection with select throws a null reference exception

### ISSUE THREAD

**Issue by vertonghenb** [aspnet/EntityFrameworkCore#17437]
Using a projection on a SingleOrDefault throws a null reference exception

```cs
var result = _context.Materials.Select(x => new SelectListItem(x.Id, x.Code, ""))
.AsNoTracking()
.SingleOrDefault(x => x.Id == 1);
```
or 
```cs
var result = await _context.Materials.Select(x => new SelectListItem(x.Id, x.Code, ""))
.AsNoTracking()
.SingleOrDefaultAsync(x => x.Id == 1);
```
or 
``` cs
var result = _context.Materials.Select(x => new SelectListItem(x.Id, x.Code, ""))
.SingleOrDefault(x => x.Id == 1);
```

or using a `OrderBy` after the select:
```cs
context.Suppliers
        .Where(x => x.Name.Contains("test"))
        .Select(x => new SelectListItem(x.Id, x.Name, Convert.ToString(x.Sequence)))
        .OrderBy(x => x.Title)
        .ToListAsync();
```
If you are seeing an exception, include the full exceptions details (message and stack trace).

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.EntityFrameworkCore.Query.ReplacingExpressionVisitor.VisitMember(MemberExpression memberExpression)
   at System.Linq.Expressions.MemberExpression.Accept(ExpressionVisitor visitor)
   at Microsoft.EntityFrameworkCore.Query.ReplacingExpressionVisitor.Visit(Expression expression)
   at System.Linq.Expressions.ExpressionVisitor.VisitBinary(BinaryExpression node)
   at System.Linq.Expressions.BinaryExpression.Accept(ExpressionVisitor visitor)
   at Microsoft.EntityFrameworkCore.Query.ReplacingExpressionVisitor.Visit(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.ReplacingExpressionVisitor.Replace(Expression original, Expression replacement, Expression tree)
   at Microsoft.EntityFrameworkCore.Query.NavigationExpansion.Internal.NavigationExpandingVisitor.FindAndApplyNavigations(Expression source, LambdaExpression lambda, NavigationExpansionExpressionState state)
   at Microsoft.EntityFrameworkCore.Query.NavigationExpansion.Internal.NavigationExpandingVisitor.ProcessWhere(MethodCallExpression methodCallExpression)
   at Microsoft.EntityFrameworkCore.Query.NavigationExpansion.Internal.NavigationExpandingVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at Microsoft.EntityFrameworkCore.Query.NavigationExpansion.Internal.NavigationExpandingVisitor.VisitSourceExpression(Expression sourceExpression)
   at Microsoft.EntityFrameworkCore.Query.NavigationExpansion.Internal.NavigationExpandingVisitor.ProcessCardinalityReducingOperation(MethodCallExpression methodCallExpression)
   at Microsoft.EntityFrameworkCore.Query.NavigationExpansion.Internal.NavigationExpandingVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at Microsoft.EntityFrameworkCore.Query.NavigationExpansion.Internal.NavigationExpandingVisitor.ProcessCardinalityReducingOperation(MethodCallExpression methodCallExpression)
   at Microsoft.EntityFrameworkCore.Query.NavigationExpansion.Internal.NavigationExpandingVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at Microsoft.EntityFrameworkCore.Query.QueryOptimizer.Visit(Expression query)
   at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.CreateQueryExecutor[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](Expression query, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass12_0`1.<ExecuteAsync>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQueryCore[TFunc](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteAsync[TResult](Expression query, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.ExecuteAsync[TResult](Expression expression, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ExecuteAsync[TSource,TResult](MethodInfo operatorMethodInfo, IQueryable`1 source, Expression expression, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ExecuteAsync[TSource,TResult](MethodInfo operatorMethodInfo, IQueryable`1 source, LambdaExpression expression, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.SingleOrDefaultAsync[TSource](IQueryable`1 source, Expression`1 predicate, CancellationToken cancellationToken)
```

### Further technical details
EF Core version: 3.0.0-preview8.19405.11
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system:  Win 10

**Comment by vertonghenb** [comment]
@smitpatel o wauw, thanks for the heads up! Can this issue be logged as a exception improvement?
