### ISSUE TITLE
 [Cosmos]The entity type 'Node' does not have a partition key set, but it is mapped to the collection 'Graphs' shared by entity types with partition keys.

### ISSUE THREAD

**Issue by NetGH** [aspnet/EntityFrameworkCore#17464]
There are two entitis , Graph and Node, Graph owns Node, and Graph has partition key, there is no way to set partition key of Node entity, because Node entity is nested in Graph.

            modelBuilder.Entity<Graph>().Property(g => g.__partitionKey);
            modelBuilder.Entity<Graph>().HasPartitionKey(g => g.__partitionKey);

            modelBuilder.Entity<Graph>().OwnsMany(g => g.Nodes,
                navigationBuilder =>
                {
               }

Message: 
    Test method RoundtripTestAsync threw exception: 
    System.InvalidOperationException:  The entity type 'Node' does not have a partition key set, but it is mapped to the collection 'Graphs' shared by entity types with partition keys.
  Stack Trace: 
    at CosmosModelValidator.ValidateSharedContainerCompatibility(IReadOnlyList`1 mappedTypes, String container, IDiagnosticsLogger`1 logger)
    at CosmosModelValidator.ValidateSharedContainerCompatibility(IModel model, IDiagnosticsLogger`1 logger)
    at CosmosModelValidator.Validate(IModel model, IDiagnosticsLogger`1 logger)
    at ValidatingConvention.ProcessModelFinalized(IConventionModelBuilder modelBuilder, IConventionContext`1 context)
    at ImmediateConventionScope.OnModelFinalized(IConventionModelBuilder modelBuilder)
    at ConventionDispatcher.OnModelFinalized(IConventionModelBuilder modelBuilder)
    at Model.FinalizeModel()
    at ModelBuilder.FinalizeModel()
    at MyDbContext.OnModelCreating(ModelBuilder modelBuilder) in MyDbContext.cs line: 55
    at CosmosMyDbContext.OnModelCreating(ModelBuilder modelBuilder) in CosmosMyDbContext.cs line: 21
    at ModelCustomizer.Customize(ModelBuilder modelBuilder, DbContext context)
    at ModelSource.CreateModel(DbContext context, IConventionSetBuilder conventionSetBuilder)
    at <>c__DisplayClass5_0.<GetModel>b__1()
    at Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
    at --- End of stack trace from previous location where exception was thrown ---
    at Lazy`1.CreateValue()
    at Lazy`1.get_Value()
    at ModelSource.GetModel(DbContext context, IConventionSetBuilder conventionSetBuilder)
    at DbContextServices.CreateModel()
    at DbContextServices.get_Model()
    at <>c.<TryAddCoreServices>b__7_3(IServiceProvider p)
    at CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, RuntimeResolverContext context)
    at CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
    at CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
    at CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
    at CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
    at CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
    at CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
    at CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
    at CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
    at CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
    at CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
    at CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
    at CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
    at CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
    at CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
    at CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
    at <>c__DisplayClass1_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
    at ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
    at ServiceProviderEngineScope.GetService(Type serviceType)
    at ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
    at <>c.<TryAddCoreServices>b__7_6(IServiceProvider p)
    at CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, RuntimeResolverContext context)
    at CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
    at CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
    at CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
    at CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
    at CallSiteRuntimeResolver.VisitIEnumerable(IEnumerableCallSite enumerableCallSite, RuntimeResolverContext context)
    at CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
    at CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
    at CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
    at CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
    at CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
    at <>c__DisplayClass1_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
    at ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
    at ServiceProviderEngineScope.GetService(Type serviceType)
    at ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
    at DbContext.GetResettableServices()+MoveNext()
    at IResettableService.ResetState()
    at DbContextPool`1.Return(TContext context)
    at IDisposable.Dispose()
    at ServiceProviderEngineScope.Dispose()

**Comment by AndriySvyryd** [comment]
A workaround is to use the metadata API to create a dummy property:

```c#
modelBuilder.Entity<Graph>().OwnsMany(g => g.Nodes,
	navigationBuilder =>
	{
            navigationBuilder.Property<string>("__partitionKey");
            navigationBuilder.OwnedEntityType.SetCosmosPartitionKeyPropertyName("__partitionKey");
        })
```

**Comment by NetGH** [comment]
Would the fix be included in nightly builds? I saw the build drop for branch 3.1 only.

        <add key="entityframeworkcore" value="https://dotnetfeed.blob.core.windows.net/aspnet-entityframeworkcore/index.json" />

**Comment by AndriySvyryd** [comment]
Yes, it would be in the 5.0 and 3.1 nightly builds

**Comment by NetGH** [comment]
Thanks much, from the version list via VS, i only see 5.0.0-alpha1*, 3.00-rc1.* 3.0.0-preview*.
There is no 3.1, did i point to the correct feed?
https://dotnetfeed.blob.core.windows.net/aspnet-entityframeworkcore/index.jso

**Comment by AndriySvyryd** [comment]
It will probably appear once we ship 3.0. For now 5.0 and 3.1 branches have the same code.

**Comment by NetGH** [comment]
Thanks Andriy !

Just tested the nightly build, it succeed to save entities now. but some update scenarios do not work.

1. Scenario one. Given that there is an existing graph  (master entity) with an existing node  (which is a owned entity)  in Cosmos DB. now Add a new node to graph
Expected Result: the new node is inserted into the graph in Cosmos DB
Actual Result: **no update**

2. Scenario Two. Given that there is an existing graph, and it has a property Name, and Name is the partition key. Update the Name, and save the Graph
Expected Result: the Graph name should be updated.
Actual Result: **The Graph Name property value is not updated**.

3. Scenario There: Remove a node from existing graph. --- **Works**!
4. Scenario Four: Update a property of an existing node. --- **Works**!

**Comment by AndriySvyryd** [comment]
@NetGH Could you file new issues for 1 and 2?

**Comment by NetGH** [comment]
Created a new issue #17616
