### ISSUE TITLE
3.0 - Regression. No longer able to catch results of async methods as base class

### ISSUE THREAD

**Issue by slubowsky** [aspnet/EntityFrameworkCore#17644]
Using 2.2.6 async code included below that either selects a base or a derived class works. Using 3.0 preview 9 (and daily as of 9/5) it fails (async only) with following exception

```
System.ArgumentException
  HResult=0x80070057
  Message=Expression of type 'System.Threading.Tasks.Task`1[ConsoleApp2.Program+PersonDetailView]' cannot be used for return type 'System.Threading.Tasks.Task`1[ConsoleApp2.Program+PersonView]'
  Source=System.Linq.Expressions
  StackTrace:
   at System.Linq.Expressions.Expression.ValidateLambdaArgs(Type delegateType, Expression& body, ReadOnlyCollection`1 parameters, String paramName)
   at System.Linq.Expressions.Expression.Lambda[TDelegate](Expression body, String name, Boolean tailCall, IEnumerable`1 parameters)
   at System.Linq.Expressions.Expression.Lambda[TDelegate](Expression body, Boolean tailCall, IEnumerable`1 parameters)
   at System.Linq.Expressions.Expression.Lambda[TDelegate](Expression body, ParameterExpression[] parameters)
   at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.CreateQueryExecutor[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](Expression query, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass12_0`1.<ExecuteAsync>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQueryCore[TFunc](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteAsync[TResult](Expression query, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.ExecuteAsync[TResult](Expression expression, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ExecuteAsync[TSource,TResult](MethodInfo operatorMethodInfo, IQueryable`1 source, Expression expression, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ExecuteAsync[TSource,TResult](MethodInfo operatorMethodInfo, IQueryable`1 source, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.FirstOrDefaultAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
   at ConsoleApp2.Program.<>c__DisplayClass4_0.<<Main>b__3>d.MoveNext() in C:\Users\slubo\source\repos\ConsoleApp2\ConsoleApp2\Program.cs:line 63
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at ConsoleApp2.Program.Main(String[] args) in C:\Users\slubo\source\repos\ConsoleApp2\ConsoleApp2\Program.cs:line 61

```

### Steps to reproduce
Code below using 2.2.6 completes with no errors as expected. Using 3.0 it throws exception as above.

```c#
using Microsoft.EntityFrameworkCore;
using System;
using System.Linq;
using System.Threading.Tasks;

namespace ConsoleApp2
{
    internal class Program
    {
        public class Person
        {
            public int Id { get; set; }
            public string Name { set; get; }
            public int Age { set; get; }
        }

        public class PersonView
        {
            public string Name { set; get; }
        }

        public class PersonDetailView : PersonView
        {
            public int Age { set; get; }
        }

        public class PersonContext : DbContext
        {
            public DbSet<Person> Persons { get; set; }

            protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
            {
                optionsBuilder.UseSqlServer(
                    @"Server=(localdb)\mssqllocaldb;Database=Persons;Integrated Security=True");
            }
        }

        private static void Main(string[] args)
        {
            var getDetails = true;
            using (var db = new PersonContext())
            {
                var person = new Person { Name = "John Doe", Age = 21 };
                db.Persons.Add(person);
                db.SaveChanges();

                var personsToFind = db
                    .Persons.Where(p => p.Age >= 21);

                IQueryable<PersonView> persons;

                if (getDetails)
                {
                    persons = personsToFind.Select(p => new PersonDetailView() { Name = p.Name, Age = p.Age });
                }
                else
                {
                    persons = personsToFind.Select(p => new PersonView() { Name = p.Name });
                }

                // works in both 2.2.6 and 3.0
                var resident = persons.FirstOrDefault();
                Console.WriteLine(resident.Name);

                Task.Run(async () =>
                {
                    // fails in 3.0 only
                    resident = await persons.FirstOrDefaultAsync();
                    Console.WriteLine(resident.Name);
                }).GetAwaiter().GetResult();
            }
        }
    }
}
```
My real use case is obviously more complex and uses AutoMapper.projectTo not manually creating specific types but this seems to reproduce the exact issue.

### Further technical details
Ef Core - 3.0.0-preview9.19423.6 (tried current 3.0 daily with same failure)
VS - 16.3.0 Preview 3.0

**Comment by ajcvickers** [comment]
@smitpatel to suggest a workaround for 3.0.

**Comment by slubowsky** [comment]
For a workaround, in the one case I've looked at so far, I can simply make sure the query is executed when the projection is added - duplicating code that shouldn't need to be duplicated (if FirstOrDefault changes to SingleOrDefault for example, I need to change in 2 places) but not difficult. Something like:
```
PersonView resident;

if (getDetails)
{
    resident = await personsToFind.Select(p => new PersonDetailView() { Name = p.Name, Age = p.Age }).FirstOrDefaultAsync();
}
else
{
    resident = await personsToFind.Select(p => new PersonView() { Name = p.Name }).FirstOrDefaultAsync();
}

Console.WriteLine(resident.Name);
```
Worse then the need for a workaround is that this is a new run time error. Easy to miss without exhaustive testing...

**Comment by smitpatel** [comment]
```C#
if (getDetails)
                {
                    persons = personsToFind.Select(p => (PersonView)new PersonDetailView() { Name = p.Name, Age = p.Age });
                }
                else
                {
                    persons = personsToFind.Select(p => new PersonView() { Name = p.Name });
                }
```

**Comment by slubowsky** [comment]
@smitpatel Thanks for the workaround. Dont know if that works for my real code though which is using AutoMapper.ProjectTo, not creating types itself.
```
if (getDetails)
{
	persons = personsToFind.ProjectTo<PersonDetailView>(config);
}
else
{
	persons = personsToFind.ProjectTo<PersonView>(config);
}
```

**Comment by smitpatel** [comment]
In that case
```C#
if (getDetails)
{
	persons = personsToFind.ProjectTo<PersonDetailView>(config);
        persons = persons.Select(p => (PersonView)p);
}
else
{
	persons = personsToFind.ProjectTo<PersonView>(config);
}
```
