### ISSUE TITLE
Duplicate backing field is throwing even with HasField correction

### ISSUE THREAD

**Issue by julielerman** [aspnet/EntityFrameworkCore#17691]
I am testing out this use case for https://github.com/aspnet/EntityFrameworkCore/pull/14735 but it is throwing even with the explicit mapping.

In my class I have:
```
   private string _name;
    public string Name => _name;
    private string m_name;
    public string OwnerName => m_name;
```
In context:
```
    modelBuilder.Entity<Company>().Property(c=>c.Name).HasField("_name");
     modelBuilder.Entity<Company>().Property(c=>c.OwnerName).HasField("m_name");
```  
When debugging, it is throwing the new exception when it hits the first configuration line (hasfield for Name) ...ambiguous fields, please use HasField().
![image](https://user-images.githubusercontent.com/5007120/64476873-54ba3380-d162-11e9-94b1-2d964e88c86e.png)

I changed the order so that OwnerName/m_name mapping is called first but that didn't help. I have cleaned. deleted bin/obj, rebuilt etc. And stared at my code to see if I'm doing something lame brained. (Which surely  will spotted instantly by someone else but I have to take my chances ;) )

package being pulled in is: 3.0.0-preview9.19423.6

**Exception** 
Exception has occurred: CLR/System.InvalidOperationException
An exception of type 'System.InvalidOperationException' occurred in Microsoft.EntityFrameworkCore.dll but was not handled in user code: 'Property 'Name' on entity type 'Company' matches both '_name' and 'm_name' by convention. Explicitly specify the backing field to use with '.HasField()' in 'OnModelCreating()'.'
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.BackingFieldConvention.TryMatch(KeyValuePair`2[] array, String prefix, String middle, String suffix, TypeInfo typeInfo, FieldInfo existingMatch, Type entityClrType, String propertyName)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.BackingFieldConvention.TryMatchFieldName(IConventionModel model, Type entityClrType, Type propertyType, String propertyName)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.BackingFieldConvention.GetFieldToSet(IConventionPropertyBase propertyBase)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.BackingFieldConvention.ProcessPropertyAdded(IConventionPropertyBuilder propertyBuilder, IConventionContext`1 context)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ImmediateConventionScope.OnPropertyAdded(IConventionPropertyBuilder propertyBuilder)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.RunVisitor.VisitOnPropertyAdded(OnPropertyAddedNode node)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.OnPropertyAddedNode.Accept(ConventionVisitor visitor)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ConventionVisitor.Visit(ConventionNode node)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ConventionVisitor.VisitConventionScope(ConventionScope node)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ConventionBatch.Run()
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ConventionBatch.Dispose()
   at Microsoft.EntityFrameworkCore.Metadata.Internal.InternalEntityTypeBuilder.Property(Type propertyType, String propertyName, MemberInfo memberInfo, Nullable`1 typeConfigurationSource, Nullable`1 configurationSource)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.InternalEntityTypeBuilder.Property(MemberInfo memberInfo, Nullable`1 configurationSource)
   at Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder`1.Property[TProperty](Expression`1 propertyExpression)
   at EFCore3DDD.CompanyContext.OnModelCreating(ModelBuilder modelBuilder) in ***\CompanyContext.cs:line 18
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelCustomizer.Customize(ModelBuilder modelBuilder, DbContext context)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.CreateModel(DbContext context, IConventionSetBuilder conventionSetBuilder)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.<>c__DisplayClass5_0.<GetModel>b__1()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)

**Comment by julielerman** [comment]
Arggh ..one minute later I had a new idea. ONLY map the OwnerName field because that's NEEDED anyway since there's nothing conventional about it's field name. And don't map the Name field. 
But I think it's not out of the question to want to explicitly map both fields. Sorry for the last minute discovery.

**Comment by smitpatel** [comment]
Convention shouldn't be throwing exception like that.

**Comment by julielerman** [comment]
Yay!
