### ISSUE TITLE
Entity objects cannot be returned within arrays in EF 3.0 preview 9

### ISSUE THREAD

**Issue by Shane32** [aspnet/EntityFrameworkCore#17744]
This query throws an error:
``` C#
db.Parts.Select(x => new object[] { x }).ToList();
```

Error message:
```
Processing of the LINQ expression '[EntityShaperExpression][Parts]' by 'RelationalProjectionBindingExpressionVisitor' failed. This may indicate either a bug or a limitation in EF Core. See https://go.microsoft.com/fwlink/?linkid=2101433 for more detailed information.
```

However, this works just fine: (and properly tracks the entity)
``` C#
db.Parts.Select(x => new MyClass { Part = x }).ToList();
```

Where Myclass is defined as: (notice that Part is still defined as an object, so that's not the issue)
``` C#
public class MyClass {
  public object Part { get; set; }
}
```

Also, selecting any non-entity works just fine:
``` C#
db.Parts.Select(x => new object[] { x.Id, x.Description }).ToList();
```

For EF 2.x, the same bug existed, but the workaround was to use AsNoTracking().  This workaround does not work in EF 3 preview 9.

Stack trace as follows:
```
   at Microsoft.EntityFrameworkCore.Query.Internal.RelationalProjectionBindingExpressionVisitor.VisitExtension(Expression extensionExpression)
   at System.Linq.Expressions.Expression.Accept(ExpressionVisitor visitor)
   at Microsoft.EntityFrameworkCore.Query.Internal.RelationalProjectionBindingExpressionVisitor.Visit(Expression expression)
   at System.Linq.Expressions.ExpressionVisitor.Visit(ReadOnlyCollection`1 nodes)
   at System.Linq.Expressions.ExpressionVisitor.VisitNewArray(NewArrayExpression node)
   at System.Linq.Expressions.NewArrayExpression.Accept(ExpressionVisitor visitor)
   at Microsoft.EntityFrameworkCore.Query.Internal.RelationalProjectionBindingExpressionVisitor.Visit(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.Internal.RelationalProjectionBindingExpressionVisitor.Translate(SelectExpression selectExpression, Expression expression)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.TranslateSelect(ShapedQueryExpression source, LambdaExpression selector)
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.CreateQueryExecutor[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](Expression query, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass9_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQueryCore[TFunc](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1.GetEnumerator()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at ZboxDbTest2.App.RunAsync() in C:\Users\Shane\Source\Repos\Zbox\ZboxDBTest2\App.cs:line 461
```

The problem exists when selecting any navigation property or returning any entity, and also occurs when returning dictionary objects.  For example, this would cause the same issue: (assuming that Manufacturer was a navigation property)

``` C#
var ret = db.Parts.Select(x => new Dictionary<string, object> { { "PartId", x.PartId }, { "Manufacturer", x.Manufacturer } }).ToList();
```

I have not been able to find any workaround -- for example, this doesn't work:
``` C#
db.Parts.Select(x => new object[] { new MyClass { Part = x } }).ToList();
```

FYI, my code uses expression builders to translate graphql queries into dynamic expression trees via nested Dictionary<string, object> objects.

### Further technical details

EF Core version: 3.0 preview 9
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET Core 3.0 preview 9
Operating system: Win 10 Pro x64
IDE: Visual Studio 2019 16.1.3

**Comment by divega** [comment]
cc @smitpatel what do you think about this?

**Comment by smitpatel** [comment]
Probably 3.1

**Comment by smitpatel** [comment]
Work-around
```C#
db.Parts.Select(x => new { x }).AsEnumerable().Select(t => new object[] { t.x }).ToList();
```

**Comment by Shane32** [comment]
The queries are created dynamically at runtime via the Expression namespace, and (as far as I know) it isn’t possible to create an anonymous type at runtime. If it is possible, that would be its own workaround, and I would not need an object returned in an array.

**Comment by smitpatel** [comment]
Tests to add in SimpleQueryTestBase.Select.cs
```C#


        [ConditionalTheory]
        [MemberData(nameof(IsAsyncData))]
        public virtual Task Projection_into_object_array(bool isAsync)
        {
            return AssertQuery(
                isAsync,
                ss => ss.Set<Customer>().OrderBy(c => c.CustomerID).Where(c => c.CustomerID.StartsWith("A"))
                    .Select(c => new object[] { c }),
                entryCount: 4,
                assertOrder: true);
        }

        [ConditionalTheory]
        [MemberData(nameof(IsAsyncData))]
        public virtual Task Projection_into_object_array_2(bool isAsync)
        {
            return AssertQuery(
                isAsync,
                ss => ss.Set<Order>().OrderBy(o => o.OrderID).Where(o => o.OrderID < 10300)
                    .Select(o => new object[] { o, o.Customer }),
                entryCount: 87,
                assertOrder: true);
        }
```

This is issue in entity equality rewrite. The entityReferenceExpression was not removed in the processing hence translation pipeline failed. Removing entityEquality makes it to pass so we have translation properly in place.

**Comment by jjxtra** [comment]
I don't get it at all. Even a simple group by fails...

```
var summaryFailedLogin = await db.FailedLoginAttempts.Where(f => f.CreatedAt >= cutoff && (machine == 0 || f.Machine.Id == machine)).OrderByDescending(b => b.CreatedAt).Take(maxCount)
                    .GroupBy(b => b.IPAddress.Country, (key, counter) => new { Country = key, Count = counter.Count() }).ToArrayAsync();
```

**Comment by Shane32** [comment]
@smitpatel @roji Does this also fix the ListInitExpression?  It would seem that the code might also need to handle VisitListInit to fix my second use case, which is the following:

``` C#
var ret = db.Parts.Select(x => new Dictionary<string, object> { { "PartId", x.PartId }, { "Manufacturer", x.Manufacturer } }).ToList();
```

I'm guessing a test case would look something like this:

``` C#
        [ConditionalTheory]
        [MemberData(nameof(IsAsyncData))]
        public virtual Task Projection_of_multiple_entity_types_into_dictionary(bool isAsync)
        {
            return AssertQuery(
                isAsync,
                ss => ss.Set<Order>().OrderBy(o => o.OrderID).Where(o => o.OrderID < 10300)
                    .Select(o => new System.Collections.Generic.Dictionary<string, object>() { { "obj", o }, { "cust", o.Customer } }),
                entryCount: 87,
                assertOrder: true);
        }
```

Thanks!!!

**Comment by roji** [comment]
@Shane32 the fix I pushed doesn't fix that issue, but I'll be submitting a separate PR for 3.1 that fixes list initialization as well as some other similar things.
