### ISSUE TITLE
Null Reference Exception when using HasData

### ISSUE THREAD

**Issue by laguer71** [aspnet/EntityFrameworkCore#17851]
I have a quite complex project, with a separate migrations assembly, modular asp.net (orchard) project, database seeding and owned types.
I was able to generate migrations with ef core 2.2, but am not longer able to do it with ef core 3. 
First thing I tried, after making it compile, was doing a migration, and got this stack trace

> System.NullReferenceException: Object reference not set to an instance of an object.
   at lambda_method(Closure , ValueBuffer )
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalShadowEntityEntry..ctor(IStateManager stateManager, IEntityType entityType, ValueBuffer& valueBuffer)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntryFactory.NewInternalEntityEntry(IStateManager stateManager, IEntityType entityType, Object entity, ValueBuffer& valueBuffer)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.CreateEntry(IDictionary\`2 values, IEntityType entityType)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationsModelDiffer.TrackData(IModel source, IModel target)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationsModelDiffer.Diff(IModel source, IModel target, DiffContext diffContext)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationsModelDiffer.GetDifferences(IModel source, IModel target)
   at Microsoft.EntityFrameworkCore.Migrations.Design.MigrationsScaffolder.ScaffoldMigration(String migrationName, String rootNamespace, String subNamespace, String language)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.AddMigration(String name, String outputDir, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigrationImpl(String name, String outputDir, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigration.<>c__DisplayClass0_0.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0\`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
Object reference not set to an instance of an object.

The project is in this github repo

https://github.com/laguer71/Albatros

**Comment by laguer71** [comment]
I issue this command in the PMC
add-migration -Project Albatros.Data.Migrations -StartupProject Albatros -Context ApplicationDbContext SomeNewMigrationWithEfCore3-verbose

**Comment by smitpatel** [comment]
The code supplied to reproduce this issue is quite complex. It would help greatly to have a simplified project/solution or code listing that isolates the issue in EF.

**Comment by laguer71** [comment]
I am trying to isolate the error, but so far have not been able to. Will keep trying latter today...

**Comment by laguer71** [comment]
I havent been able to isolate the bug. @AndriySvyryd ... you tracked it to a HasData. Did you found out what entityt seed was the one ?

**Comment by smitpatel** [comment]
@laguer71 - No. Stacktrace tells us it is HasData but no details about what actual user code.

**Comment by laguer71** [comment]
Couldn't isolate the bug, BUT found a regression bug for EF Core / Linq

**Comment by JulidaRocks** [comment]
I'm getting the same error

> Microsoft.EntityFrameworkCore.Infrastructure[10403]
      Entity Framework Core 3.0.0 initialized 'GamificationDbContext' using provider 'Microsoft.EntityFrameworkCore.SqlServer' with options: MigrationsAssembly=Netgo.Gamification.Infrastructure using lazy-loading proxies 
System.NullReferenceException: Object reference not set to an instance of an object.
   at lambda_method(Closure , ValueBuffer )
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalShadowEntityEntry..ctor(IStateManager stateManager, IEntityType entityType, ValueBuffer& valueBuffer)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntryFactory.NewInternalEntityEntry(IStateManager stateManager, IEntityType entityType, Object entity, ValueBuffer& valueBuffer)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntryFactory.Create(IStateManager stateManager, IEntityType entityType, Object entity, ValueBuffer& valueBuffer)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.CreateEntry(IDictionary`2 values, IEntityType entityType)
   at Microsoft.EntityFrameworkCore.Update.Internal.UpdateAdapter.CreateEntry(IDictionary`2 values, IEntityType entityType)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationsModelDiffer.TrackData(IModel source, IModel target)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationsModelDiffer.Diff(IModel source, IModel target, DiffContext diffContext)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationsModelDiffer.GetDifferences(IModel source, IModel target)
   at Microsoft.EntityFrameworkCore.Migrations.Design.MigrationsScaffolder.ScaffoldMigration(String migrationName, String rootNamespace, String subNamespace, String language)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.AddMigration(String name, String outputDir, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigrationImpl(String name, String outputDir, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigration.<>c__DisplayClass0_0.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
Object reference not set to an instance of an object.

**Comment by smitpatel** [comment]
@JulidaRocks - Can you share a repro project?

**Comment by JulidaRocks** [comment]
> @JulidaRocks - Can you share a repro project?

[I created a simplified project](https://github.com/JulidaRocks/GithubSample)

**Comment by smitpatel** [comment]
@JulidaRocks - Thank you so much. I am able to reproduce the error in the repro code.

**Comment by JulidaRocks** [comment]
@smitpatel Is there a workaround to get around this issue until your changes will be published?

**Comment by smitpatel** [comment]
@JulidaRocks - I am not aware of any. @AndriySvyryd ?

**Comment by laguer71** [comment]
Ry adding the seed data directly to the dbset

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by ciacco85** [comment]
do you think an hotfix will be released soon, like 3.0.1, or we've to wait till 3.1 in november?
I thought targeting old framework for new migration could be a workaround, but only for empty migration.

**Comment by ciacco85** [comment]
> Ry adding the seed data directly to the dbset Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
> […](#)
> ________________________________ From: Smit Patel <notifications@github.com> Sent: Tuesday, October 15, 2019 12:51:37 PM To: aspnet/EntityFrameworkCore <EntityFrameworkCore@noreply.github.com> Cc: Luis Guerrero <laguer71@hotmail.com>; Mention <mention@noreply.github.com> Subject: Re: [aspnet/EntityFrameworkCore] Null Reference Exception when using HasData (#17851) @JulidaRocks<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FJulidaRocks&data=02%7C01%7C%7C9883f18844b841c2671508d751985466%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637067586995665799&sdata=RRWkm8DymlhU90NHbmrqitOMFlT%2FTxKuJt0TLyvLKt4%3D&reserved=0> - I am not aware of any. @AndriySvyryd<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAndriySvyryd&data=02%7C01%7C%7C9883f18844b841c2671508d751985466%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637067586995675804&sdata=GryWlMnDa7xZLKjPTCuC%2BfEhZmTbqDNywQM7HkaEc%2Bc%3D&reserved=0> ? — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Faspnet%2FEntityFrameworkCore%2Fissues%2F17851%3Femail_source%3Dnotifications%26email_token%3DAJSTUTJWQ4AU4QVF5RUA6MDQOX7KTA5CNFSM4IWXSHOKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEBJUXHY%23issuecomment-542329759&data=02%7C01%7C%7C9883f18844b841c2671508d751985466%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637067586995685816&sdata=KSRcuInf8Y2JFKezTRV6LpP693H9R67yF2SZcfulUvU%3D&reserved=0>, or unsubscribe<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAJSTUTLF2KLPXF4J6HKHFBLQOX7KTANCNFSM4IWXSHOA&data=02%7C01%7C%7C9883f18844b841c2671508d751985466%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637067586995695821&sdata=L1frbqbeaboh34NN8c4iqs5Jtvh5HVXoFiizsedFqTA%3D&reserved=0>.

So you've moved from "HasData(new YourEntity())" to "DbSet<>().Add(new YourEntity())" for the seed that throws the exception?
How did you notice wich seeded entity throws the exception, since there's no clue on how to find it? may be because you've a null reference exception instead of invalid casting exception and so you've more detail?

**Comment by smitpatel** [comment]
A derived entity which has seed data, where base entity has a reference navigation would throw exception in model snapshot.

**Comment by smitpatel** [comment]
> perform all his checks on data seed internally writing all those verbose logs like

If you have logs then look for last entity which was tracked. With above log, it is Permission entity with given key. Whatever is next entity being used in seed data is causing the issue.

**Comment by ciacco85** [comment]
> > perform all his checks on data seed internally writing all those verbose logs like
> 
> If you have logs then look for last entity which was tracked. With above log, it is Permission entity with given key. Whatever is next entity being used in seed data is causing the issue.

That's exactly what I've done, but without success. I will double check and see.
Thank you, really appreciated.
Am I wrong or your commit was merged into v.3.1.0 preview 1 recently? Maybe I can give a try with the new version, too
You're doing great!!!

**Comment by smitpatel** [comment]
It went into v 3.1.0-preview2. Would be available in nightly builds.
