### ISSUE TITLE
Value conversion is ignored when using linq query language join syntax

### ISSUE THREAD

**Issue by realTeddy** [aspnet/EntityFrameworkCore#17861]
Value conversion is ignored when using linq query language join syntax. As a simple example take a look at the following code...

### Steps to reproduce
ModelBuilder...
``` 
var boolToCharConverter = new BoolToStringConverter("N", "Y");
modelBuilder.Entity<Lender>().Property(e => e.IsEnabled).HasConversion(boolToCharConverter);
```

Simple query code...
```
await
            (from l in repository.Lenders
             join m in repository.Memberships on new { LenderId = (int?)l.Id, l.IsEnabled, lenderId = l.Id } equals new { m.LenderId, IsEnabled = true, lenderId }
             where l.IsEnabled
             select l.Name)
.ToListAsync();
```

Generated SQL...
``` 
SELECT [l].[LenderName]
      FROM [LenderConfig].[Lender] AS [l]
      INNER JOIN [LenderConfig].[Membership] AS [m] ON (([l].[LenderID] = [m].[LenderId]) AND ([l].[EnabledFlag] = CAST(1 AS bit))) AND (([l].[LenderID] = @__lenderId_0) AND @__lenderId_0 IS NOT NULL)
      WHERE [l].[EnabledFlag] = N'Y'
```

Exception:
```
fail: Microsoft.EntityFrameworkCore.Query[10100]
      An exception occurred while iterating over the results of a query for context type 'RateTableAdmin.DataAccess.RateTable.RateTableDbContext'.
      Microsoft.Data.SqlClient.SqlException (0x80131904): Conversion failed when converting the varchar value 'N' to data type bit.
         at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
         at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
         at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
         at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
         at Microsoft.Data.SqlClient.SqlDataReader.TryHasMoreRows(Boolean& moreRows)
         at Microsoft.Data.SqlClient.SqlDataReader.TryReadInternal(Boolean setTimeout, Boolean& more)
         at Microsoft.Data.SqlClient.SqlDataReader.<>c__DisplayClass195_0.<ReadAsync>b__1(Task t)
         at Microsoft.Data.SqlClient.SqlDataReader.InvokeRetryable[T](Func`2 moreFunc, TaskCompletionSource`1 source, IDisposable objectToDispose)
      --- End of stack trace from previous location where exception was thrown ---
         at Microsoft.EntityFrameworkCore.Query.RelationalShapedQueryCompilingExpressionVisitor.AsyncQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
      ClientConnectionId:a4a680e4-2ed5-4146-9081-3828ec2a92cf
      Error Number:245,State:1,Class:16
Microsoft.Data.SqlClient.SqlException (0x80131904): Conversion failed when converting the varchar value 'N' to data type bit.
   at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.SqlDataReader.TryHasMoreRows(Boolean& moreRows)
   at Microsoft.Data.SqlClient.SqlDataReader.TryReadInternal(Boolean setTimeout, Boolean& more)
   at Microsoft.Data.SqlClient.SqlDataReader.<>c__DisplayClass195_0.<ReadAsync>b__1(Task t)
   at Microsoft.Data.SqlClient.SqlDataReader.InvokeRetryable[T](Func`2 moreFunc, TaskCompletionSource`1 source, IDisposable objectToDispose)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.EntityFrameworkCore.Query.RelationalShapedQueryCompilingExpressionVisitor.AsyncQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
ClientConnectionId:a4a680e4-2ed5-4146-9081-3828ec2a92cf
Error Number:245,State:1,Class:16
```

### Workaround 
await
            (from l in repository.Lenders
             join m in repository.Memberships on new { LenderId = (int?)l.Id, IsEnabled = l.IsEnabled == true, lenderId = l.Id } equals new { m.LenderId, IsEnabled = true, lenderId }
             where l.IsEnabled
             select l.Name)
.ToListAsync()

### Further technical details
EF Core version: 3.0.0-preview9.19423.6
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET Core 3.0
Operating system: Windows 10 Enterprise
IDE: Visual Studio 2019 16.2.4
.NET Core version: 3.0.0-preview9-19423-09

**Comment by realTeddy** [comment]
Note: The query worked on EF Core 2.2.6 with no issue.

**Comment by smitpatel** [comment]
Probably some bug in generating join predicate.
