### ISSUE TITLE
Add-Migration NullReferenceException

### ISSUE THREAD

**Issue by hannan-m** [aspnet/EntityFrameworkCore#17909]
The database context generated by `Scaffold-DbContext`. After generating the context I moved all entity configurations in `OnModelCreating`  to separate config file implementing `IEntityTypeConfiguration<T>`.  `OnModelCreating` is like this now.

```
protected override void OnModelCreating(ModelBuilder modelBuilder)
{
      modelBuilder.ApplyConfigurationsFromAssembly(GetType().Assembly);
}
```

The same setup is working in EF Core **v2.2.6**.

### Steps to reproduce

`Add-Migration IntitialSchema` 

### StackTrace
```
DesignTimeDbContextFactoryBase.BasePath: D:\Working_Projects
DesignTimeDbContextFactoryBase.Create(string): Connection string: 'Server=DW;Database=DeveDB;Trusted_Connection=True;Application Name=Portal;'.
DbContext Assembly: Portal.Persistence, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.EntityFrameworkCore.Design.Internal.CSharpHelper.Literal(String value)
   at Microsoft.EntityFrameworkCore.Migrations.Design.CSharpMigrationOperationGenerator.Generate(CreateTableOperation operation, IndentedStringBuilder builder)
   at Microsoft.EntityFrameworkCore.Migrations.Design.CSharpMigrationOperationGenerator.Generate(String builderName, IReadOnlyList`1 operations, IndentedStringBuilder builder)
   at Microsoft.EntityFrameworkCore.Migrations.Design.CSharpMigrationsGenerator.GenerateMigration(String migrationNamespace, String migrationName, IReadOnlyList`1 upOperations, IReadOnlyList`1 downOperations)
   at Microsoft.EntityFrameworkCore.Migrations.Design.MigrationsScaffolder.ScaffoldMigration(String migrationName, String rootNamespace, String subNamespace, String language)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.AddMigration(String name, String outputDir, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigrationImpl(String name, String outputDir, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigration.<>c__DisplayClass0_0.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
Object reference not set to an instance of an object.
```

### Further technical details

EF Core version: 3.0.0-rc1.19456.14
Database provider: Microsoft.EntityFrameworkCore.SqlServer (3.0.0-rc1.19456.14)
Target framework: .NET Core 3.0
SDK: .NET Core 3.0rc1
Operating system: Windows 10
IDE: Visual Studio 2019 16.2.5

**Comment by bricelam** [comment]
Probably the same root cause as #17474

**Comment by bricelam** [comment]
@hannan-m Could you share a simple repro so we can investigate?

**Comment by hannan-m** [comment]
Yes, it's related to #17474. 

#Steps to reproduce.  

**Create a database**

```
CREATE DATABASE [Blogging];
GO

USE [Blogging];
GO

CREATE TABLE [Blog] (
    [BlogId] int NOT NULL IDENTITY,
    [Url] nvarchar(max) NOT NULL,
    CONSTRAINT [PK_Blog] PRIMARY KEY ([BlogId])
);
GO

CREATE TABLE [Post] (
    [PostId] int NOT NULL IDENTITY,
    [BlogId] int NOT NULL,
    [Content] nvarchar(max),
    [Title] nvarchar(max),
    CONSTRAINT [PK_Post] PRIMARY KEY ([PostId]),
    CONSTRAINT [FK_Post_Blog_BlogId] FOREIGN KEY ([BlogId]) REFERENCES [Blog] ([BlogId]) ON DELETE CASCADE
);
GO

INSERT INTO [Blog] (Url) VALUES
('http://blogs.msdn.com/dotnet'),
('http://blogs.msdn.com/webdev'),
('http://blogs.msdn.com/visualstudio')
GO
```
**Scaffold DbContext**
```
Scaffold-DbContext "Server=(localdb)\mssqllocaldb;Database=Blogging;Trusted_Connection=True;" Microsoft.EntityFrameworkCore.SqlServer -OutputDir Models
```

**Create the following models**
```
public class Author
    {
        public int Id { get; set; }
        public string Name { get; set; }
    }

    public class AuthorPost
    {
        public int AuthorId { get; set; }
        public ICollection<Post> Posts { get; set; }

        public virtual Author Author { get; set; }
    }
```
**`DbContext` and entity configurations**
```
public partial class BloggingContext : DbContext
    {
        public BloggingContext()
        {
        }

        public BloggingContext(DbContextOptions<BloggingContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Blog> Blog { get; set; }
        public virtual DbSet<Post> Post { get; set; }
        public virtual DbSet<Author> Authors { get; set; }
        public virtual DbSet<AuthorPost> AuthorPosts { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
                optionsBuilder.UseSqlServer("Server=DW;Database=Blogging;Trusted_Connection=True;");
            }
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.ApplyConfigurationsFromAssembly(GetType().Assembly);
        }
    }

    public class BlogConfiguration : IEntityTypeConfiguration<Blog>
    {
        public void Configure(EntityTypeBuilder<Blog> builder)
        {
            builder.Property(e => e.Url).IsRequired();
        }
    }

    public class AuthorConfiguration : IEntityTypeConfiguration<Author>
    {
        public void Configure(EntityTypeBuilder<Author> builder)
        {
            // remove .HasComment("Author fullname") and then run Add-Migration. It will work.
            builder.Property(e => e.Name).IsRequired().HasComment("Author fullname");
        }
    }

    public class AuthorPostConfiguration : IEntityTypeConfiguration<AuthorPost>
    {
        public void Configure(EntityTypeBuilder<AuthorPost> builder)
        {
            builder.HasNoKey();
        }
    }

    public class PostConfiguration : IEntityTypeConfiguration<Post>
    {
        public void Configure(EntityTypeBuilder<Post> builder)
        {
            builder.HasOne(d => d.Blog)
                .WithMany(p => p.Post)
                .HasForeignKey(d => d.BlogId);
        }
    }
```
Now run
```
Add-Migration CreateAuthorAndPostRelation
``
Stacktrace
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.EntityFrameworkCore.Design.Internal.CSharpHelper.Literal(String value)
   at Microsoft.EntityFrameworkCore.Migrations.Design.CSharpMigrationOperationGenerator.Generate(CreateTableOperation operation, IndentedStringBuilder builder)
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid3[T0,T1,T2](CallSite site, T0 arg0, T1 arg1, T2 arg2)
   at Microsoft.EntityFrameworkCore.Migrations.Design.CSharpMigrationOperationGenerator.Generate(String builderName, IReadOnlyList`1 operations, IndentedStringBuilder builder)
   at Microsoft.EntityFrameworkCore.Migrations.Design.CSharpMigrationsGenerator.GenerateMigration(String migrationNamespace, String migrationName, IReadOnlyList`1 upOperations, IReadOnlyList`1 downOperations)
   at Microsoft.EntityFrameworkCore.Migrations.Design.MigrationsScaffolder.ScaffoldMigration(String migrationName, String rootNamespace, String subNamespace, String language)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.AddMigration(String name, String outputDir, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigrationImpl(String name, String outputDir, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigration.<>c__DisplayClass0_0.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
Object reference not set to an instance of an object.
```

If we remove `.HasComment("Author fullname")` migration will add successfully.

**Comment by TheProgrammator** [comment]
I get the same error (different cause) when doing a `Remove-Migration`.

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.EntityFrameworkCore.Design.Internal.CSharpHelper.Literal(String value)
   at Microsoft.EntityFrameworkCore.Migrations.Design.CSharpSnapshotGenerator.GeneratePropertyAnnotations(IProperty property, IndentedStringBuilder stringBuilder)
   at Microsoft.EntityFrameworkCore.Migrations.Design.CSharpSnapshotGenerator.GenerateProperty(String builderName, IProperty property, IndentedStringBuilder stringBuilder)
   at Microsoft.EntityFrameworkCore.Migrations.Design.CSharpSnapshotGenerator.GenerateProperties(String builderName, IEnumerable`1 properties, IndentedStringBuilder stringBuilder)
   at Microsoft.EntityFrameworkCore.Migrations.Design.CSharpSnapshotGenerator.GenerateEntityType(String builderName, IEntityType entityType, IndentedStringBuilder stringBuilder)
   at Microsoft.EntityFrameworkCore.Migrations.Design.CSharpSnapshotGenerator.GenerateEntityTypes(String builderName, IReadOnlyList`1 entityTypes, IndentedStringBuilder stringBuilder)
   at Microsoft.EntityFrameworkCore.Migrations.Design.CSharpSnapshotGenerator.Generate(String builderName, IModel model, IndentedStringBuilder stringBuilder)
   at Microsoft.EntityFrameworkCore.Migrations.Design.CSharpMigrationsGenerator.GenerateSnapshot(String modelSnapshotNamespace, Type contextType, String modelSnapshotName, IModel model)
   at Microsoft.EntityFrameworkCore.Migrations.Design.MigrationsScaffolder.RemoveMigration(String projectDir, String rootNamespace, Boolean force, String language)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.RemoveMigration(String contextType, Boolean force)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.RemoveMigrationImpl(String contextType, Boolean force)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.RemoveMigration.<>c__DisplayClass0_0.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
```
Excerpt from code:
https://github.com/aspnet/EntityFrameworkCore/blob/a6760b64ec175acda64beb5c2d1f185657cf0304/src/EFCore.Design/Migrations/Design/CSharpSnapshotGenerator.cs#L443

Please advise how to proceed.

**Comment by bricelam** [comment]
Can you submit a new issue with a repro so we can investigate?

**Comment by alanpeng66** [comment]
> Yes, it's related to #17474.
> 
> ## Steps to reproduce.
> **Create a database**
> 
> ```
> CREATE DATABASE [Blogging];
> GO
> 
> USE [Blogging];
> GO
> 
> CREATE TABLE [Blog] (
>     [BlogId] int NOT NULL IDENTITY,
>     [Url] nvarchar(max) NOT NULL,
>     CONSTRAINT [PK_Blog] PRIMARY KEY ([BlogId])
> );
> GO
> 
> CREATE TABLE [Post] (
>     [PostId] int NOT NULL IDENTITY,
>     [BlogId] int NOT NULL,
>     [Content] nvarchar(max),
>     [Title] nvarchar(max),
>     CONSTRAINT [PK_Post] PRIMARY KEY ([PostId]),
>     CONSTRAINT [FK_Post_Blog_BlogId] FOREIGN KEY ([BlogId]) REFERENCES [Blog] ([BlogId]) ON DELETE CASCADE
> );
> GO
> 
> INSERT INTO [Blog] (Url) VALUES
> ('http://blogs.msdn.com/dotnet'),
> ('http://blogs.msdn.com/webdev'),
> ('http://blogs.msdn.com/visualstudio')
> GO
> ```
> 
> **Scaffold DbContext**
> 
> ```
> Scaffold-DbContext "Server=(localdb)\mssqllocaldb;Database=Blogging;Trusted_Connection=True;" Microsoft.EntityFrameworkCore.SqlServer -OutputDir Models
> ```
> 
> **Create the following models**
> 
> ```
> public class Author
>     {
>         public int Id { get; set; }
>         public string Name { get; set; }
>     }
> 
>     public class AuthorPost
>     {
>         public int AuthorId { get; set; }
>         public ICollection<Post> Posts { get; set; }
> 
>         public virtual Author Author { get; set; }
>     }
> ```
> 
> **`DbContext` and entity configurations**
> 
> ```
> public partial class BloggingContext : DbContext
>     {
>         public BloggingContext()
>         {
>         }
> 
>         public BloggingContext(DbContextOptions<BloggingContext> options)
>             : base(options)
>         {
>         }
> 
>         public virtual DbSet<Blog> Blog { get; set; }
>         public virtual DbSet<Post> Post { get; set; }
>         public virtual DbSet<Author> Authors { get; set; }
>         public virtual DbSet<AuthorPost> AuthorPosts { get; set; }
> 
>         protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
>         {
>             if (!optionsBuilder.IsConfigured)
>             {
>                 optionsBuilder.UseSqlServer("Server=DW;Database=Blogging;Trusted_Connection=True;");
>             }
>         }
> 
>         protected override void OnModelCreating(ModelBuilder modelBuilder)
>         {
>             modelBuilder.ApplyConfigurationsFromAssembly(GetType().Assembly);
>         }
>     }
> 
>     public class BlogConfiguration : IEntityTypeConfiguration<Blog>
>     {
>         public void Configure(EntityTypeBuilder<Blog> builder)
>         {
>             builder.Property(e => e.Url).IsRequired();
>         }
>     }
> 
>     public class AuthorConfiguration : IEntityTypeConfiguration<Author>
>     {
>         public void Configure(EntityTypeBuilder<Author> builder)
>         {
>             // remove .HasComment("Author fullname") and then run Add-Migration. It will work.
>             builder.Property(e => e.Name).IsRequired().HasComment("Author fullname");
>         }
>     }
> 
>     public class AuthorPostConfiguration : IEntityTypeConfiguration<AuthorPost>
>     {
>         public void Configure(EntityTypeBuilder<AuthorPost> builder)
>         {
>             builder.HasNoKey();
>         }
>     }
> 
>     public class PostConfiguration : IEntityTypeConfiguration<Post>
>     {
>         public void Configure(EntityTypeBuilder<Post> builder)
>         {
>             builder.HasOne(d => d.Blog)
>                 .WithMany(p => p.Post)
>                 .HasForeignKey(d => d.BlogId);
>         }
>     }
> ```
> 
> Now run
> 
> ```
> Add-Migration CreateAuthorAndPostRelation
> ```
> 
> **Stacktrace**
> 
> ```
> System.NullReferenceException: Object reference not set to an instance of an object.
>    at Microsoft.EntityFrameworkCore.Design.Internal.CSharpHelper.Literal(String value)
>    at Microsoft.EntityFrameworkCore.Migrations.Design.CSharpMigrationOperationGenerator.Generate(CreateTableOperation operation, IndentedStringBuilder builder)
>    at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid3[T0,T1,T2](CallSite site, T0 arg0, T1 arg1, T2 arg2)
>    at Microsoft.EntityFrameworkCore.Migrations.Design.CSharpMigrationOperationGenerator.Generate(String builderName, IReadOnlyList`1 operations, IndentedStringBuilder builder)
>    at Microsoft.EntityFrameworkCore.Migrations.Design.CSharpMigrationsGenerator.GenerateMigration(String migrationNamespace, String migrationName, IReadOnlyList`1 upOperations, IReadOnlyList`1 downOperations)
>    at Microsoft.EntityFrameworkCore.Migrations.Design.MigrationsScaffolder.ScaffoldMigration(String migrationName, String rootNamespace, String subNamespace, String language)
>    at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.AddMigration(String name, String outputDir, String contextType)
>    at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigrationImpl(String name, String outputDir, String contextType)
>    at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigration.<>c__DisplayClass0_0.<.ctor>b__0()
>    at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
>    at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
> Object reference not set to an instance of an object.
> ```
> 
> If we remove `.HasComment("Author fullname")` migration will add successfully.

thank you!!!!!

**Comment by 404Prachi** [comment]
Hi 
I am getting same error but not able to figure out reason it is asp.net core 3.0

**Comment by 404Prachi** [comment]
I am getting System.NullReferenceException: Object reference not set to an instance of an object.   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationsModelDiffer.Initialize(ColumnOperation columnOperation, IProperty property, CoreTypeMapping typeMapping, Boolean isNullable, IEnumerable`1 migrationsAnnotations, Boolean inline)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationsModelDiffer.Add(IProperty target, DiffContext diffContext, Boolean inline)+MoveNext()
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
   at System.Linq.Enumerable.CastIterator[TResult](IEnumerable source)+MoveNext()
   at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationsModelDiffer.Add(ITable target, DiffContext diffContext)+MoveNext()
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationsModelDiffer.DiffCollection[T](IEnumerable`1 sources, IEnumerable`1 targets, DiffContext diffContext, Func`4 diff, Func`3 add, Func`3 remove, Func`4[] predicates)+MoveNext()
   at System.Linq.Enumerable.ConcatIterator`1.MoveNext()
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationsModelDiffer.Sort(IEnumerable`1 operations, DiffContext diffContext)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationsModelDiffer.GetDifferences(IModel source, IModel target)
   at Microsoft.EntityFrameworkCore.Migrations.Design.MigrationsScaffolder.ScaffoldMigration(String migrationName, String rootNamespace, String subNamespace, String language)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.AddMigration(String name, String outputDir, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigrationImpl(String name, String outputDir, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigration.<>c__DisplayClass0_0.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
Object reference not set to an instance of an object.

**Comment by ajcvickers** [comment]
@404Prachi You need to update to ASP.NET Core 3.1 and EF Core 3.1.
