### ISSUE TITLE
Expression of type 'System.Threading.Tasks.Task`1[System.Linq.IQueryable`1[System.String]]' cannot be used for return type 'System.Threading.Tasks.Task`1[System.Collections.Generic.IEnumerable`1[System.String]]

### ISSUE THREAD

**Issue by Ozyes** [aspnet/EntityFrameworkCore#18181]
After upgrading our project to EFCore 3.0, we are getting the following System.Argument exception with a select and firstordefaultasync query.

```
Expression of type 'System.Threading.Tasks.Task`1[System.Linq.IQueryable`1[System.String]]' cannot be used for return type 'System.Threading.Tasks.Task`1[System.Collections.Generic.IEnumerable`1[System.String]]
```

### Steps to reproduce
We added an example code below to reproduce the issue

``` C#
public  async Task Test()
 {
            using (var dbContext = new MyDbContext())
            {
                var query = await dbContext.SetA.Include(x => x.Details).Select(y => y.Details.Select(z => z.DisplayName)).FirstOrDefaultAsync();
            }
}

public class A
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public List<B> Details { get; set; }
    }
    public class B
    {
        public int Id { get; set; }

        public string DisplayName { get; set; }
    }

public class MyDbContext : DbContext
    {
        protected override void OnConfiguring(DbContextOptionsBuilder options)
           => options.UseInMemoryDatabase("test");

        public DbSet<A> SetA { get; set; }

        public DbSet<B> SetB { get; set; }

    }
```
Exception Message:
``` C#
System.ArgumentException: 'Expression of type 'System.Threading.Tasks.Task`1[System.Linq.IQueryable`1[System.String]]' cannot be used for return type 'System.Threading.Tasks.Task`1[System.Collections.Generic.IEnumerable`1[System.String]]''
```
StackTrace: 
``` C#
   at System.Linq.Expressions.Expression.ValidateLambdaArgs(Type delegateType, Expression& body, ReadOnlyCollection`1 parameters, String paramName)
   at System.Linq.Expressions.Expression.Lambda[TDelegate](Expression body, String name, Boolean tailCall, IEnumerable`1 parameters)
   at System.Linq.Expressions.Expression.Lambda[TDelegate](Expression body, Boolean tailCall, IEnumerable`1 parameters)
   at System.Linq.Expressions.Expression.Lambda[TDelegate](Expression body, ParameterExpression[] parameters)
   at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.CreateQueryExecutor[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](Expression query, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass12_0`1.<ExecuteAsync>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQueryCore[TFunc](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteAsync[TResult](Expression query, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.ExecuteAsync[TResult](Expression expression, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ExecuteAsync[TSource,TResult](MethodInfo operatorMethodInfo, IQueryable`1 source, Expression expression, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ExecuteAsync[TSource,TResult](MethodInfo operatorMethodInfo, IQueryable`1 source, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.FirstOrDefaultAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
   at EFCoreTest.Program.<Test>d__1.MoveNext() in C:\Users\ozlem.karagedik\source\repos\EFCoreTest\EFCoreTest\Program.cs:line 22
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at EFCoreTest.Program.Main(String[] args) in C:\Users\ozlem.karagedik\source\repos\EFCoreTest\EFCoreTest\Program.cs:line 15
```

### Further technical details

EF Core version: 3,0
Database provider: both  Microsoft.EntityFrameworkCore.SqlServer and   Microsoft.EntityFrameworkCore.InMemory
Target framework: NET Core 3.0
Operating system: Windows 10 Pro
IDE: Visual Studio 2019 16.3.1

**Comment by roji** [comment]
This repros on 3.0.0 but is gone in 3.1.0-preview1.
