### ISSUE TITLE
Query: NRE for query with groupby with Min/Max on entity

### ISSUE THREAD

**Issue by maumar** [aspnet/EntityFrameworkCore#18269]
query:

```cs
ss.Set<Gear>()
.GroupBy(g => g.CityOrBirthName)
.Select(g => new
{
   g.Key,
   Aggregate = g.Max()
})
```

exception:

```
Message: 
    System.NullReferenceException : Object reference not set to an instance of an object.
  Stack Trace: 
    at RelationalSqlTranslatingExpressionVisitor.TranslateMax(Expression expression) in RelationalSqlTranslatingExpressionVisitor.cs line: 122
    at RelationalSqlTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression) in RelationalSqlTranslatingExpressionVisitor.cs line: 306
    at MethodCallExpression.Accept(ExpressionVisitor visitor)
    at ExpressionVisitor.Visit(Expression node)
    at RelationalSqlTranslatingExpressionVisitor.Translate(Expression expression) in RelationalSqlTranslatingExpressionVisitor.cs line: 42
    at RelationalProjectionBindingExpressionVisitor.Visit(Expression expression) in RelationalProjectionBindingExpressionVisitor.cs line: 163
    at RelationalProjectionBindingExpressionVisitor.VisitNew(NewExpression newExpression) in RelationalProjectionBindingExpressionVisitor.cs line: 250
    at NewExpression.Accept(ExpressionVisitor visitor)
    at ExpressionVisitor.Visit(Expression node)
    at RelationalProjectionBindingExpressionVisitor.Visit(Expression expression) in RelationalProjectionBindingExpressionVisitor.cs line: 175
    at RelationalProjectionBindingExpressionVisitor.Translate(SelectExpression selectExpression, Expression expression) in RelationalProjectionBindingExpressionVisitor.cs line: 45
    at RelationalQueryableMethodTranslatingExpressionVisitor.TranslateSelect(ShapedQueryExpression source, LambdaExpression selector) in RelationalQueryableMethodTranslatingExpressionVisitor.cs line: 726
    at QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression) in QueryableMethodTranslatingExpressionVisitor.cs line: 343
    at RelationalQueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression) in RelationalQueryableMethodTranslatingExpressionVisitor.cs line: 72
    at MethodCallExpression.Accept(ExpressionVisitor visitor)
    at ExpressionVisitor.Visit(Expression node)
    at QueryCompilationContext.CreateQueryExecutor[TResult](Expression query) in QueryCompilationContext.cs line: 68
    at Database.CompileQuery[TResult](Expression query, Boolean async) in Database.cs line: 71
    at QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async) in QueryCompiler.cs line: 106
    at <>c__DisplayClass9_0`1.<Execute>b__0() in QueryCompiler.cs line: 96
    at CompiledQueryCache.GetOrAddQueryCore[TFunc](Object cacheKey, Func`1 compiler) in CompiledQueryCache.cs line: 84
    at CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler) in CompiledQueryCache.cs line: 59
    at QueryCompiler.Execute[TResult](Expression query) in QueryCompiler.cs line: 92
    at EntityQueryProvider.Execute[TResult](Expression expression) in EntityQueryProvider.cs line: 79
    at EntityQueryable`1.GetEnumerator() in EntityQueryable`.cs line: 94
    at LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
    at EnumerableHelpers.ToArray[T](IEnumerable`1 source)
    at Enumerable.ToArray[TSource](IEnumerable`1 source)
```

**Comment by maumar** [comment]
we should throw better exception

**Comment by sitepodmatt** [comment]
Why should an exception be thrown, isn't this in the style of the simplest of aggregation examples?

Interestingly, slighly OT, property name reminds me of a third party database we had the displeasure of using, its columns were all like PostcodeOrEmail, CustomerAgeOrNumberOfChildren etc..

**Comment by smitpatel** [comment]
> isn't this in the style of the simplest of aggregation examples?

It is not. Here GroupBy is forming `IGrouping<string, Gear>`. You can do Min/Max of `IEnumerable<Gear>` on client side but not in server side.

**Comment by maumar** [comment]
@sitepodmatt name is a typo in out model, should be CityOfBirthName. Fixed now - thx for pointing it out.
