### ISSUE TITLE
`Skip` and `Take` throw when used in-between projections with subqueries

### ISSUE THREAD

**Issue by jakubfijalkowski** [aspnet/EntityFrameworkCore#18374]
Hello,

We've discovered a problem with `Skip` and `Take` (I will use only `Skip` from now on but the behavior is the same) that is used between `Select`s (and only when the previous one contains subquery). The problem does not occur if the `Skip` is moved _after_ the last select. This somewhat worked in EFCore 2.2 but stopped working in 3.0. See the attached examples for explanation.

The issue might be related to #18341 since the exception is (in one of the examples) the same, only types differ.

### Steps to reproduce

Runnable project: https://github.com/jakubfijalkowski/EFCore.SkipBug
Or CSX file:
``` C#
#r "nuget: Microsoft.EntityFrameworkCore, 3.0.0"
#r "nuget: Microsoft.EntityFrameworkCore.InMemory, 3.0.0"

using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;

public class RootEntity
{
    public Guid Id { get; set; }
    public List<SubEntity> SubEntities { get; set; } = new List<SubEntity>();
}

public class SubEntity
{
    public RootEntity Root { get; set; }
    public Guid RootId { get; set; }
    public Guid CollectMe { get; set; }
}

public class TestContext : DbContext
{
    public DbSet<RootEntity> RootEntities => Set<RootEntity>();
    public DbSet<SubEntity> SubEntities => Set<SubEntity>();

    public TestContext(DbContextOptions<TestContext> options)
        : base(options)
    { }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        optionsBuilder.UseInMemoryDatabase("bug");
    }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<RootEntity>(e =>
        {
            e.HasKey(i => i.Id);

            e.HasMany(i => i.SubEntities)
                .WithOne(ip => ip.Root)
                .OnDelete(DeleteBehavior.Cascade);
        });

        modelBuilder.Entity<SubEntity>(e =>
        {
            e.HasKey(ip => new { ip.RootId, ip.CollectMe });
        });
    }
}

static async Task Outer_subquery_with_Skip_before_it(TestContext ctx)
{
    await ctx.RootEntities
        .OrderBy(i => i.Id)
        .Select(i => new { Item = i })
        .Skip(1)
        .Select(o => new
        {
            o.Item.Id,
            Ids = o.Item.SubEntities.Select(p => p.CollectMe).ToList(),
        })
        .ToListAsync();
}

static async Task No_subquery_but_two_projections(TestContext ctx)
{
    await ctx.RootEntities
        .OrderBy(i => i.Id)
        .Select(i => new { Item = i })
        .Skip(1)
        .Select(o => new { o.Item.Id })
        .ToListAsync();
}

static async Task Inner_subquery_with_Skip_before_it(TestContext ctx)
{
    await ctx.RootEntities
        .OrderBy(i => i.Id)
        .Select(i => new
        {
            Item = i,
            Ids = i.SubEntities.Select(p => p.CollectMe).ToList(),
        })
        .Skip(1)
        .Select(o => new
        {
            o.Item.Id,
            o.Ids,
        })
        .ToListAsync();
}

static async Task Outer_subquery_with_Skip_after_it(TestContext ctx)
{
    await ctx.RootEntities
        .OrderBy(i => i.Id)
        .Select(i => new { Item = i })
        .Select(o => new
        {
            o.Item.Id,
            Ids = o.Item.SubEntities.Select(p => p.CollectMe).ToList(),
        })
        .Skip(1)
        .ToListAsync();
}

static async Task Inner_subquery_with_Skip_after_it(TestContext ctx)
{
    await ctx.RootEntities
        .OrderBy(i => i.Id)
        .Select(i => new
        {
            Item = i,
            Ids = i.SubEntities.Select(p => p.CollectMe).ToList(),
        })
        .Select(o => new
        {
            o.Item.Id,
            o.Ids,
        })
        .Skip(1)
        .ToListAsync();
}

static async Task Single_projection(TestContext ctx)
{
    await ctx.RootEntities
        .OrderBy(i => i.Id)
        .Skip(1)
        .Select(i => new
        {
            i.Id,
            Ids = i.SubEntities.Select(p => p.CollectMe).ToList(),
        })
        .ToListAsync();
}

[DebuggerStepThrough]
static async Task HandleAsync(this Task task, string name)
{
    System.Console.Write("Testing {0}: ", name);
    try
    {
        await task;
        System.Console.WriteLine("Success!");
    }
    catch (Exception ex)
    {
        System.Console.WriteLine(ex);
    }
    System.Console.WriteLine();
}

var optionsBuilder = new DbContextOptionsBuilder<TestContext>();
await using (var ctx = new TestContext(optionsBuilder.Options))
{
    await ctx.Database.EnsureCreatedAsync();

    await Outer_subquery_with_Skip_before_it(ctx).HandleAsync(nameof(Outer_subquery_with_Skip_before_it)); // Fails
    await Inner_subquery_with_Skip_before_it(ctx).HandleAsync(nameof(Inner_subquery_with_Skip_before_it)); // Fails
    await Outer_subquery_with_Skip_after_it(ctx).HandleAsync(nameof(Outer_subquery_with_Skip_after_it)); // Works
    await Inner_subquery_with_Skip_after_it(ctx).HandleAsync(nameof(Inner_subquery_with_Skip_after_it)); // Works
    await No_subquery_but_two_projections(ctx).HandleAsync(nameof(No_subquery_but_two_projections)); // Works
    await Single_projection(ctx).HandleAsync(nameof(Single_projection)); // Works
}
```

1. `Outer_subquery_with_Skip_before_it` works on 2.2 but does not on 3.0 and fails with
```
System.InvalidOperationException: Processing of the LINQ expression 'AsQueryable<SubEntity>(NavigationTreeExpression
    Value: new { Item = EntityReferenceRootEntity }
    Expression: (Unhandled parameter: e).Item.SubEntities)' by 'NavigationExpandingExpressionVisitor' failed. This may indicate either a bug or a limitation in EF Core. See https://go.microsoft.com/fwlink/?linkid=2101433 for more detailed information.
   at Microsoft.EntityFrameworkCore.Query.Internal.NavigationExpandingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.Internal.NavigationExpandingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.Internal.NavigationExpandingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at System.Dynamic.Utils.ExpressionVisitorUtils.VisitArguments(ExpressionVisitor visitor, IArgumentProvider nodes)
   at System.Linq.Expressions.ExpressionVisitor.VisitNew(NewExpression node)
   at System.Linq.Expressions.NewExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.Internal.NavigationExpandingExpressionVisitor.ExpandNavigationsInExpression(NavigationExpansionExpression source, Expression expression)
   at Microsoft.EntityFrameworkCore.Query.Internal.NavigationExpandingExpressionVisitor.PendingSelectorExpandingExpressionVisitor.Visit(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.Internal.NavigationExpandingExpressionVisitor.ExpandAndReduce(Expression query, Boolean applyInclude)
   at Microsoft.EntityFrameworkCore.Query.Internal.NavigationExpandingExpressionVisitor.Expand(Expression query)
   at Microsoft.EntityFrameworkCore.Query.QueryTranslationPreprocessor.Process(Expression query)
   at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.CreateQueryExecutor[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](Expression query, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass12_0`1.<ExecuteAsync>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQueryCore[TFunc](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteAsync[TResult](Expression query, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.ExecuteAsync[TResult](Expression expression, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1.GetAsyncEnumerator(CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.ConfiguredCancelableAsyncEnumerable`1.GetAsyncEnumerator()
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
   at EFCore.SkipBug.Program.Outer_subquery_with_Skip_before_it(TestContext ctx) in /home/fiolek/Work/Code/tests/EFCore.SkipBug/Program.cs:line 27
   at EFCore.SkipBug.Program.HandleAsync(Task task, String name) in /home/fiolek/Work/Code/tests/EFCore.SkipBug/Program.cs:line 119
```

2. `Inner_subquery_with_Skip_before_it` does not work on neither 2.2 nor 3.0. On 3.0 it fails with
```
System.ArgumentNullException: Value cannot be null. (Parameter 'key')
   at System.Collections.Generic.Dictionary`2.FindEntry(TKey key)
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Microsoft.EntityFrameworkCore.InMemory.Query.Internal.InMemoryQueryExpression.GetMappedProjection(ProjectionMember member)
   at Microsoft.EntityFrameworkCore.InMemory.Query.Internal.InMemoryProjectionBindingExpressionVisitor.VisitExtension(Expression extensionExpression)
   at System.Linq.Expressions.Expression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.InMemory.Query.Internal.InMemoryProjectionBindingExpressionVisitor.Visit(Expression expression)
   at System.Linq.Expressions.ExpressionVisitor.VisitMember(MemberExpression node)
   at System.Linq.Expressions.MemberExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.InMemory.Query.Internal.InMemoryProjectionBindingExpressionVisitor.Visit(Expression expression)
   at Microsoft.EntityFrameworkCore.InMemory.Query.Internal.InMemoryProjectionBindingExpressionVisitor.VisitNew(NewExpression newExpression)
   at System.Linq.Expressions.NewExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.InMemory.Query.Internal.InMemoryProjectionBindingExpressionVisitor.Visit(Expression expression)
   at Microsoft.EntityFrameworkCore.InMemory.Query.Internal.InMemoryProjectionBindingExpressionVisitor.Translate(InMemoryQueryExpression queryExpression, Expression expression)
   at Microsoft.EntityFrameworkCore.InMemory.Query.Internal.InMemoryQueryableMethodTranslatingExpressionVisitor.TranslateSelect(ShapedQueryExpression source, LambdaExpression selector)
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.CreateQueryExecutor[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](Expression query, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass12_0`1.<ExecuteAsync>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQueryCore[TFunc](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteAsync[TResult](Expression query, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.ExecuteAsync[TResult](Expression expression, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1.GetAsyncEnumerator(CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.ConfiguredCancelableAsyncEnumerable`1.GetAsyncEnumerator()
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
   at EFCore.SkipBug.Program.Inner_subquery_with_Skip_before_it(TestContext ctx) in /home/fiolek/Work/Code/tests/EFCore.SkipBug/Program.cs:line 51
   at EFCore.SkipBug.Program.HandleAsync(Task task, String name) in /home/fiolek/Work/Code/tests/EFCore.SkipBug/Program.cs:line 119
```
3. Rest of the examples work.

### Further technical details

EF Core version: 3.0
Database provider: tested on: Microsoft.EntityFrameworkCore.SqlServer, Microsoft.EntityFrameworkCore.Sqlite, Microsoft.EntityFrameworkCore.InMemory
Target framework: .NET Core 3.0, 2.2
Operating system: Arch Linux
IDE: VSCode + OmniSharp

**Comment by smitpatel** [comment]
Repros in nightly.
