### ISSUE TITLE
Cannot Expose Backing Field Collection Navigation Property as Read-Only

### ISSUE THREAD

**Issue by xKloc** [aspnet/EntityFrameworkCore#18523]
I want to expose my collections for my entities as read-only versions of the backing field.

My read-only collection is in a wrapper of the original collection. This is to prevent any casting back to the original collection type and altering it that way.

Is there a way to configure this without getting the exception below?

For example:
``` C#
public class Job
{
    public Guid JobId { get; private set; }
    public string Name { get; private set; } = "";
    public string Description { get; private set; } = "";

    private readonly ICollection<Step> _steps = new HashSet<Step>();
    public IReadOnlyCollection<Step> Steps => _steps.AsReadOnly();

    private Job() { }

    internal void AddStep(Step step)
    {
        _steps.Add(step);
    }
}

public static class ReadOnlyExtensions
{
    public static IReadOnlyCollection<T> AsReadOnly<T>(this ICollection<T> source) => source is null ? null : new ReadOnlyCollectionWrapper<T>(source);
}

internal class ReadOnlyCollectionWrapper<T> : IReadOnlyCollection<T>
{
    private readonly ICollection<T> _source;

    internal ReadOnlyCollectionWrapper(ICollection<T> source)
    {
        _source = source ?? throw new ArgumentNullException(nameof(source));
    }

    public int Count => _source.Count;

    public IEnumerator<T> GetEnumerator() => _source.GetEnumerator();

    IEnumerator IEnumerable.GetEnumerator() => _source.GetEnumerator();
}

public class BloggingContext : DbContext
{
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        optionsBuilder
            .UseSqlServer(@"Server=(localdb)\mssqllocaldb;Database=Test;ConnectRetryCount=0");
    }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Job>();
    }
}

public class Program
{
    public static async Task Main()
    {
        using (var context = new BloggingContext())
        {
            context.Database.EnsureDeleted();
            context.Database.EnsureCreated();

            var job = new Job();
            job.AddStep(new Step());
            context.Add(job);

            context.SaveChanges();
        }

        using (var context = new BloggingContext())
        {
            var jobs = context.Set<Job>().Include(e => e.Steps).ToList();
        }
    }
}
```

### Stack Trace
```
Unhandled exception. System.InvalidOperationException: The type of navigation property 'Steps' on the entity type 'Job' is 'ReadOnlyCollectionWrapper<Step>' which does not implement ICollection<Step>. Collection navigation properties must implement ICollection<> of the target type.
   at Microsoft.EntityFrameworkCore.Metadata.Internal.ClrICollectionAccessor`3.GetCollection(Object instance)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.ClrICollectionAccessor`3.GetOrCreateCollection(Object instance, Boolean forMaterialization)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.ClrICollectionAccessor`3.Add(Object entity, Object value, Boolean forMaterialization)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.AddToCollection(INavigation navigation, InternalEntityEntry value, Boolean forMaterialization)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.NavigationFixer.AddToCollection(InternalEntityEntry entry, INavigation navigation, InternalEntityEntry value, Boolean fromQuery)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.NavigationFixer.SetReferenceOrAddToCollection(InternalEntityEntry entry, INavigation navigation, InternalEntityEntry value, Boolean fromQuery)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.NavigationFixer.ToDependentFixup(InternalEntityEntry dependentEntry, InternalEntityEntry principalEntry, IForeignKey foreignKey, Boolean fromQuery)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.NavigationFixer.InitialFixup(InternalEntityEntry entry, Boolean fromQuery)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.NavigationFixer.StateChanged(InternalEntityEntry entry, EntityState oldState, Boolean fromQuery)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntryNotifier.StateChanged(InternalEntityEntry entry, EntityState oldState, Boolean fromQuery)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.FireStateChanged(EntityState oldState)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.SetEntityState(EntityState oldState, EntityState newState, Boolean acceptChanges, Boolean modifyProperties)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.SetEntityStateAsync(EntityState entityState, Boolean acceptChanges, Boolean modifyProperties, Nullable`1 forceStateWhenUnknownKey, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityGraphAttacher.PaintActionAsync(EntityEntryGraphNode`1 node, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityEntryGraphIterator.TraverseGraphAsync[TState](EntityEntryGraphNode`1 node, Func`3 handleNode, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityEntryGraphIterator.TraverseGraphAsync[TState](EntityEntryGraphNode`1 node, Func`3 handleNode, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.DbContext.AddAsync[TEntity](TEntity entity, CancellationToken cancellationToken)
   at Mpm.Jobs.Data.EntityFrameworkCore.SqlServer.Jobs.JobRepository.Add(Job entity, CancellationToken cancellationToken) in C:\Users\admin\Source\Repos\Mpm.Jobs\Mpm.Jobs.Data.EntityFrameworkCore.SqlServer\Jobs\JobRepository.cs:line 20
   at Mpm.Jobs.Presentation.Administration.Terminal.Program.SeedData(IServiceProvider provider) in C:\Users\admin\Source\Repos\Mpm.Jobs\Mpm.Jobs.Presentation.Administration.Terminal\Program.cs:line 76
   at Mpm.Jobs.Presentation.Administration.Terminal.Program.Main(String[] args) in C:\Users\admin\Source\Repos\Mpm.Jobs\Mpm.Jobs.Presentation.Administration.Terminal\Program.cs:line 33
   at Mpm.Jobs.Presentation.Administration.Terminal.Program.<Main>(String[] args)
```

### Further technical details

EF Core version: 3.0
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET Core 3.0

**Comment by xKloc** [comment]
As a work around. I was able to get this working by changing my backing field from `ICollection<T>` to `HashSet<T>`. I assume that's because `HashSet<T>` implements `IReadOnlyCollection<T>`.

**Comment by ajcvickers** [comment]
@xKloc The code posted above doesn't compile for me, so I am not able to reproduce the exception you are seeing. I made a minimal change to make it compile, still leaving the backing field typed as `ICollection<Step>`, but I still don't get the exception you see.

If this is still an issue for you, then please post a _complete_ code listing (like below) that reproduces the behavior you are seeing.

```C#
public class Step
{
    public Guid Id { get; private set; }
}

public class Job
{
    public Guid JobId { get; private set; }
    public string Name { get; private set; } = "";
    public string Description { get; private set; } = "";

    private readonly ICollection<Step> _steps = new HashSet<Step>();
    public IReadOnlyCollection<Step> Steps => (IReadOnlyCollection<Step>)_steps;

    internal Job() { }

    internal void AddStep(Step step)
    {
        _steps.Add(step);
    }
}

public class BloggingContext : DbContext
{
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        optionsBuilder
            .UseSqlServer(@"Server=(localdb)\mssqllocaldb;Database=Test;ConnectRetryCount=0");
    }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Job>();
    }
}

public class Program
{
    public static async Task Main()
    {
        using (var context = new BloggingContext())
        {
            context.Database.EnsureDeleted();
            context.Database.EnsureCreated();

            var job = new Job();
            job.AddStep(new Step());
            context.Add(job);

            context.SaveChanges();
        }

        using (var context = new BloggingContext())
        {
            var jobs = context.Set<Job>().Include(e => e.Steps).ToList();
        }
    }
}
```

**Comment by xKloc** [comment]
@ajcvickers Sorry, I am using an extension method with a wrapper to expose the collection. This is to prevent casting. I've updated the code with my extension method and wrapper.

Thanks!

**Comment by ajcvickers** [comment]
@xKloc Thanks!

Note for triage: the issue here is that the backing field is not being associated with the navigation property, probably because there is no valid assignment in either way. The check likely needs to be relaxed for collection navigation properties where assignment is (mostly) irrelevant.

Model:
```
  EntityType: Job
    Properties: 
      JobId (Guid) Required PK AfterSave:Throw ValueGenerated.OnAdd
      Description (string)
      Name (string)
    Navigations: 
      Steps (no field, IReadOnlyCollection<Step>) Collection ToDependent Step
    Keys: 
      JobId PK
  EntityType: Step
    Properties: 
      Id (Guid) Required PK AfterSave:Throw ValueGenerated.OnAdd
      JobId (no field, Nullable<Guid>) Shadow FK Index
    Keys: 
      Id PK
    Foreign keys: 
      Step {'JobId'} -> Job {'JobId'} ToDependent: Steps
```
Model when exposed navigation type  is changed to `IEnumerable<Step>`. Notice that `_steps` is now detected as the backing field.
```
  EntityType: Job
    Properties: 
      JobId (Guid) Required PK AfterSave:Throw ValueGenerated.OnAdd
      Description (string)
      Name (string)
    Navigations: 
      Steps (_steps, IEnumerable<Step>) Collection ToDependent Step
    Keys: 
      JobId PK
  EntityType: Step
    Properties: 
      Id (Guid) Required PK AfterSave:Throw ValueGenerated.OnAdd
      JobId (no field, Nullable<Guid>) Shadow FK Index
    Keys: 
      Id PK
    Foreign keys: 
      Step {'JobId'} -> Job {'JobId'} ToDependent: Steps
```

**Comment by mlenart1010** [comment]
@ajcvickers I am having similar issues.  Where did you get the "Model" documentation from Oct 24?

**Comment by ajcvickers** [comment]
@mlenart1010 Drill down to the DbContext.Model.DebugView property in the debugger.

**Comment by mlenart1010** [comment]
@ajcvickers How do I make the backing field to be associated with the navigation property?
