### ISSUE TITLE
ExecutionStrategy ignored when doing ToList() in EF Core 3.0

### ISSUE THREAD

**Issue by 414004738** [aspnet/EntityFrameworkCore#18628]
The configured execution strategy (either a custom one or SqlServerRetryingExecutionStrategy via e.g. EnableRetryOnFailure()) is not being used when ToList() is called on a DbSet.

It does seems to be used when SaveChanges() is called, however.

In EF Core 2.2, the execution strategy would be used for queries (e.g. ToList()) as well as on SaveChanges().

This is causing our queries to fail occasionally due to deadlocks:
```
Microsoft.Data.SqlClient.SqlException (0x80131904): Transaction (Process ID 134) was deadlocked on lock resources with another process and has been chosen as the deadlock victim. Rerun the transaction.
   at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.SqlDataReader.TryHasMoreRows(Boolean& moreRows)
   at Microsoft.Data.SqlClient.SqlDataReader.TryReadInternal(Boolean setTimeout, Boolean& more)
   at Microsoft.Data.SqlClient.SqlDataReader.<>c__DisplayClass195_0.<ReadAsync>b__1(Task t)
   at Microsoft.Data.SqlClient.SqlDataReader.InvokeRetryable[T](Func`2 moreFunc, TaskCompletionSource`1 source, IDisposable objectToDispose)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.EntityFrameworkCore.Query.RelationalShapedQueryCompilingExpressionVisitor.AsyncQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
```
without it attempting to retry.

### Steps to reproduce

1. Create a custom execution strategy:
``` C#
public class TestExecutionStrategy : SqlServerRetryingExecutionStrategy
{
    public TestExecutionStrategy(ExecutionStrategyDependencies dependencies) : base(dependencies)
    {
    }

    protected override void OnFirstExecution()
    {
        Console.WriteLine("OnFirstExecutionCalled");
        base.OnFirstExecution();
    }
}
```

2. Configure DbContext to use custom execution strategy:
``` C#
services.AddDbContext<TestDbContext>(o =>
    o.UseSqlServer(connectionString,
        options => options.ExecutionStrategy(d => new TestExecutionStrategy(d))));
```

3. Call a method that does a ToList() on a DbSet:
``` C#
List<Order> orders = _dbContext.Orders.ToList();
```

4. Note that OnFirstExecution() is not called.

### Further technical details

EF Core version: 3.0.0
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET Core 3.0
Operating system: macOS High Sierra
IDE: Rider 2019.2.3

**Comment by ajcvickers** [comment]
@AndriySvyryd Thoughts?
