### ISSUE TITLE
Case-sensitive parameter names

### ISSUE THREAD

**Issue by zabolotnev** [aspnet/EntityFrameworkCore#18861]
I'm used to all IDbCommand implementations have case insensitive parameter names. This is true for the SqlClient namespace and the System.Data.SQLite package. This feature is very useful, but when I started using the Microsoft.Data.Sqlite package, I got an error:
System.InvalidOperationException: 'Must add values for the following parameters'

### To Reproduce

``` C#
    class TestClass
    {
        public static void Test()
        {
            var f = "testdb.sqlite";
            if (File.Exists(f))
            {
                File.Delete(f);
            }
            using (var conn = new SqliteConnection("Data source = " + f))
            {
                conn.Open();
                var cmd = conn.CreateCommand();
                cmd.CommandText = "Create table test(f1 integer)";
                cmd.ExecuteNonQuery();

                cmd.CommandText = "select * from test where f1 = @PRM";

                var p = cmd.CreateParameter();
                p.ParameterName = "@prm";
                p.Value = 1;
                cmd.Parameters.Add(p);

                using (cmd.ExecuteReader()) { }

            }
        }
    }
```
Result:
```
System.InvalidOperationException
  HResult=0x80131509
  Message=Must add values for the following parameters: @PRM
  Source=Microsoft.Data.Sqlite
  StackTrace:
   at Microsoft.Data.Sqlite.SqliteCommand.<GetStatements>d__54.MoveNext()
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader()
   at ConsoleApp14.TestMS.Test() in D:\Projects\ConsoleApp14\TestMS.cs:line 34
```
### Additional context

I found the reason of case-sensitivity here: https://github.com/aspnet/EntityFrameworkCore/blob/master/src/Microsoft.Data.Sqlite.Core/SqliteCommand.cs
Line 336:
``` C#
if (_parameters.IsValueCreated
&& !_parameters.Value.Cast<SqliteParameter>().Any(p => p.ParameterName == name))
```
Equality operator == is case sensitive.

For example, System.Data.SQLite uses this method of compare:
https://github.com/OpenDataSpace/System.Data.SQLite/blob/master/System.Data.SQLite/SQLiteStatement.cs
Line 209:
``` C#
if (String.Compare(_paramNames[n], startAt, s, 0, Math.Max(_paramNames[n].Length - startAt, s.Length), StringComparison.OrdinalIgnoreCase) == 0)
```

Microsoft.Data.Sqlite version: 3.1.0-preview2.19525.5
Target framework: .NET 4.8, Xamarin
Operating system: Windows, Android

**Comment by ajcvickers** [comment]
@zabolotnev Thanks for filing this issue. We will discuss in our next triage meeting.

/cc @bricelam

**Comment by bricelam** [comment]
Parameters are case-sensitive in SQLite:
```cs
command.CommandText = "SELECT $A, $a, @A, @a, :A, :a";
command.Parameters.AddWithValue("$A", 1L);
command.Parameters.AddWithValue("$a", 2L);
command.Parameters.AddWithValue("@A", 3L);
command.Parameters.AddWithValue("@a", 4L);
command.Parameters.AddWithValue(":A", 5L);
command.Parameters.AddWithValue(":a", 6L);
```

It would be a nice enhancement, however, to be case-forgiving when the name is not ambiguous.

**Comment by ThiagoKoster** [comment]
Hi, I want to contribute to an open source project for the first time, and since this issue has a "good first issue" tag I would like to try this one. I already downloaded the project and saw where I could do the change.  I can already start?
Thanks in advance!

**Comment by bricelam** [comment]
@ThiagoKoster Feel free to submit a PR. We can work through any implementation details there that come up.

**Comment by KevRitchie** [comment]
Hi @bricelam, is this still up for grabs?  @ThiagoKoster, do you still want to take this one?

**Comment by bricelam** [comment]
Yep, go for it

**Comment by KevRitchie** [comment]
@roji no problem at all.  It's all experience 😄 Do you want me keep the PR open for now or close it?

**Comment by ThiagoKoster** [comment]
You can take it!

**Comment by roji** [comment]
One more note for completeness... Just doing a single insensitive list pass is problematic also because an earlier parameter may match insensitively where there's a later parameter that could match sensitively.

**Comment by muralitharaan** [comment]
When we expect this fix ?

**Comment by roji** [comment]
This issue is in the Backlog milestone. This means that it is not planned for the next release (EF Core 8.0). We will [re-assess the backlog](https://docs.microsoft.com/ef/core/what-is-new/release-planning) following the this release and consider this item at that time. However, keep in mind that there are many other high priority features with which it will be competing for resources. Make sure to vote (👍) for this issue if it is important to you.
