### ISSUE TITLE
NorthwindAggregateOperatorsQueryCosmosTest.Distinct_Scalar fails on CI

### ISSUE THREAD

**Issue by AndriySvyryd** [aspnet/EntityFrameworkCore#27688]
Microsoft.EntityFrameworkCore.Query.NorthwindAggregateOperatorsQueryCosmosTest.Distinct_Scalar(async: True)

> Assert.Equal() Failure
> Expected: 69
> Actual:   68
> 
> at Microsoft.EntityFrameworkCore.TestUtilities.TestHelpers.AssertResults[T](IList`1 expected, IList`1 actual, Func`2 elementSorter, Action`2 elementAsserter, Boolean verifyOrdered) in /_/test/EFCore.Specification.Tests/TestUtilities/TestHelpers.cs:line 255
> at Microsoft.EntityFrameworkCore.TestUtilities.QueryAsserter.AssertQuery[TResult](Func`2 actualQuery, Func`2 expectedQuery, Func`2 elementSorter, Action`2 elementAsserter, Boolean assertOrder, Int32 entryCount, Boolean async, String testMethodName, Boolean filteredQuery) in /_/test/EFCore.Specification.Tests/TestUtilities/QueryAsserter.cs:line 135
> at Microsoft.EntityFrameworkCore.Query.NorthwindAggregateOperatorsQueryCosmosTest.Distinct_Scalar(Boolean async) in /_/test/EFCore.Cosmos.FunctionalTests/Query/NorthwindAggregateOperatorsQueryCosmosTest.cs:line 909

**Comment by Marusyk** [comment]
It seems everything is fine
![image](https://user-images.githubusercontent.com/9221694/170847532-8cba69e2-1ab2-4fba-8aff-5813735173ad.png)
![image](https://user-images.githubusercontent.com/9221694/170847526-17f608da-5bed-411f-9be9-0502b174e488.png)

**Comment by AndriySvyryd** [comment]
Yes, it only fails on CI, locally it passes fine
