### ISSUE TITLE
Can't generate a migration bundle when using IronPdf for Linux. The "GenerateBundle" task failed unexpectedly. 

### ISSUE THREAD

**Issue by leodip** [aspnet/EntityFrameworkCore#27753]
Hi,

We have a .NET 6 Web Api project that uses the package **IronPdf.Linux (Version 2022.3.5084)**.

The library is working fine for its purpose, that is, to generate PDFs from HTML.

The problem we're seeing is related to how IronPdf Linux integrates with our build pipeline in Azure Devops, specifically when the pipeline is generating the EF Core migration bundle.

Our build agent runs Linux (Ubuntu 20.04).

We're using the following command to generate the bundle:

`dotnet ef migrations bundle -v -o $(Build.SourcesDirectory)/migrations/document_efbundle        `

The error that we get is:

 ```
document_efbundle -> /tmp/l0ksr4nb.zn5/bin/Debug/net6.0/ubuntu.20.04-x64/document_efbundle.dll
/usr/share/dotnet/sdk/6.0.201/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Publish.targets(898,5): error MSB4018: The "GenerateBundle" task failed unexpectedly. [/tmp/l0ksr4nb.zn5/document_efbundle.csproj]
/usr/share/dotnet/sdk/6.0.201/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Publish.targets(898,5): error MSB4018: System.ArgumentException: Invalid input specification: Found entries '/tmp/DOTNET_CLI_HOME/.nuget/packages/ironpdf.native.chrome.linux/2022.3.5075/runtimes/linux-x64/native/swiftshader/libGLESv2.so' and '/tmp/DOTNET_CLI_HOME/.nuget/packages/ironpdf.native.chrome.linux/2022.3.5075/runtimes/linux-x64/native/libGLESv2.so' with the same BundleRelativePath 'libGLESv2.so' [/tmp/l0ksr4nb.zn5/document_efbundle.csproj]
/usr/share/dotnet/sdk/6.0.201/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Publish.targets(898,5): error MSB4018:    at Microsoft.NET.HostModel.Bundle.Bundler.GenerateBundle(IReadOnlyList`1 fileSpecs) [/tmp/l0ksr4nb.zn5/document_efbundle.csproj]
/usr/share/dotnet/sdk/6.0.201/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Publish.targets(898,5): error MSB4018:    at Microsoft.NET.Build.Tasks.GenerateBundle.ExecuteCore() [/tmp/l0ksr4nb.zn5/document_efbundle.csproj]
/usr/share/dotnet/sdk/6.0.201/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Publish.targets(898,5): error MSB4018:    at Microsoft.NET.Build.Tasks.TaskBase.Execute() [/tmp/l0ksr4nb.zn5/document_efbundle.csproj]
/usr/share/dotnet/sdk/6.0.201/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Publish.targets(898,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute() [/tmp/l0ksr4nb.zn5/document_efbundle.csproj]
/usr/share/dotnet/sdk/6.0.201/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Publish.targets(898,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask(ITaskExecutionHost taskExecutionHost, TaskLoggingContext taskLoggingContext, TaskHost taskHost, ItemBucket bucket, TaskExecutionMode howToExecuteTask) [/tmp/l0ksr4nb.zn5/document_efbundle.csproj]
Microsoft.EntityFrameworkCore.Tools.CommandException: Build failed. Use --verbose to see errors.
   at Microsoft.EntityFrameworkCore.Tools.Commands.MigrationsBundleCommand.Execute(String[] args)
   at Microsoft.EntityFrameworkCore.Tools.Commands.CommandBase.<>c__DisplayClass0_0.<Configure>b__0(String[] args)
   at Microsoft.DotNet.Cli.CommandLine.CommandLineApplication.Execute(String[] args)
   at Microsoft.EntityFrameworkCore.Tools.Program.Main(String[] args)
Build failed. Use --verbose to see errors.
```

Are you aware of this issue? Is there a fix or workaround?

### version information

.NET SDK 6.0.201
EF Core .NET Command-line Tools 6.0.3
IronPdf.Linux: Version 2022.3.5084
Operating system: Linux (Ubuntu 20.04).

### steps to reproduce

- Use this code: https://github.com/leodip/IronPdfTest

- Start an Ubuntu (20.04) machine - maybe other Linux distros will produce the same output

- Install the .NET SDK and .NET EF Core Tools in Ubuntu

- Go to the folder where `IronPdfTest.csproj` is.

- Use this command:

`dotnet ef migrations bundle -v -o /tmp/bundle`

**Comment by ajcvickers** [comment]
Note from triage: its unlikely that there is anything we can do here, but we will investigate.

**Comment by leodip** [comment]
Thank you @ajcvickers . 

I'm not certain what the solution would be either. 

In practice, a nuget package that is, perhaps, not well built, or not correctly formed, is breaking the EF bundle generation. 

In general project owners can't just remove nuget packages from their projects. And the project owner might not have any control over how the nuget package is built... It's a pity that, in my case, I have to make a choice between using IronPDF or using EF migrations bundle in my build pipeline.

I understand in the bundle generation there is a "dotnet publish" step. Is there anything the EF team can do, to prevent that "dotnet publish" step from breaking the bundle generation as a whole, when there's a malformed nuget package?

Even some documentation would help, on how the nuget packages should be built, so companies creating them would know the steps to fix.

Thanks again,
Leonardo

**Comment by bricelam** [comment]
If I had to guess, this is probably an issue with the way the IronPdf.Native.Chrome.Linux package is authored. For some reason it's including two versions of the same file:

* ironpdf.native.chrome.linux/2022.3.5075/runtimes/linux-x64/native/swiftshader/libGLESv2.so
* ironpdf.native.chrome.linux/2022.3.5075/runtimes/linux-x64/native/libGLESv2.so

**Comment by leodip** [comment]
Yes, @bricelam , I think that's it.
And the files have different sizes, so they are different files with the same name. I'm not sure if both are required...

I had to revert our solution to using idempotent SQL scripts for migrations, in the azure pipeline. It would be nice to be able to use EF bundles again.

**Comment by marcoatribeiro** [comment]
Hi everyone,

Not sure if there is already a solution / workaround for this issue, but it also occurs with Syncfusion.PdfViewer package:

```
efbundle -> C:\Users\VssAdministrator\AppData\Local\Temp\rkzlqcki.ghs\bin\Debug\net7.0\win10-x64\efbundle.dll
C:\hostedtoolcache\windows\dotnet\sdk\7.0.200\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Publish.targets(906,5): error MSB4018: The "GenerateBundle" task failed unexpectedly. [C:\Users\VssAdministrator\AppData\Local\Temp\rkzlqcki.ghs\efbundle.csproj]
C:\hostedtoolcache\windows\dotnet\sdk\7.0.200\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Publish.targets(906,5): error MSB4018: System.ArgumentException: Invalid input specification: Found entries 'D:\a\1\.nuget\packages\syncfusion.pdfviewer.aspnet.core.windows\20.4.0.38\lib\netstandard2.0\Pdfium(x86)\pdfium.dll' and 'D:\a\1\.nuget\packages\syncfusion.pdfviewer.aspnet.core.windows\20.4.0.38\lib\netstandard2.0\Pdfium(x64)\pdfium.dll' with the same BundleRelativePath 'x86\pdfium.dll' [C:\Users\VssAdministrator\AppData\Local\Temp\rkzlqcki.ghs\efbundle.csproj]
C:\hostedtoolcache\windows\dotnet\sdk\7.0.200\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Publish.targets(906,5): error MSB4018:    at Microsoft.NET.HostModel.Bundle.Bundler.GenerateBundle(IReadOnlyList`1 fileSpecs) [C:\Users\VssAdministrator\AppData\Local\Temp\rkzlqcki.ghs\efbundle.csproj]
C:\hostedtoolcache\windows\dotnet\sdk\7.0.200\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Publish.targets(906,5): error MSB4018:    at Microsoft.NET.Build.Tasks.GenerateBundle.ExecuteCore() [C:\Users\VssAdministrator\AppData\Local\Temp\rkzlqcki.ghs\efbundle.csproj]
C:\hostedtoolcache\windows\dotnet\sdk\7.0.200\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Publish.targets(906,5): error MSB4018:    at Microsoft.NET.Build.Tasks.TaskBase.Execute() [C:\Users\VssAdministrator\AppData\Local\Temp\rkzlqcki.ghs\efbundle.csproj]
C:\hostedtoolcache\windows\dotnet\sdk\7.0.200\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Publish.targets(906,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute() [C:\Users\VssAdministrator\AppData\Local\Temp\rkzlqcki.ghs\efbundle.csproj]
C:\hostedtoolcache\windows\dotnet\sdk\7.0.200\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Publish.targets(906,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask(ITaskExecutionHost taskExecutionHost, TaskLoggingContext taskLoggingContext, TaskHost taskHost, ItemBucket bucket, TaskExecutionMode howToExecuteTask) [C:\Users\VssAdministrator\AppData\Local\Temp\rkzlqcki.ghs\efbundle.csproj]
```
