### ISSUE TITLE
Suggest using detailed errors in QueryIterationFailed message

### ISSUE THREAD

**Issue by fairking** [aspnet/EntityFrameworkCore#30397]
The error:
```
CoreEventId.QueryIterationFailed[10100] (Microsoft.EntityFrameworkCore.Query) 
      An exception occurred while iterating over the results of a query for context type 'MyProject.DbContext'.
      System.InvalidCastException: Unable to cast object of type 'System.String' to type 'System.Int32'.
         at Microsoft.Data.SqlClient.SqlBuffer.get_Int32()
         at lambda_method4212(Closure , QueryContext , DbDataReader , ResultContext , SingleQueryResultCoordinator )
         at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
```

The above error does not describe which table / column has an issue. I have spent many hours on investigation of this issue.

Please include the column name into the exception message. Thanks.

**Comment by ajcvickers** [comment]
@fairking You can turn on [detailed errors for queries](https://learn.microsoft.com/en-us/ef/core/logging-events-diagnostics/extensions-logging?tabs=v3#detailed-query-exceptions), but there is overhead involved, so you'll probably only want to do it for debugging.

Note for triage: we should point to this in the exception message above.
