### ISSUE TITLE
Support "file" scoped types as entity types

### ISSUE THREAD

**Issue by almosmokus** [aspnet/EntityFrameworkCore#32323]
**IndexOutOfRangeException** occurs in NavigationExpandingExpressionVisitor.CreateNavigationExpansionExpression on this line:
```c#
var parameterName = GetParameterName(entityType.ShortName()[0].ToString().ToLowerInvariant());
``` 
when the entity type is a **file class**. In other words, the implementation of ShortName() is not prepared to handle file classes.

### Reproduction sample code

Console app:
```C#
using Microsoft.EntityFrameworkCore;

namespace EfCoreError;

internal class Program
{
    static async Task Main()
    {
        using var context = new MyContext();
        await context.Set<MyEntity>().ToListAsync();
    }
}

class MyContext : DbContext
{
    public MyContext()
        : base(new DbContextOptionsBuilder()
               .UseSqlServer("data source=localhost;initial catalog=master;integrated security=true;encrypt=true")
               .Options)
    { }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
        => modelBuilder.Entity<MyEntity>().HasNoKey();
}

file class MyEntity
{
    public int Id { get; set; }
}
```

### Stack trace

```
   at Microsoft.EntityFrameworkCore.Query.Internal.NavigationExpandingExpressionVisitor.CreateNavigationExpansionExpression(Expression sourceExpression, IEntityType entityType)
   at Microsoft.EntityFrameworkCore.Query.Internal.NavigationExpandingExpressionVisitor.VisitExtension(Expression extensionExpression)
   at Microsoft.EntityFrameworkCore.Query.Internal.NavigationExpandingExpressionVisitor.Expand(Expression query)
   at Microsoft.EntityFrameworkCore.Query.QueryTranslationPreprocessor.Process(Expression query)
   at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.CreateQueryExecutor[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](Expression query, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass12_0`1.<ExecuteAsync>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteAsync[TResult](Expression query, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.ExecuteAsync[TResult](Expression expression, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1.GetAsyncEnumerator(CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.System.Collections.Generic.IAsyncEnumerable<TEntity>.GetAsyncEnumerator(CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.ConfiguredCancelableAsyncEnumerable`1.GetAsyncEnumerator()
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.<ToListAsync>d__67`1.MoveNext()
   at EfCoreError.Program.<Main>d__0.MoveNext() in ...\Program.cs:line 11
```

### Provider and version information

EF Core version: 8.0, 7.0 (others may be affected too)
Database provider: Microsoft.EntityFrameworkCore.SqlServer (others may be affected too)
Target framework: 8.0 (others may be affected too)
Operating system: Windows 10 (others may be affected too)
IDE: Visual Studio 2022 17.8

**Comment by ajcvickers** [comment]
Note for triage: this happens with `file class MyEntity` but not with `public class MyEntity`.

Repro:

```C#
using var context = new MyContext();

await context.Database.EnsureDeletedAsync();
await context.Database.EnsureCreatedAsync();

await context.Set<MyEntity>().ToListAsync();

class MyContext : DbContext
{
    public MyContext()
        : base(new DbContextOptionsBuilder()
             .UseSqlServer(@"Data Source=(LocalDb)\MSSQLLocalDB;Database=AllTogetherNow")
             .LogTo(Console.WriteLine, LogLevel.Information)
             .EnableSensitiveDataLogging()
            .Options)
    { }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
        => modelBuilder.Entity<MyEntity>().HasNoKey();
}

file class MyEntity
{
    public int Id { get; set; }
}
```
