### ISSUE TITLE
Query :: projecting FirstOrDefault() on empty collection of value types may cause NRE (generated SQL returns null rather than 0)

### ISSUE THREAD

**Issue by maumar** [aspnet/EntityFrameworkCore#6061]
query:

``` cs
from c in cs
where c.CustomerID.Equals("FISSA")
select new { c.CustomerID, OrderId = c.Orders.OrderBy(o => o.OrderID).Select(o => o.OrderID).FirstOrDefault() }
```

query plan:

```
TRACKED: False
(QueryContext queryContext) => IEnumerable<<>f__AnonymousType132<string, int>> _Select(
    source: IEnumerable<ValueBuffer> _ShapedQuery(
        queryContext: queryContext, 
        shaperCommandContext: SelectExpression: 
            SELECT [c].[CustomerID], (
                SELECT TOP(1) [o0].[OrderID]
                FROM [Orders] AS [o0]
                WHERE [c].[CustomerID] = [o0].[CustomerID]
                ORDER BY [o0].[OrderID]
            )
            FROM [Customers] AS [c]
            WHERE [c].[CustomerID] = N'FISSA'
        , 
        shaper: ValueBufferShaper
    )
    , 
    selector: (ValueBuffer c) => new <>f__AnonymousType132<string, int>(
        (string) object c.get_Item(0), 
        (int) object c.get_Item(1)
    )
)
```

this query will return {FISSA, NULL}, rather than {FISSA, 0}, which causes the error

**Comment by smitpatel** [comment]
Exception:
```
arting:    Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests
    Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests.QueryNavigationsSqlServerTest.Project_first_or_default_on_empty_collection_of_value_types_returns_proper_default [FAIL]
      System.NullReferenceException : Object reference not set to an instance of an object.
      Stack Trace:
           at lambda_method(Closure , ValueBuffer )
           at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
        D:\EntityFramework\src\Microsoft.EntityFrameworkCore\Query\Internal\LinqOperatorProvider.cs(147,0): at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
           at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source, Int32& length)
           at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
           at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
        D:\EntityFramework\src\Microsoft.EntityFrameworkCore.Specification.Tests\QueryNavigationsTestBase.cs(971,0): at Microsoft.EntityFrameworkCore.Specification.Tests.QueryNavigationsTestBase`1.AssertQuery[TItem](Func`2 efQuery, Func`2 l2oQuery, Boolean assertOrder, Int32 entryCount, Action`2 asserter)
        D:\EntityFramework\src\Microsoft.EntityFrameworkCore.Specification.Tests\QueryNavigationsTestBase.cs(852,0): at Microsoft.EntityFrameworkCore.Specification.Tests.QueryNavigationsTestBase`1.Project_first_or_default_on_empty_collection_of_value_types_returns_proper_default()
        D:\EntityFramework\test\Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests\QueryNavigationsSqlServerTest.cs(1056,0): at Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests.QueryNavigationsSqlServerTest.Project_first_or_default_on_empty_collection_of_value_types_returns_proper_default()
  Finished:    Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests
```
