### ISSUE TITLE
Query: EF expression visitor can throw with in-memory store for null parameter values

### ISSUE THREAD

**Issue by ajcvickers** [aspnet/EntityFrameworkCore#6129]
This is a query such as we use for Load if the FK happens to be null. It works on the relational providers, but not for in-memory.

``` C#
public class BloggingContext : DbContext
{
    public DbSet<Blog> Blogs { get; set; }
    public DbSet<Post> Posts { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder.UseInMemoryDatabase();
        //=> optionsBuilder.UseSqlServer(@"Server=(localdb)\mssqllocaldb;Database=WonkyVB;Trusted_Connection=True;");
}

public class Blog
{
    public int Id { get; set; }
    public string Title { get; set; }

    public ICollection<Post> Posts { get; set; } 
}

public class Post
{
    public int Id { get; set; }
    public string Title { get; set; }

    public int? BlogId { get; set; }
    public Blog Blog { get; set; }
}

public class Program
{
    public static void Main()
    {
        using (var context = new BloggingContext())
        {
            context.Database.EnsureDeleted();
            context.Database.EnsureCreated();

            context.Add(new Blog { Posts = new List<Post> { new Post(), new Post() } });
            context.SaveChanges();
        }

        using (var context = new BloggingContext())
        {
            object fk = null;
            context.Blogs.Where(p => p.Id == (int)fk).ToList();
        }
    }
}
```

Stack:

```
Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.DefaultQueryExpressionVisitor.GetParameterValue[T](QueryContext queryContext, String parameterName)
   at lambda_method(Closure , Blog )
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.<_TrackEntities>d__15`2.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at ListenerTest.Program.Main() in C:\Stuff\ListenerTest\ListenerTest\Program.cs:line 58
```

**Comment by divega** [comment]
Clearing up milestone, as this seems worth discussing together with other unexpected `NullReferenceException` cases.

**Comment by divega** [comment]
**Triage:** moving this back to the backlog after discussing because it seems to be a less common issue than null navigation properties. We will prioritize it if we get more customer feedback.

**Comment by smitpatel** [comment]
```
    Entity Framework Core 3.1.0-preview3.19561.11 initialized 'MyContext' using provider 'Microsoft.EntityFrameworkCore.InMemory' with options: SensitiveDataLoggingEnabled StoreName=_modelApp
Unhandled exception. System.InvalidOperationException: An exception was thrown while attempting to evaluate the LINQ query parameter expression 'Convert(value(EFSampleApp.Program+<>c__DisplayClass0_0).fk, Int32)'.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
```
The convert node throws it off but it is expected error.
If convert node is not used (that is using fk as int?)` then it works correctly.
