### ISSUE TITLE
Query: Exception when using AutoMapper's ProjectTo: Message=variable 'x' of type 'Y' referenced from scope '', but it is not defined 

### ISSUE THREAD

**Issue by slubowsky** [aspnet/EntityFrameworkCore#9029]
Using AutoMapper, generated SQL causes exceptions. Identical code works in Entity Framework 6.
See https://github.com/AutoMapper/AutoMapper/issues/2174

Not reproduced in the gist provided but at one point during my exploration I had it where the call to entity framework core simply never returned, I was able to see the generated SQL logged but then it never returned data and the program simply sat there doing nothing. No errors, no return, just frozen.

Different exceptions in .NET Core 1.1 and .NET Core 2.0 Preview 2. Below is the 2.0 Preview 2 error:
```
System.InvalidOperationException occurred
  HResult=0x80131509
  Message=variable 'markerPersonReferenceNumber' of type 'ConsoleApp.SQLite.PersonReferenceNumber' referenced from scope '', but it is not defined
  Source=<Cannot evaluate the exception source>
  StackTrace:
   at System.Linq.Expressions.Compiler.VariableBinder.Reference(ParameterExpression node, VariableStorageKind storage)
   at System.Linq.Expressions.Compiler.VariableBinder.VisitParameter(ParameterExpression node)
   at System.Linq.Expressions.ParameterExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.Compiler.VariableBinder.Visit(Expression node)
   at System.Linq.Expressions.ExpressionVisitor.VisitBinary(BinaryExpression node)
   at System.Linq.Expressions.BinaryExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.Compiler.VariableBinder.Visit(Expression node)
   at System.Linq.Expressions.ExpressionVisitor.VisitConditional(ConditionalExpression node)
   at System.Linq.Expressions.ConditionalExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.Compiler.VariableBinder.Visit(Expression node)
   at System.Linq.Expressions.ExpressionVisitor.VisitMemberAssignment(MemberAssignment node)
   at System.Linq.Expressions.ExpressionVisitor.VisitMemberBinding(MemberBinding node)
   at System.Linq.Expressions.ExpressionVisitor.Visit[T](ReadOnlyCollection`1 nodes, Func`2 elementVisitor)
   at System.Linq.Expressions.ExpressionVisitor.VisitMemberInit(MemberInitExpression node)
   at System.Linq.Expressions.MemberInitExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.Compiler.VariableBinder.Visit(Expression node)
   at System.Linq.Expressions.ExpressionVisitor.Visit(ReadOnlyCollection`1 nodes)
   at System.Linq.Expressions.Compiler.VariableBinder.VisitLambda[T](Expression`1 node)
   at System.Linq.Expressions.Expression`1.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.Compiler.VariableBinder.Visit(Expression node)
   at System.Linq.Expressions.Compiler.LambdaCompiler.Compile(LambdaExpression lambda)
   at System.Linq.Expressions.LambdaExpression.Compile()
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.ProjectionShaper.Create(Shaper originalShaper, LambdaExpression materializer)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor.VisitSelectClause(SelectClause selectClause, QueryModel queryModel)
   at Remotion.Linq.Clauses.SelectClause.Accept(IQueryModelVisitor visitor, QueryModel queryModel)
   at Remotion.Linq.QueryModelVisitorBase.VisitQueryModel(QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.VisitQueryModel(QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor.VisitQueryModel(QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.CreateQueryExecutor[TResult](QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](Expression query, INodeTypeProvider nodeTypeProvider, IDatabase database, IDiagnosticsLogger`1 logger, Type contextType)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass15_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQueryCore[TFunc](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
   at System.Linq.Queryable.FirstOrDefault[TSource](IQueryable`1 source)
   at ConsoleApp.SQLite.Program.Main() in C:\dev\ConsoleApp.SQLite\Program.cs:line 25
```
The .error in .NET Core 1.1 is something like below (didnt actually run the gist in 1.1)
```
System.ArgumentNullException: Value cannot be null.
Parameter name: querySource
   at Remotion.Utilities.ArgumentUtility.CheckNotNull[T](String argumentName, T actualValue)
   at Remotion.Linq.Clauses.Expressions.QuerySourceReferenceExpression..ctor(IQuerySource querySource)
....
```
### Steps to reproduce
Gist here - https://gist.github.com/slubowsky/d992fd34a5e648b3c0f4fd0b0a915944

### Further technical details
EF Core version: (found in project.json or packages.config)
Tried 2.0.0-preview2-final and 1.1.2

Database Provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)
Tried Microsoft.EntityFrameworkCore.Sqlite and Microsoft.EntityFrameworkCore.SqlServer

Operating system: 
Windows 10

IDE: (e.g. Visual Studio 2015)
Visual Studio 2107

**Comment by anpete** [comment]
@slubowsky Just to confirm, the query works fine without AutoMapper in the picture?

**Comment by slubowsky** [comment]
If I do a straight projection, then yes:
```
var result = context.Persons.Select(p => new
            {
                Id = p.Id,
                Name = p.Name,
                PersonReferenceNumbers = p.PersonReferenceNumbers
            });
```

This particular one does - but my real one, which is not completely duplicated here does not. It actually freezes (no exceptions, no return) whether I use AutoMapper or not. That may be a different issue. I wasn't yet able to duplicate that behavior in a simple use case (but I believe its related as my real use case builds on this one and adds more projections).

**Comment by anpete** [comment]
Is the complex freezing case an async query?

**Comment by slubowsky** [comment]
yes it is async

**Comment by anpete** [comment]
Sorry you are hitting that. I think it is this issue: https://github.com/aspnet/EntityFramework/issues/8208

**Comment by slubowsky** [comment]
Yes, that looks like it's probably my other ssue. Seems like that's going to come up a lot especially when people try to use AutoMapper and write mapping functions that won't work with async.
Interesting that the problem doesn't seem to occur (at least in my user cases) until .Net 2.0 preview 2. The same code runs without issues in. Net 1.1 and .net 2.0 preview 1.
In any event the bug actually described in this issue is unrelated to async.

**Comment by divega** [comment]
@anpete do you think the issue tracked here was the same as https://github.com/aspnet/EntityFrameworkCore/issues/9128 or does this one still belong in the backlog?

**Comment by slubowsky** [comment]
@divega The one documented in #9128 was a separate issue. That one I believe has been fixed in the latest bits. At the time I wrote this issue I did not yet understand that the async deadlock issue was a separate issue as both were caused by one query in my code.

This one is still as issue as of today. Running the gist provided in the original comment even with entity framework core 2.1.0 preview still fails with:

```
Exception thrown: 'System.InvalidOperationException' in System.Linq.Expressions.dll
An unhandled exception of type 'System.InvalidOperationException' occurred in System.Linq.Expressions.dll
variable 'markerPersonReferenceNumber' of type 'ConsoleApp.SQLite.PersonReferenceNumber' referenced from scope '', but it is not defined
```

Project configuration for today is:
```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="6.1.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="2.1.0-preview1-26892" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="2.1.0-preview1-26892" />
  </ItemGroup>
</Project>
```

**Comment by divega** [comment]
Thanks for the details @slubowsky. I will update the title to reflect that.

**Comment by slubowsky** [comment]
With current versions (EntityFrameworkCore 2.0.1 and AutoMapper 6.2.0) this now  appears to work so closing issue
