### ISSUE TITLE
GroupJoin + Any exception

### ISSUE THREAD

**Issue by artyomszasa** [aspnet/EntityFrameworkCore#9248]
Describe what is not working as expected.

Exception is thrown is using Queryable.Any on group-joined query.

```
Unhandled Exception: System.ArgumentException: Expression of type 'System.Collections.Generic.IEnumerable`1[System.Collections.Generic.IEnumerable`1[<>f__AnonymousType0`3[System.Int32,System.String,EFAny.UserEMail[]]]]' cannot be used for return type 'System.Collections.Generic.IEnumerable`1[System.Boolean]'
   at System.Linq.Expressions.Expression.ValidateLambdaArgs(Type delegateType, Expression& body, ReadOnlyCollection`1 parameters, String paramName)
   at System.Linq.Expressions.Expression.Lambda[TDelegate](Expression body, String name, Boolean tailCall, IEnumerable`1 parameters)
   at System.Linq.Expressions.Expression.Lambda[TDelegate](Expression body, Boolean tailCall, IEnumerable`1 parameters)
   at System.Linq.Expressions.Expression.Lambda[TDelegate](Expression body, ParameterExpression[] parameters)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.CreateExecutorLambda[TResults]()
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.CreateQueryExecutor[TResult](QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](Expression query, INodeTypeProvider nodeTypeProvider, IDatabase database, ILogger logger, Type contextType)
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQueryCore[TFunc](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at System.Linq.Queryable.Any[TSource](IQueryable`1 source)
```

### Steps to reproduce

Issue can be reproduced easily, see: [Gist](https://gist.github.com/artyomszasa/a69174f8a11fd8d6b25aba86d83df738)

### Further technical details
EF Core version: 1.1.2
Database Provider: Npgsql.EntityFrameworkCore.PostgreSQL (yet issue is reproducible with other providers)
Operating system: Windows 10, Ubuntu
IDE: Visual Studio 2015/Visual Studio Code + OmniSharp

**Comment by maumar** [comment]
This works in current bits, closing
