### ISSUE TITLE
SimpleQueryTestBase.Projection_when_arithmetic tests throw

### ISSUE THREAD

**Issue by AndriySvyryd** [aspnet/EntityFrameworkCore#9341]
Projection_when_arithmetic_mixed_subqueries
Projection_when_arithmetic_expressions
Projection_when_arithmetic_mixed

 System.AggregateException : One or more errors occurred.
---- System.ArgumentException : At least one object must implement IComparable.
	at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
	at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
	at System.Threading.Tasks.Task.Wait()
	C:\enlistments\Universe\EntityFramework\src\EFCore.Specification.Tests\Query\QueryTestBase.cs(103,0): at Microsoft.EntityFrameworkCore.Query.QueryTestBase`1.AssertQuery[TItem1,TItem2](Func`3 query, Func`2 elementSorter, Action`2 elementAsserter, Boolean assertOrder, Int32 entryCount)
	C:\enlistments\Universe\EntityFramework\src\EFCore.Specification.Tests\Query\SimpleQueryTestBase.cs(750,0): at Microsoft.EntityFrameworkCore.Query.SimpleQueryTestBase`1.Projection_when_arithmetic_mixed()
	----- Inner Stack Trace -----
	at System.Collections.Comparer.Compare(Object a, Object b)
	at System.Collections.Generic.ObjectComparer`1.Compare(T x, T y)
	at System.Linq.EnumerableSorter`2.CompareKeys(Int32 index1, Int32 index2)
	at System.Linq.EnumerableSorter`1.QuickSort(Int32[] map, Int32 left, Int32 right)
	at System.Linq.EnumerableSorter`1.Sort(TElement[] elements, Int32 count)
	at System.Linq.OrderedEnumerable`1.<GetEnumerator>d__1.MoveNext()
	at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
	at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
	C:\enlistments\Universe\EntityFramework\src\EFCore.Specification.Tests\TestHelpers.cs(424,0): at Microsoft.EntityFrameworkCore.TestHelpers.AssertResults[T](IList`1 expected, IList`1 actual, Func`2 elementSorter, Action`2 elementAsserter, Boolean verifyOrdered)
	C:\enlistments\Universe\EntityFramework\src\EFCore.Specification.Tests\TestUtilities\QueryAsserter.cs(400,0): at Microsoft.EntityFrameworkCore.TestUtilities.QueryAsserter`1.<AssertQuery>d__20`2.MoveNext()

**Comment by maumar** [comment]
fixed in 28d155a6041a51059fa6f716c3077a30b4314330
