### ISSUE TITLE
[SQLCE provider 2.0] Strange test fail

### ISSUE THREAD

**Issue by ErikEJ** [aspnet/EntityFrameworkCore#9369]
- was working with 2.0-preview1, and the non-async test passes.

Microsoft.EntityFrameworkCore.Specification.Tests.AsyncQuerySqlCeTest.String_Contains_Literal [FAIL]
      System.NotImplementedException : The method or operation is not implemented.
      Stack Trace:
           at Microsoft.EntityFrameworkCore.TestModels.Northwind.NorthwindData.Set[T]()
           at Microsoft.EntityFrameworkCore.Query.AsyncQueryTestBase`1.<AssertQuery>d__396`1.MoveNext()
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
        C:\Code\EntityFramework.SqlServerCompact\test\EntityFramework.SqlServerCompact.FunctionalTests\AsyncQuerySqlCeTest.cs(51,0): at Microsoft.EntityFrameworkCore.Specification.Tests.AsyncQuerySqlCeTest.<String_Contains_Literal>d__6.MoveNext()
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

### Further technical details
EF Core version: 2.0-rtm (Myget)
Database Provider: SQLCE
Operating system: Win 10
IDE: VS 15.3.4

**Comment by smitpatel** [comment]
Looking at stack trace it seems like error in l2o query.
@maumar - Did we make any changes to query assertions before 2.0?

@ErikEJ - Can you tell exact package version? Apparently even after branching we had been generating "2.0.0-rtm" packages so you may be on some "pseudo-rtm" package which actually has things from 2.1.0 commits.

**Comment by ErikEJ** [comment]
File version: 2.0.0.17205
Product version: 2.0.0-rtm-26452

**Comment by smitpatel** [comment]
That version seems alright. You can use 2.0.0 exact one also.

**Comment by ErikEJ** [comment]
Where do it get that from? I am using: https://dotnet.myget.org/F/dotnet-2-0-0-rtm/api/v3/index.json

**Comment by smitpatel** [comment]
https://dotnet.myget.org/gallery/aspnetcore-release

**Comment by ErikEJ** [comment]
2 other related (?) test fails:

Microsoft.EntityFrameworkCore.Specification.Tests.AsyncQuerySqlCeTest.String_Contains_Literal [FAIL]
      System.NotImplementedException : The method or operation is not implemented.
      Stack Trace:
           at Microsoft.EntityFrameworkCore.TestModels.Northwind.NorthwindData.Set[T]()
           at Microsoft.EntityFrameworkCore.Query.AsyncQueryTestBase`1.<AssertQuery>d__396`1.MoveNext()
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
        C:\Code\EntityFramework.SqlServerCompact\test\EntityFramework.SqlServerCompact.FunctionalTests\AsyncQuerySqlCeTest.cs(51,0): at Microsoft.EntityFrameworkCore.Specification.Tests.AsyncQuerySqlCeTest.<String_Contains_Literal>d__6.MoveNext()
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)


Microsoft.EntityFrameworkCore.Specification.Tests.AsyncQuerySqlCeTest.String_Contains_MethodCall [FAIL]
      System.NotImplementedException : The method or operation is not implemented.
      Stack Trace:
           at Microsoft.EntityFrameworkCore.TestModels.Northwind.NorthwindData.Set[T]()
           at Microsoft.EntityFrameworkCore.Query.AsyncQueryTestBase`1.<AssertQuery>d__396`1.MoveNext()
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
        C:\Code\EntityFramework.SqlServerCompact\test\EntityFramework.SqlServerCompact.FunctionalTests\AsyncQuerySqlCeTest.cs(60,0): at Microsoft.EntityFrameworkCore.Specification.Tests.AsyncQuerySqlCeTest.<String_Contains_MethodCall>d__7.MoveNext()
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

**Comment by maumar** [comment]
@ErikEJ  can you try these tests again once 782bbf3c2c5c65d9f3a20e84d9adb1615416fbbc gets into myget? I added some more logging for `NorthwindData.Set<T>` that will hopefully shed some more light on this issue.

**Comment by ErikEJ** [comment]
I will, thanks!

**Comment by maumar** [comment]
@ErikEJ is this still a problem for you?

**Comment by ErikEJ** [comment]
I have not done any 2.1 work yet. Waiting till after 2.0.1 release

**Comment by ajcvickers** [comment]
@ErikEJ We think this is likely fixed now. Please let us know if it is still an issue when you move to 2.1.

**Comment by ErikEJ** [comment]
Fixed in 2.1-preview1
