### ISSUE TITLE
[Test] AsyncQuerySqlCeTest.Where_subquery_on_collection is not robust enough

### ISSUE THREAD

**Issue by ErikEJ** [aspnet/EntityFrameworkCore#9378]
```
Test 'Microsoft.EntityFrameworkCore.Specification.Tests.AsyncQuerySqlCeTest.Where_subquery_on_collection' failed: Assert.Equal() Failure
Expected: 0
Actual:   1
	at Microsoft.EntityFrameworkCore.TestHelpers.AssertResults[T](IList`1 expected, IList`1 actual, Boolean assertOrder, Action`2 asserter)
	at Microsoft.EntityFrameworkCore.Query.AsyncQueryTestBase`1.<AssertQuery>d__392`2.MoveNext()
	--- End of stack trace from previous location where exception was thrown ---
	at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
	at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	at Microsoft.EntityFrameworkCore.Query.AsyncQueryTestBase`1.<Where_subquery_on_collection>d__145.MoveNext()
	--- End of stack trace from previous location where exception was thrown ---
	at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
	at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	--- End of stack trace from previous location where exception was thrown ---
	at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
	at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	--- End of stack trace from previous location where exception was thrown ---
	at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
	at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```
### Further technical details
EF Core version: 2.0 rtm
Database Provider: SQLCE
Operating system: Win 10
IDE: VS 2017 15.3

**Comment by maumar** [comment]
fixed in 782bbf3c2c5c65d9f3a20e84d9adb1615416fbbc
