### ISSUE TITLE
Diagnostics logging is incompatible with windows EventLog

### ISSUE THREAD

**Issue by MaximBalaganskiy** [aspnet/EntityFrameworkCore#9437]
After an upgrade to EF Core 2.0 EventLog provider throws an exception
```
Exception message: System.AggregateException: An error occurred while writing to logger(s). ---> System.ArgumentException: Invalid eventID value '100403'. It must be in the range between '0' and '65535'.
Stack trace: at System.Diagnostics.EventLogInternal.WriteEntry(String message, EventLogEntryType type, Int32 eventID, Int16 category, Byte[] rawData)
   at System.Diagnostics.EventLog.WriteEntry(String message, EventLogEntryType type, Int32 eventID, Int16 category)
   at Microsoft.Extensions.Logging.EventLog.WindowsEventLog.WriteEntry(String message, EventLogEntryType type, Int32 eventID, Int16 category)
   at Microsoft.Extensions.Logging.EventLog.EventLogLogger.WriteMessage(String message, EventLogEntryType eventLogEntryType, Int32 eventId)
   at Microsoft.Extensions.Logging.EventLog.EventLogLogger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter)
   at Microsoft.Extensions.Logging.Logger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter)
   --- End of inner exception stack trace ---
   at Microsoft.Extensions.Logging.Logger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter)
   at Microsoft.Extensions.Logging.LoggerMessage.<>c__DisplayClass8_0`4.<Define>b__0(ILogger logger, T1 arg1, T2 arg2, T3 arg3, T4 arg4, Exception exception)
   at Microsoft.EntityFrameworkCore.Diagnostics.EventDefinition`4.Log[TLoggerCategory](IDiagnosticsLogger`1 logger, TParam1 arg1, TParam2 arg2, TParam3 arg3, TParam4 arg4, Exception exception)
   at Microsoft.EntityFrameworkCore.Internal.CoreLoggerExtensions.ContextInitialized(IDiagnosticsLogger`1 diagnostics, DbContext context, DbContextOptions contextOptions)
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.Microsoft.EntityFrameworkCore.Infrastructure.IInfrastructure<System.IServiceProvider>.get_Instance()
   at Microsoft.EntityFrameworkCore.Infrastructure.DatabaseFacade.Microsoft.EntityFrameworkCore.Infrastructure.IInfrastructure<System.IServiceProvider>.get_Instance()
   at Microsoft.EntityFrameworkCore.RelationalDatabaseFacadeExtensions.GetRelationalService[TService](IInfrastructure`1 databaseFacade)
   at Microsoft.EntityFrameworkCore.RelationalDatabaseFacadeExtensions.Migrate(DatabaseFacade databaseFacade)
   at AquaWeb.Portal.Services.SeedingService.<InitialiseDatabase>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at AquaWeb.Portal.Startup.Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory, IServiceScopeFactory serviceScopeFactory)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)
   at Microsoft.ApplicationInsights.AspNetCore.ApplicationInsightsStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder app)
   at Microsoft.AspNetCore.Server.IISIntegration.IISSetupFilter.<>c__DisplayClass3_0.<Configure>b__0(IApplicationBuilder app)
   at Microsoft.AspNetCore.Hosting.Internal.AutoRequestServicesStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
---> (Inner Exception #0) System.ArgumentException: Invalid eventID value '100403'. It must be in the range between '0' and '65535'.
   at System.Diagnostics.EventLogInternal.WriteEntry(String message, EventLogEntryType type, Int32 eventID, Int16 category, Byte[] rawData)
   at System.Diagnostics.EventLog.WriteEntry(String message, EventLogEntryType type, Int32 eventID, Int16 category)
   at Microsoft.Extensions.Logging.EventLog.WindowsEventLog.WriteEntry(String message, EventLogEntryType type, Int32 eventID, Int16 category)
   at Microsoft.Extensions.Logging.EventLog.EventLogLogger.WriteMessage(String message, EventLogEntryType eventLogEntryType, Int32 eventId)
   at Microsoft.Extensions.Logging.EventLog.EventLogLogger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter)
   at Microsoft.Extensions.Logging.Logger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter)<---
```

### Steps to reproduce
https://github.com/MaximBalaganskiy/EfEventLogIssue

### Further technical details
Target Framework: net461
EF Core version: 2.0.0
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10
IDE: Visual Studio 2017

**Comment by MaximBalaganskiy** [comment]
The base event id is defined [here](https://github.com/aspnet/EntityFrameworkCore/blob/dev/src/EFCore/Diagnostics/CoreEventId.cs) and this is not compatible with the EventLog provider

**Comment by ajcvickers** [comment]
@divega If you have any spare thinking cycles I'd appreciate your thoughts on this. I haven't been able to come up with any good ideas on how to proceed.

@Eilon Would appreciate your thoughts too. The event IDs are too long for Windows EventLog, but changing them would be a breaking change...

@AndriySvyryd @anpete @bricelam @smitpatel @maumar Any ideas?

**Comment by AndriySvyryd** [comment]
Add a high id compatibility option to the EventLog provider?

**Comment by ajcvickers** [comment]
We discussed this in triage and have this proposal:
* Change the event Ids now in 2.0.1; this is a breaking change, but the sooner we do it the better
* Communicate to the known consumers of our diagnostics that we are doing this--we think we know the most significant consumers
* Add a quirk mode that can be switched on to use the 2.0.0 event IDs if needed--to be used until all consumers have updated

@Eilon @divega Thoughts?

**Comment by ajcvickers** [comment]
@AndriySvyryd How would it work?

**Comment by AndriySvyryd** [comment]
It would use some function to map the ids to the supported range. Possibly mapping everything above `65535` to `65535` or to `% 65535`

**Comment by ajcvickers** [comment]
@AndriySvyryd Doesn't seem like we would be able to ensure uniqueness though, which would be a problem.

**Comment by AndriySvyryd** [comment]
If we only need uniqueness in EF space we can expose a mapping function that provides it.

**Comment by anpete** [comment]
I like just breaking early. Not sure the quirks mode is worth it.

**Comment by Eilon** [comment]
Hmm very interesting problem. I think I'm feeling we should just do the break now...

**Comment by ajcvickers** [comment]
@Eilon With a quirk mode or not?

**Comment by Eilon** [comment]
I think I'd err on having a quirk. It's trivial to add them.

**Comment by divega** [comment]
@ajcvickers sorry I didn’t see this before. Anyway, sounds like a good plan.

**Comment by ajcvickers** [comment]
Hi @MaximBalaganskiy. We are gathering information on the use of EF Core pre-release builds. You reported this issue shortly after the release of 2.0.0 RTM. It would be really helpful if you could let us know:

- Did you consider testing your code against the pre-release builds?
- Was there anything blocking you from using pre-release builds?
- What do you think could make it easier for you to use pre-release builds in the future?

Thanks in advance for any feedback. Hopefully this will help us to increase the value of pre-release builds going forward.

**Comment by ajcvickers** [comment]
@MaximBalaganskiy Thanks for the feedback; much appreciated.

**Comment by Eilon** [comment]
This patch bug is **approved** for the 2.0.x patch. Please send a PR to the `feature/2.0.1` branch and get it reviewed and merged. When we have the `rel/2.0.1` branches ready please port the commit to that branch.

**Comment by Eilon** [comment]
Hi, we have a public test feed that you can use to try out the ASP.NET/EF Core 2.0.3 patch!

To try out the pre-release patch, please refer to the following guide:
* https://github.com/aspnet/Announcements/issues/274 (info)
* https://github.com/aspnet/Home/issues/2254 (discussions and questions)

We are looking for feedback on this patch. We'd like to know if you have any issues with this patch by updating your apps and libraries to the latest packages and seeing if it fixes the issues you've had, or if it introduces any new issues. If you have any issues or questions, please reply on this issue to let us know as soon as possible.

Thanks,
Eilon

**Comment by MaximBalaganskiy** [comment]
I can confirm that the patch fixed this issue for me. Now I see EF logs in windows event log.
