### ISSUE TITLE
Query Testing: Failure of assertion framework should give better information

### ISSUE THREAD

**Issue by smitpatel** [aspnet/EntityFrameworkCore#9577]
The following output makes it ambiguous if there was error with linq query or just test. 

```
Test 'Microsoft.EntityFrameworkCore.Query.SimpleQuerySqlServerTest.OrderBy_Skip_GroupBy' failed: System.AggregateException : One or more errors occurred.
---- System.ArgumentException : At least one object must implement IComparable.
	at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
	at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
	at System.Threading.Tasks.Task.Wait()
	D:\code\EntityFrameworkCore\src\EFCore.Specification.Tests\Query\QueryTestBase.cs(83,0): at Microsoft.EntityFrameworkCore.Query.QueryTestBase`1.AssertQuery[TItem1](Func`2 query, Func`2 elementSorter, Action`2 elementAsserter, Boolean assertOrder, Int32 entryCount)
	D:\code\EntityFrameworkCore\src\EFCore.Specification.Tests\Query\SimpleQueryTestBase.GroupBy.cs(513,0): at Microsoft.EntityFrameworkCore.Query.SimpleQueryTestBase`1.OrderBy_Skip_GroupBy()
	D:\code\EntityFrameworkCore\test\EFCore.SqlServer.FunctionalTests\Query\SimpleQuerySqlServerTest.GroupBy.cs(438,0): at Microsoft.EntityFrameworkCore.Query.SimpleQuerySqlServerTest.OrderBy_Skip_GroupBy()
	----- Inner Stack Trace -----
	at System.Collections.Comparer.Compare(Object a, Object b)
	at System.Collections.Generic.ObjectComparer`1.Compare(T x, T y)
	at System.Linq.EnumerableSorter`2.CompareKeys(Int32 index1, Int32 index2)
	at System.Linq.EnumerableSorter`1.QuickSort(Int32[] map, Int32 left, Int32 right)
	at System.Linq.EnumerableSorter`1.Sort(TElement[] elements, Int32 count)
	at System.Linq.OrderedEnumerable`1.<GetEnumerator>d__1.MoveNext()
	at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
	at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
	D:\code\EntityFrameworkCore\src\EFCore.Specification.Tests\TestUtilities\TestHelpers.cs(428,0): at Microsoft.EntityFrameworkCore.TestUtilities.TestHelpers.AssertResults[T](IList`1 expected, IList`1 actual, Func`2 elementSorter, Action`2 elementAsserter, Boolean verifyOrdered)
	D:\code\EntityFrameworkCore\src\EFCore.Specification.Tests\TestUtilities\QueryAsserter.cs(354,0): at Microsoft.EntityFrameworkCore.TestUtilities.QueryAsserter`1.<AssertQuery>d__18`1.MoveNext()

```

**Comment by maumar** [comment]
fixed in d6de54c3ab1b6f32d38c8333a66e754ff594e208
