### ISSUE TITLE
Query: Navigation rewrite throws null check on navigation

### ISSUE THREAD

**Issue by smitpatel** [aspnet/EntityFrameworkCore#9742]
```c#
        [Theory]
        [InlineData(false)]
        [InlineData(true)]
        public virtual void Include_collection_with_multiple_conditional_order_by(bool useString)
        {
            using (var context = CreateContext())
            {
                var orders
                    = useString
                        ? context.Orders
                            .Include("OrderDetails")
                            .OrderBy(o => o.OrderID > 0)
                            .ThenBy(o => o.Customer != null ? o.Customer.City : String.Empty)
                            .Take(5)
                            .ToList()
                        : context.Orders
                            .Include(c => c.OrderDetails)
                            .OrderBy(o => o.OrderID > 0)
                            .ThenBy(o => o.Customer != null ? o.Customer.City : String.Empty)
                            .Take(5)
                            .ToList();

                foreach (var order in orders)
                {
                    CheckIsLoaded(
                        context,
                        order,
                        orderDetailsLoaded: true,
                        productLoaded: false,
                        customerLoaded: false,
                        ordersLoaded: false);
                }
            }
        }
```
```
Output from Microsoft.EntityFrameworkCore.Query.IncludeSqlServerTest.Include_collection_with_multiple_conditional_order_by(useString: False):
  Entity Framework Core 2.1.0-preview1 initialized 'NorthwindRelationalContext' using provider 'Microsoft.EntityFrameworkCore.SqlServer' with options: SensitiveDataLoggingEnabled CommandTimeout=600
  
  Compiling query model: 
  '(from Order o in 
      (from Order c in DbSet<Order>
      select [c]).Include("OrderDetails")
  order by [o].OrderID > 0 asc, [o].Customer != null ? [o].Customer.City : __Empty_0 asc
  select [o]).Take(__p_1)'
  
  Including navigation: '[c].OrderDetails'
Test 'Microsoft.EntityFrameworkCore.Query.IncludeSqlServerTest.Include_collection_with_multiple_conditional_order_by(useString: True)' failed:
	System.InvalidOperationException : The operands for operator 'NotEqual' do not match the parameters of method 'op_Inequality'.
	at System.Linq.Expressions.Expression.GetMethodBasedBinaryOperator(ExpressionType binaryType, Expression left, Expression right, MethodInfo method, Boolean liftToNull)
	at System.Linq.Expressions.Expression.NotEqual(Expression left, Expression right, Boolean liftToNull, MethodInfo method)
	at System.Linq.Expressions.Expression.MakeBinary(ExpressionType binaryType, Expression left, Expression right, Boolean liftToNull, MethodInfo method, LambdaExpression conversion)
	at System.Linq.Expressions.Expression.MakeBinary(ExpressionType binaryType, Expression left, Expression right, Boolean liftToNull, MethodInfo method)
	D:\code\EntityFrameworkCore\src\EFCore\Query\ExpressionVisitors\Internal\NavigationRewritingExpressionVisitor.cs(372,0): at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.NavigationRewritingExpressionVisitor.VisitBinary(BinaryExpression node)
	at System.Linq.Expressions.BinaryExpression.Accept(ExpressionVisitor visitor)
	at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
	D:\code\EntityFrameworkCore\src\EFCore\Query\ExpressionVisitors\Internal\NavigationRewritingExpressionVisitor.cs(381,0): at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.NavigationRewritingExpressionVisitor.VisitConditional(ConditionalExpression node)
	at System.Linq.Expressions.ConditionalExpression.Accept(ExpressionVisitor visitor)
	at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
	at Remotion.Linq.Clauses.Ordering.TransformExpressions(Func`2 transformation)
	at Remotion.Linq.Clauses.OrderByClause.TransformExpressions(Func`2 transformation)
	D:\code\EntityFrameworkCore\src\EFCore\Query\ExpressionVisitors\Internal\ExpressionTransformingQueryModelVisitor.cs(76,0): at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.ExpressionTransformingQueryModelVisitor`1.VisitOrderByClause(OrderByClause orderByClause, QueryModel queryModel, Int32 index)
	D:\code\EntityFrameworkCore\src\EFCore\Query\ExpressionVisitors\Internal\NavigationRewritingExpressionVisitor.cs(1439,0): at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.NavigationRewritingExpressionVisitor.NavigationRewritingQueryModelVisitor.VisitOrderByClause(OrderByClause orderByClause, QueryModel queryModel, Int32 index)
	at Remotion.Linq.Clauses.OrderByClause.Accept(IQueryModelVisitor visitor, QueryModel queryModel, Int32 index)
	at Remotion.Linq.QueryModelVisitorBase.VisitBodyClauses(ObservableCollection`1 bodyClauses, QueryModel queryModel)
	at Remotion.Linq.QueryModelVisitorBase.VisitQueryModel(QueryModel queryModel)
	D:\code\EntityFrameworkCore\src\EFCore\Query\ExpressionVisitors\Internal\NavigationRewritingExpressionVisitor.cs(238,0): at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.NavigationRewritingExpressionVisitor.Rewrite(QueryModel queryModel, QueryModel parentQueryModel)
	D:\code\EntityFrameworkCore\src\EFCore\Query\EntityQueryModelVisitor.cs(288,0): at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.OptimizeQueryModel(QueryModel queryModel, Boolean asyncQuery)
	D:\code\EntityFrameworkCore\src\EFCore.Relational\Query\RelationalQueryModelVisitor.cs(1161,0): at Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor.OptimizeQueryModel(QueryModel queryModel, Boolean asyncQuery)
	D:\code\EntityFrameworkCore\src\EFCore\Query\EntityQueryModelVisitor.cs(165,0): at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.CreateQueryExecutor[TResult](QueryModel queryModel)
	D:\code\EntityFrameworkCore\src\EFCore\Storage\Database.cs(70,0): at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](QueryModel queryModel)
	--- End of stack trace from previous location where exception was thrown ---
	at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
	D:\code\EntityFrameworkCore\src\EFCore\Query\Internal\QueryCompiler.cs(164,0): at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](Expression query, INodeTypeProvider nodeTypeProvider, IDatabase database, IDiagnosticsLogger`1 logger, Type contextType)
	D:\code\EntityFrameworkCore\src\EFCore\Query\Internal\QueryCompiler.cs(103,0): at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass15_0`1.<Execute>b__0()
	D:\code\EntityFrameworkCore\src\EFCore\Query\Internal\CompiledQueryCache.cs(69,0): at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQueryCore[TFunc](Object cacheKey, Func`1 compiler)
	D:\code\EntityFrameworkCore\src\EFCore\Query\Internal\CompiledQueryCache.cs(44,0): at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
	D:\code\EntityFrameworkCore\src\EFCore\Query\Internal\QueryCompiler.cs(99,0): at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
	D:\code\EntityFrameworkCore\src\EFCore\Query\Internal\EntityQueryProvider.cs(62,0): at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
	at Remotion.Linq.QueryableBase`1.GetEnumerator()
	at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
	at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
	D:\code\EntityFrameworkCore\src\EFCore.Specification.Tests\Query\IncludeTestBase.cs(3109,0): at Microsoft.EntityFrameworkCore.Query.IncludeTestBase`1.Include_collection_with_multiple_conditional_order_by(Boolean useString)
	D:\code\EntityFrameworkCore\test\EFCore.SqlServer.FunctionalTests\Query\IncludeSqlServerTest.cs(1429,0): at Microsoft.EntityFrameworkCore.Query.IncludeSqlServerTest.Include_collection_with_multiple_conditional_order_by(Boolean useString)
```

**Comment by ajcvickers** [comment]
A workaround is to not add the null-checking code at all, since this is handled by EF Core. For example:
```C#
.ThenBy(o => o.Customer.City)
```
