### ISSUE TITLE
EF generates very unclear error message in case too generic key types in M:M relationship

### ISSUE THREAD

**Issue by shytikov** [aspnet/EntityFrameworkCore#9817]
I have `many-to-many` relationship entity that accidentally got property of type `object`. This happened by accident — during automatic creation of the property by Visual Studio. Later that property was set as a key by `FluentAPI`.

During start-up my application ensures that database created, and as soon it reaches that place — following exception fired:

```
Exception message: The property 'Sprint.TempId' is of type 'object' which is not supported by current database provider. Either change the property CLR type or ignore the property using the '[NotMapped]' attribute or by using 'EntityTypeBuilder.Ignore' in 'OnModelCreating'.
Stack trace:    at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.PropertyMappingValidationConvention.Apply(InternalModelBuilder modelBuilder)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ImmediateConventionScope.OnModelBuilt(InternalModelBuilder modelBuilder)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.OnModelBuilt(InternalModelBuilder modelBuilder)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.Model.Validate()
   at Microsoft.EntityFrameworkCore.Metadata.Internal.InternalModelBuilder.Validate()
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.CreateModel(DbContext context, IConventionSetBuilder conventionSetBuilder, IModelValidator validator)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.<>c__DisplayClass5_0.<GetModel>b__0(Object k)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.GetModel(DbContext context, IConventionSetBuilder conventionSetBuilder, IModelValidator validator)
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()
   at Microsoft.EntityFrameworkCore.Infrastructure.EntityFrameworkServicesBuilder.<>c.<TryAddCoreServices>b__7_1(IServiceProvider p)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.<>c__DisplayClass22_0.<RealizeService>b__0(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.Microsoft.EntityFrameworkCore.Infrastructure.IInfrastructure<System.IServiceProvider>.get_Instance()
   at Microsoft.EntityFrameworkCore.Infrastructure.DatabaseFacade.Microsoft.EntityFrameworkCore.Infrastructure.IInfrastructure<System.IServiceProvider>.get_Instance()
   at Microsoft.EntityFrameworkCore.Infrastructure.AccessorExtensions.GetService[TService](IInfrastructure`1 accessor)
   at Microsoft.EntityFrameworkCore.Infrastructure.DatabaseFacade.get_DatabaseCreator()
   at Microsoft.EntityFrameworkCore.Infrastructure.DatabaseFacade.EnsureCreated()
   at Web.Startup.ConfigureServices(IServiceCollection services)
```

### Steps to reproduce

1. Create 2 entities. In my case `Issue` and `Sprint`;
1. Create N:N relation entity. In my case `IssueSprint`;
1. Set type of a property to `object`. In my case `SprintId`;
1. Use that property as key by FluentAPI;
1. Try to create database;

From `N:N` relation entity:
```c#
public class IssueSprint
    {
        #region Public Constructors

        public IssueSprint(Issue issue, Sprint sprint)
        {
            Issue = issue;
            IssueId = issue.Id;

            Sprint = sprint;
            SprintId = sprint.Id;
        }

        #endregion Public Constructors

        #region Public Properties

        public Issue Issue
        {
            get;
            private set;
        }

        public string IssueId
        {
            get;
            private set;
        }

        public Sprint Sprint
        {
            get;
            private set;
        }

        public object SprintId  // <-- note generic type `object`. It should be `string` as for `IssueId`
        {
            get;
            private set;
        }

        #endregion Public Properties

        #region Public Methods

        public override string ToString()
        {
            return $"{IssueId} <-> {SprintId}";
        }

        #endregion Public Methods
    }
```
From `DbContext.cs`:
```c#
        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<IssueSprint>()
                .HasKey(record => new { record.IssueId, record.SprintId });

            // 1:N connection from relation entity to issue
            modelBuilder.Entity<IssueSprint>()
                .HasOne(relation => relation.Issue)
                .WithMany(issue => issue.Sprints)
                .HasForeignKey(relation => relation.IssueId);

            // 1:N connection from relation entity to sprint
            modelBuilder.Entity<IssueSprint>()
                .HasOne(relation => relation.Sprint)
                .WithMany(sprint => sprint.Issues)
                .HasForeignKey(relation => relation.SprintId);

            base.OnModelCreating(modelBuilder);
        }
```

From `Startup.cs`:
```c#
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddMvc();

            using (var context = new DbContext())
            {
                context.Database.EnsureCreated();
            }
        }
```

*Problem*: Error message tells about problem with `Sprint.TempId` field. Which does not exist anywhere. While in reality `IssueSprint.SprintId` is the main reason of that exception. Switching type from `object` to less generic type (`string` in my case) has fixed the issue. 

Although just by reading this error message it is almost impossible to find real cause. 

I believe error message should be updated to point user to correct location in the code, that triggers the issue.

### Further technical details
EF Core version: 2.0.0
Database Provider: Microsoft.EntityFrameworkCore.Sqlite
Operating system: Windows 10 x64
IDE: Visual Studio 2017

**Comment by smitpatel** [comment]
Note: We would throw for object property in first entity type we encounter (perhaps alphabetically).

**Comment by ajcvickers** [comment]
@shytikov I was unable to reproduce this using the code below--it correctly throws, "The property 'IssueSprint.SprintId' is of type 'object' which is not supported by current database provider. Either change the property CLR type or ignore the property using the '[NotMapped]' attribute or by using 'EntityTypeBuilder.Ignore' in 'OnModelCreating'."

There is probably something different in your entity types that makes it throw for "Sprint.TempId". Can you update the repro code below so that it exhibits the behavior you are seeing?
```C#
public class Issue
{
    public string Id { get; set; }

    public ICollection<IssueSprint> Sprints { get; set; }
}

public class Sprint
{
    public string Id { get; set; }

    public ICollection<IssueSprint> Issues { get; set; }
}

public class IssueSprint
{
    public IssueSprint(Issue issue, Sprint sprint)
    {
        Issue = issue;
        IssueId = issue.Id;

        Sprint = sprint;
        SprintId = sprint.Id;
    }

    public Issue Issue
    {
        get;
        private set;
    }

    public string IssueId
    {
        get;
        private set;
    }

    public Sprint Sprint
    {
        get;
        private set;
    }

    public object SprintId  // <-- note generic type `object`. It should be `string` as for `IssueId`
    {
        get;
        private set;
    }

    public override string ToString()
    {
        return $"{IssueId} <-> {SprintId}";
    }
}

public class TestDbContext : DbContext
{
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        optionsBuilder.UseSqlServer(
            @"Server=(localdb)\mssqllocaldb;Database=Test;Trusted_Connection=True;ConnectRetryCount=0");
    }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<IssueSprint>()
            .HasKey(record => new { record.IssueId, record.SprintId });

        // 1:N connection from relation entity to issue
        modelBuilder.Entity<IssueSprint>()
            .HasOne(relation => relation.Issue)
            .WithMany(issue => issue.Sprints)
            .HasForeignKey(relation => relation.IssueId);

        // 1:N connection from relation entity to sprint
        modelBuilder.Entity<IssueSprint>()
            .HasOne(relation => relation.Sprint)
            .WithMany(sprint => sprint.Issues)
            .HasForeignKey(relation => relation.SprintId);
    }
}

public class Program
{
    public static void Main()
    {
        using (var context = new TestDbContext())
        {
            context.Database.EnsureDeleted();
            context.Database.EnsureCreated();
        }
    }
}
```

**Comment by shytikov** [comment]
Maybe it's an issue on specific provider implementation. I was able to catch this exception for `SQLite`, I haven't tried for `SQL Server`

```c#
        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseSqlite("Data Source=test.sqlite");
        }
```

**Comment by ajcvickers** [comment]
@shytikov As @smitpatel pointed out, there is an order dependency--I was able to repro just by changing the name IssueSprint to SprintIssue. So no need to dig further to get it to repro on your end--thanks for filing the issue!

**Comment by AndriySvyryd** [comment]
We should validate explicit configuration and non-shadow properties first

**Comment by douglasg14b** [comment]
Seeing this error in 2.1 for configuring a join table entity for a many-to-many relationship using Pomelos MySQL connector.

Was there eventually a fix for this?

**Comment by AndriySvyryd** [comment]
@douglasg14b Your scenario is different from this bug. A key can only contain primitive properties:
```C#
modelBuilder.Entity<TransactionTagsEntity>()
    .HasKey(c => new { c.TagId, c.TransactionId });
```

**Comment by douglasg14b** [comment]
ohhhh, I see. That's actually a fault of my own then, that should have been the `TransactionId`. Thanks for catching that.

Keep doing great things!

**Comment by jjxtra** [comment]
Getting this error trying to use a byte[] as part 2 of a primary key. Any database will allow a byte[] (blob) to be part of a primary key, why does this error show up for that? Very odd...

**Comment by AndriySvyryd** [comment]
@jjxtra If you are getting this error in v2.2.0 or higher please file a new issue with a small repro project

**Comment by jjxtra** [comment]
It was due to lack of get/set on the field, maybe it would be helpful to add that as a possible resolution in the error message.
