### ISSUE TITLE
Query: Queryable.Cast<T?> causes ArgumentException

### ISSUE THREAD

**Issue by mbashov** [aspnet/EntityFrameworkCore#9848]
Materializing a query containing a Cast method fails on EntityFramework Core 2.0.0 with ArgumentException:

```
context.Set<Simple>().Select(s => s.Id).Cast<int?>().FirstOrDefault();

public class Simple
{
    public int Id { get; set; }
}
```

```
Exception message: 
Expression of type 'System.Collections.Generic.IEnumerable`1[System.Int32]' cannot be used for return type 'System.Collections.Generic.IEnumerable`1[System.Nullable`1[System.Int32]]'

Stack trace:
   at System.Linq.Expressions.Expression.ValidateLambdaArgs(Type delegateType, Expression& body, ReadOnlyCollection`1 parameters)
   at System.Linq.Expressions.Expression.Lambda[TDelegate](Expression body, String name, Boolean tailCall, IEnumerable`1 parameters)
   at System.Linq.Expressions.Expression.Lambda[TDelegate](Expression body, Boolean tailCall, IEnumerable`1 parameters)
   at System.Linq.Expressions.Expression.Lambda[TDelegate](Expression body, ParameterExpression[] parameters)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.CreateExecutorLambda[TResults]()
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.CreateQueryExecutor[TResult](QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](Expression query, INodeTypeProvider nodeTypeProvider, IDatabase database, IDiagnosticsLogger`1 logger, Type contextType)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass15_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQueryCore[TFunc](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
   at System.Linq.Queryable.FirstOrDefault[TSource](IQueryable`1 source)
```

**Comment by smitpatel** [comment]
As a work-around you can do `context.Set<Simple>().Select(s => (int?)s.Id).FirstOrDefault()`

**Comment by smitpatel** [comment]
Works correctly in 3.1.
