### ISSUE TITLE
nullreference when during add-migration when migration implementations lack migration attribute

### ISSUE THREAD

**Issue by kbilsted** [aspnet/EntityFrameworkCore#9920]
if you implement a migration hook and forgetting the attribute. Then call `add-migration foo`

If you are seeing an exception, include the full exceptions details (message and stack trace).

```
System.ArgumentNullException: Value cannot be null.
Parameter name: key
   at System.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationsAssembly.<>c__DisplayClass3_0.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Internal.LazyRef`1.get_Value()
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationsAssembly.get_Migrations()
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationsAssembly.FindMigrationId(String nameOrId)
   at Microsoft.EntityFrameworkCore.Migrations.Design.MigrationsScaffolder.ScaffoldMigration(String migrationName, String rootNamespace, String subNamespace)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.AddMigration(String name, String outputDir, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigrationImpl(String name, String outputDir, String contextType)

```

### Steps to reproduce

```
    [DbContext(typeof(CustomerContext))]
    //[Migration("Custom migrations")]
    class MigrationHook : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
        }
    }
}
``` 

### Further technical details

The problem *is* the below code from `MigrationsAssembly.cs` using `?.` not realizing that you cannot use null as a key. The error message should *not* be nullreferenceexception, but rather that the implementor forgot to apply an attribute.

Similarly, if using the attribute, and forgetting the subclassing, and error should be show. This is not the case now where only subclasses are investigated

https://github.com/aspnet/EntityFrameworkCore/blob/888b188731264cf2cebee16ce5a9ad4e65fe6f8c/src/EFCore.Relational/Migrations/Internal/MigrationsAssembly.cs

    _migrations = new LazyRef<IReadOnlyDictionary<string, TypeInfo>>(
                () => (
                        from t in Assembly.GetConstructableTypes()
                        where t.IsSubclassOf(typeof(Migration))
                              && t.GetCustomAttribute<DbContextAttribute>()?.ContextType == contextType
                        let id = t.GetCustomAttribute<MigrationAttribute>()?.Id
                        orderby id
                        select new { Key = id, Element = t })
                    .ToDictionary(i => i.Key, i => i.Element));

**Comment by bricelam** [comment]
> If using the attribute, and forgetting the subclassing, an error should be show.

Having `[Migration]` without inheriting from `Migration` seems very unlikely. Classes like these will continue to be silently ignored for now.
