### ISSUE TITLE
Query: compilation exception for query projecting negated conditional expression inside anonymous type

### ISSUE THREAD

**Issue by maumar** [aspnet/EntityFrameworkCore#9944]
query:

```cs
ctx.Tags.Select(t => new { c = !(t.Gear.HasSoulPatch ? true : t.Gear.HasSoulPatch) });
```

exception:

```
System.ArgumentException : Argument must be boolean
	at System.Linq.Expressions.Expression.Condition(Expression test, Expression ifTrue, Expression ifFalse)
	D:\git\EntityFrameworkCore\src\EFCore.Relational\Query\Sql\DefaultQuerySqlGenerator.cs(1890,0): at Microsoft.EntityFrameworkCore.Query.Sql.DefaultQuerySqlGenerator.BooleanExpressionTranslatingVisitor.ConvertToValue(Expression expression)
	D:\git\EntityFrameworkCore\src\EFCore.Relational\Query\Sql\DefaultQuerySqlGenerator.cs(1848,0): at Microsoft.EntityFrameworkCore.Query.Sql.DefaultQuerySqlGenerator.BooleanExpressionTranslatingVisitor.ApplyConversion(Expression expression)
	D:\git\EntityFrameworkCore\src\EFCore.Relational\Query\Sql\DefaultQuerySqlGenerator.cs(1828,0): at Microsoft.EntityFrameworkCore.Query.Sql.DefaultQuerySqlGenerator.BooleanExpressionTranslatingVisitor.VisitUnary(UnaryExpression unaryExpression)
	at System.Linq.Expressions.UnaryExpression.Accept(ExpressionVisitor visitor)
	at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
	D:\git\EntityFrameworkCore\src\EFCore.Relational\Query\Sql\DefaultQuerySqlGenerator.cs(1815,0): at Microsoft.EntityFrameworkCore.Query.Sql.DefaultQuerySqlGenerator.BooleanExpressionTranslatingVisitor.VisitUnary(UnaryExpression unaryExpression)
	at System.Linq.Expressions.UnaryExpression.Accept(ExpressionVisitor visitor)
	at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
	D:\git\EntityFrameworkCore\src\EFCore.Relational\Query\Expressions\AliasExpression.cs(89,0): at Microsoft.EntityFrameworkCore.Query.Expressions.AliasExpression.VisitChildren(ExpressionVisitor visitor)
	at System.Linq.Expressions.ExpressionVisitor.VisitExtension(Expression node)
	D:\git\EntityFrameworkCore\src\EFCore.Relational\Query\Sql\DefaultQuerySqlGenerator.cs(1837,0): at Microsoft.EntityFrameworkCore.Query.Sql.DefaultQuerySqlGenerator.BooleanExpressionTranslatingVisitor.VisitExtension(Expression extensionExpression)
	at System.Linq.Expressions.Expression.Accept(ExpressionVisitor visitor)
	D:\git\EntityFrameworkCore\src\EFCore.Relational\Query\Expressions\AliasExpression.cs(69,0): at Microsoft.EntityFrameworkCore.Query.Expressions.AliasExpression.Accept(ExpressionVisitor visitor)
	at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
	D:\git\EntityFrameworkCore\src\EFCore.Relational\Query\Sql\DefaultQuerySqlGenerator.cs(1734,0): at Microsoft.EntityFrameworkCore.Query.Sql.DefaultQuerySqlGenerator.BooleanExpressionTranslatingVisitor.Translate(Expression expression, Boolean searchCondition)
	D:\git\EntityFrameworkCore\src\EFCore.Relational\Query\Sql\DefaultQuerySqlGenerator.cs(334,0): at Microsoft.EntityFrameworkCore.Query.Sql.DefaultQuerySqlGenerator.ApplyOptimizations(Expression expression, Boolean searchCondition, Boolean joinCondition)
	D:\git\EntityFrameworkCore\src\EFCore.Relational\Query\Sql\DefaultQuerySqlGenerator.cs(353,0): at Microsoft.EntityFrameworkCore.Query.Sql.DefaultQuerySqlGenerator.GenerateProjection(Expression projection)
	D:\git\EntityFrameworkCore\src\EFCore.SqlServer\Query\Sql\Internal\SqlServerQuerySqlGenerator.cs(124,0): at Microsoft.EntityFrameworkCore.Query.Sql.Internal.SqlServerQuerySqlGenerator.GenerateProjection(Expression projection)
	D:\git\EntityFrameworkCore\src\EFCore.Relational\Query\Sql\DefaultQuerySqlGenerator.cs(466,0): at Microsoft.EntityFrameworkCore.Query.Sql.DefaultQuerySqlGenerator.GenerateList[T](IReadOnlyList`1 items, Action`1 generationAction, Action`1 joinAction)
	D:\git\EntityFrameworkCore\src\EFCore.Relational\Query\Sql\DefaultQuerySqlGenerator.cs(226,0): at Microsoft.EntityFrameworkCore.Query.Sql.DefaultQuerySqlGenerator.VisitSelect(SelectExpression selectExpression)
	D:\git\EntityFrameworkCore\src\EFCore.Relational\Query\Expressions\SelectExpression.cs(1054,0): at Microsoft.EntityFrameworkCore.Query.Expressions.SelectExpression.Accept(ExpressionVisitor visitor)
	at Remotion.Linq.Parsing.ThrowingExpressionVisitor.Visit(Expression expression)
	D:\git\EntityFrameworkCore\src\EFCore.Relational\Query\Sql\DefaultQuerySqlGenerator.cs(130,0): at Microsoft.EntityFrameworkCore.Query.Sql.DefaultQuerySqlGenerator.GenerateSql(IReadOnlyDictionary`2 parameterValues)
	D:\git\EntityFrameworkCore\src\EFCore.Relational\Query\Internal\RelationalExpressionPrinter.cs(49,0): at Microsoft.EntityFrameworkCore.Query.Internal.RelationalExpressionPrinter.CommandBuilderPrinter.TryPrintConstant(ConstantExpression constantExpression, IndentedStringBuilder stringBuilder, Boolean removeFormatting)
	D:\git\EntityFrameworkCore\src\EFCore\Query\Internal\ExpressionPrinter.cs(395,0): at Microsoft.EntityFrameworkCore.Query.Internal.ExpressionPrinter.VisitConstant(ConstantExpression constantExpression)
	D:\git\EntityFrameworkCore\src\EFCore\Query\Internal\ExpressionPrinter.cs(220,0): at Microsoft.EntityFrameworkCore.Query.Internal.ExpressionPrinter.Visit(Expression expression)
	D:\git\EntityFrameworkCore\src\EFCore\Query\Internal\ExpressionPrinter.cs(583,0): at Microsoft.EntityFrameworkCore.Query.Internal.ExpressionPrinter.VisitMethodCall(MethodCallExpression methodCallExpression)
	D:\git\EntityFrameworkCore\src\EFCore\Query\Internal\ExpressionPrinter.cs(244,0): at Microsoft.EntityFrameworkCore.Query.Internal.ExpressionPrinter.Visit(Expression expression)
	D:\git\EntityFrameworkCore\src\EFCore\Query\Internal\ExpressionPrinter.cs(583,0): at Microsoft.EntityFrameworkCore.Query.Internal.ExpressionPrinter.VisitMethodCall(MethodCallExpression methodCallExpression)
	D:\git\EntityFrameworkCore\src\EFCore\Query\Internal\ExpressionPrinter.cs(244,0): at Microsoft.EntityFrameworkCore.Query.Internal.ExpressionPrinter.Visit(Expression expression)
	D:\git\EntityFrameworkCore\src\EFCore\Query\Internal\ExpressionPrinter.cs(459,0): at Microsoft.EntityFrameworkCore.Query.Internal.ExpressionPrinter.VisitLambda[T](Expression`1 lambdaExpression)
	at System.Linq.Expressions.Expression`1.Accept(ExpressionVisitor visitor)
	at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
	D:\git\EntityFrameworkCore\src\EFCore\Query\Internal\ExpressionPrinter.cs(224,0): at Microsoft.EntityFrameworkCore.Query.Internal.ExpressionPrinter.Visit(Expression expression)
	D:\git\EntityFrameworkCore\src\EFCore\Query\Internal\ExpressionPrinter.cs(156,0): at Microsoft.EntityFrameworkCore.Query.Internal.ExpressionPrinter.PrintInternal(Expression expression, Boolean removeFormatting, Nullable`1 characterLimit, Boolean highlightNonreducibleNodes)
	D:\git\EntityFrameworkCore\src\EFCore\Query\Internal\ExpressionPrinter.cs(127,0): at Microsoft.EntityFrameworkCore.Query.Internal.ExpressionPrinter.Print(Expression expression, Boolean removeFormatting, Nullable`1 characterLimit)
	D:\git\EntityFrameworkCore\src\EFCore\Extensions\Internal\CoreLoggerExtensions.cs(319,0): at Microsoft.EntityFrameworkCore.Internal.CoreLoggerExtensions.QueryExecutionPlanned(IDiagnosticsLogger`1 diagnostics, IExpressionPrinter expressionPrinter, Expression queryExecutorExpression)
	D:\git\EntityFrameworkCore\src\EFCore\Query\EntityQueryModelVisitor.cs(634,0): at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.CreateExecutorLambda[TResults]()
	D:\git\EntityFrameworkCore\src\EFCore\Query\EntityQueryModelVisitor.cs(179,0): at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.CreateQueryExecutor[TResult](QueryModel queryModel)
	D:\git\EntityFrameworkCore\src\EFCore\Storage\Database.cs(70,0): at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](QueryModel queryModel)
	--- End of stack trace from previous location where exception was thrown ---
	at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
	D:\git\EntityFrameworkCore\src\EFCore\Query\Internal\QueryCompiler.cs(164,0): at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](Expression query, INodeTypeProvider nodeTypeProvider, IDatabase database, IDiagnosticsLogger`1 logger, Type contextType)
	D:\git\EntityFrameworkCore\src\EFCore\Query\Internal\QueryCompiler.cs(103,0): at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass15_0`1.<Execute>b__0()
	D:\git\EntityFrameworkCore\src\EFCore\Query\Internal\CompiledQueryCache.cs(69,0): at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQueryCore[TFunc](Object cacheKey, Func`1 compiler)
	D:\git\EntityFrameworkCore\src\EFCore\Query\Internal\CompiledQueryCache.cs(44,0): at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
	D:\git\EntityFrameworkCore\src\EFCore\Query\Internal\QueryCompiler.cs(99,0): at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
	D:\git\EntityFrameworkCore\src\EFCore\Query\Internal\EntityQueryProvider.cs(62,0): at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
	at Remotion.Linq.QueryableBase`1.GetEnumerator()
	at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
	at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
```

**Comment by maumar** [comment]
possibly same underlying issue as https://github.com/aspnet/EntityFrameworkCore/issues/9275
